### ISSUE TITLE
Issues with Checkstyle and vimrc

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#101]
# Summary
I am having issues with checkstyle flagging incorrect indentation and tabs being present.

## Description 
I was told to make sure that the tabstop was equals to 4 as shown in the 2nd picture but I still continue to face this issue.

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/a08eb5e7-8d6e-4573-af4a-e5f85be0a25b)

![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/e8a7b4fb-171e-4f6f-a852-e6432297e214)

**Comment by LimZiXiong** [comment]
Did u change the vimrc setting only after writing ur program? If so some tab character still exist. Easy way to check is to use vscode under setting search for "editor.renderWhitespace": your empty space should be a dot.

**Comment by weiyangng** [comment]
> Did u change the vimrc setting only after writing ur program? If so some tab character still exist. Easy way to check is to use vscode under setting search for "editor.renderWhitespace": and change it to all. Your empty space should be a dot. Each dot represent 1 indentation so you should see 4 dots

these were the original settings my vimrc came with, I did not change anything

**Comment by zuoshihua** [comment]
Re-download the `.vimrc` in this repo and replace your current `.vimrc`.

Next, reopen whatever `.java` files in Vim and hit `:gg=G`. This will fix the indentation for the whole file.

Be sure to hit `:wq` to save and quit when you're done.
