### ISSUE TITLE
What Vim has done to me.

### ISSUE THREAD

**Issue by mingzheMOG** [nus-cs2030/2324-s2#102]
# Summary
My slow descend into insanity due to Vim. 
And my need to class part.

## Description 
Can anyone recognise my morse coded "S.O.S", constructed through the use of the high-pitch beep error notification sounds made by Vim?

Dr Maxwell Maltz once said that it takes 21 days for a habit to be formed. However, I beg to differ, it only took 2 labs for Vim to permanently corrupt any previous semblance of proper typing habits I had.

My journey towards self-destruction began when I first took 2030 and was introduced to the wicked machination known as Vim. Unlike any other Java IDEs out there, Powershell + Vim was probably the single worst combination I could have ever encountered. It was like choosing to return to clay tablets after the invention of paper and pen, except that the clay tablets also blasted an annoying beep sound every time you made a mistake.

Despite the seemingly unintuitiveness of Vim, like the deletion of characters in front of the current text marker and the initial confusion of jumping between insertion mode or command mode, this was all squared away by the god awful high pitched beep that cascaded out of my laptop speakers. It was only through pure agony and torture which quickly aided to Pavlov me from a once well adjusted normal keyboard typer into a Soldier of Vim.

I am now a Servant of Msys, only capable of following the dogmas of Vim:
-  to press "i" before all insertions
- to press "x" to delete all that lies before us
- to press "u" to undo all that stands in our way

Vim is my Lord and Master, and through Msys shall his bidding be carried out. No longer do I engage in simpleton typing which is limited by a single modular system or a deletion method which is non-unidirectional.

I am now a Soldier of Vim and my cross "x" is ready to delete all those that stand to be corrected.

## Screenshots (if any): 
![image(1)](https://github.com/nus-cs2030/2324-s2/assets/158056179/56e5e902-77b8-4aa0-b25e-6d1811c23747)

**Comment by yuntsingg** [comment]
All the best Soldier of Vim!!

**Comment by samuelneo** [comment]
help how do I exit from clay tablet

**Comment by ZHD1987E** [comment]
Considering giving up on the labs...

**Comment by ZHD1987E** [comment]
In the labs: Vim

Outside: VSCode

**Comment by kaywoon** [comment]
You got this Soldier of VIM! In solidarity and in my quest for class part, I heed the request of the soldier himself to send this poster. 
![vimsoliderrecruitment](https://github.com/nus-cs2030/2324-s2/assets/152489584/bbcabe5b-d613-4025-a7f4-4ba1656544d0)

**Comment by jackclx** [comment]
still have no idea why vim was being used compulsory in this course, absolutely unnecessary.

**Comment by ZHD1987E** [comment]
Just in case you only have a Unix CLI which is likely what most servers run on…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hwkchia** [comment]
Great contributions and love the sense of humour... So much so that I've created a new section on the wiki.  Keep them coming! 💯 👍

**Comment by CChaosuan** [comment]
warrioers we are almost there

**Comment by ZHD1987E** [comment]
it’s still halfway bro…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZhengJie2001** [comment]
cant be said better....
