### ISSUE TITLE
Use of Protected Suddenly Banned

### ISSUE THREAD

**Issue by wkleow123** [nus-cs2030/2324-s2#106]
## Description:

In my server class for Lab 2, I declared a "protected double availableTime;" attribute and my code worked fine in codecrunch. I did this to help in my logic of updating the server's availableTime when serving a customer. However, suddenly in Lab 3 submission in codecrunch, it gives the error in the screenshot below. Are we not allowed to use protected on its own? I'm just wondering if this is an error because it was previously okay to do so in Lab 2.

## Screenshots

![Screenshot (2367)](https://github.com/nus-cs2030/2324-s2/assets/122266559/0218f9f3-d8b5-489a-9e55-bb915e9d9630)

**Comment by samuelneo** [comment]
you mentioned that you declared it as "protected double availableTime". the error message says it's "not declared private/protected *final*". did you declare it as final too?

**Comment by wkleow123** [comment]
yea thats the thing, it was fine in lab 2, but now lab 3 submission is giving me this error/ban, so i'm unsure why the change in grading system

**Comment by weikiatt** [comment]
by right all your properties are supposed to have final, if you want to change your availableTime, you can maybe try creating a new server with the updated time and reassign back to the same server

**Comment by hwkchia** [comment]
Closed as resolved.
