### ISSUE TITLE
Things relating to the `compareTo` method on Strings...

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#107]
# Question Description

>Q4: Note the use of compareTo in the compare method of the LexiComp class. By referring to the String class in the Java API, what can you find out about the compareTo method?

## Your contribution:

They check each and every letter of the original and the target string, and should there be any difference, then said difference is returned.

If there are no differences, then the length is taken instead.

See screenshot below for more info.

But still, this may present problems if we desire our sorting algorithm to do something else.

Thanks @samuelneo for notifying me of the error!

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/34389b77-4409-44b3-b799-adac6db15e2d)
Taken from [here](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#compareTo-java.lang.String-)
`

**Comment by samuelneo** [comment]
> They consider string size first (if different the difference of the string lengths is returned), otherwise they will compare them letter-by-letter.

this doesn't seem to match the screenshot you've attached - the documentation in the screenshot notes that the strings are compared pairwise until there is a difference. if there is no difference in the pairwise comparisons, only then is the string length used as comparison

**Comment by ZHD1987E** [comment]
Took a look again, you’re right!

Will have to go back and change my contribution.

Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hwkchia** [comment]
Included in Lecture 2 notes.
