### ISSUE TITLE
serviceTime.get()

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#108]
How do i get around this problem?

For context, i only call serviceTime.get() when my customer is served and saved the timing to my Server. Then my customers in queue will refer to my Server available time. But look like this method is calling serviceTime.get() multiple time. 

<img width="340" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156635387/a2d805fd-f371-4489-aa60-00a7a3c461c6">

**Comment by samuelneo** [comment]
try using `System.out.println` to debug by having it print whenever `serviceTime.get()` is called

**Comment by BZAStudent** [comment]
> try using `System.out.println` to debug by having it print whenever `serviceTime.get()` is called

If my server available is from my customer serviceTime.get(), and I call my server available multiple time, does this mean my serviceTime.get() is called multiple time as well?

If so, is there a way for me to save it as a separate space?

**Comment by samuelneo** [comment]
if your server's available method calls the customer's `serviceTime.get()`, and your server's available method is called multiple times, yes that means `serviceTime.get()` is called multiple times too

you should only be calling `serviceTime.get()` in one place. I do not recommend having it in your server's available method if you're going to call that multiple times

**Comment by BZAStudent** [comment]
> if your server's available method calls the customer's `serviceTime.get()`, and your server's available method is called multiple times, yes that means `serviceTime.get()` is called multiple times too
> 
> you should only be calling `serviceTime.get()` in one place. I do not recommend having it in your server's available method if you're going to call that multiple times

ok thanks. But if i can only call serviceTime.get() in my ServeEvent, then how do I set my WaitEvent?

Previously I set my WaitEvent timing by referring to my server's available time which refer to the customer.serviceTime.get().

**Comment by ZHD1987E** [comment]
Refer here:
https://github.com/nus-cs2030/2223-s1/issues/176

or here:
https://github.com/nus-cs2030/2223-s1/issues/191

**Comment by LimZiXiong** [comment]
Wait event should consist of 2 parts, wait again or can be served. If the customer has to wait again, you need to update and 'inform' the customer when the server will be available again

**Comment by BZAStudent** [comment]
> Wait event should consist of 2 parts, wait again or can be served. If the customer has to wait again, you need to update and 'inform' the customer when the server will be available again

yes thats what i did. but in order to wait further,  the waitevent refer to the server's available time which refers means i have to get customer.getServiceTime() again

**Comment by BZAStudent** [comment]
> Refer here: [nus-cs2030/2223-s1#176](https://github.com/nus-cs2030/2223-s1/issues/176)
> 
> or here: [nus-cs2030/2223-s1#191](https://github.com/nus-cs2030/2223-s1/issues/191)

thanks, i will take a look.

**Comment by ZHD1987E** [comment]
You don't have to.

Serve event does the updating.
________________________________

**Comment by LimZiXiong** [comment]
It seems that way but do remember the reason why the customer has to wait in the first place is because there is a customer infront of him and when he is done you can make use of that customer end timing to update it

**Comment by BZAStudent** [comment]
> It seems that way but do remember the reason why the customer has to wait in the first place is because there is a customer infront of him and when he is done you can make use of that customer end timing to update it

does this mean I can call it twice? Once when the server serve the customer, another time to see whether he is done.

**Comment by LimZiXiong** [comment]
> > It seems that way but do remember the reason why the customer has to wait in the first place is because there is a customer infront of him and when he is done you can make use of that customer end timing to update it
> 
> does this mean I can call it twice? Once when the server serve the customer, another time to see whether he is done.

Also the maximum number of time you can call get is equal to the number of served customer so if 5 served 1 left your get() method can only be called at max 5 times

**Comment by BZAStudent** [comment]
Ok thanks. I will see what I can do

**Comment by ZHD1987E** [comment]
Yay

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
