### ISSUE TITLE
Exercise #2 Assigning Solid type to Shape3D type

### ISSUE THREAD

**Issue by nak979** [nus-cs2030/2324-s2#109]
For context, in Exercise #2, I have a Shape3D interface (implemented by Cuboid and Sphere) and a Solid interface (implemented by SolidCuboid and SolidSphere). Cuboid/Sphere are parent classes to SolidCuboid/SolidSphere. 

Based on line 30-31 in the image, shape of type Shape3D is expected to be substituted by solid of type Solid.
I'm confused as to why substituting a Shape3D type with a Solid type is supposed to work if Shape3D is not a sub-type of Solid. Is there another connection that I should be making between the Shape3D and Solid interfaces to produce the expected assignment?

![image](https://github.com/nus-cs2030/2324-s2/assets/160406553/8c3d8752-182b-4f66-9d66-9f2b7cdeab6e)

**Comment by samuelneo** [comment]
> Shape3D is not a sub-type of Solid

you may want to reconsider this

**Comment by KoalaLyfestyle** [comment]
Just a note, interfaces can extend other interfaces as well.
