### ISSUE TITLE
Cyclic Dependency

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#111]
Currently my design is;

Arrival Event creates either Leave Event, Serve Event or Wait Event.
Serve Event creates Done Event.
Done Event may create Serve Event if there are customers in queue.
Wait Event doesn't produce anything.

How can i get around the cyclic dependency between Serve Event and Done Event?

**Comment by samuelneo** [comment]
your Wait currently doesn't produce anything. consider having it produce Serve so that Done doesn't have to?

**Comment by BZAStudent** [comment]
> your Wait currently doesn't produce anything. consider having it produce Serve so that Done doesn't have to?

Previously I had my wait event produces the serve event but this lead to me using the serviceTime.get() too many time.  Once I call serviceTime.get() and use that value to create a new server, will that value have a different space?

**Comment by samuelneo** [comment]
what do you mean by that value having a "different space"?

**Comment by BZAStudent** [comment]
> what do you mean by that value having a "different space"?

Means that if i refer to my server available time, it does not call customer serviceTime.get() to get that number. Instead it refer to server.availabletime() or something

**Comment by samuelneo** [comment]
depends on your implementation. as long as your server.availableTime() doesn't call serviceTime.get() (or a method that calls serviceTime.get()), it should work

**Comment by BZAStudent** [comment]
ok thanks. I will give it a try then

**Comment by BZAStudent** [comment]
Thanks everyone who helped me. I managed to pass lab3
