### ISSUE TITLE
Exercise 2: Level 5

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#112]
<img width="443" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/6f330725-cf9d-4373-a072-cd3fd4f9fce7">

I have trouble implementing the last sentence, as SolidImpl has a Shape3D object, but Shape3D cannot be an attribute of SolidImpl, else the last statement will not work.

**Comment by samuelneo** [comment]
the last line should hint to you that your implementation should have `SolidImpl` be substitutable for `Shape3D`

**Comment by naomiiiwu** [comment]
shape3D is an interface, so consider implementation/inheritance in this case to make it substitutable, i.e. SolidImpl should be a subtype of shape3D.
