### ISSUE TITLE
Lecture 3 Q1

### ISSUE THREAD

**Issue by mfchloe** [nus-cs2030/2324-s2#114]
Q1: Why does Java not allow multiple inheritance? Think of a situation where an ambiguity arises.

During recitation, our TA Enzio shared with us that Java loves to avoid its problems, hence Java does not allow multiple inheritance, primarily to avoid the "diamond problem.” This arises when a class inherits from two classes that have a common ancestor, leading to ambiguity in the subclasses where the subclass does not know which implementation of a method to use.

For example, we have classes A and B, both of which have a method foo() (that has been fully implemented). Now, if class C inherits from both A and B, and both A and B have a foo() method, which one should be inherited by C? This ambiguity can make the code difficult to understand and maintain.

To avoid this issue, Java only allows inheritance from 1 class maximum (but allows inheritance from multiple interfaces).

**Comment by myathetchai** [comment]
To supplement Chloe’s point, here is a code snippet illustrating the issue

``
 class A {
     private final int x;

     f() {
        return this.x;
    }

class B {
    private final int y;

    f() {
        return this.x * 2;
     }

``

A and B both have a method f(), with the same method implementation. However, the output would be different, depending on which class’s f() is called.

I also recall that from cs1010a, python allowed multiple inheritance of classes, where it attempted to resolve the “diamond problem” by adopting mro (Method Resolution Order), where the method to be executed is chosen based on the order specified while inheriting the classes.

**Comment by Shanicey98** [comment]
To add on to Chloe and Mya's points, while Java does not support multiple inheritance of classes, it supports multiple inheritance through interfaces while avoiding the "diamond problem"

Firstly, there is only method specification in interfaces, but no code implementation. Classes that implement the interfaces must provide their own implementation for the methods declared. Hence, even if the interfaces contain methods with the same name, there is no ambiguity regarding the choice of method to implement, as only 1 method implementation is provided in the class.

Additionally, interfaces can declare constants, but cannot have instance variables (fields). Hence, this prevents other ambiguity issues such as fields having the same name in multiple inherited classes.

With multiple inheritance through interfaces, Java provides a more flexible and convenient way of building classes. Classes can implement multiple interfaces, each specifying a set of methods to be implemented in the classes, without the ambiguity problems associated with multiple inheritance of classes.

**Comment by hwkchia** [comment]
Contributions included in Lecture 03
