### ISSUE TITLE
Checkstyle Error

### ISSUE THREAD

**Issue by pramoth20** [nus-cs2030/2324-s2#115]
I have been getting this error consistently, does anyone know how to resolve it. This is for exercise 2 where I have to calculate the volume of a sphere with (4/3) * pi * r^3

the (4/3) is being flagged out for being a magic number
![Screenshot 2024-02-20 at 4 59 27 PM](https://github.com/nus-cs2030/2324-s2/assets/155830463/e800a5f3-afea-45b2-bc16-50bfd52c15da)

**Comment by jwoongg** [comment]
4/3 is considered a "magic number"  as it  appears "without any explanation", which makes it harder to read the code, you will need to declare 4/3 on top along with your other variables at the top of the class. For example: private static double final fourThirds =  4.0 / 3 and just use the variable name when required.

**Comment by jackclx** [comment]
you have to declare the number on top as attribute and use when required so it avoids repeating and adds meaning to it.
