### ISSUE TITLE
method access modifiers

### ISSUE THREAD

**Issue by ya-en** [nus-cs2030/2324-s2#116]
would we be marked down if we do not declare methods to be private? (methods are public by default)

**Comment by weikiatt** [comment]
It should be fine to leave your methods public, but if the methods are only used within your class, I think it'll be better to leave them as private.

**Comment by AustinKong** [comment]
What @weikiatt said ^^^. In general, it is best practice to limit the scope of your methods using `private`/`protected` etc. if they are only used internally in the class. Although, it is technically not wrong to leave them all as `public`, it is still highly recommended to set them to private.

**Comment by SanShaoQian** [comment]
same! i normally leave them all as public first then assign methods as private when checking if i realise they havent been used outside of the class (e.g. overloaded constructors)
