### ISSUE TITLE
Lab 3 Test Case 7/10 Output Incorrect

### ISSUE THREAD

**Issue by AustinKong** [nus-cs2030/2324-s2#117]
# Summary

In Lab 3 test case 7, it appears that the expected output is incorrect.

## Description:

In Lab 3 test case 7 (see screenshot attached), the output `0.313 1 done serving by 1` should come before (the next line) `0.313 2 arrives`. This is because:

From lab 2 on Code Crunch, it is said that "Events are ordered by earliest occurrence of the event, and in the case of ties, by order in which the customer arrives."

Going by this definition, `0.313 1 done serving by 1` should have priority over (the next line) `0.313 2 arrives`. This is because customer 1 arrives before customer 2, and thus any events tied to customer 1 should have priority over any events tied to customer 2 (in the case of a tie).

As such, I find it strange that `0.313 1 done serving by 1` should come after `0.313 2 arrives`. Am I missing something, did anybody else face this issue and how did you resolve it?

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/69255175/2655b1e8-830b-4a15-a4f4-ee9abf2eeddb)

**Comment by samuelneo** [comment]
that's odd, I didn't have that issue and I ordered events by that definition given. something I can think of is that there may be a slight difference in timings between the two `0.313` events that is more precise than 3 decimal places. are you comparing the events based on their exact time, or based on the `toString()` method (or any other method that results in just comparing 3 decimal places)?

**Comment by ZHD1987E** [comment]
I think indeed there is a slight difference. So far in lab 2, they said that timings given are in 3 decimal places (according to my lab TA). This time I think they amped up by including test cases with more than 3 decimal places.

**Comment by AustinKong** [comment]
Thanks for the replies. The issue is resolved, turns out that there really is a slight difference in timing.

For reference, if anybody is facing the same issue, my old code was:

```java
return (int) Math.round((event1.getTime() - event2.getTime()) * 10)
```

Which only accounts for 1 decimal place (probably because Lab 2's test cases only had up until 1 decimal place). All I had to do was use comparison `>` instead of finding the difference to fix it.

**Comment by ZHD1987E** [comment]
Did your lab TA communicate this to you?

**Comment by AustinKong** [comment]
> Did your lab TA communicate this (the fact that timings can be more than 3d.p) to you?

Not really, but I might have missed it. Anyhow issue resolved.
