### ISSUE TITLE
Exercise 3 "does not meet substitutability requirement"

### ISSUE THREAD

**Issue by tzs69** [nus-cs2030/2324-s2#118]
<img width="350" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156649283/3aae63cd-3f75-4f49-b01d-5435b5ee951e">

Test cases 1-4 all pass and everything from test case 5 other than that line is pass. What does "does not meet substitutability requirement" mean?

**Comment by tzs69** [comment]
> there may be an inheritance relationship that you're missing

Could you please elaborate on this? I tried one time by using a RecycledLoader subclass with only one Service class and another time by using a RecycledService Subclass with only one Loader class but both times I got the same output as above.

**Comment by samuelneo** [comment]
is your `BigCruise` a `Cruise` and is your `SmallCruise` a `Cruise`?

**Comment by tzs69** [comment]
Yup. Both my BigCruise and SmallCruise extend from parent class Cruise.

**Comment by ZHD1987E** [comment]
Is your service able to take in ANY kind of Loader and ANY kind of Cruise?
