### ISSUE TITLE
Exercise 3 level 4 test cases

### ISSUE THREAD

**Issue by LinusLee17** [nus-cs2030/2324-s2#119]
<img width="780" alt="Screenshot 2024-02-22 at 12 06 20 PM" src="https://github.com/nus-cs2030/2324-s2/assets/53119648/ce4e319c-07a8-4a0f-ad6a-35b70bb6df33">
<img width="972" alt="Screenshot 2024-02-22 at 12 05 46 PM" src="https://github.com/nus-cs2030/2324-s2/assets/53119648/69a89dff-5d98-4609-a0f8-445c13b0bfef">

I'm having some trouble understanding the expected output for exercise 3 level 4 (white). Why is it "Loader #3 serving S2030@1031" (output line 6) and not "Loader #1 serving S2030@1031" when loader #1 is also available. Why does it assign loader #3 and #4 before it comes back to #1 and #2 again? 

It seems like the loader should be assigned by numerical order eg. after loader 2, 3 and 4 finish serving B1112@0901, loader 2 is deployed to serve B1113@0902 since loader 1 is still serving S1111@0900. Yet it doesn't follow this pattern subsequently?

**Comment by samuelneo** [comment]
it's based on when the Loader was freed up. if multiple Loaders were freed up simultaneously (perhaps because they were serving the same Cruise), only then does it go by numerical order. if you've implemented the queues in Level 3 correctly, you should get the expected output
