### ISSUE TITLE
Thinking about it...

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#121]
We're more likely going to use `Optionals` for Functional Programming purposes (pretty much Declarative Programming), instead of being used as a mere way to masquarade as just another `null`. Yay to streams I guess...

**Comment by samuelneo** [comment]
in CS2030 the elevator doesn't take you anywhere, rather a new elevator is created at the target destination with you in it

**Comment by ZHD1987E** [comment]
Holy **[CENSORED]**

_Proceeds to suffer under unimaginable physics thereby probably wiping out ZHD1987E in existence_

**Comment by ZHD1987E** [comment]
Sorry if the video gets changed many times. Video itself is immutable.

**Comment by ZHD1987E** [comment]
Still open for too long... closing it now
