### ISSUE TITLE
Exercise 3 Level 3 Logic issue

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#122]
<img width="1213" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/b925cb68-6fe3-484a-9f24-5c195cf15fbc">

I have trouble implementing this logic. Any help is appreciated.

**Comment by LimZiXiong** [comment]
You would need 2 - 3 ImList 2 for the services and 1 for returning back. For each cruise, go through the Active list to see which service should be placed into the expired queue. Remove them in the active queue and place it into the expired queue (Be very careful here removing elements means the size and order of the list change). Now check if the expired queue is empty if so you need to make new service or else assign that service to the cruise and similarly, delete it from expired queue and place it into active queue.

**Comment by hadyamanisanto** [comment]
> You would need 2 - 3 ImList 2 for the services and 1 for returning back. For each cruise, go through the Active list to see which service should be placed into the expired queue. Remove them in the active queue and place it into the expired queue (Be very careful here removing elements means the size and order of the list change). Now check if the expired queue is empty if so you need to make new service or else assign that service to the cruise and similarly, delete it from expired queue and place it into active queue.

You can do this with for loop, or while loop?

**Comment by LimZiXiong** [comment]
> > You would need 2 - 3 ImList 2 for the services and 1 for returning back. For each cruise, go through the Active list to see which service should be placed into the expired queue. Remove them in the active queue and place it into the expired queue (Be very careful here removing elements means the size and order of the list change). Now check if the expired queue is empty if so you need to make new service or else assign that service to the cruise and similarly, delete it from expired queue and place it into active queue.
> 
> You can do this with for loop, or while loop?

Personally for me I used both since i found that freeing up the active list using for loop you would need to be very careful when removing items
