### ISSUE TITLE
Mock PA1 Test Case 6 PrivateCarX

### ISSUE THREAD

**Issue by hansneddyanto** [nus-cs2030/2324-s2#123]
<img width="799" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/89475468/611e035e-22c5-4e70-a10b-80348ef886b2">

May I know for the mock PA1 Test Case 6, what is PrivateCarX and why is the expected output as such? Thank you!

**Comment by hadyamanisanto** [comment]
I don't know either. I'll ask my TA

**Comment by c-c05** [comment]
thats the hidden test case on codecrunch, did you put a toString method for booking?

**Comment by ZHD1987E** [comment]
This test case introduces new kinds of drivers and services, and checks if your Booking can handle ANY kind of driver and ANY kind of service.

Anyway, is Elon Musk going to sue Snatch for ripping off SpaceX?

**Comment by hansneddyanto** [comment]
I have managed to resolve this issue. The key is to use abstraction instead of checking the type of Driver
