### ISSUE TITLE
Mock PA Logic

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#124]
<img width="1186" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/de62c4a6-1585-472c-a0de-d9af7d337ef0">
Level 3 states that the service with the lowest fare is printerd, yet

<img width="1186" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/7fdd28de-1777-49d5-a5a9-84586fea86e5">
Level 5 implies that all services from the Driver and their fares are printed.

Do I have to forgo the rule in Level 3? Any help is appreciated.

**Comment by hadyamanisanto** [comment]
*printed

**Comment by samuelneo** [comment]
notice that each line of output in level 5 is a separate `Booking`. you'll have to modify your `Booking` accordingly to accommodate this

your level 5 code should still work with level 3 test cases

**Comment by kohsweehong** [comment]
you can modify your Booking class with certain attribute/method to identify the service accordingly. Also, your findBestBooking method should control how the Bookings are "Queued" in the ImList such that the output is return as shown.

**Comment by LimZiXiong** [comment]
Hint is constructor overloading can be used to achieve this

**Comment by c-c05** [comment]
i think you got to use constructor overloading and also could create a method that returns list of all possible bookings not just the best one?
