### ISSUE TITLE
Mock PA test case 3

### ISSUE THREAD

**Issue by yewyaorui** [nus-cs2030/2324-s2#125]
<img width="1440" alt="Screenshot 2024-02-24 at 2 17 11 AM" src="https://github.com/nus-cs2030/2324-s2/assets/157351044/af060c40-5f90-4625-bbd0-a577f4d3ca99">
hi does anyone know what test case 3 may be testing about? i tried all the jshell commands from the pdf for level 3 and i got the correct output but for some reason i cant pass test case 3. thank you!

**Comment by craezydodo** [comment]
could it be that your compareTo() method is not implemented correctly?

**Comment by c-c05** [comment]
did you try implementing the comparator?

**Comment by ZHD1987E** [comment]
Test case 3 checks if your comparator works 100% as what others said.

according to what they want, they check the price first, before they check waiting time.

**Comment by ZHD1987E** [comment]
Anyway, judging from the error, I think your comparator is quite broken…
