### ISSUE TITLE
Mock PA1

### ISSUE THREAD

**Issue by c-c05** [nus-cs2030/2324-s2#126]
i had to use the comparator and until now it still gets me very confused.... how to i default sort without using bookings.sort(null)

**Comment by LimZiXiong** [comment]
I used Comparator<Booking> comp = (x, y) -> x.compareTo(y);

**Comment by ZHD1987E** [comment]
Comparator.naturalOrder()

**Comment by timothyngcy** [comment]
Does anyone know the proper way of implementing the sort method while still using the `compareTo()` method because one of the levels said that we were supposed to `implement Comparable<Booking>` in `Booking` and in that class we defined the `compareTo()` method.

**Comment by ZHD1987E** [comment]
Actually…

If you just pass .sort(Comparator.naturalOrder()), it will just auto sort

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
