### ISSUE TITLE
L1 Q3 Advantage of Using Point as Part of the Definition

### ISSUE THREAD

**Issue by wkleow123** [nus-cs2030/2324-s2#13]
# Question Description:

Q3: What is the advantage of using the latter definition as compared to the first one?

## Your Contribution:

The advantage of taking in Point objects as inputs instead of four double variables as inputs for the distanceBetween method is that it allows for an additional abstraction barrier when using this method. It also becomes clearer that the purpose of this method is to find the distanceBetween 2 points instead of 4 random looking double values.

**Comment by hwkchia** [comment]
Updated Lecture01.
