### ISSUE TITLE
Exercise 3 clarification

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#132]
<img width="509" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/c3ea6a57-d72e-4d63-b2dd-96845b7ad025">
When they say 1 minute per 50 passengers, does it mean less than 50 passengers = 0 minutes?

**Comment by ZHD1987E** [comment]
Yes.
0 to 50 persons take 1 minute
51 to 100 persons take 2 minutes
so on and so forth
