### ISSUE TITLE
Exercise 4 Level 2 questions

### ISSUE THREAD

**Issue by xin-yi-phang** [nus-cs2030/2324-s2#133]
Hi!! I'm currently attempting Exercise 4 Level 2 and have been hit with some error statements I have difficulty understanding why

I have difficulty understanding where I went wrong. 

The 2 initial error messages were gone after I took out `<T>` in the return statement. I googled the error messages and found out that happens when java finds something inappropriate during compilation, but I am unsure why is this so. (wouldn't you need to specify the type of Tester, similar to the test code `Main.<Integer>testing(10, tester)`?

<img width="278" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158749925/53d6d1f0-1b07-47a5-a49e-8464c141d37e">

**Comment by ZHD1987E** [comment]
I think it has something to do with the Generics...

**Comment by BZAStudent** [comment]
Hi. For level 2, you're not suppose to return a generic type. And also i believe in Java, we can't return a generic type else it can lead to many problems such as if another method using the return of this generic method. The only way is to typecast the return generic method.

**Comment by luckrainbow** [comment]
The tester that you input would already have its <T> specified when it's created and passed into the function, so it doesn't really make sense to specify another <T> when you call tester's method .test

**Comment by xin-yi-phang** [comment]
> The tester that you input would already have its specified when it's created and passed into the function, so it doesn't really make sense to specify another when you call tester's method .test

hmm okie, i see now :)!

for the case of the test code, `Main.<Integer>testing(10, tester)`, we need to specify the type here, since we need to indicate what <T> is right?
