### ISSUE TITLE
Mock PA1 Test Case 6 PrivateCarX 

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#134]
![Screenshot 2024-02-26 164600](https://github.com/nus-cs2030/2324-s2/assets/111676024/d745be0d-8c17-40ad-9c75-bfcd36e19f2d)

Anybody knows why for the output my share a ride is missing an X? The rest if the output is the same.

**Comment by ZHD1987E** [comment]
Did you hardcode anything?

**Comment by JosiahPraeman** [comment]
The only thing i "hardcoded" is the tostring methods, etc 
![Screenshot 2024-02-26 182533](https://github.com/nus-cs2030/2324-s2/assets/111676024/af895984-42c7-4c6b-be95-ec921df890b8)

u see the return "Justride"

**Comment by ZHD1987E** [comment]
That’s odd…

I did the same and it worked 100% for me.

Contact Henry to let him know the fault.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LimZiXiong** [comment]
Hmm strange i am quite sure how the program structure should be is that PrivateCarX has a ShareARideX(has a relationship) so I basically made my driver class have the service it suppose to provide (I hardcoded this part) and my program submitted just fine

**Comment by ka10252** [comment]
I am having the same issue + when I try in jshell, mine shows the result as below so I am not sure how it can run in condecrunch.
<img width="611" alt="Screen Shot 2024-03-05 at 10 09 45 PM" src="https://github.com/nus-cs2030/2324-s2/assets/124032938/a47f4e5c-72a2-44a7-a061-e44e33924896">
