### ISSUE TITLE
Debugging Java on VSCode

### ISSUE THREAD

**Issue by RadieonAjax** [nus-cs2030/2324-s2#137]
### Introduction
Welcome to this quick reference on debugging your Java code using VSCode. Now, before the Vim enthusiasts come at me, let me just say this: I know the main guideline here is to embrace the Vim, and you should definitely learn how to use it. 

But I mean, if by chance your code goes wrong, and you're not sure why, VSCode is just sitting there on your computer, quietly whispering, "Hey, I can edit **and** debug, you know."  ¯\ _ (ツ) _ /¯

> I'm not saying you **should** use VSCode for debugging, but rather simply you **can** use it. There are multiple debuggers works (IntelliJ etc). Use whatever tickles your fancy.

### Context
Now, a bit of context. Ever since Lab 1, I have set out on a quest to simulate the command `java Main < 1.in` in the program, through variable manipulation to I/O editing, though none has been successful (Thanks TA for putting up with my questions). I then started searching up the command structure, which ultimately leads me to [this](https://unix.stackexchange.com/questions/283374/what-does-the-left-chevron-triangle-bracket-do). Equipped with that knowledge, I was able to figure out a way to pass in the input files for the debugger!

### Requirements
- Visual Studio Code
- Visual Studio Code Extension Pack for Java
- Git

### Procedures
1. We first need to set the console environment to Unix environment (similar to msys). After you have opened your folder location, you should see a bottom window showing "Problems, Output, Debug Console...". Select on **Terminal** (or you can press "Ctrl + `"). Click on the arrow beside the "+" icon, and select "Select Default Profile". The default would be set to Powershell.

![image](https://github.com/nus-cs2030/2324-s2/assets/46739337/2a21db62-39d8-45c3-bf0e-0ea314a45b62)

2. You should then see these pop up at the top of the screen. Select "Git Bash" to change to Unix terminal.

![image](https://github.com/nus-cs2030/2324-s2/assets/46739337/6cbe1fdc-22cf-467c-b50f-d587ee4461b0)

3. With our environment changed, we now need to setup the launch config for our debugger session. Here's the current one which worked for me: 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Current File",
            "console":"internalConsole",
            "request": "launch",
            "mainClass": "${file}",
            "args": ["<", "${workspaceFolder}/1.in"]
        },
        {
            "type": "java",
            "name": "Main",
            "request": "launch",
            "mainClass": "Main",
            "projectName": "Lab", //change this to whatever is generated for you.
            "args": ["<", "${workspaceFolder}/1.in"]
        }
    ]
}
```

4. And that's it! You'll be able to run the debugging session. Hope this helps you as much as it helps me! Honestly the debugging configuration doesn't look perfect, but I'm just winging it at this point. You know the saying: 

> If it ain't broken, don't fix it.

Here's a homage to whatever I've been doing so far:
![meme](https://github.com/nus-cs2030/2324-s2/assets/46739337/b05c7f6d-366c-4446-9b93-9482fba7e509)

**Comment by ZHD1987E** [comment]
1: this won’t work for JShell scripts.
How then?

Create a test class then! Put your functions in it, set some breakpoints, and make it go!

2: I only use it for CS2030
lol no, CS2040 will make heavy use of the Debugger, so better learn what VSCode can do or else have fun printing statements.

VSCode: Say “GOOD BYE!EVERYONE!” to Print Debugging.

Also note this applies to other IDEs, like JetBrain IntelliJ line of IDEs.

**Comment by CChaosuan** [comment]
Adding print after every line is basically me doing lab[🃏]

**Comment by Gracesong146** [comment]
> Adding print after every line is basically me doing lab[🃏]

and forgetting to remove a hidden print in the mountain of codes is what caused me 2hours of pain getting F grade on CodeCrunch...

**Comment by ZHD1987E** [comment]
…which is why you use a debugger outside the lab.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZHD1987E** [comment]
**BONUS**

Sick and tired of constantly passing `checkstyle *.java`?

Go install the Checkstyle extension from the VSCode marketplace
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/c8f16a9d-f621-4011-884a-04bbb4d144c3)

Then set up your extension as follows:

```
...
    "checkstyle.configurationPath": "...\\cs2030_checks.xml",
    "checkstyle.checkstylePath": "...\\checkstyle-10.3.3-all.jar",
...
```
