### ISSUE TITLE
Exercise 3 error in jsh

### ISSUE THREAD

**Issue by allis-g** [nus-cs2030/2324-s2#138]
Hi, may I know what this error means and how to fix it? I have the serveCruises method defined but it seems like compiler cant find it, same for my Service class. For jsh files do we have to initialise the lists just like a normal class, am not very familiar with writing code in jsh directly, thanks in advance!
<img width="400" alt="Screenshot 2024-02-27 at 3 21 39 PM" src="https://github.com/nus-cs2030/2324-s2/assets/161267008/9a52d63d-400e-4006-b009-b3fe6c0c023a">
<img width="518" alt="Screenshot 2024-02-27 at 3 21 55 PM" src="https://github.com/nus-cs2030/2324-s2/assets/161267008/f45a3639-d815-465f-9745-281e6e9e16b6">

**Comment by wkleow123** [comment]
Did u open your Service.java file and your level3.jsh file before you ran the test code in jshell?

Also, can't really tell from the screenshot of the code of your serveCruises method but did u add a } after the last line?

**Comment by allis-g** [comment]
Yes I did.. but still doesnt work

**Comment by wkleow123** [comment]
that is quite weird but usually when such a thing happens whereby u can open the .java file but yet it says class not found, there is usually a bug in the class file that actually makes it unable to compile properly but it does not show up when you open the file. It might be something small like a variable not being defined properly. usually, from my experience, having static final constants will cause the bug to not show up when you try to instantiate the object so try to remove the static portion for testing purposes then i think itll give the bug more clearly when you try to instantiate the object
