### ISSUE TITLE
What is the issue with this?

### ISSUE THREAD

**Issue by jianhaosoh** [nus-cs2030/2324-s2#140]
I am able to get the output for file 1.in to 3.in but not for 4.in. Codecrunch does not show me any test output as well. Can I check what's the general issue for this problem, thanks!

![Screenshot 2024-02-27 at 10 15 56 PM](https://github.com/nus-cs2030/2324-s2/assets/142876316/47f22310-d604-497c-802d-3dff107d2703)

**Comment by LimZiXiong** [comment]
if nothing appears there is probably an infinite loop going on. Try System.out.println your queue and see what happens
