### ISSUE TITLE
mock pe

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#141]
Hello. I used protected final for my classes but failed code crunch audit. Does this mean for mockPE, i am not allowed to do that?

<img width="265" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156635387/d08e6971-d82c-4410-b7a4-7b521e7c2ff7">

<img width="261" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156635387/4d26f85a-d842-4440-a745-51a9196293be">

**Comment by ZHD1987E** [comment]
Taken from my PowerPoint slides:
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/3a490a34-3619-4d80-bda5-d660c566d502)
_pardon from the angry emojis..._

**Comment by minhkiwi14** [comment]
> Taken from my PowerPoint slides: ![image](https://private-user-images.githubusercontent.com/140680858/309142708-3a490a34-3619-4d80-bda5-d660c566d502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzk4MDYsIm5iZiI6MTcwOTI3OTUwNiwicGF0aCI6Ii8xNDA2ODA4NTgvMzA5MTQyNzA4LTNhNDkwYTM0LTM2MTktNGQ4MC1iZGE1LWQ2NjBjNTY2ZDUwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwNzUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmIyYjBmZTE0ODVkNTM4YzJkYTFlYjdiNGFiNTBmNTYzZDA1ZmEwNmJmMTYyYTBhYzAzODAxMzUyNjU1ZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WZs53KsvyATuQa06cIfxaLHagPcXgos6jN_1GWDouUk) _pardon from the angry emojis..._

Being aware of this, for labs, we are still allowed to use `protected final`. Meanwhile, regarding self-practice exercises and the Mock PA, it is prohibited. This would be very inconsistent.
