### ISSUE TITLE
Unable to pass test case 10 lab 3

### ISSUE THREAD

**Issue by andrelau123** [nus-cs2030/2324-s2#143]
# Summary
unable to pass test case 10
Description of the question / problem here.

## Description:
I am still unable to pass test case 10 despite only calling for getservicetime() in my serve event. tried to debug with sys.peint.out, and ensured that getservicetime was called the same number of times the customer was served.
Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="631" alt="Screenshot 2024-02-28 at 1 52 47 AM" src="https://github.com/nus-cs2030/2324-s2/assets/81068338/9c73dd14-40a4-424f-be64-16656e417694">

Screenshots (if any)

**Comment by LimZiXiong** [comment]
If that is the case it means your program is serving more customer than it should be. Try this test case (test case 10 but without the serve duration being different) you should still see 12 served 1 left

2 3
0.500
1.100
1.200
1.300
1.400
1.500
1.600
1.700
1.800
1.900
10.000
11.000
12.000
