### ISSUE TITLE
Only Simulator -> PQ dependency allowed.

### ISSUE THREAD

**Issue by ALPHANIGEL1** [nus-cs2030/2324-s2#144]
What does this mean?

**Comment by huangtian666** [comment]
did you use PQ in other classes? i think we only can use PQ in Simulator class

**Comment by MarcusLiangg** [comment]
@huangtian666 is right, I had this problem in Lab 2 when I added an event in the PQ in other classes

**Comment by ZHD1987E** [comment]
Basically your PQ can ONLY be in the Simulator, and cannot be called anywhere else.

Also Lab 3 is done long time ago… please close it and spring clean this forum, thanks.

**Comment by arinng5** [comment]
PQ is only allowed to appear in Simulator.java
