### ISSUE TITLE
Exercise 4 incompatible parameter types in lambda expression

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#145]
![Screenshot 2024-02-28 154306](https://github.com/nus-cs2030/2324-s2/assets/158589429/dc7463b9-6285-46f1-ad5b-4c6e04739b64)

I cannot pass any of the lambda related test cases because of the incompatible parameter types. However, when I search online it just keeps telling me to typecast the input, how should I instead approach the problem.

**Comment by samuelneo** [comment]
if the generic type of `testing` is bound to `Integer`, think of how you can modify the parameter that `testing` takes in such that it works with a `Tester<Object>`

you might want to review lecture 4 content on covariant/contravariant subtyping
