### ISSUE TITLE
Tweak ImList .sort() method suggestion

### ISSUE THREAD

**Issue by bobbaID** [nus-cs2030/2324-s2#146]
We are taught 2 different ways to sort elements in a list - either pass a Comparator class or define a Comparable method in the elements themselves. Currently, if we want to use the elem's Comparable methods (i.e. natural sort) in an ImList, we have to pass a null in ImList.sort(null).

Taken from the ImList implementation
```
* If the specified comparator is {@code null} then all elements in this
* list must implement the {@link Comparable} interface and the elements'
* {@linkplain Comparable natural ordering} should be used.

public ImList<E> sort(Comparator<? super E> cmp) {
ImList<E> newList = new ImList<E>(this.elems);
newList.elems.sort(cmp);
return newList;
}
```

In previous sems where null wasn't rejected, this wasn't an issue. However, for the MockPAs and the labs, there is a blanket ban on the usage of null so CodeCrunch will reject the above usage in any instance. Passing nothing will also not allow the code to compile. Currently, the workaround is to create another Comparator class (shown here: https://github.com/nus-cs2030/2324-s2/issues/126). However, I think this solution is quite unintuitive as having the need to write both Comparator and Comparable feels unnecessary. 

Therefore, for ImList's implementation, I would suggest to overload .sort() with a secondary method without any arguments that does allow natural sorting to function as intended.

**Comment by zuoshihua** [comment]
Or just use a lambda expression

``` java
bookings.sort((b1, b2) -> b1.compareTo(b2));
```

**Comment by ZHD1987E** [comment]
Why not `Comparator.naturalOrder()`?

**Comment by bobbaID** [comment]
My point is that it shouldn't be necessary to have to write these workarounds in order to get ImList to use natural sorting within its elements. 

ArrayList already comes with a way to use natural sort within its methods, pass .sort(null) - and considering that ImList simply implements ArrayList, it should be reasonable to dictate that ImList works in a similar manner. With null being banned, using simply sort() should work as well.

Needing to write a lambda function or an additional Comparator to use natural sorting feels unneccesary in my opinion, when the parent that ImList implements from already has an in-built way to use it, I hope you get my point.

**Comment by zuoshihua** [comment]
So you want ImList to have a `sort()` method which under the hood calls `sort(null)`, and still pass CodeCrunch's tests?

**Comment by hwkchia** [comment]
The reason is simple: `sort(null)` with elements that are not Comparable will lead to an exception.
