### ISSUE TITLE
Failed Test Case 7 (Wrong Service Timings)

### ISSUE THREAD

**Issue by xiang-qiuyu** [nus-cs2030/2324-s2#147]
# Summary

I am unable to pass test case 7 because the service times for customer 6 and customer 4 are incorrect.

## Description:

I am unsure of why I am unable to access the correct service timings for each customer (specifically just customers 6 and 4), especially since my events seem to be in the correct sequence and I only call serviceTime.get() when a Serve event is created.

## Code Snippets
![Screenshot 2024-02-28 233904](https://github.com/nus-cs2030/2324-s2/assets/161620098/b162b516-28db-427a-9062-a3c23c8c103f)
![Screenshot 2024-02-28 233936](https://github.com/nus-cs2030/2324-s2/assets/161620098/890bb169-5094-4bec-8555-abade17faa4e)

## Screenshots
![Screenshot 2024-02-28 233711](https://github.com/nus-cs2030/2324-s2/assets/161620098/31fe6c09-9e7a-4a9a-a957-dfd1db6e76b9)

Thank you for reading!

**Comment by xiang-qiuyu** [comment]
solved! I was calling getServiceTiming at the wrong time

**Comment by kohweien** [comment]
hi! can i ask what you mean by calling getServiceTiming at the wrong time? i'm getting the same error too

**Comment by xiang-qiuyu** [comment]
hi! basically instead of calling getServiceTiming when i transit from Serve to Done, i instantiated it when I create my Serve event. we are only allowed to call the function when Serve is being executed. hope this clarifies!
