### ISSUE TITLE
Exercise 3 level 3 clarification about whether files are provided

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#149]
<img width="400" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/142191494/184f2a97-31fc-4ec1-9807-8bc13992236b">
<img width="462" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/142191494/7e0edd44-fb45-40b6-b070-44b0176b2df6">

Hi, I saw this on CodeCrunch. I understand that there should have been template files level3.jsh and level5.jsh given to us because of the highlighted parts. In Exercise 1, we were also provided with such a jsh file. Please clarify if I am wrong.

**Comment by minhkiwi14** [comment]
> Hi, I think we'll need to create our own .jsh file

But "minimal modifications to the file level5.jsh" should mean that there has been a file provided for us and we modify as few as possible, right?

**Comment by SheYuting** [comment]
The original problem says : "By modifying level3.jsh, incorporate the above with minimal modifications to the file level5.jsh."
My understanding is to create level5.jsh with minimum change to the file level3.jsh, so there are two separate file we will need to create

**Comment by minhkiwi14** [comment]
> The original problem says : "By modifying level3.jsh, incorporate the above with minimal modifications to the file level5.jsh." My understanding is to create level5.jsh with minimum change to the file level3.jsh, so there are two separate file we will need to create

So what you mean is that level5.jsh is just a modified version of level3?

**Comment by SheYuting** [comment]
Yep!

**Comment by minhkiwi14** [comment]
> Yep!

Ok thanks a lot!
