### ISSUE TITLE
Excericise 3: Regarding protected and private final

### ISSUE THREAD

**Issue by SheYuting** [nus-cs2030/2324-s2#150]
Regarding the use of protected final and private final, may I know when fo we use protected final in the parent class(es) and when to use private final not only in this excercise but in general?
Since the use of protected final is not accepted in Excercise 3.
<img width="1126" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/119406337/46db1af8-a08b-4f0c-9684-fdb47869232b">

**Comment by ZHD1987E** [comment]
Private Final is very dumdum-proof: If your child class tries to meddle the attributes, it will be prohibited from doing so.
Protected Final just allows what I said above.
In exercise 3, I do not think your child class needs to modify its attributes, lest it meddles wrongly and your cruise terminal explodes.

**Comment by gnimnix** [comment]
Are you asking about when to use `protected` in general for your future projects/career? Or when you can use `protected` in general for labs and exercises?

For labs and exercises, all attributes should be declared as `private final` or `private static final` unless explicitly stated otherwise.
