### ISSUE TITLE
Exercise 2 Level 4 : Error when extending

### ISSUE THREAD

**Issue by HoSCD** [nus-cs2030/2324-s2#154]
Hi, I am having an error when trying to make SolidCuboid extend Cuboid class , Cuboid is currently implementing Shape3D. However i do not see what the issue is.

<img width="413" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158131860/e502d8ec-786d-4cad-bdfe-0ad885e6c030">

**Comment by ginxaij** [comment]
what is your Cuboid implementation?

**Comment by zuoshihua** [comment]
Did you perform `javac *.java` first? This will show any compilation errors that JShell is not showing

**Comment by iceflakes12** [comment]
Regarding ur first error, can u show ur implementation for SolidCuboid? It could be u call super() wrongly on initialisation in SolidCuboid.

As for the subsequent errors, I think u can read and understand what those errors are saying. Second error states that this.volume() is not implemented in SolidCuboid, this could be a hint for your first error, it is possible that you did not call super() correctly during initialisation.

Third error states that your method where u put the @Override declarator is not overriding any superclass methods, this one check if you have any syntax issues when u declare ur method in the subclass.

Fourth error also shows that u might have used super() wrongly during initialisation.

**Comment by HoSCD** [comment]
Fixed the issue, realized i wasn't opening Shape3D.

**Comment by iceflakes12** [comment]
Bruh moment
