### ISSUE TITLE
Too many service times generated

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#155]
# Summary

Description of the question / problem here.

## Description:

I am initialising all my customers in one go is this implementation wrong

## Code Snippets

![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/0def699a-c1b2-4793-976a-e1ee5a8dbd06)

## Screenshots
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/49a2d3ff-4fa6-413c-9a2b-69673bb9d770)

**Comment by timothyngcy** [comment]
Is your `serviceTime.get()` only utilised here?

Also, you should be getting your service time just when the customer is about to be served only i.e. in your Serve event (`serviceTime.get() + arrivalTimes.get(i)`) Not when the customer arrives.

**Comment by weiyangng** [comment]
> Is your `serviceTime.get()` only utilised here?
> 
> Also, you should be getting your service time just when the customer is about to be served only i.e. in your Serve event (`serviceTime.get() + arrivalTimes.get(i)`) Not when the customer arrives.

yup its only used this one time, so I cant call all the service times first in that one loop correct?

**Comment by zuoshihua** [comment]
Call it in your serve event

**Comment by weiyangng** [comment]
so after i declare

public double getServiceTime() {
        return this.serviceTime.get();
    }

i only can use getServiceTime within the service class? Or should I not use it at all after that

**Comment by LimZiXiong** [comment]
if your program calls the supplier at the right place correctly and you still see this error it means there is some logic error regarding how your customer is served. For some reason the number of supplier called is checked before codecrunch continues to grade your program so if for example the correct output is 12 served 1 left your program evaluates 13 served 0 left (in this case your program would have called the supplier 13 times) you will see this error

**Comment by iceflakes12** [comment]
@weiyangng After u declare getServiceTime() in customer, u can use the getServiceTime method outside of customer class, but only once. And u have to make sure you call it during serve event so that customers who decide to leave wont get a service time (also because of the sequence of service times but thats another problem which wont exist if u call getServiceTime in your serve event :D)

**Comment by weiyangng** [comment]
yup if i remove all other uses of my getServiceTime the error disappears, but now how would I update the next available time and how long the customer stays for now without having the service time.

**Comment by iceflakes12** [comment]
@weiyangng Let me give you an example and see if you can change your implementation accordingly.

Customer A is served by waiter A for 1 hour(? forgive me i dont remember the units )
Customer B comes and waits in the queue for waiter A
Customer C comes and waits in the queue for waiter A
Customer A is done being served by waiter A
Customer B is being served by waiter A

If you see the above example, customer B and customer C are waiting in queue for customer A to finish being served by waiter A. However, both do not have a "service time" in the queue. It is only when customer A is done being served by waiter A, then the serve event for customer B is triggered and then customer B is given a service time.

How u want to implement this is up to you, but from what you have done there are quite a few things to change (for example you will need to allow customer C to wait for customer A and B, but then you only know how long customer C waits for customer A, and only when customer A is finished then u will know how long customer C waits for customer B.

For what I have done at least, wait returns wait until serve can be called. But there are probably other better ways to implement this.

**Comment by iceflakes12** [comment]
Also if i were to add, in your code, as long as service time is still being generated for customers who leave and do not get served, then you will still keep seeing the "Too many service times generated error"
