### ISSUE TITLE
adding text 'recycled' to recycled loader exercise 3

### ISSUE THREAD

**Issue by kohweien** [nus-cs2030/2324-s2#158]
# Summary

how do i add the text 'Recycled' in front of recycled loader?

## Description:

ive passed almost all my test cases apart from the last one, and for the last one, the order in which the loaders are serving the cruises seems correct. all i'm missing is the word 'recycled' to indicate that a loader is recycled. does anyone have any tips on how to solve this? do we only have to edit level5.jsh or can we create another class for recycled loaders? thank you so much!

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by ZHD1987E** [comment]
Remember... inheritence and polymorphism!

**Comment by gnimnix** [comment]
You need to create another class that extends your `Loader` class, then `@Override` the `toString()` method. Then in your `level5.jsh` file, implement the logic to create this new `RecycledLoader` object every third loader.

**Comment by kohweien** [comment]
ive gotten it, thanks everyone! i didnt know we could create another class, i assumed the question only wanted us to edit level5.jsh
