### ISSUE TITLE
Lecture 1 Quesion 7: How to check for the same point?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#16]
# Question Description:

> Q7: By making modifications to the Point class, how do you test if p and q refer to the same point, or different points with the same x and y values?

## Your Contribution:

I'm thinking of this:
```
    public boolean equal(Point other Point) {
        return otherPoint.xCoord == this.xCoord && otherPoint.yCoord == this.yCoord;
    }
```

Edit: I forgot about how I initalised it! Here's the context:

```
...
private final double xCoord;
private final double yCoord;

public Point (double x, double y) {
    this.xCoord = x;
    this.yCoord = y;
}
...
```

**Comment by hwkchia** [comment]
I was not referring to the `equals` method.  I will cover this in week 3.  

I'm asking how to use jshell to **convince** us that p and q are actually the same `Point` object, or otherwise. *Hint*: don't make the properties `final`.

**Comment by eggrrrr** [comment]
maybe we can use the moveTo method to move point p and see if point q is moved as well? 

here's the edited Point Class:

```java
Class Point {
    private double x;
    private double y;

    Point(double x, double y) {
        this.x = x;
        this.y = y;
    }

    public String toString() {
        return "(" + this.x + "," + this.y + ")";
    }

    void moveTo(double a, double b) {
        this.x = a;
        this.y = b;
    }
}
```

when i moved point p to (2.0, 2.0), i realised point q is moved as well! as shown below: 
<img width="402" alt="Screenshot 2024-01-21 at 2 39 53 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156998070/0e7afe05-19dc-46e6-8e59-e051b30bdadd">



hence, p and q refer to the same Point object in this case!

**Comment by hwkchia** [comment]
Yes, very convincing indeed.  

Realize that we were only able to test this by removing the `final` modifier from the properties, hence making the object mutable.  

If we restrict ourselves to working with immutable objects (i.e. properties are always declared `final`), do you think it matters whether `p` and `q` refer to the same object, or different objects with the same property values?  For example, have you ever been concerned whether two Strings `"abc"` and `"abc"` refer to the same `String` object or different objects, given that `String` is immutable?

**Comment by hwkchia** [comment]
Included in Lecture01
