### ISSUE TITLE
Exercise 3 Level 5

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#160]
# Summary

Description of the question / problem here.

## Description:

my program is just making every third service a recycled server instead of every third event any suggestions

## Screenshots
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/b0815b80-69e3-4c70-8512-9ef7704e5c51)

**Comment by kee-x** [comment]
You need to add an additional 60 minutes to the end of the serving time for recycled loaders. Then check if there is any loader that is free to be used for serving the next cruise. If it isn't free, create new loaders.

**Comment by weikiatt** [comment]
Is your code checking whether the number of cruises % 3 == 0 at the start of the for loop?
you can try checking if `loaderId % 3 == 0` whenever transferring loaders from the active to expired queue and whether `noOfLoaders % 3 == 0` when creating new loaders

**Comment by gnimnix** [comment]
1. What is your logic for simulating `Loader` and `Service`?
2. Are you getting an infinite loop before level 5? If not, what is your logic for `RecycledLoader`?
