### ISSUE TITLE
Test case 7 Lab 3

### ISSUE THREAD

**Issue by Xiang-le** [nus-cs2030/2324-s2#161]
# Summary
Hi all, I am facing an error for test case 7 in lab 3 and am having trouble identifying the source of the error. Would anyone be able to advise me where to look for the error?

## Screenshots
<img width="311" alt="error" src="https://github.com/nus-cs2030/2324-s2/assets/101037442/13b2725d-8ef5-4136-9bcc-663d70dad3ce">

**Comment by xiang-qiuyu** [comment]
hi! i think this test case usually they catching people who invoked getServiceTiming() at the wrong place (i had this error too). did u call it while ur Serve is being executed?

**Comment by gnimnix** [comment]
From your screenshots, it is not enough to narrow down where exactly went wrong. Try to manually create a larger test case (say 5 servers and 15 customers) then print out the timings and figure out whichever event is causing you issues.

**Comment by iceflakes12** [comment]
U gave customers a service time once they entered the queue, which is not what the question requires.

For customers waiting in a queue they dont have service time, service time is only given when the customer exits the queue and gets served by the server.

**Comment by Xiang-le** [comment]
thank you everyone for your help! finally managed to get a correct implementation.
