### ISSUE TITLE
Use of instanceof

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#162]
Hello. For the ungraded ex 1, instanceof can only be used in a class to check instanceof the same class, e.g. within a typical equals(Object) method.

But after submitting my code, 

![image](https://github.com/nus-cs2030/2324-s2/assets/156635387/4a8f68da-4575-4441-8474-ca37c173df7a)

So can we use instanceof or cannot?

Thanks in advance.

**Comment by iceflakes12** [comment]
can use instanceof,

use it this way:
class A implements B {
....
public int tempMethod(B x) {
    if (x instanceof A) {
        ...
    }
}

in the above example, instanceof is used within a method of class A to check whether an object is an instance of class A
This is the only time codecrunch allows this i think

**Comment by BZAStudent** [comment]
Thanks. I found out that they only allow us to use instanceof in the specific method.
