### ISSUE TITLE
Ungraded Exercise #1: Distance Fare Calculation

### ISSUE THREAD

**Issue by Partillay** [nus-cs2030/2324-s2#166]
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/f427e08e-7421-4998-9946-c19b6b91586c)

If I am not mistaken, based on the test cases in the original task, Distance Fare calculates the fare based on cumulative distances. However, the expected output above for the fare for the trip of cabs is 7 where the maximum fare should be only 5 (where 1 + (5-1)/2*2 = 5). What is the problem here?

**Comment by samuelneo** [comment]
the argument for the maximum distance does not include the flat fare distance

**Comment by Partillay** [comment]
> the argument for the maximum distance does not include the flat fare distance

Oh, no wonder, thanks!
