### ISSUE TITLE
Memory Address

### ISSUE THREAD

**Issue by Lhanxi** [nus-cs2030/2324-s2#167]
In lecture 6 we were introduced to the Stack and Heap Memory Model. In the provided lecture example, 
Point centre = new Point(0.0, 0.0)
Circle circle = new Circle(new Point(0.0, 0.0), 1.0)
so I thought that centre and the point object stored in circle would be separate objects with separate memory addresses. However, in the lecture example, both point objects have the same memory address as seen in the diagram (Lecture 6 pg 9). Thus, is this expected behaviour where immutable objects with the same variable values will default to having the same address for memory optimisation? Or is there another reason for this?

Screenshots (if any)
![Uploading image.png…]()

**Comment by iceflakes12** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/106156502/d760371a-0504-4807-91a6-40a9e982717e)
I think shld be different lol

**Comment by iceflakes12** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/106156502/040be5a2-0df4-4b5e-a9bd-400031842b47)

**Comment by hwkchia** [comment]
There was an error in the slides.  I've already uploaded a correct version, and also edited the video recording.
