### ISSUE TITLE
Ungraded Exercise #1: Explicit typecasting detected

### ISSUE THREAD

**Issue by craezydodo** [nus-cs2030/2324-s2#168]
Hi! I encountered this problem. I am not very sure what is an explicit typecasting, could it be this? Thanks

<img width="412" alt="Screenshot 2024-03-04 at 4 51 28 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157350945/323a486d-9040-4843-a3e3-117c38da1eb0">
<img width="438" alt="Screenshot 2024-03-04 at 4 52 25 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157350945/bcada560-becc-4d47-8e27-1e8d2d3f2fd5">

**Comment by samuelneo** [comment]
yes that `(Bus)` is explicit typecasting

Java 16+ has pattern matching for `instanceof` that allows you to do this without explicit typecasting, you might want to refer to lecture 3 where prof introduced this
