### ISSUE TITLE
Ungraded Ex 1: Inverted Commas

### ISSUE THREAD

**Issue by jwoongg** [nus-cs2030/2324-s2#169]
Hi, I encountered this problem but I'm not really sure why I'm getting such an output. 
<img width="626" alt="Screenshot 2024-03-04 at 10 59 41 PM" src="https://github.com/nus-cs2030/2324-s2/assets/158253939/10b01e4f-76b2-4b71-9d95-439630c92ee9">
Thanks

**Comment by craezydodo** [comment]
I had that output when I declared
``` 
String result = "";
```
then append other strings to it

**Comment by wkleow123** [comment]
Maybe you could show us your toString() code maybe theres extra inverted commas somewhere

**Comment by killuasmurf** [comment]
![Screenshot 2024-03-06 161651](https://github.com/nus-cs2030/2324-s2/assets/128378362/e5c2e472-b7a1-4852-afdf-c5ff0aae0b30)
![Screenshot 2024-03-06 161718](https://github.com/nus-cs2030/2324-s2/assets/128378362/709df59d-2ab5-49af-91c5-9d2fdf0c156d)

I have this problem if i use toString() as well

**Comment by killuasmurf** [comment]
![Screenshot 2024-03-06 161651](https://github.com/nus-cs2030/2324-s2/assets/128378362/ae7f4978-f3bc-46da-af40-323f0606c6a1)
![Screenshot 2024-03-06 161718](https://github.com/nus-cs2030/2324-s2/assets/128378362/151c8e5a-cbe6-4a91-a6d8-589a82d37f30)

same for me, I can't get rid of the inverted commas

**Comment by iceflakes12** [comment]
encompass the string in the tostring method of a seperate class and return that class.

jshell seems to be taking the string in every other non tostring method that returns a string as a raw string, which is why funny things happen

**Comment by iceflakes12** [comment]
so ideally avoid returning String for class methods unless it is a toString method

**Comment by joshuagde** [comment]
Hi could it be because your next method returned a String? The next method should return a Trip and that could be why your output has the inverted commas
