### ISSUE TITLE
Lecture 1 Question 9

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#17]
# Question Description:

I quote:

> Give an example of an interesting problem with a OOP solution that requires top-down design, and bottom up implementation.

## Your Contribution:

Think of a bus. The bus has multiple systems, for example, the drivetrain. Even the drivetrain or other systems has sub-systems, for example the engine itself, the gearbox, the axles and all that stuff. All that integration needs to be planned so that the unit designs fit the agreed specifications (you don’t want an engine that is too big to fit the gearbox!)

From here, you develop these sub-systems (develop the engine, drivetrain and other basic parts) and test them to make sure they work as a unit (the engine starts and runs as planned, the transmission has no fatal flaws), and then integrate them slowly (with good testing to make sure they integrate well with no strange side effects, you don’t want to install an air conditioner and cause the engine to fail for some odd reason) until you have an entire bus that works well.

There, a full working bus.

**Comment by hwkchia** [comment]
This is a good analogy.  But I'm also looking for something concrete, so that we can work out some code.

**Comment by zuoshihua** [comment]
> Give an example of an interesting problem with a OOP solution that requires top-down design, and bottom up implementation.

Let's say we want to implement the game Tic-Tac-Toe. We could design a "Gameboard" class and a "Player" class.

One property of the "Gameboard" class could be a 2D array to represent the 3x3 board.

Methods of the "Gameboard" class could include

- Handling the moves of a player
- Determining which player is the winner

One property of the "Player" class could be a boolean property to represent whether they are a cross (X) or circle (O).

One method of the "Player" class could include

- Prompt the user for their move

These are the details I have from the top of my head. Only when we actually code it will we discover if more methods or properties are needed.

**Comment by hwkchia** [comment]
Included in Lecture01. Closed due to no further contributions.
