### ISSUE TITLE
Exercise 5 is not up yet

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#175]
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/ce3dffd0-21ae-4e89-ba45-c5be524a4613)

**Comment by hwkchia** [comment]
So sorry.  I set the release time, but I kept it hidden. 😭

**Comment by ZHD1987E** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/b55fe24f-2667-4d8a-8719-fd56820b39ad)

_OK noted I see it now_
