### ISSUE TITLE
Request to use personal Bluetooth/wired keyboards for PA2

### ISSUE THREAD

**Issue by Desmondchung888** [nus-cs2030/2324-s2#177]
Dear Prof Henry,

I am writing to request for the permission to use personal keyboard during PA2, as it significantly increases my typing speed and accuracy. I understand the need for exam integrity and am willing to comply with any checks or conditions you set forth to ensure fairness. I believe this adjustment will allow for a more accurate assessment of my abilities and improve my exam performance.

Thank you for considering my request.

Best regards,

Desmond

**Comment by hwkchia** [comment]
Considering fairness to all students, I would have to reject the request.  Anyway, the PA is not meant to be a race.

@Desmondchung888 I've removed your student number in your post.
