### ISSUE TITLE
When you log into Codecrunch, did you notice anything new?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#178]
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/570eeea0-91ac-4382-8be5-f08ac95073f7)

Where did 'IVLE' go? How about the footer?

It was all gone thanks to the CodeCrunch team removing them (and I let them know that these are obsolete and have to be removed)

**Comment by zaccymomo** [comment]
nice 👍

**Comment by zuoshihua** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/64007522/ec35310b-b5d6-485c-bbc0-69fa5806ff71)Impressive... very nice.

**Comment by ZHD1987E** [comment]
Issue closed because the novelty factor wore off...
