### ISSUE TITLE
Lec07 

### ISSUE THREAD

**Issue by Bryanngu03** [nus-cs2030/2324-s2#180]
# Description
Hi prof, i want to ask can we use " (this.get() == other.get()) " instead of 
" this.get().equals(other.get()); "  for equals method in Maybe? 
this can solve the issue when there are 2 maybe.empty right?
There are minor typo in page 5 of lecture slides:  instanceof Maybe<?> instead of Maybe <T> ;
Thank you vm;

**Comment by wkleow123** [comment]
im not sure if this will work. just take for example, u cannot do String1 == String2

**Comment by mChewWW** [comment]
I believe this won't work, as you will be comparing the memory addresses of the objects rather than the values itself.

**Comment by hwkchia** [comment]
Yes, it's supposed to be `instanceof Maybe<?>` instead of `instanceof Maybe<T>`.  I've re-uploaded the slides to Canvas.

Thanks. 👍

**Comment by Bryanngu03** [comment]
Ok.. ya cannot use "this.get() == other.get()". Thanks guys
