### ISSUE TITLE
Before you dare use Visual Studio Code or some other IDE to tunnel into your PE node...

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#185]
# Just don't.
Wait, why? Is there a reason behind this? I may have tried it before and I can't believe that there is this warning?!
# Here's why:
- When your IDE connects, it will attempt to download things onto the PE node (e.g. Visual Studio Code would download its own VSCode server files onto it)
- When you install extensions, your IDE will do the same to your PE node
- This means that you CAN cause your storage quota to exceed, or the system flags you for downloading files.
- And **technical and teaching staff** will know about it and **will chase you down**
- [You die! I die! Everybody die!](https://www.youtube.com/watch?v=6VoPmNPG_Sg)

<strong> Moral of the story? Just stick to Vim </strong>

---
...but I still want to use Visual Studio Code!!!
# NO 🚫 NO 🚫 NO 🚫 NO 🚫
_insert kurt tay doing the 'no' pose_

**Comment by hohinnn** [comment]
wow thats interesting! will be sure to take note of that!

**Comment by ZHD1987E** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/72ae4627-4b08-4ca0-8fca-76a7b52ba99e)
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/343cfd31-242b-4bde-8919-95cd3eb4c80f)
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/e890167f-b0fb-445d-939e-cc33ad87b5b9)

**Comment by samuelneo** [comment]
you didn't do this for PA1 did you?

**Comment by ZHD1987E** [comment]
Did use VIM for PA1 as instructed.

**Comment by Gracesong146** [comment]
I hated vim at first and i cried in Lab 1 suffering using vim but... trust me, the more you use vim, the more you will get used to it, and the more you will appreciate it especially if you take time to learn all the shortcuts to make your life easier ✨ like DD for delete, U for undo, there are many shortcuts that make vim easy to use

**Comment by ZHD1987E** [comment]
@Gracesong146 especially if you are dealing with a Unix shell, not a GUI.

**Comment by zuoshihua** [comment]
> I hated vim at first and i cried in Lab 1 suffering using vim but... trust me, the more you use vim, the more you will get used to it, and the more you will appreciate it especially if you take time to learn all the shortcuts to make your life easier ✨ like DD for delete, U for undo, there are many shortcuts that make vim easy to use

Vim users, we have a convert

**Comment by ZHD1987E** [comment]
Now you 🫵 guys know what you cannot ⛔🚫🚳🚭🙅🙅‍♂️🙅‍♀️ do, this issue is closed.
