### ISSUE TITLE
Lab 03 ungraded testing compilation error

### ISSUE THREAD

**Issue by hanlinnnnn** [nus-cs2030/2324-s2#187]
Hello, I've been experiencing this error when I try to submit my Lab 3 code through the new "lab 3 ungraded testing" submission portal, and I have not seen this error in any other thread..has anyone experienced this before? What could've resulted in this error?

<img width="743" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/119099121/a9aac42b-daa3-4537-9c0d-29380b43ea71">

Also I could compile the files with javac *.java, and there were no issues when I ran checkstyle *.java. I tried to submit the same files into the new "project" submission portal, and this error does not show up, hence I'm really confused about this. Would greatly appreciate any help !!

**Comment by ZHD1987E** [comment]
That. Is. So. Odd.

**Comment by tarshalim** [comment]
hmm i've never seen this before either.. it seems like there might have been a mix-up where the linker is trying to process a Java source file (BlindlyWait.java) as if it were a linker script, which is causing confusion. To fix this, perhaps try 1) making sure your file is saved with the correct file extension (.java) and 2) double-check the command you're using to compile your Java file (javac YourFile.java). make sure you're not accidentally trying to compile it with a different compiler

**Comment by hanlinnnnn** [comment]
updates on this, i submitted yesterday and this error doesnt show up no more..unsure what caused the error and no idea how it was fixed but thanks anyways!
