### ISSUE TITLE
Curly Brackets instead of Square Brackets

### ISSUE THREAD

**Issue by timothyngcy** [nus-cs2030/2324-s2#188]
Hello! Anyone knows how to implement the toString() method so that it would print the curly brackets instead of the square brackets? I tried calling map.values() but it returned me the square bracket version.

Codecrunch:
<img width="450" alt="Screenshot 2024-03-16 at 12 54 54 AM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/86ce021d-58c7-4dbd-9539-e6f71b961f65">

Mine:
<img width="526" alt="Screenshot 2024-03-16 at 12 55 05 AM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/ef80e5de-23e4-4f05-a616-4ac1a3c9a06f">

Thanks a lot!

**Comment by LimZiXiong** [comment]
You can remove the square bracket by using substring method since the curly bracket is the first and last character, use substring(1, stringname.length() - 1). Just to note however calling the values() method is not allowed codecrunch will reject your program

**Comment by Mathewvanh** [comment]
You can also try override the toString() method!

**Comment by jpowcm** [comment]
Hi! I am also facing the same issue, may i know how u resolved it since we are not allowed to use values()?

**Comment by kingcard02** [comment]
did u use ImList instead of a dictionary? anyway just hardcode the curly brackets in that’s what i did
