### ISSUE TITLE
Lab 4 test case 1 producing nullpointerexception error

### ISSUE THREAD

**Issue by LimZiXiong** [nus-cs2030/2324-s2#189]
# Summary

After submitting my program for evaluation, my output is immediately met by nullpointerexception error.

## Description:

On the side of 'Expected Output' there are 2 empty spaces but on the side of  'Your Output' it shows nullpointerexception error.
The part that managed to get evaluated seems to match the expected output. How do I rectify this issue?

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/157023573/74d68232-0088-4a6b-a7ac-305d4e459764)

**Comment by ZHD1987E** [comment]
Yout `Object` might have been a `null`, so use the `Optionals.orElse()` or something similar to deal with it!

**Comment by LimZiXiong** [comment]
> Yout `Object` might have been a `null`, so use the `Optionals.orElse()` or something similar to deal with it!

Hmm but the error appeared at the top before the autograder starts evaluating. Unless error will be brought all the way to the top?

**Comment by ZHD1987E** [comment]
Oh well then…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LimZiXiong** [comment]
Error does indeed get bubbled to the top. I was using substring and didn't take into account what if the string is empty. (Too used to optional handling such cases)
