### ISSUE TITLE
Stuck at KeyableMap

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#190]
Hello, my implementation of KeyableMap is my class will extend the keyable that they are storing. For example, Course extends KeyableMap Assessment.

However for the method put, we are instructed to return a KeyableMap and while returning a KeyableMap<V>, the return type class is not the same as the class itself.

<img width="691" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156635387/9f50b2ff-54a1-49d2-9ce4-29c9afa717f3">

The above testcase says that I can't do that cause course.put(assessment) does not return a course but a KeyableMap 
Assessment. Am i suppose to overwrite the put method in each of my classes to non KeyableMap?

**Comment by yolotouch** [comment]
Yes, for mine I override the put method in both my student and course classes

**Comment by BZAStudent** [comment]
> Yes, for mine I override the put method in both my student and course classes

Hi can you explain to me how you override? I tried overriding but it doesn't work. KeyableMap put return a KeyableMap but I don't store a KeyableMap in my ImmutableMap. I store the type that extends Keyable. 

<img width="539" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156635387/c7fdc672-2afe-4641-818c-2dc458314632">
Above is what i am trying to do but it doesn't work.

**Comment by yolotouch** [comment]
My second line was Keyable<Assessment> newmap = super.put(a), and the return new Course second parameter was the dict of the newmap

It works using all the test cases in jshell, but ive yet to try the ones in codecrunch yet though

**Comment by BZAStudent** [comment]
Hey thanks. I was so tunnel in that i didn't see the map of KeyableMap is the the type of map that the classes are storing
