### ISSUE TITLE
Excess Output

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#191]
how do i get rid of the Lab1= and Lab2= without using substring()

![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/88509654-a5a9-43c1-ba4e-2ef631225ecd)

**Comment by kohsweehong** [comment]
you can try to create a toString() method in your class like the one shown at the beginning of the instructions to override it.

<img width="333" alt="l4" src="https://github.com/nus-cs2030/2324-s2/assets/156646904/7e68bf06-73f2-463b-a5fb-663b9741eb8c">
