### ISSUE TITLE
Lab 4 map and flatMap

### ISSUE THREAD

**Issue by yolotouch** [nus-cs2030/2324-s2#192]
Hello, I'm currently stuck in level 4 where I have to create a map method. Since, we are not allowed to use .get() on an optional, how do we get the value from it? Are we supposed to use .orElse(...) instead?

![Screenshot 2024-03-16 at 1 02 05 PM](https://github.com/nus-cs2030/2324-s2/assets/148688315/0be3d033-5520-4516-b60d-e98f56450310)

**Comment by ZHD1987E** [comment]
OK... I faced the same issue as you before...

On level 4, you use the `.orElse()` method to handle cases where the student/course/assignment exists or not, which is where this method comes in handy. Don't worry about the `null`, tell the Optional what you want to do with that null and take it easy!

**Comment by yolotouch** [comment]
So I should use .orElse(null) for now?

**Comment by ZHD1987E** [comment]
`null` is BAN

So you need to figure out what else can come and replace

**Comment by yolotouch** [comment]
wait... I just realised I don't have to implement the map by myself inside KeyableMap (cuz its already in Optional anyways), is it?

**Comment by LimZiXiong** [comment]
> wait... I just realised I don't have to implement the map by myself inside KeyableMap (cuz its already in Optional anyways), is it?

no need to create your own map. ImmutableMap returns back an optional when you retrieve value and optional itself have map implemented

**Comment by yolotouch** [comment]
Thanks everyone
