### ISSUE TITLE
Lab 4: Use of java.util.Set (Restricted API detected)

### ISSUE THREAD

**Issue by xiang-qiuyu** [nus-cs2030/2324-s2#193]
# Summary
Use of restricted API (java.util.Set) detected.

## Description:

I suspect that the detection of API is when I am looping the entries through the entrySet, however, I am unsure of how to adjust this code so as to not use the API.

## Code Snippets
<img width="544" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/161620098/db648c08-dfe7-489b-8f03-a6a8b39177b4">

## Screenshots

Screenshots (if any)
<img width="171" alt="Screenshot 2024-03-16 162845" src="https://github.com/nus-cs2030/2324-s2/assets/161620098/36312b5e-9c70-4b70-8027-614fabbe747c">

**Comment by lim-4158** [comment]
https://github.com/nus-cs2030/2324-s2/issues/184

the same issue was raised here

**Comment by TongZhengHong** [comment]
You can loop through an `ImmutableMap` directly:
```java
for (Map.Entry<String, Assessment> e : this.map) {
    ...
}
```

**Comment by xiang-qiuyu** [comment]
got it, thank you !
