### ISSUE TITLE
Generics: PECS Principle vs. Function Declaration

### ISSUE THREAD

**Issue by ameliaw286** [nus-cs2030/2324-s2#198]
Hello, I've been grappling with some confusion regarding Java generics and am having trouble reconciling the principles of PECS (Producer-extends, Consumer-super) with the declaration syntax in Java's Function interface. I understand that PECS dictates using extends for producers (when reading from a collection) and super for consumers (when adding to a collection), but I'm unsure why the declaration Function<? super T, ? extends R> is structured the way it is. It seems counterintuitive to me.

My guess is that 'super' and 'extends' wildcards in Function<? super T, ? extends R> are related to the types that the function can accept as input (super T) and produce as output (extends R), and not adding or retrieving elements from collections?

Could someone shed some light on this or point me in the right direction? Thank you!

**Comment by samuelneo** [comment]
> My guess is that 'super' and 'extends' wildcards in Function<? super T, ? extends R> are related to the types that the function can accept as input (super T) and produce as output (extends R), and not adding or retrieving elements from collections?

yes, that's right. when applying the PECS principle, use the perspective of the generic object in question - so for a Function, the Function _consumes_ an input (`? super T`) and _produces_ an output (`? extends R`). I too still find the PECS principle in general a little unintuitive, but maybe this perspective helps

**Comment by ZHD1987E** [comment]
Well said @samuelneo!

**Comment by ameliaw286** [comment]
@samuelneo Yep, that does make more sense, thank you!
