### ISSUE TITLE
hashing? 

### ISSUE THREAD

**Issue by lim-4158** [nus-cs2030/2324-s2#199]
![Screenshot 2024-03-16 at 11 15 46 PM](https://github.com/nus-cs2030/2324-s2/assets/129579903/43c9f679-7f56-47be-b28a-0877d3f42769)

## Description:

What is the difference between the first and second chunk, that allowed and disallowed duplicate keys?

**Comment by LimZiXiong** [comment]
You can try it out in jshell by typing "one".hashCode(). You will realise that each time you do "one".hashCode() the same hash value will be produced. Meanwhile when creating a new object you can type obj.hashCode() and you will realize the hashcode is different

**Comment by lim-4158** [comment]
thanks! makes sense!

**Comment by lim-4158** [comment]
thanks! it makes sense now!
