### ISSUE TITLE
L1 Q4: Data abstraction and a class with has-a relationship and abstraction of behaviour

### ISSUE THREAD

**Issue by Wang-Chuhao** [nus-cs2030/2324-s2#20]
## Question:
Q4: Besides Point and Circle, give another example of a class, together with the abstractions of data and behaviour. Think of another class with a has-a relationship to this first class as its data abstraction, and provide relevant abstractions of behaviour.
Description of the question here.

## Your Contribution:
Maybe a plane object can be defined with two vectors. The vectors can each store 3 values. Building on, a n-dimensional space can store n vectors to help define the space. 
Some of the possible methods can be :
_generateRandomPoint_ input: plane    output: a random point inside the space by multiplying the vectors by random doubles and adding them together
_isOnPlane_ input: plane, point    output: boolean value of if the point is on the plane
_getEigenVector_ input: space output: eigenvector of the space

Just wanted to share what I think of this very interesting question. Please share your thoughts

**Comment by hwkchia** [comment]
We certainly can go with this.  One thing to note is that *generateRandomPoint* will make the method have different outcomes, which goes against effect-free (or side-effect free) programming.  We want the method to have a predictable outcome.

How about providing some code?

**Comment by Wang-Chuhao** [comment]
Thank you Prof for the advice. Writing code for this is beyond my ability. 
I thought about how to make a effect free function in this case and I think maybe this function _generatePlane_ with input: two vectors and output: a plane
I hope by the end of this mod I will work hard and maybe implement this.

**Comment by hwkchia** [comment]
Closed with no further contributions.
