### ISSUE TITLE
Error for lab 4

### ISSUE THREAD

**Issue by andrelau123** [nus-cs2030/2324-s2#201]
# Summary

why do i get this error for lab4?
<img width="1395" alt="Screenshot 2024-03-17 at 12 28 02 AM" src="https://github.com/nus-cs2030/2324-s2/assets/81068338/8e17eef4-a8a0-427f-9cba-735a1b5d1ce3">

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by samuelneo** [comment]
did you import an `Optional` that's different from `java.util.Optional`?
