### ISSUE TITLE
Getting started with Lab 4

### ISSUE THREAD

**Issue by yewkhang** [nus-cs2030/2324-s2#202]
Is Assessment an ImmutableMap? From the desired output it seems that the code below should suffice, and afterwards when creating Course it should contain an ImmutableMap<String, Assessment> where the key is assessment.getKey(). 

But I noticed that Course should also have a .get() method that returns an Optional of the key's value. Does this mean that Course extends from ImmutableMap<String, Assessment>? If so how should I go about doing it? Any ideas on how I should proceed would be appreciated :)

``` Java
class Assessment implements Keyable {
    private final String course;
    private final String grade;

    Assessment(String course, String grade) {
        this.course = course;
        this.grade = grade;
        
    }

    public String getKey() {
        return this.course;
    }

    public String getGrade() {
        return this.course;
    }

    public String toString() {
        return String.format("{%s: %s}", this.course, this.grade);
    }
}
```

**Comment by ZhengJie2001** [comment]
Personally, I did not change anything in my Assessment so i think it should suffice.

yes, you are heading in the right direction. Indeed, Course extends from ImmutableMap<String, Assessment>.

**Comment by ZHD1987E** [comment]
Very soon you'll learn that you put an ImmutableMap into another ImmutableMap into another ImmutableMap...

All of which then transforms into a KeyableMap.

**Comment by yewkhang** [comment]
> Personally, I did not change anything in my Assessment so i think it should suffice.
> 
> yes, you are heading in the right direction. Indeed, Course extends from ImmutableMap<String, Assessment>.

I see... So would something like this be correct? Doesn't seem right to override ImmutableMap's get() method here though(I've tried calling ImmutableMap's constructor when creating course but I can't seem to put or get values from it). Also for Course's toString() is the only way to iterate through the map and print each value, while also checking whether it should include a ","?

``` Java
import java.util.Optional;
import java.util.Map;

class Course extends ImmutableMap<String, Assessment> implements Keyable {
    private final String course;
    private final ImmutableMap<String, Assessment> map;

    Course(String course) {
        this. map = new ImmutableMap<>();
        this.course = course;
    }

    private Course(String course, ImmutableMap<String, Assessment> map) {
        this.map = map;
        this.course = course;
    }

    public String getKey() {
        return this.course;
    }

    public Optional<Assessment> get(Object key) {
        return this.map.get(key);
    }

    public Course put(Assessment a) {
        return new Course(this.course, this.map.put(a.getKey(), a));
    }

    public String toString() {
        String output = this.course + ": {";
        for (Map.Entry<String, Assessment> entry : this.map) {
            output = output + entry.getValue();
        }
        return output + "}";
    }
}
```

**Comment by ZhengJie2001** [comment]
Edit: Oh wait, sorry I meant to say you actually need to extends KeyableMap<String, Assessment> instead of ImmutableMap.

Then you will realised actually Course, Student, etc will extends KeyableMap.

So you just need a toString method in your KeyableMap - what i did is to utilise hasNext(), if there is I will append a ", " into the string.

Hope this helps 👍

**Comment by yewkhang** [comment]
> Edit: Oh wait, sorry I meant to say you actually need to extends KeyableMap<String, Assessment> instead of ImmutableMap.
> 
> Then you will realised actually Course, Student, etc will extends KeyableMap.
> 
> So you just need a toString method in your KeyableMap - what i did is to utilise hasNext(), if there is I will append a ", " into the string.
> 
> Hope this helps 👍

yup it works now ty!
