### ISSUE TITLE
Error: Incompatible Type (FlatMap - Ex5 Level5)

### ISSUE THREAD

**Issue by ZhengJie2001** [nus-cs2030/2324-s2#204]
Error: Incompatible Type, i am not exactly sure how to debug this

![image](https://github.com/nus-cs2030/2324-s2/assets/158128400/1e2ec0c0-9b48-4bbc-8eaf-d43989fc2acd)

**Comment by dnardnar** [comment]
you can look at what flatMap mapping functions return examples given at level5

**Comment by juelin708** [comment]
it seems that your mapper function is returning a type of ? extends R instead of Maybe<R>

**Comment by Jeremythong2002** [comment]
1. The flatMap argument function of flatMap should return a maybe. 
2. Flatmap itself should also return a Maybe object

**Comment by ZhengJie2001** [comment]
yeahh, thanks yall @dnardnar @juelin708 @Jeremythong2002
