### ISSUE TITLE
Main Class not Updating Correctly

### ISSUE THREAD

**Issue by timothyngcy** [nus-cs2030/2324-s2#205]
Hi! Does anyone know why my Main class does not update the roster correctly? I used the following input:

<img width="212" alt="Screenshot 2024-03-17 at 10 11 17 AM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/b3469431-5a27-4088-b46e-d796f8f5623e">

According to jshell, when I typed everything manually, it updated fine:
<img width="652" alt="Screenshot 2024-03-17 at 10 11 47 AM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/a9f07953-ba78-4a8b-8272-6f7023f121ac">

But when I put the inputs into my Main class, the output was different:
<img width="724" alt="Screenshot 2024-03-17 at 10 12 31 AM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/c5c9584a-2cca-4c1f-969b-5b5debdf86cc">

Is there a reason why there was a difference in the output when all the things were input the same way?

This is my Main class:
<img width="422" alt="Screenshot 2024-03-17 at 10 12 56 AM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/44811864-9264-435a-92af-c28d71ff8cde">

Ignore the messed up toString() xD

**Comment by dnardnar** [comment]
try printing the roster outside of the loop? maybe it has to do with toString since your add is working based on the jshell snippet you sent

**Comment by timothyngcy** [comment]
<img width="582" alt="Screenshot 2024-03-17 at 5 45 49 PM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/c4ddbbdf-0b2c-4408-80c5-0e358b1fee42">

i submitted this and i managed to get A... i guess i implemented the scanner wrongly LOL

if anyone knows how to fix my the Main class lmk! thank yous!

**Comment by ZHD1987E** [comment]
Everything looks good to me

**Comment by hadyamanisanto** [comment]
> <img alt="Screenshot 2024-03-17 at 5 45 49 PM" width="582" src="https://private-user-images.githubusercontent.com/142781724/313461389-c4ddbbdf-0b2c-4408-80c5-0e358b1fee42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzIxMTMsIm5iZiI6MTcxMDczMTgxMywicGF0aCI6Ii8xNDI3ODE3MjQvMzEzNDYxMzg5LWM0ZGRiYmRmLTBiMmMtNDQwOC04MGM1LTBlMzU4YjFmZWU0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMzE2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGY3MDExYjk4NDdkMzFkZDA2ZGU0YzNmYmU2MGViZGMyMjMxMjNkOTRhNjUzYzJiNTFhZWVlNTI2NjFmYzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a816FYoIlat7U9nDgC6-iY5MtEoMgks55R_gkNiap-0">
> i submitted this and it works... i guess i implemented the scanner wrongly LOL
>
> if anyone knows how to fix my the Main class lmk! thank yous!

Try to add to roster in the for loop to avoid hardcoding.

**Comment by timothyngcy** [comment]
@hadyamanisanto i did... in my submission but it didn't update properly for some reason

**Comment by hadyamanisanto** [comment]
> @hadyamanisanto i did... in my submission but it didn't update properly for some reason

You don't need newRoster in the Main class.

**Comment by frdyli** [comment]
you can try to update your roster in each time of your for-loop. 
![image](https://github.com/nus-cs2030/2324-s2/assets/150454622/3a58ccfa-cb47-4b34-aef3-518fb1661c17)
The one you did with hardcoding is almost correct already. All you need to do is to remove the manually adding part and have the roster.add(name, course, assessment, grade) within for-loop.

**Comment by timothyngcy** [comment]
My problem is quite similar to #246 and it works fine now!

**Comment by zuoshihua** [comment]
+1 for Gruvbox Theme
