### ISSUE TITLE
how does Course class work 

### ISSUE THREAD

**Issue by lim-4158** [nus-cs2030/2324-s2#206]
# Summary

Course Class
Is the course name the key and assessment the value? 
then how does it work when:
  new Course("CS2040")
does this mean im creating a map with a key without value

And when i do this
new Course("CS2040").put(new Assessment("Lab1", "B")).put(new Assessment("Lab2","A+"))
does it mean im creating a map with 2 values?

**Comment by Jeremythong2002** [comment]
For the first two levels, the Course class contain its name and an ImmutableMap for the Assessments. 

So when initially creating a Course("CS2040") it will be just an empty ImmutableMap. To get the result output by this function call, you can use the name attribute of the Course class. 

When you new Course("CS2040").put(new Assessment("Lab1", "B")).put(new Assessment("Lab2","A+")), it should create a map with two key and two values, one for each respectively. This will return you a Course which stores all the assessments. 

Keyable only has getKey() method, I read it as a hint that the ImmutableMap should take the getKey() from Assessment as the key and the entire Assessment object as the value of the respective key.

**Comment by xinweixw** [comment]
Hello I'm also a bit lost for this part. 

> Course class contain its name and an ImmutableMap for the Assessments.

Does this mean Course is not an ImmutableMap but it contains an ImmutableMap of Assessments? Thank you.

**Comment by Cpkee** [comment]
jshell> new Course("CS2040").put(new Assessment("Lab1", "B"))
$76 ==> CS2040: {CS2040={Lab1:B}}
This is my current output, how do I fix my code so I can just extract the value and not the entire immutableMap?

**Comment by TokPinXiang** [comment]
implement your own toString(), dont need to extend immutableMap

**Comment by TongZhengHong** [comment]
A `Course` object should contain the name of the course followed by a map of assessments associated with it. When you create a new course, you just assign the name of the course. For example, when creating `new Course("CS2030")`:
```java
{
    courseName: "CS2030",
    assessmentMap: {}
}
```

When you call the `put` method to add a new assessment, it would add the `Assessment` object into the `ImmutableMap` (via the `put` method of the `ImmutableMap` class). 

After calling `new Course("CS2040").put(new Assessment("Lab1", "B")).put(new Assessment("Lab2","A+"))`, the course object would look something like this: 
```java
{
    courseName: "CS2030",
    assessmentMap: {
        "Lab1": "B",
        "Lab2": "A+",
    }
}
```

> Does this mean Course is not an ImmutableMap but it contains an ImmutableMap of Assessments? Thank you.

Yes, for the first 2 parts of Lab 4. But for level 3 and beyond, a Course would become a `KeyableMap`

> This is my current output, how do I fix my code so I can just extract the value and not the entire immutableMap?

Override the `toString()` method for the `Course` class to show the desired output as shown in the lab 4

**Comment by jiancheng37** [comment]
when u do new Course("2040"), u are creating an object w name course and and an empty immutable map . When u put assessments, u are adding new entries into your immutable map in your course class
