### ISSUE TITLE
Lab 4 Course toString() method

### ISSUE THREAD

**Issue by jpowcm** [nus-cs2030/2324-s2#208]
## Description:

I'm not sure how to go about implementing the toString() method in the Course class. I tried using values() but it returns square brackets instead. Any help is appreciated, thanks!

## Code Snippets

Attach code snippets (if any)

## Screenshots

my current output:
<img width="681" alt="Screenshot 2024-03-17 at 12 55 39 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156867299/26f2ef28-5154-489b-a081-13a3b18079bc">

**Comment by jpowcm** [comment]
I also just found out that we are to allowed to use values(), can i get other suggestions on how to implement toString() then?

**Comment by weikiatt** [comment]
you can try looping through each item in the immutablemap object, there's an example on how to do that in the exercise

**Comment by jpowcm** [comment]
> you can try looping through each item in the immutablemap object, there's an example on how to do that in the exercise

hi, thanks for the help! i tried that too but im stuck at how i should add commas only between adjacent elements 😭

**Comment by weikiatt** [comment]
check if the string is empty, if its not empty, add a comma then the element, if its empty, just add the element

**Comment by jpowcm** [comment]
> check if the string is empty, if its not empty, add a comma then the element, if its empty, just add the element

solved! thanks so much!
