### ISSUE TITLE
How do i start my Main.java for lab4 level 6

### ISSUE THREAD

**Issue by TokPinXiang** [nus-cs2030/2324-s2#209]

**Comment by weikiatt** [comment]
put the inputs into test.in file, then try typing this into vim or vsc's command prompt
`less test.in`
`javac *.java`
`java Main < test.in`

**Comment by jackclx** [comment]
vim 6.in
copy the text into 6.in
in the main terminal/directory, not in jshell run 
java Main < 6.in
