### ISSUE TITLE
Lab 4 level 2

### ISSUE THREAD

**Issue by JovanFoo** [nus-cs2030/2324-s2#210]
I am creating an assessment object with "" inputs in my Course class constructor. How can I design it such that it do not show the extra curly brackets when i create a course object?

![Screenshot 2024-03-17 at 2 12 46 PM](https://github.com/nus-cs2030/2324-s2/assets/133492195/955b69d4-e992-422d-adde-8650ea9196ad)

**Comment by TokPinXiang** [comment]
well i guess one way u could use if (your imMap is empty()) {String.format("%s: {}", this.key)}
else { your initial code }

**Comment by Jett-Tan** [comment]
Try using iterator

**Comment by JovanFoo** [comment]
Okay thank you!
