### ISSUE TITLE
even square bracket is not allowed???

### ISSUE THREAD

**Issue by jackclx** [nus-cs2030/2324-s2#211]
![Screenshot 2024-03-17 at 2 37 04 PM](https://github.com/nus-cs2030/2324-s2/assets/102727713/2523bb25-8940-4df5-9ad3-f87041a3346b)

everyday im finding some new things banned in cs2030... is it really necessary to even ban the square bracket to select the element in an array??

**Comment by craezydodo** [comment]
try to use sc.next() bah

**Comment by AxeRaye** [comment]
I guess you cannot use the split() method

**Comment by TokPinXiang** [comment]
use next()
for eg,
String studentId = sc.next();

**Comment by Durpfish** [comment]
i think u can try using the next()

**Comment by Bryanngu03** [comment]
Try use sc.next();

**Comment by ZHD1987E** [comment]
No arrays at all.

**Comment by jiancheng37** [comment]
You can try use sc.next()!

**Comment by eleorakow** [comment]
because square brackets would mean that you have created a new array construct which is not allowed ;-;
just use `sc.next()`!

**Comment by hanlinnnnn** [comment]
.next() works brother
