### ISSUE TITLE
Do I need to delete the useless codes for PA?

### ISSUE THREAD

**Issue by jeslynzhou** [nus-cs2030/2324-s2#213]
# Summary
I m not sure if I need to delete all some of the useless code in PA (e.g., the useless getters). Will this affect the similarity?

**Comment by khaixuen** [comment]
hello! i think we can just delete the useless lines of code! i previously asked my TA the same question and her reply was to delete because the grader will delete it while marking anyways

**Comment by jeslynzhou** [comment]
> hello! i think we can just delete the useless lines of code! i previously asked my TA the same question and her reply was to delete because the grader will delete it while marking anyways

Ok!! Thanks!!
