### ISSUE TITLE
Use of restricted API detected. > java.util.Set

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#214]
# Summary
I used ImmutableMap's keySet method, but codecrunch still throw me Use of restricted API detected. > java.util.Set error. may i ask why

Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)
<img width="527" alt="Screenshot 2024-03-17 at 3 12 58 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/b26bbf00-ce88-46f9-b383-432e56b7f66d">

## Screenshots

Screenshots (if any)

**Comment by TokPinXiang** [comment]
use the for loop example they gave u, can use it in toString()

**Comment by xiang-qiuyu** [comment]
i had the same problem! someone told me that you can loop through ImmutableMap directly and the code provided helped me a lot :)

for (Map.Entry<String, Assessment> e : this.map) {
    ...
}

**Comment by itzsihui** [comment]
thank you !!
