### ISSUE TITLE
Method references detected error

### ISSUE THREAD

**Issue by yuntsingg** [nus-cs2030/2324-s2#215]
# Summary

Hi, I got this compilation error that says method references detected, may I ask what that means?

Thank you!

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

![photo_2024-03-17_16-48-50](https://github.com/nus-cs2030/2324-s2/assets/142105948/7967f52f-f3a8-4c11-81a1-b36c7a7cd0d4)

**Comment by kaywoon** [comment]
I am facing the same error too, any help would be much appreciated!

**Comment by ZHD1987E** [comment]
For example…

`X::doSomething`

**Comment by ettenyll** [comment]
I believe method references is when you use "::" in your code. For example: map(Assessment::getGrade) uses method referencing.

**Comment by jiancheng37** [comment]
avoid using :: in your code!

**Comment by allis-g** [comment]
instead of :: try to use -> instead!
