### ISSUE TITLE
Lab 3 Generating too many service times

### ISSUE THREAD

**Issue by Durpfish** [nus-cs2030/2324-s2#216]
# Summary

hello all, when trying to submit my lab3 to codecrunch i keep getting this error of "calling getServiceTime() too many times"
however, according to my code (I've attached snippets of my code which i believe are relevant), i have only called getServiceTime() once ever, in my serving event class. this method is part of my customer class, and i did not call it in my simulator either.
is there any other areas which i may have overlooked that is causing this issue? 

## Code Snippets

// getServiceTime() method in my Customer class:
public Double getServiceTime() {
        return this.serviceTime.get();
    }

// customer ImList constructor in my Simulator class: (this.servicetime -> private final Supplier<Double> serviceTime)
public ImList<Customer> createCustomerList() {
        ImList<Customer> customers = new ImList<Customer>();
        for (int i = 0; i < listArrTimes.size(); i++) {
            double aTime = listArrTimes.get(i);
            customers = customers.add(new Customer(aTime, this.serviceTime, i + 1, 0));
        }
        return customers;
}

// servingEvent constructor in my servingEvent class:
public ServingEvent(Customer customer, double time, int serverID) {
        super(customer, time);
        this.serverID = serverID;
        this.serTime = customer.getServiceTime();
}

**Comment by ZHD1987E** [comment]
Odd…

I’m guessing that your method name of getting the data from the supplier may have to change as well.

**Comment by 0liverkong** [comment]
it could be that you are serving customers that are not intended to be served.

**Comment by Durpfish** [comment]
hi guys i realised the error was in my simulator class, where I my updateServers method (which was called after doEvent) unintentionally produced an extra serve event, hence calling getServiceTime twice for the same exact event.  thanks all for ur input!

if (!e.hasNext(servers)) {
                pr = pq.poll();
                pq = pr.second(); // removes first event
            } else { // adding the next event to the PQ
                pq = pr.second().add(e.doEvent(servers));
            }

            servers = e.updateServers(servers);
            doneCounter += e.customersServed();
            waitTime += e.cusWaitTime(servers);
