### ISSUE TITLE
Strange compilation warning

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#219]
Hi, does anyone know what does this mean and how can I fix it?
![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/a3108ee0-1e7a-4f45-b055-8c44e696eb3f)

**Comment by mChewWW** [comment]
Have you tried javac *.java in vim to check for any compilation errors before submitting to codecrunch? It seems that you have compilation issues in your code.

**Comment by tarshalim** [comment]
i think the error message "Killed" means that your Java program was forcibly terminated, likely due to it using too much memory. maybe you can try to look for any parts of your program that might be using memory inefficiently. try to simplify  those parts and see if it works?

**Comment by hanlinnnnn** [comment]
perhaps run javac *.java and checkstyle *.java in your terminal and observe if theres any error on your end, code crunch does not give the best "explanation" for the error

**Comment by ettenyll** [comment]
hello! I've gotten this twice before on separate exericses. Just wait a while before resubmitting your files. Could be that the program crashed while attempting to run the code. This worked for my friends as well so it should work for you :)

**Comment by minhkiwi14** [comment]
> hello! I've gotten this twice before on separate exericses. Just wait a while before resubmitting your files. Could be that the program crashed while attempting to run the code. This worked for my friends as well so it should work for you :)

Yep, after some basic modifications, I still got through. But thanks a lot!

**Comment by ZHD1987E** [comment]
@minhkiwi14 Mind if you close this issue to clean up the 'issues section'?
