### ISSUE TITLE
PRO-TIP: Don't use Microsoft Edge (especially on Strict Security) on CodeCrunch!

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#22]
Otherwise, it will not submit anything and you will either have to modify your settings, or use another browser!

**Comment by limbenben** [comment]
Is it normal for codecrunch to not run on Chrome or safari?

**Comment by limbenben** [comment]
Yup, so I think my concern is: are we supposed to run it on Microsoft edge (despite the warning?) since it cant run on the other two browsers

**Comment by ZHD1987E** [comment]
It depends on your system configurations. Try running in any browser, tweak the settings and see what works.
