### ISSUE TITLE
Lab 04 Submission not uploaded from Lab

### ISSUE THREAD

**Issue by cyting01** [nus-cs2030/2324-s2#221]
Wanted to check if others have faced this issue so far, as I have seen many threads on Lab 04 being posted here already.
After the lab from last week, my progress was not uploaded to CodeCrunch and there are no submissions/files for me to download. I've checked with people in my lab group as well and they have faced the same problem. I do remember saving all the files and exiting the terminal correctly on Friday. Wonder if the files need to be downloaded from somewhere else? Thanks!

**Comment by neozemin** [comment]
Yup, I faced the same issue as well. I just recoded from scratch.

**Comment by ZHD1987E** [comment]
I think I might be the cause of this ever since I killed my Unix PE node...

So sorry.

**Comment by khooxr** [comment]
Mine was also not uploaded, had to start over again.

**Comment by cyting01** [comment]
Thanks, seems like I'm not the only facing the problem then.
