### ISSUE TITLE
Square brackets detected

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#222]
# Summary
i alr removed the public static main void(String[] args) but codecrunch still throw me Square brackets detected error.  may i ask why?

Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)
<img width="512" alt="Screenshot 2024-03-17 at 10 58 16 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/ed6ee6ea-f523-42b6-a897-d89be6559d8f">
<img width="482" alt="Screenshot 2024-03-17 at 10 58 25 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/b6845170-085f-47d3-81e6-b802bee986a2">

## Screenshots

Screenshots (if any)

**Comment by ZHD1987E** [comment]
Odd…

I literally used public static void main(String[] args) and it worked well.

did you try to initialise an array somewhere? Try using Ctrl+F and putting square brackets and let VSCode search for you (see that you are using VScode)

**Comment by itzsihui** [comment]
oo yeapp, i realised there is an array, thank you
