### ISSUE TITLE
Lab 03 test case 7 

### ISSUE THREAD

**Issue by avrilmohh** [nus-cs2030/2324-s2#223]
# Summary

Able to pass the first 6 test cases, but fail on the 7th test case.

## Description:

Does anyone know what is this test case and why I am failing it?

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/133679903/a8c4b368-7b27-40f5-90e8-b416094672ad)

**Comment by Durpfish** [comment]
hello, u might want to try printing an extra line of code to debug everytime your getServiceTime() is called/ everytime a serveEvent occurs/ everytime you update your server,; this helped to solve my issue and identify which part of my code caused getservicetime() to unintentionally be called, or an extra serveevent to be produced. hope this helps!

**Comment by ettenyll** [comment]
"Too many service times generated" error occurs when getServiceTime() is called more times than there are supposed to be customers served. I had the same issue and realised I had an infinite loop where the customer was stuck at my serveEvent. During debugging I printed an output line everytime the customer transitioned to each event which enabled me to find my error!

**Comment by avrilmohh** [comment]
hmm I did this and the number of serveEvents is correct and when i run it on my system there are 10 generating service times... generated and there are 10 inputs... (as shown in the screenshot) and 1 input is only supposed to generate the service time once so the number seems to be adding up but i cant pass the test case HAHAHHA I appreciate the help though!

![image](https://github.com/nus-cs2030/2324-s2/assets/133679903/0f676003-2c41-4299-b40d-eaa613a4df33)

**Comment by mChewWW** [comment]
You should only call the supplier getServiceTime() method when a customer is being served. Your error means that you are calling it when it is not needed. eg for customers which leave, also take note that calling it in the wrong area (outside of the arrive method) will likely cause you to encounter errors as well.

**Comment by avrilmohh** [comment]
oh i thought getServiceTime() should be called in the serve method? thats what my TA told me

**Comment by ettenyll** [comment]
the number of serviceTimes you generate should = number of customers served which in the example you shared should be 9. if you have 10 serviceTimes that is one too many which would cause the error. maybe check that you only generate serviceTime for the customer when the customer is being served?

**Comment by avrilmohh** [comment]
the number of customers that was served was 9 and number of customers that left was 1 in this test case so it is a total of 10 customers

**Comment by mChewWW** [comment]
> oh i thought getServiceTime() should be called in the serve method? thats what my TA told me

sorry, yes it should be called in the serve method, i had a typo

**Comment by ettenyll** [comment]
> the number of customers that was served was 9 and number of customers that left was 1 in this test case so it is a total of 10 customers

yes, but only those served should have serviceTime^^ the customer that was not served (ie left) should not have a corresponding serviceTime called for them

**Comment by mChewWW** [comment]
> the number of customers that was served was 9 and number of customers that left was 1 in this test case so it is a total of 10 customers

in this case, double check that your getServiceTime() method is called exactly 9 times and not for the customer that left

**Comment by avrilmohh** [comment]
OHHH HAHAHA ok that makes sense my bad

**Comment by mChewWW** [comment]
additionally, if your getServiceTime method is in your serve method as you mentioned, it is abit unusual for customers which leave to even interact with the Serve class at all that may have resulted in you calling it more than needed.  Just something to consider!

**Comment by avrilmohh** [comment]
ok i will think about this! thank you for your help
