### ISSUE TITLE
Unable to log in to CodeCrunch

### ISSUE THREAD

**Issue by nhptrangg** [nus-cs2030/2324-s2#225]
# Summary
When I tried to log in to my account, I have been receiving this message since yesterday.

## Screenshots (if any): 
<img width="702" alt="Screenshot 2024-03-18 at 8 55 36 AM" src="https://github.com/nus-cs2030/2324-s2/assets/153381084/cd48d522-c849-4330-b268-a4a64af80782">

**Comment by ZHD1987E** [comment]
[Please let SOC-RT know about this.](https://rt.comp.nus.edu.sg/techserv)

**Comment by AxeRaye** [comment]
Try leaving it for awhile and log in again later?
