### ISSUE TITLE
Lab 4 Level 5

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#227]
I am trying to figure out a dynamic implementation of the add method of the Roster class for Level 5 without using isPresent() [As part of the restrictions]

<img width="489" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/be7549bd-b6a9-4c2d-a6bc-f642aa793aaa">

Intended output:
<img width="566" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/e671fe36-6d46-4961-9920-de51d73d9f13">

My output:
<img width="566" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/6e378e86-d683-4e01-849a-a43b691908bf">

Any help is appreciated, thank you.

**Comment by ZHD1987E** [comment]
You're literally overwriting stuff.

**Comment by w1nsl** [comment]
Yup, I used orElse() too!

**Comment by hadyamanisanto** [comment]
It worked. Thanks!
