### ISSUE TITLE
FOR THOSE STUCK FIGURING OUT THE ROSTER (ESPECIALLY `ADD`)...

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#228]
# I have one message for you...
Use `.orElse()`!!!

https://github.com/nus-cs2030/2324-s2/assets/140680858/89f1b15e-2b65-46f8-8916-ef74d0821248

sorry if it comes across a bit like kurt tay...

note: this message will close on friday

**Comment by hadyamanisanto** [comment]
Thanks

**Comment by AustinKong** [comment]
Thanks 🔥

**Comment by JosiahPraeman** [comment]
Thank you so much i was also facing issues with my add classs this helped a lot.

**Comment by khooxr** [comment]
Wow! Thanks!

**Comment by kaiju10** [comment]
Thanks, much appreciated

**Comment by jiancheng37** [comment]
thanks !
 :>

**Comment by kziyang1207** [comment]
Thank you so much!

**Comment by kingcard02** [comment]
thanks!!!

**Comment by totallyregi** [comment]
thank you very much!!!!!!!!

**Comment by zarastanline** [comment]
thank you!

**Comment by tanninettt** [comment]
thank you!

**Comment by fishiebloop** [comment]
Thank you!!

**Comment by Bryanngu03** [comment]
Thank you so much Haodong!!!!! ;)

**Comment by m5x4** [comment]
thank you hao dong!!!!!!!!!!!!!!

**Comment by cyting01** [comment]
thank you!

**Comment by KoalaLyfestyle** [comment]
thank you Hao Dong!!!!!

**Comment by jianhaosoh** [comment]
thanks Hao Dong!

**Comment by ZHD1987E** [comment]
You guys know what to do already.

**Comment by hohinnn** [comment]
thanks hao dong!

**Comment by anqixxxx** [comment]
thanks! :D

**Comment by zenlxy** [comment]
great thank hao dong!

**Comment by caleblowy** [comment]
thanks hao dong! :)

**Comment by winghyxn** [comment]
thanks bro

**Comment by brianpang02** [comment]
thanks a lot!

**Comment by Monoji77** [comment]
Thanks bro! This helped me a bunch!

**Comment by jorized** [comment]
Thank you so much for this!

**Comment by yewyaorui** [comment]
thanks a lot !!

**Comment by snatzehua** [comment]
wow thanks man

**Comment by ZHD1987E** [comment]
Now that Lab4 is over (sucks to be true baby!), this shall go down into the archives.
