### ISSUE TITLE
Lab 04 level 3 incompatible type

### ISSUE THREAD

**Issue by ccqie233** [nus-cs2030/2324-s2#229]
# Summary
Incompatible Type Error

## Description:

Hi, my Course Class extends KeyableMap<Assessment>, but jshell told me that there's an incompatible type error i.e. KeyableMap<Assessment> cannot be converted to Course. 

## Screenshots

Screenshots (if any)
<img width="900" alt="Screenshot 2024-03-18 at 2 35 42 PM" src="https://github.com/nus-cs2030/2324-s2/assets/98001460/3ec6d9ee-ece8-4c08-adcc-abf89be623dc">

**Comment by neozemin** [comment]
I think you might want to consider redefining the put(...) method in your subclasses of KeyableMap so they return the appropriate class.

**Comment by jiancheng37** [comment]
this is because .put(new asessment) returns a new KeyableMap<Assessment> but .put(new course) expects a course

**Comment by ccqie233** [comment]
thank you!
