### ISSUE TITLE
Compilation error - instanceof keyword detected

### ISSUE THREAD

**Issue by codingtemp** [nus-cs2030/2324-s2#23]
# Summary

I encountered a compliation error - ```instanceof``` keyword detected when submitting my code on codecrunch.
![image](https://github.com/nus-cs2030/2324-s2/assets/101398907/4382b33b-bf76-448c-b7f3-96509a9fe57c)

## Description:
However, the only ```instanceof``` keyword was used in ImList, which I did not edit. Also, my code passed all the test case when I run it manually in jshell.

## Screenshots
![image](https://github.com/nus-cs2030/2324-s2/assets/101398907/aefb59e6-7f37-4301-b5ad-b30dc4bda8ae)
Screenshots (if any)

**Comment by hwkchia** [comment]
Thank you for your feedback.  When I tested it, I did not submit `ImList.java`.  Anyway, I've tweaked the grader, and regraded your submission.  It should be fine now.

**Comment by Lhanxi** [comment]
Hi Prof @hwkchia, I am currently facing the same issue!
<img width="1605" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/118047094/f0c26a53-81b4-4c3e-9429-bdbba7e66978">

**Comment by ZHD1987E** [comment]
OK everyone...

Do NOT submit ImList.java.

What they only need is your `Circle.java`, `Point.java`, and `main.jsh`.
