### ISSUE TITLE
Exercise 5 Maybe Test Cases

### ISSUE THREAD

**Issue by cyting01** [nus-cs2030/2324-s2#231]
I've managed to pass all the test cases given in the question for Exercise #5 Maybe, but ran into an issue on CodeCrunch.
While I'm unable to see the other lines of code before this, I would assume A and B are of different types and hence the equals method should return a false. However, I'm confused as to why it is not a Maybe<A/B>empty() object after calling filter().
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/0e1e6004-fe98-4470-9ef7-83030bb9ba98)
This is my current implementation of filter.
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/f8aca28f-dcdb-4fa5-9c9d-5f1c7177d7e8)
Any help would be appreciated, thank you!

**Comment by kryst-ll** [comment]
I think you can check your equals method to see if you handled the case where either this or other is empty but not both

**Comment by cyting01** [comment]
Ahh it works now. Yup, I didn't check the case where either of this/obj could be empty. Thank you!
