### ISSUE TITLE
Lab04 level3 : Why does the "put" method need to be overwritten but not the "get" method?

### ISSUE THREAD

**Issue by delulu04** [nus-cs2030/2324-s2#234]
For the Student and Course class which extends KeyableMap, why does only the "put" method need to be overwritten?

## Description:
Since there is a put and get method already defined in KeyableMap, why do I still need to override the "put" method in the Student and Course class?

**Comment by totallyregi** [comment]
The get method doesn't need to be overridden because it typically retrieves an item based on a key, and its behaviour doesn't change based on the subclass. The return type and the logic for retrieval remain consistent across different subclasses of KeyableMap.

**Comment by ZHD1987E** [comment]
If you don’t you will return a KeyableMap, not some Student or Course and that causes a bad crash.

**Comment by frdyli** [comment]
Taking example of a Course class, the put method is overridden because the behavior of adding an Assessment to a Course might differ from adding it to a generic KeyableMap. Additional logic specific to a Course object needs to be executed when adding an assessment. But for the get method in the Course class, its behavior remains consistent with the KeyableMap class. The method retrieves an Assessment based on a given key, and the behavior doesn't need to change in the context of a Course

**Comment by kailincoder** [comment]
Get method is a generic operation that receives ur value, form key. it doesnt need to be overwritten as you can directly inherit from the superclass keyable map. for Put method, u have to override it for based on keys for ur student obj, cos they are unique based on what you are putting

**Comment by Lhanxi** [comment]
<img width="908" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/118047094/ad5f5a20-7d7d-41b7-9776-e224011a15fd">

if you look at the level 2 test cases, you will not be able to assign the output of put method to a Student as a Keyable class is returned. You have to override the put method in student and course to return you the specific class that you need.

**Comment by arinng5** [comment]
put is unique for the class

**Comment by hohinnn** [comment]
The get method just retrieves a value, but put needs to be overwritten as its return type changes based on the subclass

**Comment by tanbeng123** [comment]
By overriding the put method, it allows us to encapsulate the class-specific behaviors within the Student and Course classes, ensuring that they operate according to their intended semantics and constraints.

**Comment by notlynnnn** [comment]
I believe that put have a different return type depending on the subclasses which have different behaviours

**Comment by ZHD1987E** [comment]
@delulu04 Since lab 4 is over for quite some time, mind if you close this issue for others to browse through open issues easier?

Thanks...
