### ISSUE TITLE
exercise5 compilation error

### ISSUE THREAD

**Issue by ka10252** [nus-cs2030/2324-s2#235]
hi i uploaded my code in codecrunch and it is showing such compilation errors:
<img width="1422" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/124032938/fc131b3c-4e7b-44c8-b947-e19cc32161b9">

I'm not sure what is the problem since my code line 28 is:
<img width="264" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/124032938/51cfeeeb-eb7d-4d8a-af5e-b2547dfb9c90">

and 58 is:
<img width="378" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/124032938/573cd5e7-ca3c-4196-8c26-a26903b4492b">

Is anyone having the same trouble?

**Comment by kingcard02** [comment]
idt null is allowed to be used even when comparing values, for L28, maybe can change the method to return this.equals(Maybe.empty())

**Comment by funkypants5** [comment]
for line 57 i wrote consumer.accept(this.value) and it works, maybe you want to try that?

**Comment by Cpkee** [comment]
null is restricted when comparing values

**Comment by jarethlee** [comment]
Try running `checkstyle Maybe.java` on your terminal and check the return. That might be where the issue lies.

I don't think that it is the null value being used since `isEmpty()` was in the base code given to us.

**Comment by ZHD1987E** [comment]
Did it work?

I hope it did.

By the way, you might want to close this issue since there may be much more to come soon on this forum, @ka10252 ...
