### ISSUE TITLE
Maybe.java Flatmap 

### ISSUE THREAD

**Issue by lim-4158** [nus-cs2030/2324-s2#236]
# Description

Prof left this for us to figure out on ourselves. Why cant the code in the screenshot not compile, that is the short form but the code that is commented can compile? 

#Screenshot

<img width="1360" alt="Screenshot 2024-03-18 at 4 56 36 PM" src="https://github.com/nus-cs2030/2324-s2/assets/129579903/958325f7-7c80-47fe-92ba-41a9447f3c20">

**Comment by zuoshihua** [comment]
Prof explained it here in this article

https://github.com/nus-cs2030/2324-s2/wiki/Lecture07#higher-order-methods-in-maybe
