### ISSUE TITLE
toString method for Course class

### ISSUE THREAD

**Issue by pramoth20** [nus-cs2030/2324-s2#237]
Anyone else getting this issue regarding the toString method in their course class? Should i override the default toString of the ImmutableMap using a loop or something, or is there any other way around it? 
![IMG_2344](https://github.com/nus-cs2030/2324-s2/assets/155830463/0bb9cf09-a901-42a0-9e2a-ad0de0b4392e)

**Comment by pramoth20** [comment]
thanks for your tip!! idt im at that level yet haha

**Comment by w1nsl** [comment]
for me i iterated through a ImmutableMap and updated an output string with the toString() method of the values.
so instead of returning the whole ImmutableMap i manually added the toString() of the values to a `String output = ""`

**Comment by mikio13** [comment]
You can try creating your own version of the `toString` method, the default toString of ImmutableMap doesn't give you the desired format. You loop through the map and print the values.  For the loop can try what they gave in the pdf ` (Map.Entry<.., ..> x: ..) {..`

**Comment by pramoth20** [comment]
thanks for the help guys!! for others reference, this is what i did:

    public String toString() {
        String result = this.name + ": {";
    
        for (Map.Entry<String, Assessment> entry : assessments) {
            //loop and add the toStrings
        }
        result += "}";
        return result;
    }
