### ISSUE TITLE
Restricted APIs for Lab 4

### ISSUE THREAD

**Issue by kingcard02** [nus-cs2030/2324-s2#239]
![IMG_0930](https://github.com/nus-cs2030/2324-s2/assets/163496518/fceab46a-48c4-474c-a375-2c59c7088794)
![IMG_0932](https://github.com/nus-cs2030/2324-s2/assets/163496518/6acfe2b8-4058-46fc-8ed9-75c8295b91a9)
![IMG_0933](https://github.com/nus-cs2030/2324-s2/assets/163496518/699cb46c-e3b8-4d53-a87f-aabe05be9226)
![IMG_0934](https://github.com/nus-cs2030/2324-s2/assets/163496518/38ac2aed-44dc-45f8-a039-4c76e75efc17)
the following 4 for Main class as well as Collection API for classes other than ImmutableMap
edit: letting everyone know what APIs are restricted and what will give an instant F so that you do not have to waste time resubmitting

**Comment by frdyli** [comment]
you can try refer to #211 and #184

**Comment by arinng5** [comment]
i did this too and its because i was using the get() method in another class which is not allowed

**Comment by starryfieldz** [comment]
Yup, I think you can try exploring other methods in Optional that will help to return <T>.
