### ISSUE TITLE
Doubts about the content on page 8

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#240]
# Description

Questions on flatmap method being used in stream.

## Topic:

Streams

Question: 
How will the use of 'flatMap' differ from 'map' in terms of stream transformation and what does it mean to flatten the stream?

**Comment by Jeremythong2002** [comment]
The difference is what they return. 

If there is a context where the map method of the context returns another instance of the context, then using map will return an error of bad return type. In such cases we need to use flatMap. 

So, 

map::IntStream -> (Int -> Int) -> IntStream
flatMap::IntStream -> (Int -> IntStream) -> IntStream 

for e.g. in the lecture, in attempting to create a nested loop, 
`IntStream.rangeClosed.map(x -> IntStream.rangedClosed(x,3).map( x -. x * y))`
will throw an error

**Comment by ZHD1987E** [comment]
Hey @JosiahPraeman 

The issues section is quite cluttered, so mind if you close this issue to declutter this section?

Thanks.
