### ISSUE TITLE
Lab 04 Level 3

### ISSUE THREAD

**Issue by Andrew22Teoh** [nus-cs2030/2324-s2#242]
# Summary

I know that one way to solve this level is to override the put() method in the Student and Course classes, but does anyone know of a way to avoid this overriding using Java Generics?

## Description:

Due to the KeyableMap class' .put() method returning a new instance of a KeyableMap, this is not assignable to a Student or Course class. However, it seems like there might be a way to use generics or wildcards to modify KeyableMap's .put() method such that it returns <T extends KeyableMap<V>> T, rather than just KeyableMap. This would help to reduce the amount of duplication necessary, since overriding the .put() method in Student and Course classes means that the KeyableMap's .put() method becomes redundant.

Would anyone happen to be familiar with how this might be possible? Thank you!

**Comment by JingLeEa** [comment]
I don't think it's possible, you would need to implicitly / explicitly cast KeyableMap into type T (Course, Student). Overriding the put() method does this, any other methods seem a bit complicated.

**Comment by AustinKong** [comment]
I agree with what @JingLeEa said, to my information overriding `put()` is the easiest method to do this. But I'd be open to see how other people do it.

**Comment by eleorakow** [comment]
I agree, there's no other way to solve this level without overriding the put() method

**Comment by Andrew22Teoh** [comment]
Thank you for the inputs! I'll leave this up for another day in the hopes that someone is able to come by with a novel approach to this, after which I'll be closing the thread.
