### ISSUE TITLE
Is CodeCrunch down right now?

### ISSUE THREAD

**Issue by jarethlee** [nus-cs2030/2324-s2#247]
# Summary
I've been trying to access codecrunch for the past 1h but my browser keeps showing ERR_CONNECTION_TIMED_OUT. Is there a timeline for when codecrunch will be back online?

## Screenshots (if any): 
<img width="755" alt="Screenshot 2024-03-19 at 1 39 27 PM" src="https://github.com/nus-cs2030/2324-s2/assets/29792236/55e93030-0ed0-44df-b404-6ee57ade05cd">

**Comment by KoalaLyfestyle** [comment]
I had that issue in SoC too but I think its up now.

**Comment by AxeRaye** [comment]
Maybe try to refresh

**Comment by khooxr** [comment]
yea mine isn't working rn either :(

**Comment by Lazyou1734** [comment]
I think it's working now
