### ISSUE TITLE
LAB 4 - Wildcard Usage for Level 3

### ISSUE THREAD

**Issue by walkaround54** [nus-cs2030/2324-s2#249]
# Summary
Hi, I'm a little bit confused as to where I have to used wildcard types in the KeyableMap class, and when I simply declare the type explicitly? I'm trying to broadly implement the PECS framework, but I don't understand when I need to declare wildcard types.

#Details
Here is a screenshot of some errors I am facing when trying to compile:

KeyableMap.java:11: error: unexpected type
        ImmutableMap<String, ? super Keyable> innerMap = new ImmutableMap<String, ? super Keyable>();
                                                                         ^
  required: class or interface without bounds
  found:    ? super Keyable
KeyableMap.java:21: error: incompatible types: Optional<CAP#1> cannot be converted to Optional<Keyable>
        return this.innerMap.get(name);
                                ^
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object super: Keyable from capture of ? super Keyable
KeyableMap.java:37: error: incompatible types: Entry<String,CAP#1> cannot be converted to Entry<String,Keyable>
        for (Map.Entry<String, Keyable> a: this.innerMap) {
                                               ^
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object super: Keyable from capture of ? super Keyable
3 errors

Any help is appreciated, thank you!

**Comment by w1nsl** [comment]
`ImmutableMap<String, ? super Keyable> innerMap = new ImmutableMap<String, ? super Keyable>();`
i think youre not supposed to have `? super Keyable ` when you initialise a new object

**Comment by zuoshihua** [comment]
I don't recall using any wildcards for Lab 4. Anyone solved Lab 4 using wildcards?

**Comment by lim-4158** [comment]
instead of super, try extends. that is because you are tryign to create an immutablemap of objects that implement the Keyable interface. 

hope this helps

**Comment by aeonsparkz** [comment]
Did not use wildcards, I think for wildcards probably dont use during assignment and in constructors but probably can use in your method parameters like map(Function<? super T>, <? extends U>) e.g.

**Comment by kee-x** [comment]
Did not use wildcard for lab 4 as well

**Comment by heezxeo** [comment]
Agreed, for level 3 try sticking with the template given in the description:
class KeyableMap<V extends Keyable> implements Keyable {
    ...
}

**Comment by hohinnn** [comment]
You only require declaration of the generic i.e. V extends Keyable at the top when declaring the class, other than that what I did was just use V for the methods

**Comment by W-WJ-Ryan** [comment]
same i used Class<V extends KeyableMap> for example because technically you can see it as a producer in a way that you are trying to produce this new class which is an implementation of the keyablemap, hence extends instead of super. I would think tha super would be used in a scenario where for example u want to take in something and read it, hence super because you consume it

**Comment by Bryanngu03** [comment]
I didnt use wilcard for this lab, just follow the template given <V extends Keyable>.

**Comment by allis-g** [comment]
highly agree with the rest, even though the description in codecrunch did state that the topic coverage includes generic class, i think that the suggested template of using "extend" will be easier to understand and complete this lab4

**Comment by ZHD1987E** [comment]
@walkaround54 I hope that all of these answered your query.

If it did, you might want to close this issue to declutter this forum. Thank you!
