### ISSUE TITLE
How will our programming environment in labs be like?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#25]
Do we...

1. Use our own devices, or use the ones provided in the programming labs?
2. Have the ability to download any plugins to our development environment (e.g. plugins for syntax and error checking)?

**Comment by hwkchia** [comment]
You will be using the programming labs and connecting to our servers.  As such, no additional plugins.  We want to train our students to code with no reliance on IDEs.

**Comment by ZHD1987E** [comment]
By the way, are we allowed to continue on with our lab work remotely?
