### ISSUE TITLE
KeyableMap<Assessment> cannot be converted to Course

### ISSUE THREAD

**Issue by ethanmanzz** [nus-cs2030/2324-s2#250]
Hi,

When I call my put method in Student to take in a course, it says KeyableMap<Assessment> cannot be converted to Course because Course extends KeyableMap<assessment>. How to overcome this issue?

**Comment by w1nsl** [comment]
maybe you can try overriding your `put()` method in your Course and Student classes to return a Course or Student respectively instead of returning a KeyableMap<Course>

**Comment by zuoshihua** [comment]
How to do this without casting?

**Comment by iceflakes12** [comment]
My way of getting around this is defining a new Course constructor which takes in a KeyableMap, and doing the same for Student. Hopefully this can help you.

**Comment by LMDlifers** [comment]
Your Course class should extend from KeyableMap<Assessment>, not sure if this is your issue.

**Comment by ethanmanzz** [comment]
> maybe you can try overriding your `put()` method in your Course and Student classes to return a Course or Student respectively instead of returning a KeyableMap

Ah, alright makes sense, will try that, thanks!
