### ISSUE TITLE
Lab 4 Level 5

### ISSUE THREAD

**Issue by nicklass8** [nus-cs2030/2324-s2#251]
# Summary

Description of the question / problem here.

I am unable to pass level 5 of Lab 4, specifically the add method in my Roster class. It is able to add new students and new courses but unable to add new assessments. See below for a snippet of my implementation of the add method as well as the issue im facing when testing on jshell.

## Description:

In the screenshot, the roster already has cs2040 with lab1. However, when i try to add test to cs2040, it overrides the lab1 assessment instead of adding it to the back of lab1

## Code Snippets

<img width="614" alt="Screenshot 2024-03-19 at 3 39 40 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163880002/d02ae952-33cf-4459-ba18-f54dc9bc78b5">

## Screenshots

<img width="441" alt="Screenshot 2024-03-19 at 3 37 40 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163880002/97268838-b12e-4c7b-a506-b1191ef6dff5">

**Comment by gnimnix** [comment]
Hi there, not sure why you are doing `course.getKey().equals(...))` and why is there a `break`, are you iterating through the students then checking if the course is the one you are looking for?

Try to print `newCourse`, are both assessments showing up?

**Comment by zuoshihua** [comment]
No need for any `if` checks. Just use `Optional`'s `orElse` method in `Roster`'s `add` method.

**Comment by ccqie233** [comment]
orElse() method will automatically checks whether there's an existing student or not; if there is one, the Student student will be returned, else you can create a new student

this applies to course and assessment as well, then just put back everything

**Comment by Bryanng41** [comment]
You can try Optional<Student> listStudent = this.get(name); to get the student obj 
If its empty it will return an empty optional
Else check if it has a course in it then do it again for course
Put a new Assessment into the new course obj
Then put course into student, then student into roaster

**Comment by LMDlifers** [comment]
Can consider utilizing optional methods such as get() to return the value present within the Optional instance or orElseget() to provide a more flexible way to handle the case where the Optional might be empty. You should incorporate lambda functions to shorten your code a lot as well.

**Comment by iceflakes12** [comment]
Maybe on top of what everyone has said here, the way ImmutableMap works is that duplicate keys can never coexist, so it doesn't matter if you are putting a key-value pair into ImmutableMap that already has the same key, doing so will just override the value associated with that key.

**Comment by Lhanxi** [comment]
If there is already a pre-existing key "CS2040" in the ImmutableMap, your current method will "override" the existing key-value pair when you try to "add" another value with the same key. This is because ImmutableMap has unique keys (if you used python in the past it would be akin to dictionaries). Hence you should use orElse() instead as it allows you to check before adding.

**Comment by zuoshihua** [comment]
*overwrite

**Comment by nickifung** [comment]
You have to check if the student name or course name is already inside, so you can consider using the orElse() function if it isn't. hence you do not have to use if loop to iterate through, after all the orElse() will check if there are existing name inside already. After which you can then use your put method at the end.

**Comment by hohinnn** [comment]
I used the orElse() function too so it helps to check if there is already an existing name, and if there isn't it will create a new course/student, should fix the issue!

**Comment by aeonsparkz** [comment]
It is because of the put method, put removes your original value of your key-value if the key inputted is the same, this is probably why it is not added but instead overwrote the original value with the input.
