### ISSUE TITLE
Restricted API for Lab 4

### ISSUE THREAD

**Issue by ethanmanzz** [nus-cs2030/2324-s2#253]
# Summary
I submitted and I passed all the test cases provided.
However, it seems I have used a restricted API but I do not know what it is because after looking through my code, I do not see any method that came from java.util.Collection.

## Description:
Use of restricted API detected.
> java.util.Collection
Grading terminated.

## Screenshots
<img width="261" alt="Screenshot 2024-03-19 at 4 14 55 PM" src="https://github.com/nus-cs2030/2324-s2/assets/159884036/07d65fd2-b64e-4050-b07b-b486e4bf4c6c">

**Comment by gnimnix** [comment]
You can't call `ImmutableMap::values()`, you have to iterate over the values or do `ImmutableMap::get()`.

**Comment by jwoongg** [comment]
did u use any of the methods that cannot be used such as "isPresent()" , isEmpty?

**Comment by LMDlifers** [comment]
Might want to look out for unnecessary files submitted

**Comment by ethanmanzz** [comment]
> did u use any of the methods that cannot be used such as "isPresent()" , isEmpty?

realised I used .values() method somewhere, fixed it already, thanks!
