### ISSUE TITLE
Course class string output for Lab 4 

### ISSUE THREAD

**Issue by ezclap02** [nus-cs2030/2324-s2#254]
Hi, how do I print the required string output for the ImmutableMap of Assessments in the Course class? 
Currently I have this output.

![image](https://github.com/nus-cs2030/2324-s2/assets/111750139/6e9a6aad-e98c-4e7b-b010-e3bb2b27d7e8)

**Comment by neozemin** [comment]
You can consider writing a toString() that generates the required string directly rather than using the toString() of ImmutableMap

**Comment by hngkxn** [comment]
The default toString() of the ImmutableMap gives the output shown in ur screenshot so we cannot directly use it. To output it like what is required in the exercise, you can try modifying ur toString perhaps by running through each entry of ur ImmutableMap and calling the toString() of ur assessment class, all the best!

**Comment by LimZiXiong** [comment]
And to note when browsing through immutablemap there are some useful stuff you think you can use like values(). They are banned

**Comment by UserNameWasTakenAlreadyy** [comment]
iirc Collections are not accepted on code crunch so take a look at the ImmutableMap class provided again, there should be a method that returns an iterable that will get you values directly.

**Comment by Cpkee** [comment]
you can try to use the for loop method example provided in the top of the Lab4 assignment to print out your desired output as well as the toString() method of the immutableMap.

**Comment by zay-nin** [comment]
Right now you seem to be printing the toString of the map directly. Instead, you should loop through the map and create the final output by concatenating the respective elements of map

**Comment by sophielluo** [comment]
inside your Course`toString()` method, instead of directly printing out the Assessment `toString()` method, try calling the `getValue()`method on map entry (key-value pair) instead. 

For example: 
Assessment `toString()` method will give you `Lab1={Lab1: B}`
Whereas calling `getValue()` method on each map entry will give you `{Lab1: B}`

**Comment by ezclap02** [comment]
thanks everyone!
