### ISSUE TITLE
Compilation errors in codecrunch but not on vim

### ISSUE THREAD

**Issue by mChewWW** [nus-cs2030/2324-s2#258]
Hello, I am getting the following errors when submitting onto code crunch. 
![image](https://github.com/nus-cs2030/2324-s2/assets/156818769/7f091e0e-c126-412e-a2f3-10851e15a86b)

When I javac *.java on vim, I have no compilation errors.
I am submitting the correct files.
I have done import java.util.Optional; for all classes.

I noticed for the following code mentioned in level 4, i get a slightly different output:
![image](https://github.com/nus-cs2030/2324-s2/assets/156818769/fa93d26b-0ce1-4894-8933-851880fa8a1d)
![image](https://github.com/nus-cs2030/2324-s2/assets/156818769/2a134ed6-75a4-4e01-8aae-7632a8af68f8)
I'm not sure how to interpret this difference.

As you can see, the calling object are Optionals of different types, so it is strange that the methods cant be called.

Help would be appreciated!

**Comment by ZHD1987E** [comment]
Jangan Gunan ‘.isPresent()’!

**Comment by mChewWW** [comment]
> Jangan Gunan ‘.isPresent()’!

what do you recommend otherwise?

**Comment by ZHD1987E** [comment]
orElse()

Let the optional worry about the null case, not you!

**Comment by mChewWW** [comment]
> orElse()
> 
> Let the optional worry about the null case, not you!

It works now, thank you! That being said, why is it that the code is able to compile in vim and everything works find in jshell and not in code crunch?

Surely the fact that it works in jshell would imply that everything works smoothly.

**Comment by ZHD1987E** [comment]
They engineer their Optional Class bro…

They took the Optional Class to some workshop in Tuas, changed parts out, and put it back.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BZAStudent** [comment]
hi they limit the use of  these Optional methods

1. .get()
2. isPresent()
3.isEmpty()
4. equals()

**Comment by ZHD1987E** [comment]
That's woight @BZAStudent !

These methods have been **DELETE**

**DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE DELETE**

**Comment by kee-x** [comment]
Hi, you are not allowed to use the isPresent() method for this lab

**Comment by quadryan** [comment]
@ZHD1987E grammar correction! "These methods have been DELETED."

**Comment by ZHD1987E** [comment]
Kurt Tay bro…

[Image.png]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZHD1987E** [comment]
@quadryan

Kurt Tay bro…

One of his gimmicks is to post on his telegram group:

‘X has been BAN’

At one point in time through a voice message he wants ‘Haters will be DELETE’

**Comment by ZHD1987E** [comment]
yay

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
