### ISSUE TITLE
java Error: Cannot find symbol when trying to create new Point 

### ISSUE THREAD

**Issue by squgily** [nus-cs2030/2324-s2#26]
# Summary
Hello, trying to start out with Exercise 01 (At 1st step of Level 1) but keep getting this error: 

```jshell> new Point(0.0, 1.0)
|  Error:
|  cannot find symbol
|    symbol:   class Point
|  new Point(0.0, 1.0)
|      ^---^
```
I don't really understand what does this mean? I am able to execute /open Point.java without any issues
I'm using Mac to code

**Comment by hwkchia** [comment]
You don't have the `Point` class loaded in `jshell`.  If the `Point.java` file is there, then in jshell type:
```
/open Point.java
```

**Comment by squgily** [comment]
Hi prof, thanks for the quick reply. Yes I've typed that in jshell already with the Point.java file in the same folder, but still getting this same error.

**Comment by hwkchia** [comment]
How about `/list Point`?  Do you see the `Point` class?  And is it correct?

**Comment by squgily** [comment]
Hi prof, it returns me 
```
|  No such snippet: Point. 
```

I've also tried opening the file through its file path, i.e. 

```
 /open /Users/user/Point.java 
```
But I still get the same result.

**Comment by LimZiXiong** [comment]
I had the same problem as well but turns out my point.java I didnt close the class with } so even though when I do /open point.java without error the file didn't load
