### ISSUE TITLE
Lab 4 Level 5: printing of updated roster after being added

### ISSUE THREAD

**Issue by hzhitong** [nus-cs2030/2324-s2#261]
# Summary
Problem: I'm unsure about the correct method to print the updated roster after using the add() function. Currently, my code prints the entire roster instead of just the updated portion according to the test case. I attempted to address this by printing only the new update via a new roster, but this approach doesn't align with the test case requirements either. Do i create a new toString() method in the Roster class? I'm uncertain about the exact requirements of the question.

## Code Snippets
input: jshell> roster.add("Natasha", "CS1231", "Test", "A-")
expected output: $.. ==> AY1920: {Natasha: {CS2040: {{Lab1: B}}, CS1231: {{Test: A-}}}}
my output: $.. ==> AY1920: {Natasha: {CS2040: {{Lab1: B}}, CS1231: {{Test: A-}}}, Tony: {CS1231: {{Test: A-}}}}

input: jshell> roster.add("Natasha", "CS2040", "Test", "A-")
expected output: $.. ==> AY1920: {Natasha: {CS2040: {{Lab1: B}, {Test: A-}}}}
my output $.. ==> AY1920: {Natasha: {CS2040: {{Lab1: B}, {Test: A-}}, CS1231: {{Test: A-}}}, Tony: {CS1231: {{Test: A-}}}}

thank you in advance!

**Comment by W-WJ-Ryan** [comment]
i think you can define a new updated toString method in the roster class that overrides the one which u may have in KeyableMap, but you can still abstract out the similar parts and try to reuse the code as much as possible. Because based on the output seems like your roster is having double of the string? You can try not printing in the add method but rather print in initialising a new roster

**Comment by ccyenn** [comment]
you may be assigning the edited roster to the original roster

**Comment by eleorakow** [comment]
did you add Tony into the roster before doing this? As it seems like your code is working fine, just that Tony is in the roster as well. maybe you accidentally did `roster = roster.put(Tony)`

**Comment by zi-yii** [comment]
Agree with the others that it is likely you assigned the edited roster to the original roster in your code. Instead, this assignment is done by the client and not in the add method

**Comment by hzhitong** [comment]
I will work on the suggestions, thank you so much guys!
