### ISSUE TITLE
Complilation Errors 

### ISSUE THREAD

**Issue by Bryanng41** [nus-cs2030/2324-s2#262]
# Summary
Compilation warnings

## Description:

Does anybody know why this error is occurring? It does happen in VIM

## Screenshots

![Screenshot 2024-03-20 161549](https://github.com/nus-cs2030/2324-s2/assets/52643493/44bc58be-81cd-44e0-aa54-c123da76f784)

**Comment by KoalaLyfestyle** [comment]
What do you mean by it does happen in VIM? Maybe you can try to compile the file with -Xlint to check the errors, otherwise try to upload again?

**Comment by Bryanng41** [comment]
I dont know why but after I submitted again it ran normally

**Comment by KoalaLyfestyle** [comment]
haha codecrunch just acts weird sometimes
