### ISSUE TITLE
lab 4 level 6 wrong output

### ISSUE THREAD

**Issue by zenlxy** [nus-cs2030/2324-s2#263]
## Description:

does anyone know why my code prints out the wrong output? thank you!

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="252" alt="Screenshot 2024-03-20 at 5 19 34 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157443693/555a7faf-d822-48d5-8d67-8cf7bcc47472">

**Comment by winghyxn** [comment]
can you try printing out your roster to see if it is generated correctly?

**Comment by zenlxy** [comment]
i've printed out my roster and it is generated correctly

**Comment by winghyxn** [comment]
yea you should check your getGrade() function again

**Comment by zenlxy** [comment]
<img width="672" alt="Screenshot 2024-03-20 at 5 53 30 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157443693/66265141-aee0-4580-94c8-831dcaf5dc55">

i realised that my roster generates the wrong output as only one course is printed out for each student

**Comment by winghyxn** [comment]
i think ur add method may be wrong then

**Comment by lim-4158** [comment]
does your level 5 work? 

level 6 code depends on wether your previous levels code work

**Comment by zenlxy** [comment]
yup levels 1-5 work!

**Comment by zenlxy** [comment]
thank you all i've solved it!
