### ISSUE TITLE
Lab 4 Level 6

### ISSUE THREAD

**Issue by KoalaLyfestyle** [nus-cs2030/2324-s2#264]
# Summary

Not very sure how to handle the Main class.

## Description:

I have implemented the Main class in a similar way to lab 3's Main.java, using `java.util.Scanner`. I used the following signature:
```java
class Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        ...
    }
}
```
However, CodeCrunch gave me a compilation error: `Square brackets detected`. If I change `String[] args` to `String args`, It gives me another error as shown in the screenshot below.

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/146793482/deeaec1e-fa7c-4884-a86a-79d6ba5ddb75)

![image](https://github.com/nus-cs2030/2324-s2/assets/146793482/8a4d00a7-a1a4-4905-b692-d74698b873a6)

**Comment by nicklass8** [comment]
Hi you are allowed to use String[] args in your main class for the void main method. However you cannot use square brackets anywhere else in your main class. Hope this helps!

**Comment by KoalaLyfestyle** [comment]
Thank you! I have resolved the issue, closing it now.
