### ISSUE TITLE
Lab 4 Level 3 Question on abstraction principle

### ISSUE THREAD

**Issue by iannntsw** [nus-cs2030/2324-s2#265]
Question: My KeyableMap class implements a put method that takes in a key-value pair of type V as mentioned in level 3 of Lab 4. As such, does creating put methods in other classes such as Course, Student and Roster that extends and overrides the put method in the KeyableMap class violate the abstraction principle ?

Clarifications: I ask this because implementing just the put method in the KeyableMap class alone returned me errors such as "KeyableMap<Assessment> cannot be converted to course" when i try to use the put function of adding courses to students and students to rosters.

Let me know if further clarification is needed

**Comment by lim-4158** [comment]
I am not too sure if it violates the abstraction principal but the problem lies within the generic class where the put method could only return a keyable type. 

and in your course and student class, the return method for put would need to be course and student respectively. 

and keyablemap is more general thatn course and thus cannot be converted. 

the only way to solve this is to create overriding methods even though the code may be repeated.

**Comment by wkleow123** [comment]
no it does not break abstraction barrier because the idea is that you want to return a KeyableMap object after using put of which Course, Student, Roster are all subclasses of KeyableMaps

**Comment by LimKaiWei** [comment]
at level 3 what should the is `put` method signature look like? i know the return type is `KeyableMap<V>` but the parameter as type `V` gives me issues like OPs `KeyableMap<Assessment> cannot be converted to course`. also is `KeyableMap<Course>` a subtype of `Student`?

**Comment by brianpang02** [comment]
> at level 3 what should the is `put` method signature look like? i know the return type is `KeyableMap<V>` but the parameter as type `V` gives me issues like OPs `KeyableMap<Assessment> cannot be converted to course`. also is `KeyableMap<Course>` a subtype of `Student`?
> 
> edit: i found out you were not suppose to abstract out the put method since the return type for each put method for each subclass is different

from the test cases u can see keyablemap is a course, keyablemap is a student, not the other way round (ie keyablemap is a subtype of student). to return a course, you might want to have a new constructor in course which calls the parent's constructor and copy the values of the key and immutablemap over.

**Comment by hanlinnnnn** [comment]
> > at level 3 what should the is `put` method signature look like? i know the return type is `KeyableMap<V>` but the parameter as type `V` gives me issues like OPs `KeyableMap<Assessment> cannot be converted to course`. also is `KeyableMap<Course>` a subtype of `Student`?
> > edit: i found out you were not suppose to abstract out the put method since the return type for each put method for each subclass is different
> 
> from the test cases u can see keyablemap is a course, keyablemap is a student, not the other way round (ie keyablemap is a subtype of student). to return a course, you might want to have a new constructor in course which calls the parent's constructor and copy the values of the key and immutablemap over. this creates a new course with the updated immutable map.

do u mean that course is a keyablemap<assessment> and student is a keyablemap<course> ? also my understanding is that KeyableMap's put method takes in a V but when u put an assessment into a course, if u do not override the put method to return a new course but a keyablemap<assessment>, this would cause problems when u try to put this "course" into the student as this "course" is a keyablemap<assessment> rather than a course, and if u want to pass it into student's put as a course then u would have to explicitly typecast it to course

am i understanding it right? but actually why can i not just have student's put return a keyablemap<keyablemap<assessment>> rather than a student

**Comment by hzhitong** [comment]
Hi Ian!  Adding put methods in classes like Course, Student, and Roster that tweak the put method from the KeyableMap class is totally fine and doesn't break the abstraction principle. This principle is all about keeping the nitty-gritty details hidden and offering a clear way to use things. In your situation, changing the put method in subclasses is a smart move to give a tailored implementation that suits each subclass, while still sticking to the overall idea of the put method from the KeyableMap class. As long as the new put methods keep the same overall vibe and purpose as the original, you're all good and keeping in line with the abstraction principle. Hope this helps!

**Comment by allis-g** [comment]
hi im sure it will not violate the abstraction principle and you will definitely need to override the put method of your KeyableMap class in other classes so as to get the desired output

**Comment by brianpang02** [comment]
> > > at level 3 what should the is `put` method signature look like? i know the return type is `KeyableMap<V>` but the parameter as type `V` gives me issues like OPs `KeyableMap<Assessment> cannot be converted to course`. also is `KeyableMap<Course>` a subtype of `Student`?
> > > edit: i found out you were not suppose to abstract out the put method since the return type for each put method for each subclass is different
> > 
> > 
> > from the test cases u can see keyablemap is a course, keyablemap is a student, not the other way round (ie keyablemap is a subtype of student). to return a course, you might want to have a new constructor in course which calls the parent's constructor and copy the values of the key and immutablemap over. this creates a new course with the updated immutable map.
> 
> do u mean that course is a keyablemap(assessment) and student is a keyablemap(course) ? also my understanding is that KeyableMap's put method takes in a V but when u put an assessment into a course, if u do not override the put method to return a new course but a keyablemap(assessment), this would cause problems when u try to put this "course" into the student as this "course" is a keyablemap(assessment) rather than a course, and if u want to pass it into student's put as a course then u would have to explicitly typecast it to course
> 
> am i understanding it right? but actually why can i not just have student's put return a keyablemap(keyablemap(assessment)) rather than a student

yep, you will have to override the put methods in course and students to return a new course and student respectively. u cannot just have student's put return a keyablemap since we cant assign Student student = student.put(__) since keyablemap is not a student. (however, student is a keyablemap)

**Comment by ZHD1987E** [comment]
@iannntsw Since lab 4 is over for quite some time, mind if you close this issue? Thanks.
