### ISSUE TITLE
Why is the <R> type not specified in here?

### ISSUE THREAD

**Issue by HaoZeHuin** [nus-cs2030/2324-s2#268]
![photo_2024-03-20_20-48-03](https://github.com/nus-cs2030/2324-s2/assets/155894600/2c1f6f6f-fb4a-4475-9f22-3410b0978c6c)

This was from recitation 6 guide. Why is there no <R> type sepcified when trying to invoke the methods Try.fail and Try.ok in this case. Shouldnt it be required since we cannot return a pure Try?

**Comment by brianpang02** [comment]
if im not wrong it is ok because it is type-inferred. since u can be sure that the output from the function is something more specific than R, it automatically creates a Try object of type R.

**Comment by HaoZeHuin** [comment]
oh i see thankyou
