### ISSUE TITLE
KeyableMap constructor error

### ISSUE THREAD

**Issue by ezclap02** [nus-cs2030/2324-s2#269]
Hi I get this error message when trying to run the files in jshell. Why does KeyableMap need to have a construtor with no arguments?

![image](https://github.com/nus-cs2030/2324-s2/assets/111750139/85f06c73-1529-4549-8bd9-bafa88c516ae)

**Comment by quadryan** [comment]
Or did u happen to not close a curly bracket? }

**Comment by hanlinnnnn** [comment]
Are you trying to instantiate a KeyableMap with a constructor that does not take in any arguments? The Course and Student constructors are supposed to take in a String, so if you do super(String) it wouldnt work if you don't have the right constructor in KeyableMap

**Comment by brianpang02** [comment]
the error does not mean that you need to have a constructor with no arguments, just that there are no constructors available for the arguments that u are calling the constructor with. you might want to check your constructors to see if there is one to fit your arguments

**Comment by ezclap02** [comment]
Thanks everyone for your help :)
