### ISSUE TITLE
Why are the `of` methods not declared static?

### ISSUE THREAD

**Issue by erichugy** [nus-cs2030/2324-s2#270]
# Description

In the github notes of Lecture 4 on Generics, why is it that the `of` methods are not declared static in the ImList class in the snippet below? Without the `static` keyword, how can you call these methods? When I try, my jshell throws me an error (and, at least according me, understandably so).

```java
import java.util.ArrayList;
import java.util.List;

public class ImList<E> {
    private final ArrayList<E> elems;

    private ImList() { // constructor is private
        this.elems = new ArrayList<>();
    }

    private ImList(List<E> list) { // constructor is private
        this.elems = new ArrayList<>(list);
    }

    static <T> ImList<T> of() {
        return new ImList<>();
    }

    static <T> ImList<T> of(List<T> list) {
        return new ImList<>(list);
    }

    // I added the code below
    public String toString(){
        return elems.toString();
    }

}

```
## Topic:

Static Methods
Generic Methods

## Screenshots

Here's the one of the errors when I try to run 
```java
/open ImList.java
List<Integer> list = List.of(1, 2, 3)
ImList.of(list)
```

```jshell
jshell> ImList.of(list)|  Error:
|  non-static method <T>of(java.util.List<T>) cannot be referenced from a static context
|  ImList.of(list) // ImList<Integer> type-inferred implicitly since list is List<Integer>
|  ^-------^
|  Warning:
|  unchecked call to <T>of(java.util.List<T>) as a member of the raw type ImList        
|  ImList.of(list) // ImList<Integer> type-inferred implicitly since list is List<Integer>
|  ^-------------^

```

**Comment by ZHD1987E** [comment]
That might help:

https://docs.oracle.com/javase/tutorial/java/generics/methods.html

**Comment by zuoshihua** [comment]
> In the github notes of Lecture 4 on Generics, why is it that the of methods are not declared static in the ImList class in the snippet below?

It is most likely a typo since it is written immediately after the code block that both `of` methods are static.

> Here's the one of the errors when I try to run

`List`'s `of` method is generic. Therefore you must specify the type. In your case,

```java
List<Integer> list = List.<Integer>of(1, 2, 3);
ImList.<Integer>of(list);
```

**Comment by hwkchia** [comment]
Yes, it's a typo.  Fixed.
