### ISSUE TITLE
Rest Time Not working properly

### ISSUE THREAD

**Issue by yolotouch** [nus-cs2030/2324-s2#272]
When I try and run the test case 3, my server 1 and 2 is not resting after done serving 3 and 2 respectively. My current implementation is that in the Done class, if the rest time is >0, I will create a new Rest event. I will also make the server not idle (cannot serve customer immediately even if queue is empty), and return the updated serverlist too.

CodeCrunch answer:
<img width="264" alt="Screenshot 2024-03-21 at 12 18 55 AM" src="https://github.com/nus-cs2030/2324-s2/assets/148688315/3b5d4b5c-dfb5-4591-ba4e-8c72bf38d132">

My output:
![Screenshot 2024-03-21 at 12 19 14 AM](https://github.com/nus-cs2030/2324-s2/assets/148688315/3deceddf-be8b-4244-98a8-d5b7f2d8aef4)

Could anyone please suggest any areas that I'm missing out? Thank you!

**Comment by huangtian666** [comment]
hihi, for me i create a rest event regardless of the rest time. if the rest time is 0, it just has no effect on the server's available time and the rest event will be my terminating event. 
and you might also need to change some parts of your wait event as now the customers need to wait until the server has finished resting. you cant just return a serve event even if the customer is the first one in the queue. this depends on how u implemented your wait event. but i experienced the same problem before i changed my wait event.

**Comment by yolotouch** [comment]
hmmm okay thanks, so in the wait event, I would also have to check whether the wait event's time is greater than the server's next available time?

**Comment by huangtian666** [comment]
because i have a waitAgain event that keeps returning the waitAgain event until the server is available again, i checked if the time of the event == the server's available time. hope this helpss :)
