### ISSUE TITLE
java.util.set private case

### ISSUE THREAD

**Issue by urmothergei** [nus-cs2030/2324-s2#276]
# Summary
i submitted my code on codecrunch but i keep facing the issue of "java.util.set" detected. I cannot see where I have utilised this set since I have never imported java.util.set package for any of my class. i suspect the problem might come from my toString() method in my KeyableMap class below. 

Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="401" alt="Screenshot 2024-03-21 141034" src="https://github.com/nus-cs2030/2324-s2/assets/126307515/eb118cb0-6795-4d29-a7c2-8df238666b35">

**Comment by zzhengweii** [comment]
the issue is in your this.map.entrySet() as this method belongs to the ImmutableMap class which uses java.util.set, instead you can easily loop through this.map by using the code prompt given in Code Crunch.

**Comment by jennipho** [comment]
I also faced this issue - what helped me was that I didn't run through the set and instead just the map in my for loop, aka I did .... : map instead of .... : map.entrySet() - this is provided in CodeCrunch!

**Comment by allis-g** [comment]
^^ yes you should just use entry : map directly or refer to the ImmutableMap.java code provided to us as reference!
