### ISSUE TITLE
Lab 4 level 3 

### ISSUE THREAD

**Issue by zzhengweii** [nus-cs2030/2324-s2#277]
when I implement **KeyableMap<V> put( V item) { ...}**, i tried calling **item.getMap()** but I will face the error of incompatible types, does anyone know why is this the case?

**Comment by urmothergei** [comment]
i think the error arises due to the fact that item is of a generic type V. try to initialize a new KeyableMap<V> that initializes the this.map.put(item.getKey())

**Comment by zzhengweii** [comment]
ooooo i see thank you !!
