### ISSUE TITLE
Getting msys to point to correct jdk

### ISSUE THREAD

**Issue by ChinZJ** [nus-cs2030/2324-s2#28]
# Summary
Error thrown using "alias" junction.

## Description 
Following the instructions, under "[Setting up unix for java development](https://github.com/nus-cs2030/2324-s2/wiki/Setting-up-Unix-for-Java-Development)", I have created a junction for my user that has spaces in between (eg. "A B C", junction "A" created.

However, after running the following command, 
`echo "PATH=/c/Users/A/scoop/apps/openjdk17/current/bin/:\$PATH" >> ~/.profile

source ~/.profile`

The following error was thrown:
`sh: B: command not found`

Is there a manual way to check if this "pointing" has be done regardless of the error thrown?

Edit: This error is being thrown for subsequent commands requiring user access ie. the shortcut for checkstyle.

**Comment by hwkchia** [comment]
If you are using `junction` as your alias, then your path should also be using `junction` rather than `A`?

**Comment by ChinZJ** [comment]
Sorry, for clarification I have used the command `mklink /j A"A B C"`
