### ISSUE TITLE
Lab 4 Restricted API 

### ISSUE THREAD

**Issue by tannorine** [nus-cs2030/2324-s2#280]
# Summary

Received this Compilation error in CodeCrunch, even though my code compiles in terminal 

Use of restricted API detected.
> java.util.Collection
Grading terminated.

Only imported java.util.Collection in ImmutableMap and I did not upload it onto code crunch

**Comment by ykwong2002** [comment]
hi norine! i think its because you used a .values() method, which returns a Collection. But since we dont have any methods to deal with collections, we should get the Map.Entry<String, V> type instead using the getValue() method!

**Comment by tannorine** [comment]
noted I have resolved the issue, thank you for your help!
