### ISSUE TITLE
Lab 04 Level 2 Unable to use .values()

### ISSUE THREAD

**Issue by yfongsin** [nus-cs2030/2324-s2#281]
The toString method for Course requires us to have the values of the ImmutableMap. However, we are not supposed to use the .values() function. I tried using the for loop method but I am unsure how I can add the ", " for every entry except the last entry.

**Comment by LimZiXiong** [comment]
You can just add the ", " normally and use substring to remove the last 2 character

**Comment by omgacai** [comment]
instead of using values() you can try using iterator() instead, its defined in the ImmutableMap class, you can check that out

**Comment by eleorakow** [comment]
additionally you can initiate a count to check if it is the last object if it is not , then add a ", " if  it is then just print out the entry

**Comment by meowmeowpeepee** [comment]
You can use a StringBuilder type, which allows you to remove elements inside the String, which String objects does not allow you to.
StringBuilder str = new StringBuilder();
and StringBuilder `delete` method allows you to remove the extra ", " at the end

**Comment by nidia-ww** [comment]
you can try to define a boolean and if it is true, it will add "," to the output (this being in the loop)

**Comment by allis-g** [comment]
you can try to define a boolean in the loop of map and when it is true, add "," to the output

**Comment by hanlinnnnn** [comment]
1. concat {
2. implement a for loop to add comma after every value
3. if the map is not empty, substring() to remove the latest comma
4. concat }

**Comment by RatesLearner** [comment]
Instead of using values(), I found that iterator() in the ImmutableMap class could be a better option. It's pretty neat because it lets you iterate through the elements of the map smoothly.

As for the toString() method, after adding each element, I opted to check if the iterator has a next element using an if clause. If it does, I add a comma and space to separate the elements.

**Comment by jwoongg** [comment]
add the "," before every value in your for loop

**Comment by frdyli** [comment]
you can try using the substring method where 
.substring(int beginIndex, int endIndex)
then your endindex can be (output.length()-2)

**Comment by IYKYKY** [comment]
you can also try iterating through Map.Entry<String, V>, getValue() method is useful here. first you check whether the output string is empty, if it is, then directly concatenate getValue(), if not, add a ", " and then use getValue() to concatenate.

**Comment by TongZhengHong** [comment]
Most answers here check for the last entry, or remove the addition "," from regular concatenation. You can consider doing the opposite, by checking the front instead, which only needs you to check for the **first** entry (which is simpler) 

Inside your for-loop: 
1. If `index == 0`, just print out the entry
2. Subsequent entries, add "," before printing the entry

To check for the first entry, you can also check if the resulting string (which is initially declared to be empty string "") is empty "", signifying that no entry has been appended to it yet.

**Comment by ZHD1987E** [comment]
@yfongsin You may have finished Lab 4, so you might want to close this issue and declutter the forum, thanks!
