### ISSUE TITLE
Cyclic dependency

### ISSUE THREAD

**Issue by HoSCD** [nus-cs2030/2324-s2#284]
# Summary
How is this possible if my Nutri class does not reference my Drink class, etc?

## Screenshots (if any): 
<img width="216" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158131860/9fc70dd4-2bdc-4306-95ea-a23af606508a">

**Comment by urmothergei** [comment]
I have this issue before. its because of cyclic dependency despite what it looks like. as seen in your error section.
