### ISSUE TITLE
Exercise 5 level 4

### ISSUE THREAD

**Issue by nicklass8** [nus-cs2030/2324-s2#286]
## Description:

Facing some issues with regards to the implementation of the or method in level 4 of exercise 5. Why cant my Supplier<Maybe<Integer>> be converted to Supplier<Maybe<? extends Object>> when Integer extends Object?

## Code Snippets

![Screenshot 2024-03-21 at 11 35 42 PM](https://github.com/nus-cs2030/2324-s2/assets/163880002/f20edf2b-937f-4fd5-896a-e30dd90e5811)

## Screenshots

![Screenshot 2024-03-21 at 11 36 18 PM](https://github.com/nus-cs2030/2324-s2/assets/163880002/01af787d-8e47-4a50-a797-af4fb77674a9)

**Comment by samuelneo** [comment]
`Maybe<Integer>` can be converted to `Maybe<? extends Object>`. However, a `Supplier<Maybe<Integer>>` cannot be converted to a `Supplier<Maybe<? extends Object>>` (remember: generics are type-invariant). you might need a `? extends Maybe`

**Comment by nicklass8** [comment]
oh i get it now thanks for the help!
