### ISSUE TITLE
Project help

### ISSUE THREAD

**Issue by w1nsl** [nus-cs2030/2324-s2#288]
hi i am having trouble passing this test case and i cant figure out why,  can anyone help me out?
<img width="601" alt="Screenshot 2024-03-22 at 12 23 56 PM" src="https://github.com/nus-cs2030/2324-s2/assets/148077346/00c6d6a8-4ae7-4c56-b5d5-b67548e1a18c">

**Comment by itsokkk** [comment]
Check your arithmetic for the different events. Ensure the correct time is passed.

**Comment by eleorakow** [comment]
it looks like an issue with your self check queue, 13 should be at the front of the queue however for your code 15 is at the front of the queue instead and is being served first

**Comment by Zhengtat** [comment]
Maybe something went wrong with your queuing mechanism. Perhaps you can look at which events you add 1 to Q and which events you remove 1 from queue and also whether the correct version of the server is being used to add/remove from the Q.

**Comment by marshchxstxrmello** [comment]
note that at self-check 3, it is first self check out counter where customers queue. At line 37, notice that 13 serves at self-check 3. In other words, 13 waited and was also served by 3. The expected output for this test case wants ur code to be flexible for 13 to accept any SCC (self-check 3,4,5 ... onwards). Therefore they wanted customer 13 to be served at self check 4 as at event time(0.862), it was the most readily available SCC to serve customer 13
