### ISSUE TITLE
Discrete event simulator

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#289]
# Summary
Multiple outputs detected

## Description 
When i submit the codes on code crunch, it throws this compilation error saying multiple outputs detected. What does this mean?
![Screenshot 2024-03-22 145539](https://github.com/nus-cs2030/2324-s2/assets/111676024/4e188c49-0080-4c98-9c81-4c7da1fc1031)

**Comment by itsokkk** [comment]
I got the same problem too, and fixed it when I removed extra print statements. I think you must ensure there's no extra outputs.

**Comment by Cpkee** [comment]
getServiceTime() can only be called once

**Comment by eleorakow** [comment]
make sure that you only have one output and delete all other print statements!

**Comment by jurongWest** [comment]
I fixed mine for the project by combining all my outputs into one String variable in the simulator :)

**Comment by Lhanxi** [comment]
don't submit Main.java and DefaultServiceTime.java files onto codecrunch as they contain print statements

**Comment by wdgyn** [comment]
Make sure that you don't have any print statements(in the case of debug purposes)

**Comment by ZHD1987E** [comment]
I hope that you managed to fix it. If you did, as a courtesy to those in the forum you might want to close this issue.

Thanks @JosiahPraeman !
