### ISSUE TITLE
Try-catch or throw detected, grading terminated

### ISSUE THREAD

**Issue by kingcard02** [nus-cs2030/2324-s2#291]
# Summary

Description of the question / problem here.

## Description:

Very puzzled as to why this happens? Are we not supposed to throw IllegalArgumentException: Invalid arguments for invalid inputs as stated in the test case for level 1? If that is not the case what am I supposed to do? Thanks.

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

![Screenshot 2024-03-22 174538](https://github.com/nus-cs2030/2324-s2/assets/163496518/3b06925c-0f0d-4fdd-bd0a-12527b08bf83)
![Screenshot 2024-03-22 174554](https://github.com/nus-cs2030/2324-s2/assets/163496518/a131931b-e600-4b63-a3cb-28e9a3c3ef55)

**Comment by chloetohce** [comment]
hi, we should be using the `orElseThrow` method

**Comment by ZHD1987E** [comment]
Moreover, don’t ever do this:

`public X doSomething() throws SomeError`

**Comment by 763312** [comment]
Hello! You can try using orElseThrow from the optionals class!
