### ISSUE TITLE
lab 5 level 1 error

### ISSUE THREAD

**Issue by zenlxy** [nus-cs2030/2324-s2#292]
## Description:

does anyone know why i get this error? i used orElseThrow once in each of my of methods and my code works on jshell as well, any help is appreciated thank you!

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="340" alt="Screenshot 2024-03-22 at 6 04 12 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157443693/30e238ff-edf0-402c-96e4-b918df5e78ac">

**Comment by isaacyclai** [comment]
You're probably only allowed to use it once in the whole class. If you're doing it for both of methods, try calling one in the other instead to eliminate the need for using orElseThrow twice!

**Comment by ZHD1987E** [comment]
That’s exactly what I did.

**Comment by zenlxy** [comment]
thanks all!
