### ISSUE TITLE
Q&A 22 MARCH 2023 LAB 5

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#293]
~~So hi, everyone! I am superstar celebrity Gold Medallist Kurt Tay! It's true! It's true! It's true! It's real! It's real! It's real!~~

~~_does some wrestling gimmick_~~

~~Today I answer my questions post on my Telegram Group! If you have more questions, you ask on the comments section!~~

Never mind, let's not resort to Kurt Tay-style Q&A.

---

# Walaowei. Why I get so many `flatMap` like Kurt Tay saying '10! 10! 10! 10! 10!' (esp. those of you who kena retribution at level 5 but never knock down by car 🚗🚘🚙🏎️ and lorry 🚒🛻🚚🚛)

https://github.com/nus-cs2030/2324-s2/assets/140680858/e71df01f-05b8-4edc-8adc-d5fb9e546c94

_just replace that with `log`. you get the idea_

It means that you have used too many `flatMap` in your recursion call. Don't concatinate them! See the 'Recursion' section for more info.

**In simple words, you only use one `flatMap` per recursion call. Not tutututututu `flatMap` and certainly not 10 10 10 10 10 `flatMap`**

How does it work? They use a custom function that prints out each time `flatMap` was called.

# Can use iteration in `level5.jsh` meh?

> while-loop for-loop iteration has been BAN

If you do, it will detect that you are using these and it throws an error. Not like this message in Kurt Tay's chat when he bans someone and [certainly not him screaming at the void deck of Block 225 Yishun Street 21](https://www.youtube.com/watch?v=Mkqj7EcKzC0).

How? Good ol’ Recursion. You have to. See below if you're scared of it.

# I get an error saying that I can’t use Try-Catch or Throw!
That’s because you are either explicitly using those things, or you declare on your method that you will throw an error. Example below:
`public class doSomething() throws Exception()`

What should you do? Since you’re asked to use an Optional, you might as well use `orElseThrow()` to throw the error, and not include `throws` on the method declaration.

# What? I can’t use `orElseThrow()` more than once?
Actually, if you have two `orElseThrow()` calls, it’s likely that your two `of()` methods look similar and you could do some abstraction. In fact, you can regard one of those methods as if you passed an empty string! Go figure!

# I don't know how to use `Optional.ofNullable()` to handle cases of null!

Hint: Optional has `.map()`, `.flatMap()`, and `orElseThrows()`. Do some incremental development! Also see the 'Recursion' section.

Moreover, if you dare to use these:
> - `.isPresent()`
> - `.get()`
> - `.isEmpty()`
> - `.of()`

You ~~will get trapped in the next lift you ride~~ cannot compile. Why? They have an custom `Optional` class without these methods! ~~That means now you will have to press the intercom button and wait for someone to come rescue you, or if you're really desperate, call 995 to free you.~~ _Never mind about getting stuck in the lift._

# My `equals()` method is being wonky when I reverse the order being passed!

This especially happens in one of the private test cases, and you may get frustrated at what classes A and B are. Here's an example of what might happen:

`Log.<Object>of(new A()).equals(Log.<Object>of(new B()))` evaluates as true, but `Log.<Object>of(new B()).equals(Log.<Object>of(new A()))` evaluates as false!

Well, your equals() method is just too tightly bound, when that happens type narrowing happens and it might not be what you want.

Remember the PECS (Producer _Extends_, Consumer _Super_) principle, and use wildcards!

# Wah piang! The recursion so chim! Recursion is HATER! Recursion has been BAN! Recursion, DON'T [REDACTED] ME OFF 📴!

Woah woah woah, don't resort to screaming at your void deck and banning anyone whose name includes 'Recursion'.

Consider this example:

```
public static Log<Integer> fib(int n) {
    if (n == 1) {
        return Log.<Integer>of(1, "multiply by 1");
    } else {
        String toSay = String.format("multiply by %s", n);
        return fib(n-1).flatMap(b -> Log.<Integer>of(n, toSay).map(a -> b * a))
    }
}
```
To make it simple as possible (although if Kurt Tay was reading this he'll go '_Har?_')...
Think of these
- `fib(n - 1)` shall be the next Log object that give birth.
- `.flatMap(b -> Log.<Integer>of(n, toSay).map(a -> b * a))` shall be what you want to do to said Log object after it gives birth.
- `Log.<Integer>of(1, "multiply by 1")` is your base case.

Or if this helps, when n is 4, it is somewhat like this:
```
Log.<Integer>of(3,"mynameissuperstarkurttay").flatMap(b -> Log.<Integer>of(4,"thewwewrestlingchampion").map(a -> b * a))
```

Hey, since `a` = 4 and `b` = 3, you know what's gonna happen since you did recursion at _Programming Methodology I_

Hopefully that makes it a bit clearer when you try to create the `level5.jsh` monstrosity. Play around with it and don't play it on the road because you will kena knock down by car🚗🚙🚘 and lorry 🛻🚚🚛and die 👻💀☠️🪦!

# My logs all screwed up bro! Now my logs all look super duper funny.

Relax. If you think about it...

```
Log[1]**\n**doSomething**\n**doSomethingElse
```
leads to you printing:
```
Log[1]
doSomething
doSomethingElse
```

Wait a sec, can't you chain them and is there some relationship in the string?

The answer is:

Yes!👌Yes!✅Yes!✔️Yes!👍

What pattern? All up to you!

# CodeCrunch is HATER! CodeCrunch tolling me asking me put JavaDoc comments! I hate trollers trolling even though I like trolley bag!

**Update: This might not be required since the autograder is revised. If it still requires JavaDoc comments, read on!**

Apparently, I suspect the autograder is broken, so in the meantime you might want to put nonsensical JavaDoc comments. Anyway, CS2030 doesn't really require documentation.

For example, that IS my JavaDoc code for one of the methods:
```
    /**
     * Lol.
     */
    public boolean equals(Log<? super T> somethingElse) {
        ...
    }
```

Oh! It's true! It's true! It's true! It's real! It's real! It's real!

To @hwkchia :
---
I think there is something wrong with the autograder regarding JavaDoc comments, mind if you check?

# JSHELL IS A [EXPLETIVE] HATER!!! I ALREADY [EXPLETIVE] OFF!!! 📴 ~~I MORE MENTALS THAN WEN LOONG!!!~~

Not sure what went wrong? Try creating a Java class and put a main method below like this

```
public class YourClassNameGoesHere {
    public Log<Integer> f(int n) {
        // your code goes there
    }

    public Log<Integer> sum(int n) {
        //your code goes there
    }

    public static void main(String[] args) {
        System.out.println(f(5));
        System.out.println(sum(5));
    }
}
```

# Can use `instanceof` meh?

Well well well, you guess you guess you guess 你猜你猜你猜!

The answer is:

Yes!👌Yes!✅Yes!✔️Yes!👍

If cannot use this word, how to check leh? Be god ah?

# CodeCrunch call my phone number and tell me I use 'other non-private method', should I curse back at CodeCrunch?

I imagine this is what you might have gotten... **TOTALLY FICTIONAL**
> CodeCrunch: Hello, is this ZHD1987E?
> Me: Yes, why?
> CodeCrunch: We're calling to tell you that you used non-private methods
> Me: [cue a whole load of cursing and labelling CodeCrunch a 'scammer' and a 'fraud']

1: CodeCrunch will not call your phone number
2: Even if you curse at CodeCrunch like [Kurt Tay being called by a fake security agency called HG Security](https://www.youtube.com/watch?v=346LqB7h-N4), it's likely a bot and not a human being.

Still, from my understanding these are the ONLY public methods allowed:
- map
- flatMap
- of() [with or without message]
- equals

All others should be made private.

# BONUS: Can you code for me?

Well well well, you guess you guess you guess 你猜你猜你猜!

The answer is:
**No!⛔No!🚫No!🙅‍♂️No!🙅‍♀️**s!

The moment I code for you, we kena karma and retribution and will ~~be knock down by car🚗🚙🚘 and lorry 🛻🚚🚛and die 👻💀☠️🪦~~ will have a plagiarism hearing and that won't end well (F for this course, bad mark on transcript)!

# BONUS BONUS: I feel my lab TA isn't doing the job properly

If you REALLY feel that your lab TA just really suck at the job (e.g. read off the slides in a boring manner, comes off as rude or condescending) and NOT because you dislike the person or some trivial reason...

I have one image to summarise everything:

![Smile! You're on Camera](https://github.com/nus-cs2030/2324-s2/assets/140680858/5cc20c7e-6587-4b19-b925-20e808a389be)
_Smile! You're on Camera! Yes, I take stock images off Google..._

You do the following:
- Gather ALL evidence that your Lab TA is not doing your job properly (e.g. Telegram chat records)
- E-mail the professors to let them know your greviences
- On course feedback, go ahead and leave constructive criticisms (**DO NOT BRIGADE AND LEAVE RUDE COMMENTS!**)

NUS and the teaching staff will take action accordingly if it is serious enough.

---
Q&A will be dynamically updated when more questions appear.
Q&A behaviour inspired (a bit) Kurt Tay's Q&A style, though much more civilised. You can watch a real one [here](https://www.youtube.com/watch?v=otAewRErSAk).

Unfortunately, I can't replicate Kurt's behaviour.

If you want to see more of Kurt's antics, here is his [live chat (pirated)](https://t.me/Chaoahgualive) and here is the [cleaner version](https://t.me/kurttayupdates).

**Comment by 763312** [comment]
Thanks Hao Dong! That's really insightful!

**Comment by yeeejieee** [comment]
hi how did you solve the equals part, did you use any typecasting?

**Comment by MarcusLiangg** [comment]
Thanks Hao Dong for sharing!

**Comment by feliciahmq** [comment]
wow thanks haodong!

**Comment by kziyang1207** [comment]
Thank you! This is very helpful!

**Comment by AustinKong** [comment]
I also faced the "use `orElseThrow` more than once" issue, your insight on abstraction helped clear it up. thanks!

**Comment by ZHD1987E** [comment]
@yeeejieee ~~answer in 2 April 2024 Q&A~~ just joking.

I just decided to use the `equals()` method, since every single object has to implement it someway.

You know, think of it as 2.0 (as a double) equal 2 (as an integer), it will evaluate as true!

**Comment by yeeejieee** [comment]
@ZHD1987E oh ok thank u

**Comment by jurongWest** [comment]
Thanks for sharing :)

**Comment by JingLeEa** [comment]
Thank you for the recursion tip using `flatMap`!

**Comment by kingcard02** [comment]
thanks!! very helpful

**Comment by Bryanngu03** [comment]
Thank you Haodong!!

**Comment by zzhengweii** [comment]
thank you bro you are the goat

**Comment by khaixuen** [comment]
glad that i saw this post before starting on my lab so ik what to avoid! thank you zhd!

**Comment by JosiahPraeman** [comment]
Thanks haodong you are so knowledgeable! I think you deserve the most hardworking student for CS2030 award.

**Comment by CSnoobCS** [comment]
Although rather dramatic, this is indeed a helpful post. Good to take a look before starting on the lab.

**Comment by ZHD1987E** [comment]
Hey at least it is fun to read!
________________________________

**Comment by Light0009** [comment]
Thanks for this post

**Comment by jaiwee** [comment]
thank you for the read !

**Comment by jorized** [comment]
Thanks Hao Dong! Really helped me a lot with level 5!

**Comment by harvestingmoon** [comment]
Thanks for the post Hao Dong, its quite insightful

**Comment by HoSCD** [comment]
Thanks Hao Dong!!!

**Comment by phantomeng** [comment]
thank you kurtkishi kurtista kurtberg raikurt

**Comment by lim-4158** [comment]
you covered all problems that i faced in this lab bro. thanks for your contribution!

**Comment by ZHD1987E** [comment]
@phantomeng want REAL Kurt antics? Go search 'Kurt Tay Updates' on Telegram!

**Comment by jianhaosoh** [comment]
Thanks Hao Dong!

**Comment by owokays** [comment]
Thanks for this post, really helped when I could not understand how do do some of the things in lab 5.

**Comment by ziyuanchong** [comment]
Thank you ! this is so helpful

**Comment by starryfieldz** [comment]
Wow that was really an insightful sharing. Thanks for sharing, it was so helpful!!

**Comment by kailincoder** [comment]
Thank you for the insightful sharing!

**Comment by hadyamanisanto** [comment]
Thanks, Hao Dong!

**Comment by dlkw13** [comment]
Thank you Hao Dong for the insightful sharing, it really helped!

**Comment by hadyamanisanto** [comment]
Thanks, Hao Dong!

**Comment by Slyriss** [comment]
Thank you! This is rly useful!
