### ISSUE TITLE
How to implement rest time?

### ISSUE THREAD

**Issue by 763312** [nus-cs2030/2324-s2#294]
# Summary
Hi guys im a bit lost on how to implement rest time... any help would be greatly appreciated... Thanks!

**Comment by jarrenoh** [comment]
After a human server serves a customer it has a random chance to rest. This is checked by using calling the .get() from its rest time supplier which will return either 0.0 (it doesnt rest) or a non-zero double.  So what you should be doing is to check if a server has a non-zero rest time and if so, make it such that the other events are know its next available time.

**Comment by huangtian666** [comment]
hii, i implemented the getRestTime() in my server class. I also created a Rest class that extends from Event. then in my Rest class, i update my server's availableTime using getRestTime().

**Comment by UEr-nAMe** [comment]
its quite similar to the Supplier of serviceTime in the previous round:) but instead of calling it on each customer, try call it on the servers. and when the get() method get called, a double resting time would be generated

**Comment by ZHD1987E** [comment]
OK...

So, when your human worker finish serving Person Number 1, there is a chance that this worker take a rest of a random time.

If there is indeed a rest time, the next person that arrives will have to enqueue and wait for the worker to finish taking his rest (cough cough Kurt Tay slacking and using multiple phones in his job as a Security Officer), or if the person is away and there is no way to queue, abandon the purchase lor.

**Comment by Zhengtat** [comment]
It also depends on your implementation. For me, I did not use a Rest Class, so I placed my getRestTime() in my Done Class. Also also, to avoid generating the rest time twice, it may be useful to have your getRestTime() method initialise the rest time as part of the server's attribute by returning a new server.

**Comment by bzastudent293** [comment]
Hi, how do we make sure that the customer is only dequeued after the server has finished resting?

**Comment by ZHD1987E** [comment]
@bzastudent293 Just get the next time it's available lol.

**Comment by bzastudent293** [comment]
Sorry I meant like how do we dequeue the server correctly, because right now a new customer who arrives  is being added to the queue of a server who is resting when the queue should not be modified during that time?

**Comment by jarrenoh** [comment]
For me i didnt change how my customers are dequeued. iirc the server thats resting is still able to accept customers into its queue just that it wont serve them. As for transitioning to a serve event, ensure that the customer is able to check the next available time of the server after its done resting

**Comment by ZHD1987E** [comment]
For me, I literally maintain a counter object that counts how many people are on the queue, so that when someone gets dequeued, the counter decreases.

**Comment by 763312** [comment]
Thanks everyone for the kind help! going to close the thread now.
