### ISSUE TITLE
Project level 11

### ISSUE THREAD

**Issue by UserNameWasTakenAlreadyy** [nus-cs2030/2324-s2#296]
# Summary
Anybody know whats going on here?

## Description 
I understand that i must find the earliest possible selfcheckout server to serve but i dont think im doing it right.

## Screenshots (if any): 
<img width="410" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/97379279/53133b87-679e-48a5-bcb7-8447ca9144b6">

**Comment by ZHD1987E** [comment]
Yes, earliest possible self-checkout. That means something may have been wrong with how you update event times.
