### ISSUE TITLE
The Log method in level 1 of lab 5

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#297]
# Summary

Trouble writing the method without having to use instanceof, javareflection

## Description:

I am facing an issue in my method as i only can use one orElseThrow inside the method and the codecrunch rejects instanceof, getclass() and the isinstance below so what else can i implement in the method to prevent breaking of banned java syntax for this lab?

![Screenshot 2024-03-23 010113](https://github.com/nus-cs2030/2324-s2/assets/111676024/6344df3d-6f9b-4ae2-9cee-6e6f70a61ccb)

**Comment by ZHD1987E** [comment]
`instanceof` can be used to check if it belongs to the same class lol.

**Comment by mikio13** [comment]
The 2 different `of` methods actually look similar, so you can implement the of method shown in your image, then the 
`<T> Log<T> of(T value) ` version can just call the one in your image and input an empty String for log. This way you only use 1 orElseThrow.

**Comment by ArkAzrael** [comment]
> The 2 different `of` methods actually look similar, so you can implement the of method shown in your image, then the `<T> Log<T> of(T value) ` version can just call the one in your image and input an empty String for log. This way you only use 1 orElseThrow.

They are asking how to check for Log though without reflection or class() methods and not how to call the of method with 1 argument.

**Comment by JosiahPraeman** [comment]
ok thank you ArkAzrael and mikio i will look at the method again.

**Comment by JovanFoo** [comment]
you can directly utilise Optional.ofNullable(log) within the lambda expression. 
example: .flatMap(x -> Optional.ofNullable(log))

**Comment by ZHD1987E** [comment]
I hope it all works for you. As a courtesy of those in the forum, mind if you close your issue yeah?

Thanks @JosiahPraeman !
