### ISSUE TITLE
Checking for log with method overloading

### ISSUE THREAD

**Issue by ArkAzrael** [nus-cs2030/2324-s2#298]
# Summary

Tried writing a separate of method that takes in an Log instead of a U, hoping this will work.

## Description:

Java still prioritises the of method that takes in (U u) instead of (Log l)

**Comment by ArkAzrael** [comment]
I ended up just writing a new method that had a different name that took in an Optional instead and it worked.

**Comment by TongZhengHong** [comment]
Can you show some code snippets and elaborate more about the problem?

**Comment by samuelneo** [comment]
the check for whether the input is a `Log` shouldn't be done using method overloading. remember that within a class, you are you to use `instanceof` to check whether objects are of the same class

**Comment by ArkAzrael** [comment]
I basically did

static <U> Log<U> of(U u) {
      return of (Optional.ofNullable(u), "");
}

static <U> Log<U> of(Log l) {
      return of (Optional.empty(), "");
}

but Java still utilises the first of method. I gave up on it and decided to just rework how I check for Log instead.

**Comment by ArkAzrael** [comment]
> the check for whether the input is a `Log` shouldn't be done using method overloading. remember that within a class, you are allowed to use `instanceof` to check whether objects are of the same class

I was unaware of this, since I was told you could only use instance of within the .equals() method we overwrote
