### ISSUE TITLE
Exercise 5 level 4

### ISSUE THREAD

**Issue by caleblowy** [nus-cs2030/2324-s2#306]
# Summary

![Screenshot 2024-03-23 174822](https://github.com/nus-cs2030/2324-s2/assets/163880189/5468ce19-2937-46f9-94dd-06d0f6141eff)

## Code Snippets

Attach code snippets (if any)

## Screenshots
![Screenshot 2024-03-23 172706](https://github.com/nus-cs2030/2324-s2/assets/163880189/6f983789-8eee-4f04-9223-0cd170d46165)

Screenshots (if any)

**Comment by samuelneo** [comment]
you might want to refer to #286

**Comment by jpowcm** [comment]
generics are type invariant: meaning Supplier<T> cannot be converted to Supplier<S> even if T <: S, but Supplier<T> can be converted to Supplier<? extends S>. so in this case, the or method should probably take in a Supplier<? extends Maybe<? extends T>> instead

**Comment by caleblowy** [comment]
ok understood thanks all for the help
