### ISSUE TITLE
Exercise 5 unchecked cast

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#308]
<img width="891" alt="Screenshot 2024-03-23 at 5 46 44 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/62e9c9fa-8cd3-4720-9c41-dbf6bd13350a">
may i ask why do i keep getting this error?

**Comment by itzsihui** [comment]
my error is with regards to level 5 flatMap method

**Comment by ArkAzrael** [comment]
You are doing explicit casting of result to (Maybe<U>) when it was instantiated as a Maybe<T>.

**Comment by itzsihui** [comment]
oo thank you
