### ISSUE TITLE
lab 5 level 1 try catch

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#309]
# Summary

Description of the question / problem here.
for lab 5 level 1, may i ask how do i get around the issue where i cannot use try - catch?
## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="421" alt="Screenshot 2024-03-23 at 7 00 37 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/4816f94c-e358-4157-892a-2fee45799f33">

Screenshots (if any)

**Comment by samuelneo** [comment]
use `Optional::orElseThrow` instead

**Comment by Bryanngu03** [comment]
I used something like this Optional.ofNullable(…)... at the end . orElseThrow(new Exception…….)

**Comment by itzsihui** [comment]
thank you so much
