### ISSUE TITLE
Test case 5

### ISSUE THREAD

**Issue by ya-en** [nus-cs2030/2324-s2#31]
May I know what is this test case testing for? 
<img width="363" alt="testcase5" src="https://github.com/nus-cs2030/2324-s2/assets/156638191/2df128b2-cacf-4c4f-a48b-c7458112b849">

**Comment by ZHD1987E** [comment]
I think this is to catch certain edge cases (for example, if the point is just within the circle)...

**Comment by ZHD1987E** [comment]
So what you do next is…

Check the original question (and the code) to see what they need from you.

**Comment by jpowcm** [comment]
Hi I am facing the same issue, could anyone provide a hint?
