### ISSUE TITLE
discrete event simulator help

### ISSUE THREAD

**Issue by bzastudent293** [nus-cs2030/2324-s2#310]
# Summary
Hi, was anyone stuck at this test case, I can't seem to figure out what this test case is trying to test? I verified that the rest time supplier is only called once.

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="424" alt="Screenshot 2024-03-23 at 10 28 28 PM" src="https://github.com/nus-cs2030/2324-s2/assets/134027838/64936310-1a6b-4509-8e10-35f324501991">

**Comment by marshchxstxrmello** [comment]
it seems that server 1 is not being updated with its supposed rest time after 0.313. Expected a rest time from (0.313 to 0.627). since u say u called rest time, maybe u did not update server 1 next available time(wif a rest time) prior to '1 done 1 serving 1'

**Comment by bzastudent293** [comment]
Ohh I see, I will check that, thank you.
