### ISSUE TITLE
Lab 5 Level 1: How to check if string is null

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#311]
# Summary

Description of the question / problem here.

## Description:

tried to use .flatMap(Optional::ofNullable) to check if string is null but when i run 

jshell> try { Log.<Integer>of(5, null); } 
   ...> catch (Exception e) { System.out.println(e); }
java.lang.IllegalArgumentException: Invalid arguments

the illegak argument exception does not trigger

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by LimZiXiong** [comment]
I flatMap my Optional.ofNullable(value) x -> Optional.ofNullable(String).map(...). If Optional.ofNullable(String) is null then I am flatMapping my value to null which will then trigger orElseThrow

**Comment by ZhengJie2001** [comment]
what i did was i return Optional.ofNullable then filter flatMap orElseThrow

**Comment by jorized** [comment]
You can try to use Optional.ofNullable(t) to check if the value is null, followed by the filter method to filter out any Log instances, then followed by the flatMap, whereby the value will be parsed onto another Optional.ofNullable, but this time with the string inside! The value can then be mapped to return a new Log object if it is not null. Don't forget your orElseThrow too, which is the last operation after the flatMap!

It will look something like this : .flatMap(x -> Optional.ofNullable(log).map(y -> new Log<T>(x,y)))

**Comment by dingus891** [comment]
try to use the ofNullable method found in optional to check the value before proceeding

**Comment by weiyangng** [comment]
managed to use @LimZiXiong's idea and managed to get the answer by filtering for the instance of Log before using flatmap
