### ISSUE TITLE
Lab 5 question 4 

### ISSUE THREAD

**Issue by dingus891** [nus-cs2030/2324-s2#312]
Hello all! for level 4 im having trouble passing a testcase where 
Log.<Integer>of(5).flatMap(x -> Log.<Integer>of(x)).equals(Log.<Integer>of(5)) // monad right identity
is giving false rather than true 

    public <R> Log<R> flatMap(Function<? super T, ? extends Log<? extends R>> mapper) {
        if (this.value == null) {
            return Log.of(null, "null");
        } else {
            Log<? extends R> lg = mapper.apply(this.value);
            return Log.<R>of(lg.getValue(),this.log + "\n" + lg.getLog());
        }
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj instanceof Log<?>) {
            Log<?> other = (Log<?>) obj;
            if (this.getValue().equals(other.getValue())) {
                return this.getLog().equals(other.getLog());
            }
        }
        return false;
    }        
 
 with the following as my code. to be honest I cant really decipher whats wrong I saw something about empty strings is the flatmap but to be honest im not sure how that works any assistance would be really appreciated thank you!

**Comment by mChewWW** [comment]
i'm not sure if its recommended to equate this.value == null here

**Comment by mChewWW** [comment]
maybe try using an optional to check null?

**Comment by joshuagde** [comment]
the issue is the blank spaces in the cases when either one of the logs are empty so your current method will give outputs that have blank lines between them which then might not be equal to the other thing. So basically you need to account for this using some if statements or using Optional

e.g
Log[6]

add 1


VS

Log[6]
add 1

**Comment by jorized** [comment]
Hi, this happens because of the concatenation of the "\n". This is because when you use the flatMap, you are adding an additional "\n". As such, when comparing with an empty string, it is not the same. 

A suggestion could be to create a private method to return the "\n" output only if both strings are not empty.

e.g.  

  if (this.log.isEmpty()) {
      return newLog;
  } else if (newLog.isEmpty()) {
      return this.log;
  } else {
      return this.log + "\n" + newLog;
  }

**Comment by mChewWW** [comment]
> the issue is the blank spaces in the cases when either one of the logs are empty so your current method will give outputs that have blank lines between them which then might not be equal to the other thing. So basically you need to account for this using some if statements or using Optional
> 
> e.g Log[6]
> 
> add 1
> 
> VS
> 
> Log[6] add 1

i agree! i recommend using optional though, as something similar might come out for PA2 so you should learn how to do it here

**Comment by dingus891** [comment]
> the issue is the blank spaces in the cases when either one of the logs are empty so your current method will give outputs that have blank lines between them which then might not be equal to the other thing. So basically you need to account for this using some if statements or using Optional
> 
> e.g Log[6]
> 
> add 1
> 
> VS
> 
> Log[6] add 1

so basically even if they have this difference they should still return true yes

**Comment by joshuagde** [comment]
> > the issue is the blank spaces in the cases when either one of the logs are empty so your current method will give outputs that have blank lines between them which then might not be equal to the other thing. So basically you need to account for this using some if statements or using Optional
> > e.g Log[6]
> > add 1
> > VS
> > Log[6] add 1
> 
> so basically even if they have this difference they should still return true yes

You need to make it such that it doesnt have this difference

**Comment by dingus891** [comment]
> Hi, this happens because of the concatenation of the "\n". This is because when you use the flatMap, you are adding an additional "\n". As such, when comparing with an empty string, it is not the same.
> 
> A suggestion could be to create a private method to return the "\n" output only if both strings are not empty.
> 
> e.g.
> 
> if (this.log.isEmpty()) { return newLog; } else if (newLog.isEmpty()) { return this.log; } else { return this.log + "\n" + newLog; }

hi! in regards to this would newLog be the log you get after using flatMap?
