### ISSUE TITLE
lab 5 level 1 2XorElseThrow

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#313]
# Summary

Description of the question / problem here.
hii we cannot use 2 orElseThrow, and i have been trying to get around with the problem as shown in my code, but nothing seems to work, any help would be appreciated, thank you 

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)
<img width="755" alt="Screenshot 2024-03-24 at 1 15 16 AM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/c766d0a6-c91a-4d84-a0c6-2f4026263728">

## Screenshots
<img width="842" alt="Screenshot 2024-03-24 at 1 15 32 AM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/943c0fcc-4c1c-49bc-ad17-b911e1bdbd60">

Screenshots (if any)

**Comment by zuoshihua** [comment]
A couple pointers:
1. Consider using `.filter()` to filter out those that are `instanceof Log`
2. Create another `Optional` containing `log`. This will allow `.orElseThrow()` to react accordingly

**Comment by jaiwee** [comment]
maybe u could try doing a .filter() before doing a .flatmap() to filter out the nulls first !

**Comment by ArkAzrael** [comment]
Change it to .map(v -> Optional.ofNullable(log).map(f -> new Log<U> (v,f))).orElseThrow(() -> new IllegalArgumentException())

Right now your are replacing null logs with "" which is an empty string.
empty string=/=null value and so will not throw the exception

**Comment by itzsihui** [comment]
thank you all !

**Comment by cyting01** [comment]
I would like to clarify what is the issue with my code. I understand the logic provided by @ArkAzrael but when I try to compile it I run into this error.
Am i right to say that if at any moment of my pipeline I have an empty Optional, it will throw the IllegalArgumentException when it reaches the end? (Due to the orElseThrow definition)
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/ef0dc0e5-0cba-4199-a471-bf31b624caf4)
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/03983c7e-371b-4534-bafc-17eb60c9ab0f)

**Comment by cyting01** [comment]
Managed to fix it by casting the new Log created to type <T>.

**Comment by totallyregi** [comment]
> I would like to clarify what is the issue with my code. I understand the logic provided by @ArkAzrael but when I try to compile it I run into this error. Am i right to say that if at any moment of my pipeline I have an empty Optional, it will throw the IllegalArgumentException when it reaches the end? (Due to the orElseThrow definition) ![image](https://private-user-images.githubusercontent.com/153883538/316319219-ef0dc0e5-0cba-4199-a471-bf31b624caf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDQyNDIsIm5iZiI6MTcxMTYwMzk0MiwicGF0aCI6Ii8xNTM4ODM1MzgvMzE2MzE5MjE5LWVmMGRjMGU1LTBjYmEtNDE5OS1hNDcxLWJmMzFiNjI0Y2FmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNTMyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWU5NTI4ZDc4ZmM4ZGNmNjhmMGQzMTU3ODJmOWI5MzBkNjQ2MmExZTJlMTdmYmU0Y2VlYzBmMWJlY2VlYTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HLDyobmnhX0NHE40pz_Jh_pbRak40BGu1xJE5Yqzm-c) ![image](https://private-user-images.githubusercontent.com/153883538/316319364-03983c7e-371b-4534-bafc-17eb60c9ab0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDQyNDIsIm5iZiI6MTcxMTYwMzk0MiwicGF0aCI6Ii8xNTM4ODM1MzgvMzE2MzE5MzY0LTAzOTgzYzdlLTM3MWItNDUzNC1iYWZjLTE3ZWI2MGM5YWIwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNTMyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGJlNWVhNjYwOTFjY2U0MjM5NWQ1NmUwNDM4MjBjMDVkOWZjNjQ2NDYzYTljZTE3Mjc3Mjg1MWY1NjQ5YzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9flc-VI3OsGeZ0Dom_0jFcGRdCeq2gKGkARviq9GYB8)

hi im getting the same error, can you explain how u fixed it?
