### ISSUE TITLE
lab 5 - only use one orElseThrow()

### ISSUE THREAD

**Issue by ethanmanzz** [nus-cs2030/2324-s2#314]
# Summary

It says I cannot use more than one orElseThrow(). But there are two factory methods we need to implement and both can throw an exception, hence i used two orElseThrow() methods. What method should I use to connect the two factory methods together.

<img width="275" alt="Screenshot 2024-03-24 at 3 47 37 AM" src="https://github.com/nus-cs2030/2324-s2/assets/159884036/9dc7f3d6-9453-4a68-8214-512b31123c55">

**Comment by jianhaosoh** [comment]
Since the two factory methods are similar, for the `static <T> Log<T> of(T value)`, can just call the other factory method and pass in an empty string ""

**Comment by huangtian666** [comment]
^yep, i used ` return of(t, "")` to call the other factory method
