### ISSUE TITLE
Exercise 5 level 4

### ISSUE THREAD

**Issue by hanlinnnnn** [nus-cs2030/2324-s2#315]
Hi guys i dont quite understand why i am not passing this test case, would appreciate any help!

<img width="771" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/119099121/cc52743e-1199-4af1-9e75-71e7ee491715">

<img width="771" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/119099121/e267e1ec-b7de-46c3-8d06-37d878b8e4e3">

**Comment by ZHD1987E** [comment]
I think you will have to obtain what is in the Maybe...

**Comment by zuoshihua** [comment]
Your return type should be `Maybe<T>`

**Comment by 763312** [comment]
Your return type should be  Maybe<T>, which means that you should create a variable by doing Maybe<? extends T> temporaryMaybe = supplier.get() first. Hope this helps!

**Comment by hanlinnnnn** [comment]
thanks guys i got it :))

**Comment by ZHD1987E** [comment]
@hanlinnnnn you might want to close the issue yeah?
