### ISSUE TITLE
Lab05 Level 5 Issue 

### ISSUE THREAD

**Issue by delulu04** [nus-cs2030/2324-s2#317]
# Summary

Honestly I am a bit confused with how to do the recursion, I don't rly gets the calling of 2 flat maps as seen in my code below. Also, my output of the log statements are incorrect and I am not very sure why 

## Description:
As seen in the screenshot, the statements come out from adding 5 to base case instead of the opposite, and there is a "space" generated too. I think this could be due to my toString method but I don't know how to change it without affecting the correctness of my other levels

## Screenshots
![2024-03-24 15 19 08](https://github.com/nus-cs2030/2324-s2/assets/155940515/ff2f9a4b-b9da-4e36-a656-5eacbbbe00f9)

<img width="481" alt="Screenshot 2024-03-24 at 3 22 33 PM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/57e49b51-6356-4ee7-9acd-08fb8694c781">

Any help is appreciated, thank you!

**Comment by huangtian666** [comment]
hiii, in order for the string to come in ascending order, the string needs to be added after the `sum(n - 1)` method call. so u just have to swap the order of calling the first and second factory methods. 

so this is what i did: 
`return Log.<Integer>of(n).flatMap(x -> sum(n - 1).flatMap(y ->
 Log.<Integer>of(x + y,  "adding " + x)));`

**Comment by delulu04** [comment]
Ohh i understand, thank you @huangtian666
