### ISSUE TITLE
How to make vim and vscode highlight java syntax in a .jsh?

### ISSUE THREAD

**Issue by hanlinnnnn** [nus-cs2030/2324-s2#319]
Is there a way to make vim and vscode recognize that the .jsh is written in java so that it would highlight keywords and stuff?

**Comment by Andrew22Teoh** [comment]
I don't believe there's a way to do this, unfortunately. 
The point of .jsh files are to emulate the jshell UI, which does not highlight any information for syntax assistance that vim does.
If you'd like some kind of syntax assistance or keyword highlighting, you could write your .jsh files as a .java file and then copy the lines over from your .java to .jsh file!

I'd look forward to being proven wrong by someone who knows better though! Would be very helpful to have colour highlighting in a .jsh file 😄

**Comment by kohtw** [comment]
It is possible in vscode

![image](https://github.com/nus-cs2030/2324-s2/assets/160722433/fcb830b6-df92-47ef-b073-7e3899e27196)
click on plain text

![image](https://github.com/nus-cs2030/2324-s2/assets/160722433/7ed58a87-7b4e-449c-84f7-5bc72091fab3)
just choose Java at this window

**Comment by ZHD1987E** [comment]
Thanks, will try!

**Comment by hanlinnnnn** [comment]
> vim: add the following line at the end of ur .vimrc file `au BufRead,BufNewFile *.jsh set filetype=java`
> 
> vscode: ![image](https://private-user-images.githubusercontent.com/160722433/316298915-fcb830b6-df92-47ef-b073-7e3899e27196.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzU3NzQsIm5iZiI6MTcxMTI3NTQ3NCwicGF0aCI6Ii8xNjA3MjI0MzMvMzE2Mjk4OTE1LWZjYjgzMGI2LWRmOTItNDdlZi1iMDczLTdlMzg5OWUyNzE5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMDE3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Zjg2MjAyYjVkOGE3NTQ3YWNmMzMzZmZhNmY5ODJhOTQ2OTI3YmM1MDU0ODkxNWViMWEzMDU4NDcyZjQ1OWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-vSnIQ0agXyoqpfWY3BdMu73rf7QiMtJockrxIwGG54) click on plain text
> 
> ![image](https://private-user-images.githubusercontent.com/160722433/316298958-7ed58a87-7b4e-449c-84f7-5bc72091fab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzU3NzQsIm5iZiI6MTcxMTI3NTQ3NCwicGF0aCI6Ii8xNjA3MjI0MzMvMzE2Mjk4OTU4LTdlZDU4YTg3LTdiNGUtNDQ5Yy04NGY3LTViYzcyMDkxZmFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMDE3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzBhYmUyYTdlN2QzNWM3ODQ1Yzk2NTNlMWIwOGZlOWYzNTk1ZTkyYTNlNGI2M2ZmODQxZjJmZTc4ZTY0MjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uJfVSDIVcAPMq7weWPWITODv0nL3lK_wnoQBRpgCGs4) just choose Java at this window

THANKS MAN URE SO HOT

**Comment by ZHD1987E** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/e5d2bfb2-47ff-4f97-9d0e-0ba9cd42fc15)
It works! Thanks!

**Comment by ZHD1987E** [comment]
Since our PA is over, mind if you close this issue yeah?
