### ISSUE TITLE
Missing a Javadoc comment

### ISSUE THREAD

**Issue by brianxlim** [nus-cs2030/2324-s2#323]
Hi everyone, I received this error when I submit my Log.java. Does anyone know how to fix this?

<img width="849" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/121876669/fe6f7dbf-d14e-47e8-bfbe-79941ecd0ebb">

**Comment by serweiq** [comment]
Can you share your code and show where the error occurs?

**Comment by brianxlim** [comment]
you must write a javadoc to solve the issue. a javadoc looks like this for example:

/**
     * Applies the given function to this Log's value, returning a new Log of type {@code <R>}. This
     * method transforms the value to another Log instance. If this log message is empty, it 
     * directly returns the function's result, otherwise combines the log messages.
     *
     * @param <R> The type parameter for the returned Log, determined by the function.
     * @param mapper The function to apply, taking a value of type {@code <T>} or its supertype and
     *               returns a Log of type {@code <R>}.
     * @return A new Log instance of type {@code <R>}. If this instance's log is not empty, 
     *         the returned Log's message combines this instance's and the result's logs. Otherwise,
     *         it returns the result directly.
     */

**Comment by brianxlim** [comment]
Thank you! @brianxlim
