### ISSUE TITLE
Lab 5 - Assoc.apply test case giving false

### ISSUE THREAD

**Issue by ethanmanzz** [nus-cs2030/2324-s2#326]
# Summary
I managed to pass the monad left and right identity, but then I fail the assoc method. 

My code:
![Screenshot 2024-03-24 at 6 39 36 PM](https://github.com/nus-cs2030/2324-s2/assets/159884036/5adfa676-f3c9-4275-be07-e5fd027c3614)

Then, I went to separate out the assoc method into l1 and l2 to see the system output of each one, and they look exactly the same... but when I equal them together it is still false .. anyone can help?
![Screenshot 2024-03-24 at 6 40 06 PM](https://github.com/nus-cs2030/2324-s2/assets/159884036/5793f71c-027d-4f05-a2f5-647eb378ee54)

**Comment by wkleow123** [comment]
maybe you want to try and implement your equals method in a way similar to how prof showed us the Maybe's equals implementation in lecture

**Comment by huangtian666** [comment]
hii, u can use equals() method to compare the values and string logs as T may not be of a primitive type.
