### ISSUE TITLE
Lab5

### ISSUE THREAD

**Issue by JovanFoo** [nus-cs2030/2324-s2#327]
![Screenshot 2024-03-24 at 7 28 17 PM](https://github.com/nus-cs2030/2324-s2/assets/133492195/7be422c5-044e-4112-b94d-5ec236456cd0)
![Screenshot 2024-03-24 at 7 28 30 PM](https://github.com/nus-cs2030/2324-s2/assets/133492195/74d8f5ed-d0e1-4deb-a34b-ce5e715bb3e2)

Im not sure why this is return false? Is there something wrong with my equals method that i cant seem to debug?

**Comment by Jett-Tan** [comment]
flatmap should not append blank ""

**Comment by JovanFoo** [comment]
ohh okay got it

**Comment by LimZiXiong** [comment]
Consider your initial Log to be empty string. Then when you flatMap to a new log with some string, you end up with "" + "\n" + "your log" which will prints 
(Empty space)
your log

**Comment by ezclap02** [comment]
you can consider implementing something similar to this:
if this log string == "":
return other log string
if other log string == "":
return this string
if this string and other string both not empty
return this string + "\n" + other string

**Comment by JovanFoo** [comment]
thank you! Ill give it a try!
