### ISSUE TITLE
Lab #5 Missing a Javadoc Comment

### ISSUE THREAD

**Issue by khooxr** [nus-cs2030/2324-s2#329]
![Screenshot 2024-03-24 215612](https://github.com/nus-cs2030/2324-s2/assets/163562737/8592bb20-0a9e-4354-b812-6c7764c71d59)

Came across this error on Codecrunch. Does anyone know what the issue is?

**Comment by starryfieldz** [comment]
Hi, could it be due to the format/syntax of your javadoc comments such as @Override?

**Comment by khooxr** [comment]
![Screenshot 2024-03-24 224620](https://github.com/nus-cs2030/2324-s2/assets/163562737/4d6cabe1-dc7f-4098-9b30-a45fc40a61a2)
Hmm I tried editing those but got thrown these errors instead

**Comment by ZHD1987E** [comment]
I suspect there is an autograder problem.

I have now mounted a question on #293 (my Q&A) and tagged Henry regarding this problem.

Alternatively, you can email him privately.

**Comment by iceflakes12** [comment]
Can you provide a snapshot of your code from line 38 to 51 in your Log file?

**Comment by khooxr** [comment]
I have resolved the issue by adding Javadoc comments for the flagged methods. Here's an example for the of method:
/**
     * Returns a Log object with the given value and log message.
     * @param value The value associated with the log entry.
     * @param log   The log message.
     * @param <T>   The type of the value.
     * @return A Log object containing the specified value and log message.
     */
Thanks everyone for your help!
