### ISSUE TITLE
Lab 5 Defining "of" method

### ISSUE THREAD

**Issue by starryfieldz** [nus-cs2030/2324-s2#330]
Hi everyone, 

I would like to clarify for the definition of 'of' method with regards to the following instructions:
"To ensure that a valid Log is created, an IllegalArgumentException would be thrown from the of method when the argument is null or another Log.".

In this case static <T> Log<T> of(T value, String log) {
Why are we not allowed to filter to check for whether log instance of String in this case since if it is not a String value taken in, aka a null value, it will not be passed through the pipeline of Optional.ofNullable(......). Whereas in checking whether value is null or not we are able to use instanceof Log.

Thanks in advance for the help!

**Comment by Bryng23** [comment]
you can use instanceof to check if an object is an instance of the current class you are working on (in this scenario its log class). That's why you can't check if log is instanceof String.  What i did was use Optional.ofNullable(this.log) to check if log is empty then use .orElseThrow to throw the illegal argument exception

**Comment by lim-4158** [comment]
if the string is null, when passed into optional.ofNullable(...), i believe an Optional.empty() would be created

**Comment by starryfieldz** [comment]
Thanks for your response @lim-4158, I did use ofNullable(...) to check if value and string is empty in the end. But do you know why are we not allowed to use instanceof to filter if String is null? Because I did use instanceof to check if the value passed in is Log or not since Exception will be thrown when argument is another Log. Codecrunch throws an error "instanceof key detected" when I did the former but it did not throw the error when I did the latter.

**Comment by starryfieldz** [comment]
Thanks for responding @Bryng23! I apologise for the confusion of naming of my 'of' method.

static <T> Log<T> of(T value, String log) {

The 'log' i am referring to is the 2nd argument passed onto this method above^.

**Comment by dillonph34** [comment]
Yeah you can use Optional.ofNullable to catch the cases where the input is null. In my case I used instanceof not to check for null, but to check whether value is a Log. 
I think the purpose of this is so that we learn to use Optional to encapsulate null values. As using of null may be problematic.

**Comment by lim-4158** [comment]
hey @starryfieldz, @dillonph34 gave a pretty good answer to that question! in this course we generally are not allowed to use instanceof and typecasting other than when defining our equals method.

**Comment by starryfieldz** [comment]
Thanks everyone for the help!!
