### ISSUE TITLE
discrete event simulator private test cases

### ISSUE THREAD

**Issue by aNNexh** [nus-cs2030/2324-s2#331]
![Screenshot 2024-03-24 223628](https://github.com/nus-cs2030/2324-s2/assets/164228063/fe3b8b2f-81e5-4b67-b35e-f772d777c01e)

I managed to pass all the test cases given in the assignment but I'm failing the private test cases. Its quite difficult to even begin debugging since I dont know the inputs and cant trace the code. Can anyone suggest what I mightve missed out on or failed to take into account?

**Comment by ZHD1987E** [comment]
Something may be wrong with your self checkout system...

**Comment by mChewWW** [comment]
to debug these types of test cases, i recommend you add a 
if statement to print the desired debugging variables you wish to see. in this case i would do:

if (watingTime == 1.125 && noServed == 16) {
System.out.println("whatever variables you want");
}

this may give you a better idea of which values are wrong causing your issue.

**Comment by ZHD1987E** [comment]
Actually, thinking about it, I think something IS wrong with your self-server dequeuing.

More specifically, I bet Mr. Customer 16 thought the self-checkouts queue is just occupied and decided to abandon purchase, even though the queue has capacity thanks to those being served.

If that was Kurt Tay, he would have made an angry complaint long time ago...

**Comment by iceflakes12** [comment]
Your error comes from the serve events of 13 and 14 not being executed as expected.

Customer 16 and 17 behaves as expected because your 13 and 14 has not been dequeued since the serve events for 13 and 14 were not executed as expected.

**Comment by iceflakes12** [comment]
If you do observe 13 and 14 serve being executed anywhere else further along the code, you might have coded it in a way that SCC has a rest time. Otherwise, you should check the logic behind your Serve and Simulator classes. You could choose to test using existing public test cases and inject print statements whenever you see fit because more often than not it could still reveal some logical errors despite you having passed all public test cases.

**Comment by jarrenoh** [comment]
Seems like your customer in the self check queue is not going to the next available self check. Try and make the customers in the self check queue get polled out as wait events at the minimum next available time of the self check counters.
