### ISSUE TITLE
Lab 5 null value detected

### ISSUE THREAD

**Issue by Yuxin-Mellisa** [nus-cs2030/2324-s2#335]
What does it mean? 
I cannot mention null in my of method?
<img width="187" alt="截屏2024-03-25 上午12 30 27" src="https://github.com/nus-cs2030/2324-s2/assets/157778558/971067a2-9ce4-41af-890e-0ac91470016c">

**Comment by iceflakes12** [comment]
You cant use null in the whole of 2030. Try using the .ofNullable method in Optional instead

**Comment by Yuxin-Mellisa** [comment]
But then object cannot filter how to filter out the condition that t is log

**Comment by LimZiXiong** [comment]
> But then object cannot filter how to filter out the condition that t is log

If you use ofNullable you don't have to filter for null. If something is null when you perform any operation on it, it will be null and then finally after all the operation is finished, orElseThrow will trigger.

**Comment by Yuxin-Mellisa** [comment]
not filter for null filter for log

**Comment by LimZiXiong** [comment]
> not filter for null filter for log

Just use instanceof Log. 
Optional.ofNullable(T value).filter(x -> !(instanceof Log).flatMap(...). Its OK to use instanceof here

**Comment by naomiiiwu** [comment]
Codecrunch bans the usage of Null in general. So check if you used == Null or something similar in your code. I think can try to use filter/OfNullable/Map/instanceOf functions to assist you.
