### ISSUE TITLE
Discrete event simulator

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#336]
Anyone knows why the test case 3 for the discrete event simulator is wrong?

![Screenshot 2024-03-25 010502](https://github.com/nus-cs2030/2324-s2/assets/111676024/01dfbfde-b61e-49b2-95cc-e174599557ed)

**Comment by iceflakes12** [comment]
If I recall correctly this issue seems to be because you are giving servers rest time in the serve event instead of the done event, so the order of rest time given to the servers is wrong.

**Comment by JosiahPraeman** [comment]
Hi iceflakes12, if i were to give the servers rest time in the done event instead of serve event, then will it help with the next few test cases? What are some other considerations i would need to take note of down the road?

**Comment by iceflakes12** [comment]
Yes, it was specified in the specs as well. I think for this project, you can fix logic bugs here and there based on the 18 test cases provided, its not easy to pre-empt everything either

**Comment by JovanFoo** [comment]
I updated the rest time in my done event and that worked fine! so maybe you can consider giving it a try too!

**Comment by iceflakes12** [comment]
ʚ(*´꒳`*)ɞ
