### ISSUE TITLE
Lab 5 Level 4: Java.lang.IllegalArgument returned instead of a boolean?

### ISSUE THREAD

**Issue by SheYuting** [nus-cs2030/2324-s2#337]
Description of the question / problem here.
As the title, instead of true or false, I get an exception raised instead of a boolean method. What is happening here? I am guessing there is some null values hidden inside class A here?

Furthermore, when I am trying to test my code with class A defined as class A { }, my equals method always return false so I am not sure how the exception is thrown

## Screenshots
<img width="1039" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/119406337/edce484a-5551-44cd-bf57-c244aff65674">

**Comment by SheYuting** [comment]
Further more, if I try to test my code with class A defined as class A { }, my equals method always return false so I am not sure how the exception is thrown

**Comment by ZHD1987E** [comment]
See my Q&A #293

**Comment by Yiting55** [comment]
Can you test Log.of(new A()) and see whether the exception is thrown. If so, check your constructor, only throw exception when the input is an instance of Log or null, not other class. And for Level 4 'equals' implementation, use equals instead of ==.

**Comment by SheYuting** [comment]
Hi thank both for the reply, I am not getting any exceptions thrown when calling Log.of(new A()) so I am not sure whats happening here, for equals, I am trying to compare two objects by calling equals as well (psudocode below):
equals(Object obj) {
        if (obj == this) {
            return true;
        } else if (obj instanceof Log<?> other) {
            return check this.value.equals(other.value) && check this.stringLog.equals(other.stringLog);
        }
        return false;
    }
I'm not sure whats going wrong here hmm is it because of the <?> wildcard?

**Comment by zuoshihua** [comment]
Your `of` method should throw `IllegalArgumentException` if you pass in a `Log` object. This is clearly stated in the lab instructions.
