### ISSUE TITLE
Exercise 5 Level 4 "or"

### ISSUE THREAD

**Issue by kienanana** [nus-cs2030/2324-s2#338]
Hi all ive seen some of the other threads on this particular method but im not too sure how to go about solving it still. how do i overcome the incompatible types error and return a Maybe of T from here? would appreciate any help thank u!
<img width="402" alt="Screenshot 2024-03-25 at 2 15 19 AM" src="https://github.com/nus-cs2030/2324-s2/assets/119132853/170626d2-a681-41c4-9f2e-0e9f4562e7b4">

beforehand my supp was a Supplier of a Maybe of T without the wildcard which resulted in this error.
<img width="924" alt="Screenshot 2024-03-25 at 2 16 18 AM" src="https://github.com/nus-cs2030/2324-s2/assets/119132853/1d6346db-20e6-4d28-8f01-5f6c56ebcc3b">

**Comment by RyanLucasHo** [comment]
supp.get() would return a Maybe<? extends T> which is not the same as the Maybe<T> defined in your return type. To fix this issue, take it one step at a time like prof mentioned to get the correct typing. Something like this would help:

 ```java
 Maybe<? extends T> m = sup.get();
 T t = m.get();
 return Maybe.<T>of(t);
 ```

**Comment by eugfoo** [comment]
the return type of supp.get() will not be the same as Maybe<T>

**Comment by kienanana** [comment]
got it thanks for the help guys :)
