### ISSUE TITLE
Lab 5 equals method (Class A, B,C)

### ISSUE THREAD

**Issue by MarcusLiangg** [nus-cs2030/2324-s2#339]
<img width="702" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157345221/74c6da1d-ca03-4e4e-b33d-41a6eab3f8f3">

Hi, I'm very confused about how to tackle his part. Can anyone provide any hints?

**Comment by RyanLucasHo** [comment]
Try checking the conditions within your equals method:
1. Check if the object passed into equals is itself
2. Check if the object is an instance of Log and check the value wrapped within both Logs
3. Else, return false

**Comment by MarcusLiangg** [comment]
Yeah, my problem is comparing the values. Because new A() doesn't equal to new A()? I don't really understand that part :(

**Comment by wallaacee26** [comment]
hi, did you check the values/attributes in the Log object using the equals() method instead of ==? that could be an issue.

**Comment by ccyenn** [comment]
i managed to solve this problem by using something similar to the equals method in lecture 3

**Comment by MarcusLiangg** [comment]
Hi, thanks for helping everyone. I found the error, apparent this.value.equals(other.value) is not the same as this.value == other.value
