### ISSUE TITLE
Lab 5 Level 4

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#341]
# Summary

Description of the question / problem here.

## Description:

Im not able to get the last 3 test cases, my method compares this == object, and checks whether the object is an instance of Log before using the standard equals function to compare the orignal object and String

## Code Snippets

Attach code snippets (if any)

## Screenshots
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/b5663f7d-a5be-47f1-9b32-6fa4fbeecf25)

**Comment by bbxg16** [comment]
The problem may be related to your flatMap method. You could try Log.<Integer>of(5)).flatMap(x -> Log.<Integer>of(x)) to see the output and adjust conditions of returning a new String in your flatMap accordingly

**Comment by weiyangng** [comment]
> The problem may be related to your flatMap method. You could try Log.of(5)).flatMap(x -> Log.of(x)) to see the output and adjust conditions of returning a new String in your flatMap accordingly

yup thanks i realised there were several trailing empty lines that were causing the equals method not to trigger

**Comment by Yuxin-Mellisa** [comment]
u can check whether your output have empty line maybe u use \n but never check whether your original this.log is empty or not
