### ISSUE TITLE
Lab 5 Level 5 sum

### ISSUE THREAD

**Issue by bbxg16** [nus-cs2030/2324-s2#342]
# Summary
correct integer answer but wrong String output

## Description:

I used flatMap() to do the sum and update the String. However, the output shows that I could get Log[15] for sum(5) but the string output only have "adding 5"

<img width="372" alt="Screenshot 2024-03-25 at 10 32 12 AM" src="https://github.com/nus-cs2030/2324-s2/assets/160305895/4b5ea7d1-6976-4c90-af06-09fa33d271fa">

**Comment by WWYYiXuan** [comment]
maybe you wanna check your flapmap() method again?

**Comment by Yiting55** [comment]
problem may occur in flatMap(). You may check whether you concatenate the string to the original string or you simply return the new string

**Comment by bbxg16** [comment]
Thank you! The problem is related to update of the String in flatMap()
