### ISSUE TITLE
Null value detected

### ISSUE THREAD

**Issue by niclow236** [nus-cs2030/2324-s2#344]
# Summary

I got a null value detected error when submitting via codecrunch.

## Description:

Could it be because a null value is being returned in one of my methods or that i used a null value directly in my code? If so, how should i check whether the log is null (instead of String) together with the value in the of(T t, String log) method? Thanks

## Screenshots

<img width="422" alt="2024-03-25_160001" src="https://github.com/nus-cs2030/2324-s2/assets/156642018/fc3eef06-c805-4a58-bf70-fb405ee6c39b">

**Comment by kohsweehong** [comment]
You can consider using Optional.ofNullable in your overloaded "of" method to catch the null value and throw an Exception then.

As suggested from the instructions:
<img width="451" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156646904/da89215d-f0c0-48f1-8d1a-80c8a22a40b6">

**Comment by niclow236** [comment]
> You can consider using Optional.ofNullable in your overloaded "of" method to catch the null value and throw an Exception then.
> 
> As suggested from the instructions: <img alt="image" width="451" src="https://private-user-images.githubusercontent.com/156646904/316434617-da89215d-f0c0-48f1-8d1a-80c8a22a40b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTU2ODUsIm5iZiI6MTcxMTM1NTM4NSwicGF0aCI6Ii8xNTY2NDY5MDQvMzE2NDM0NjE3LWRhODkyMTVkLWYwYzAtNDhmMS04ZDFhLTgwYzhhMjJhNDBiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwODI5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWZiYjdjNTJlZTRmZGFlMTM0NmJkODZmN2NhYmY2Y2NiYmQzOWZmY2U5MWYxNmFhM2UwM2VlMzRiY2YzOWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qjTTJC0TTX37Di-xhvqGO7fwfjctH2Hn1IHH6asR7_A">

Oh so I would have to call Optional.ofNullable twice within the same method, perhaps a nested one for log, in order to catch both cases if either one was null?

**Comment by andrelau123** [comment]
yes, you can use flatmap and optional of nullable to generate the 2nd log

**Comment by kohsweehong** [comment]
yes, should use it twice to catch for filtering and mapping

**Comment by niclow236** [comment]
> yes, should use it twice to catch for filtering and mapping



> yes, you can use flatmap and optional of nullable to generate the 2nd log

Ok thanks!
