### ISSUE TITLE
Empty spaces in Level 5 part 2

### ISSUE THREAD

**Issue by Gracesong146** [nus-cs2030/2324-s2#345]
Everything works for Level 5 except the existence of spaces....

![image](https://github.com/nus-cs2030/2324-s2/assets/62082817/219d74ef-11bb-4bf1-8eaf-40cf7fdb07c0)

**Comment by AustinKong** [comment]
Try removing a `\n` somewhere inside your code? I'm not really sure how you implemented it so I can't really help.

**Comment by Gracesong146** [comment]
Ah its alright, I found my error, i wrote two lines of flatmap and overcomplicated stuff. thanks!

**Comment by ZHD1987E** [comment]
@Gracesong146 you might want to close that issue, since it's done already...
