### ISSUE TITLE
Using split tab on vim

### ISSUE THREAD

**Issue by mChewWW** [nus-cs2030/2324-s2#347]
I would like to see if there is an option to create a split tab on vim such that I can see 2 vim windows side by side, without opening a new ‘msys’ window entirely.

Right now if I open msys I get one vim window. If i try right clicking it and select ‘split tab’, it opens a powershell window which i do not know how to use to navigate to vim.

**Comment by travistan2003** [comment]
open 1 file first, then type :vsp *the next file you want to open*

**Comment by mChewWW** [comment]
> You can try this out bro I think it works
> 
> split screen — :vsplit {filename.java} for vertical split, :split {filename.java} for horizontal split
> 
> * change between tabs in vim — ctrl + w + w (i.e. press w twice)

it works bro thanks
