### ISSUE TITLE
help with project test case 2

### ISSUE THREAD

**Issue by wxlee1807** [nus-cs2030/2324-s2#349]
# Summary
hiii not sure why i'm failing this test case as i placed the getresttime() in the done event, not sure why my server availability is incorrect at this particular test case~ 

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="456" alt="Screenshot 2024-03-25 at 10 34 59 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156640028/37cf7040-4bf4-4750-8214-1c7f437cdf0d">

**Comment by ZHD1987E** [comment]
I suppose you need to update the server availability time correctly.

**Comment by UserNameWasTakenAlreadyy** [comment]
You might want to check if your human servers are resting properly. It seems like right after serving customer 2, server 1 is immediately ready to serve customer 3 when it should be server 2 that is serving customer 3. Perhaps server 1 isnt given an appropriate rest time?

**Comment by MaverickWongKeJun** [comment]
Depending on your implementation, you might want to check if u are updated the servers next available time correctly. For my case, my events are designed to terminate based on a boolean value (Events Done and Leave being true, vice versa) as some events do not return subsequent events. Before the implementation of human servers, my implementation does not process Done events, and would thus not update the next available time with rest time correct. If your code is failing to update rest times correctly, this could be one of the possible reasons, cause Done events now need to be evaluated to check if the server requires downtime.

Another consideration down the line would be that self checkout counters will not require evaluation of done, which means you will eventually need to add another check to terminate done events specifically for self checkout counters

**Comment by Jeremythong2002** [comment]
You should make sure that the Servers rest times are called in the Done event, or whichever event such that it can get called and updates before the next action
