### ISSUE TITLE
A surprise video from me will come soon.

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#350]
What will it be?

You guess you guess you guess 你猜你猜你猜!!! 🤔🤔🤔🤔🤔

You will only know in Week 12 or Week 13.

Clues:
- Toilet
- No lecturing

**Comment by AustinKong** [comment]
2 hour video of "Intro to Java Programming".

**Comment by ZHD1987E** [comment]
no

clue: toilet paper

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kaiju10** [comment]
How Henry's ideology of toilet paper in one of his lectures helps other students taking this course

**Comment by ZHD1987E** [comment]
No

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LimJiaWeng** [comment]
How toilet paper will help me do functional programming

**Comment by ZHD1987E** [comment]
Nvm.

Guess guess guess!!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZHD1987E** [comment]
Keep the guesses coming!
