### ISSUE TITLE
Lab 5 Level 4 test case 4_1

### ISSUE THREAD

**Issue by bbxg16** [nus-cs2030/2324-s2#352]
# Summary

Wrong outputs for two equals test cases

## Description:

My equals method performs well for all other cases except 
_Log.of(new B()).equals(Log.of(new A()))
Log.of(new C()).map(x -> x).equals(Log.of(new A()))_
I am not sure if the issue is related to B and C are subclass of A, since my output for this 
_Log.of(new A()).map(x -> x).equals(Log.of(new C()))_
is correct.

I used .equals() to compare the value and log.
Can anyone help which parts of the code may cause these two test cases to fail?

<img width="868" alt="Screenshot 2024-03-25 at 11 11 00 PM" src="https://github.com/nus-cs2030/2324-s2/assets/160305895/cc28e95c-9d36-4e04-bfe4-d4266ab5e26c">

**Comment by WWYYiXuan** [comment]
well maybe you want to check your instanceof Log's wildcard? to ensure the subclass is considered

**Comment by zuoshihua** [comment]
Make sure your `instanceof` clause checks against `Log<?>` and not Log<? extends T>

**Comment by bbxg16** [comment]
I did not use instanceof in equals method since the question states that the input is another Log. Another question is that I do not understand why my code is working for Log.of(new A()).equals(Log.of(new B())). I thought that new A().equals(new B()) should return false instead of true.

**Comment by zuoshihua** [comment]
`B` extends `A`

**Comment by MaverickWongKeJun** [comment]
I had the same problem for this and realised the output is wrong because I overlooked how the two objects are different instances despite having the same value. Using the class .equals as a comparison for value equality should fix this

**Comment by yfongsin** [comment]
it works when i use the Object .equals() method to compare the values

**Comment by juliannxe** [comment]
I had the same problem because I used != instead of equals(). The equals() method was more appropriate, as != compared whether it was literally the same object or not.
