### ISSUE TITLE
Lab 5 Restricted Optionals Error

### ISSUE THREAD

**Issue by lim-4158** [nus-cs2030/2324-s2#354]
# Summary

I got an email from prof asking me to resubmit saying that there was a bug in the grader after I submitted and got an A. 

After resubmission i faced this problem. Does anyone know what this problem is about? 
 
## Screenshots

Screenshots (if any)
![Screenshot 2024-03-26 at 12 15 32 AM](https://github.com/nus-cs2030/2324-s2/assets/129579903/c408bf28-2dd0-47ea-bb37-7aa920238037)

**Comment by zuoshihua** [comment]
Mind listing out what methods of `Optional` you used?

**Comment by zi-yii** [comment]
In lecture 5 slide 16, we were told to avoid using get(), isEmpty(), isPresent() declared in Optional class, so maybe you could check if you used these methods

**Comment by lim-4158** [comment]
@zuoshihua i used ofNullable, filter then instanceof, flatmap, equals 

im not using anything illegal right

**Comment by zuoshihua** [comment]
My guess is your usage of `Optional.equals()` may have triggered CodeCrunch.

**Comment by lim-4158** [comment]
thanks, it was the equals method.
