### ISSUE TITLE
Lab 5 level 5 f method output

### ISSUE THREAD

**Issue by WWYYiXuan** [nus-cs2030/2324-s2#355]
# Summary

Description of the question / problem here.

## Description:

i followed the f method codcrunch provided but the returning result it the reverse of expected. I am somehow not sure how to continue. Any idea would be appreciated! thx!

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="130" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/163511252/d6aae997-50fc-4ef0-897c-387a48ef8af8">

**Comment by zuoshihua** [comment]
Try invoking `f()` inside `flatMap()`.

**Comment by hanlinnnnn** [comment]
I would suggest you think of the order of evaluation of methods. When you call flatMap, you are essentially appending the new String to the back of your old String, what should you do if you want to attach it in front instead?

**Comment by ZHD1987E** [comment]
OK.

I admit my #293 Q&A probably wasn’t clear enough lol, others are still getting stuck.

Thing here is pretend that you have the recursive result evaluated, think what you need to do to said result.

**Comment by nicklass8** [comment]
the order for f function is the opposite of the sum function so try and find a way to reverse the order of the output through the use of flatMap. Otherwise, the logic for both sum and f is more or less the same

**Comment by heezxeo** [comment]
For each of the recursive statement (if - else statement), try to return a different result for each of them with the use of flatMap. The logic for if-else would stay the same as what code crunch description provided.

**Comment by WWYYiXuan** [comment]
okay solved! thank everyone who helped!
