### ISSUE TITLE
Why can I assign Maybe(String) to Maybe(Object)?

### ISSUE THREAD

**Issue by hanlinnnnn** [nus-cs2030/2324-s2#356]
I am not too sure why this is legal, should it not return an error?
<img width="700" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/119099121/79a664e6-5825-44ee-a60f-083a3521933d">
<img width="760" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/119099121/b47bad15-a158-4504-bcf1-065cd0e7a629">
I get why the first 2 works like that, since Maybe(String) and Maybe(?) are covariant, whereas Maybe(String) and Maybe(Object) are invariant.
But why is it that when I flatMap a Maybe(String) to another Maybe(String), I can now assign that to a Maybe(Object)??

**Comment by zuoshihua** [comment]
Anything which extends `String` also extends `Object`

**Comment by PengRongNeo** [comment]
Hi just to clarify, does maybe.get() return String? then Maybe.of(string) returns Maybe<String> object? then how is it possible to assign to Maybe<Object> 
Or issit that maybe.get() return ? extends String? then Maybe.of(?extendsString) returns Maybe<?extendsString> object which can then be assigned to Maybe<Object>

**Comment by hanlinnnnn** [comment]
> Hi just to clarify,in the flatMap method, does maybe.get() return String? then Maybe.of(string) returns Maybe(String) ? then how is it possible to assign to Maybe(Object) Or issit that maybe.get() return ? extends String? then Maybe.of(?extendsString) returns Maybe(?extendsString) object which can then be assigned to Maybe(Object)

Hello! I didnt change the get method provided, it returns this.value of type T, also say if there was a Maybe(? extends String), I dont think it can be assigned to Maybe(Object) either, since Maybe(? extends String) and Maybe(Object) are invariant

**Comment by hanlinnnnn** [comment]
Credits to a cs friend
<img width="584" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/119099121/e103a75e-d4e8-47f5-9773-8fa5712b308a">
which I think makes the most sense (gonna leave it here for everyones benefit)

If anyone disagrees or has a better or more elaborate explanation please also drop it!

**Comment by dingus891** [comment]
the string extension will be by default an extension of object

**Comment by joshuagde** [comment]
If you are assigning to a Maybe<Object>, your U is now Object meaning your mapper function can be any function that returns a Maybe<? extends Object>. So say you have a mapper function that maps from a String to a Maybe<String>, it is allowed and once this map operation is completed, since you declared the return type to be a Maybe<Object>, it will become a Maybe<Object>. I think this is how it works?

**Comment by Jeremythong2002** [comment]
Part of the issue is that the moment you use the Maybe interface, there is a barrier between String and Object. Maybe<String> does not extend Maybe<Object> event though String extends Object. 

When you do assignment, `Maybe<Object> mo` the local generic type `<U>` will be Object

**Comment by mChewWW** [comment]
string extends object

**Comment by ZHD1987E** [comment]
I hope these above helped to answer the question, @hanlinnnnn...

As a reminder, you might want to close this issue to help declutter the forum.

Thanks!
