### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by omgacai** [nus-cs2030/2324-s2#357]
hii could anyone help me with what this error means? I passed all the test cases for this submission already and got an A but this error appeared in the output. 

<img width="1358" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/134914115/26e453d7-e789-4bf9-89e8-47454d34f791">

**Comment by ZHD1987E** [comment]
Test it with checkstyle command.

**Comment by zuoshihua** [comment]
Try resubmitting, it may just be fault on CodeCrunch

**Comment by LimZiXiong** [comment]
Had this problem before. Resubmitting after awhile works

**Comment by kee-x** [comment]
You can try resubmitting it on codecrunch

**Comment by nickifung** [comment]
It is related to the checkstyle
