### ISSUE TITLE
Exercise 5 level 4

### ISSUE THREAD

**Issue by dingus891** [nus-cs2030/2324-s2#358]
<img width="433" alt="Screenshot 2024-03-26 at 4 07 47 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163809302/0c92e0cf-41ea-434b-b499-239fb1efd2d9">
hi guys for the or function that i have provided here i currently get a Maybe of a Maybe when it returns a Maybe.of(supplier.get()) however, if i just try to return supplier.get() the code does not compile any tips?

**Comment by bzastudent293** [comment]
Your or function should take in a T object that is wrapped in a Maybe object and when you call the get method it returns a Maybe object not a T value

**Comment by kshoo-0957315** [comment]
Your supplier returns a Maybe object when you call supplier.get(). Perhaps you could do some unwrapping/re-wrapping before returning it? As for compiler error, your method returns Maybe<T>, but your supplier only guarantees a <? extends T> when you return supplier.get()

**Comment by dingus891** [comment]
> Your supplier returns a Maybe object when you call supplier.get(). Perhaps you could do some unwrapping/re-wrapping before returning it? As for compiler error, your method returns Maybe, but your supplier only guarantees a <? extends T> when you return supplier.get()

oh so even though its supposed to be a Maybe since the supplier can't guarantee what it is this causes the compilation error?

**Comment by huangtian666** [comment]
hiii, for level 4, the `or()` method is taking in a supplier of `Maybe<T>`, so the parameter should be sth like `Supplier<? extends Maybe<? extends T>> maybeSupplier` . then u can do unwrapping and rewrapping the value with Maybe
