### ISSUE TITLE
Error: Unable to access jarfile

### ISSUE THREAD

**Issue by ziyingg** [nus-cs2030/2324-s2#36]
Hello, I was trying to run the file in msys for checkstyle HelloWorld.java, but I got the error Unable to access jarfile. May I know how I should proceed from here?

**Comment by ziyingg** [comment]
Hello, thank you for replying. I did follow the steps exactly as outlined, but I am still struggling. Please refer to the image. 

![photo_2024-01-23_22-32-30](https://github.com/nus-cs2030/2324-s2/assets/134266442/22bc9936-65ea-4602-acf3-05c1c8a537a6)

**Comment by ziyingg** [comment]
Sorry, could I clarify what the profile file is and how to check if I have already saved it?

**Comment by SumitShinde0702** [comment]
![Screenshot 2024-01-23 234529](https://github.com/nus-cs2030/2324-s2/assets/94443578/c6343ee1-0a2a-4c3f-a9b6-5825d0ec6a44)

there should be such a file in your folder. (the folder which opens when you input 'explorer.exe .'

if you do not have such a file, then you will have to create it. Instructions is on the wiki. 

If you do have the file, then open it and paste that portion into it. For me, I opened it with vs code and then pasted it below my other paths.

**Comment by ziyingg** [comment]
Hello, could you help me with this?
<img width="718" alt="Screenshot 2024-01-24 001558" src="https://github.com/nus-cs2030/2324-s2/assets/134266442/97ab2936-fc0a-4583-bb64-a3d7b4567693">

**Comment by ziyingg** [comment]
this was extracted from the .profile:
alias checkstyle="java -jar ~/checkstyle-10.3.3-all.jar -c ~/cs2030_checks.xml" >> ~/.profile

**Comment by SumitShinde0702** [comment]
1) open your .profile with vs code
2) paste 'echo "alias checkstyle="java -jar ~/checkstyle-10.3.3-all.jar -c ~/cs2030_checks.xml"" >> ~/.profile' into it 

![Screenshot 2024-01-24 001958](https://github.com/nus-cs2030/2324-s2/assets/94443578/e223f55a-e6b9-46c3-901b-44e32838b3d8)

you do not have to paste it into terminal.
after pasting that line into your .profile, run this in your terminal 'source ~/.profile'
