### ISSUE TITLE
Lab 5 equals method

### ISSUE THREAD

**Issue by clarequek** [nus-cs2030/2324-s2#360]
## Description:

I have tried to find my error and  I'm not sure where my code went wrong.  i think that the issue lies with the class of other.t and this.t.  can anyone help me w this?

## Code Snippets
toString() method:
<img width="331" alt="Screenshot 2024-03-26 at 5 06 35 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164228670/ca6daabd-0b91-4fa4-ad6a-0b345bd01bda">

equals() method:
<img width="693" alt="Screenshot 2024-03-26 at 5 07 11 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164228670/c377b119-bb58-4d3b-9c38-ce87d60611c8">

here's my output:
<img width="322" alt="Screenshot 2024-03-26 at 5 07 40 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164228670/e1d3e705-d22c-405f-82e4-17447b646b3a">

**Comment by zzhengweii** [comment]
when you write Log<?> other =  Log.of(obj), you are double "boxing" so you will get Log[Log[obj]] instead maybe you can try  if (obj instance of Log<?> log) and you compare t and log of this and log

**Comment by LimZiXiong** [comment]
Following the lecture slides on how to implement equals method will work fine. 
`if (obj instanceof Log<?> otherLog) {
    return otherLog.getValue().equals(...);`

**Comment by W-WJ-Ryan** [comment]
or alternatively you may consider using type casting such as (Log<?>) obj to avoid the double boxing in the event that the object is a log. If the test case still fails you can consider looking at flatMap as i had quite a few issues with that as well when submitting

**Comment by LimJiaWeng** [comment]
You can try to do (obj instanceof Log<?> log) instead so you dont have to create a new Log. If obj is an instance of Log<?>, it typecasts obj into Log<?> and assigns it to the variable log. After that you can compare them using this.t.equals(log.t) && this.logString.equals(log.logString)

**Comment by jpowcm** [comment]
for ur debugging the 4th line that u print shld be other.getT() instead of this.getT()? maybe that will help you see why ur current this.t does not equal to other.t
