### ISSUE TITLE
Project Test Case 11

### ISSUE THREAD

**Issue by zuoshihua** [nus-cs2030/2324-s2#361]
Hi, anyone has encountered the following for test case 11? I have made sure that:

- [x] Server rests at the done event
- [x] Server serves and dequeues at the serve event
- [x] If one self checkout enqueues all of the other self checkouts enqueue
- [x] If one self checkout dequeues all of the other self checkouts dequeue

![image](https://github.com/nus-cs2030/2324-s2/assets/64007522/8ac77708-c048-432e-bb69-35dcb2e7062b)

Any help is appreciated. Thanks!

**Comment by wkleow123** [comment]
there may be some sort of indexing error going on

**Comment by aNNexh** [comment]
could have to do with how you store your serverid in the event, causing the wrong servers to be identified and updated. you could also deliberately generate a wrong output for that specific case to get code crunch to give you full view of all the output statements so you can better trace your errors. this was how i resolved my issues for this case. all the best.

**Comment by LimZiXiong** [comment]
Try to check if the server that you are dequeuing is up to date as well. I was having a lot of trouble with customer waiting at server that should be full. Turns out i did not use the most up to date server

**Comment by ZHD1987E** [comment]
I think something probably went wrong with the resting time. Try test cases where the rest time probability is set to 1.0

**Comment by zuoshihua** [comment]
Thanks all, I solved the problem! Turns out my customer was fixated on waiting for a particular self checkout. It did not consider the fact that other self checkouts could finish earlier.
