### ISSUE TITLE
Discrete Event Simulator

### ISSUE THREAD

**Issue by garethdcruz** [nus-cs2030/2324-s2#365]
![CodeCrunch - Google Chrome 27_3_2024 10_21_33 am](https://github.com/nus-cs2030/2324-s2/assets/137087296/d099dbe1-8214-4452-b91c-680d75bfda50)

Hi does anyone know why I have experienced this error for test case 4, thank you!

**Comment by UserNameWasTakenAlreadyy** [comment]
You might be using indexes to find certain things in your ImList (of available Servers etc.). Here, it seems like you have not considered some edge cases where if the element does not exist in the list, it might return you a -1 as per the implementation of indexOf() method. TLDR: Indexing error (index past the bound or is negative)

**Comment by garethdcruz** [comment]
> You might be using indexes to find certain things in your ImList (of available Servers etc.). Here, it seems like you have not considered some edge cases where if the element does not exist in the list, it might return you a -1 as per the implementation of indexOf() method. TLDR: Indexing error (index past the bound or is negative)

Thank you for your help, found the bug!
