### ISSUE TITLE
Recitation 8: Use of BigInteger

### ISSUE THREAD

**Issue by juelin708** [nus-cs2030/2324-s2#366]
How does the use of BigInteger avoid the problem of overflowing?

**Comment by KoalaLyfestyle** [comment]
A BigInteger is a data type in Java that allows you to represent and perform calculations with extremely large integers that would exceed the range of the standard integer data types (like int or long). Essentially, it provides a way to work with arbitrarily large integers, limited only by the available memory in the system. For example in rec8 Fibonacci, the integers can get very large, therefore to avoid a overflow BigInteger is used.

**Comment by zuoshihua** [comment]
It depends on the JDK. For instance OpenJDK uses a `int[]`

Array size is not limited by size like primitive types, making them suitable for storing arbitrarily large values as long as there is enough memory

**Comment by kailincoder** [comment]
BigInteger is a class in java, and Unlike primitive integer types such as int or long, which have fixed sizes and can overflow if the result of a computation exceeds their maximum representable value, BigInteger can handle calculations involving integers of any magnitude. it will not overflow, as it provides a flexible and dynamic representation of arbitrary large integers
