### ISSUE TITLE
"Too many constants declared."

### ISSUE THREAD

**Issue by timothyngcy** [nus-cs2030/2324-s2#367]
Hi! This was the compilation error I had received upon submitting my project to CodeCrunch. I solved it by removing all my static variables.

But does anyone know what a "constant" is? Is it just static variables? Or does it include non-static variables as well?

## Screenshots (if any): 
![photo_2024-03-27_15-26-49](https://github.com/nus-cs2030/2324-s2/assets/142781724/7a8c8ba2-b628-4b42-8a8a-4c4bd41dea1b)

**Comment by huangtian666** [comment]
constants are like `private static final int NO_AVAILABLE_SERVERS = -1`, u use it to prevent magic numbers in ur code

**Comment by darylchen46** [comment]
Non-static variables technically are constants as well. The difference is that these variables belong to each instance of the class and their value cannot be changed after you initialise them e.g. `private final int serverId;` then `new Server(1)`. The variable `serverId` is tied to the Server class and cannot be changed.

**Comment by santtoshh** [comment]
In this case, I'm pretty sure its due to having too many `private static final` constants.  0s and 1s are not considered magic numbers so you dont have to declare a `private static final int` for them, to reduce your total constants declared.

**Comment by Jeremythong2002** [comment]
There can only be a maximum of 2 static variables that can be declared. Make sure that you are not uploading the Main.java when submitting as they have static variables within them

**Comment by timothyngcy** [comment]
Thanks for d assistance everybody!
