### ISSUE TITLE
X<?> vs X<T> when using instanceof

### ISSUE THREAD

**Issue by ezclap02** [nus-cs2030/2324-s2#368]
in general when should we use ? or T when checking instanceof, and why would one be preferred over the other?

`obj instanceof X<?> other`
`obj instanceof X<T> other`

**Comment by zuoshihua** [comment]
It depends. Use `X<?>` if you want to check if both objects are `X` containers. Use `X<T>` to check if both `X` containers and on top of that, both objects contain item(s) of type `T`

**Comment by Jeremythong2002** [comment]
You might want to use X<T> if you want to call a method that is specific to T in your code. It might otherwise throw a compilation error

**Comment by blacksesamezongzi** [comment]
Depends on your purpose. If you want to have the type of X the same as T, then can use X<T>, if just check whether other is an X, then can use X<?>

**Comment by alterVega** [comment]
(x instanceof y) only compiles when it can be safely assumed that the x can be cast into a y, or if y extends/implements x. Assuming obj is of type Object, X<T> won't compile and you will get the "Object cannot be safely cast to X<T>" error, because obj can be cast into a general X<?> type, but cannot be cast into a specific X<T> type.

**Comment by jesgiveup** [comment]
it depends on the question requirement. Use ? when you're checking against a generic type without caring about the specific type parameter. Use T when you need to ensure the object matches the specific generic type parameter of the context you're working in.

**Comment by yminnnx** [comment]
like what others have mentioned, <?> is typically used when you want to achieve flexibility and writing a generic code that is independent of the actual type argument while T is used when ur code needs to depend on a specific type argument

**Comment by ezclap02** [comment]
thanks for all your inputs!
