### ISSUE TITLE
vim very unresponsive

### ISSUE THREAD

**Issue by MarcusLiangg** [nus-cs2030/2324-s2#37]
Hi, I need help fixing vim, it seems to be very unresponsive. Each time I want to enter a character or do something I need to hold the key for a couple of seconds (e.g. to just enter a letter, 'p', I need to p key for a few seconds).

The vim editor only behaves like this in Jshell (/edit) but works fine in msys when creating the HelloWorld.java file.

Any help is appreciated. Thanks!!

**Comment by hwkchia** [comment]
The fix is to remove vim as the jshell editor.  Use the default one provided.
