### ISSUE TITLE
Exercise 5 error

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#371]
<img width="288" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/956e59ac-4020-4912-b271-5396a08ee678">

I can run my code perfectly, but there seems to be an error on CodeCrunch.

<img width="252" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/632e7dbd-9922-473e-8795-91c95a03d3ba">

Did I add too many import statements?

**Comment by nicklass8** [comment]
Hi, I have the same import statements as you and did not get this error. Judging from the error statement, it seems that some part of your code may have used the java PrintStream class that is not allowed on code crunch.

**Comment by hadyamanisanto** [comment]
<img width="254" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/2cf9b92d-51df-4aca-85b3-e4c43957d3fa">

Found, any alternatives to suggest?

**Comment by jennipho** [comment]
Try using the for loop given on code crunch! Run through map instead of stream :)

**Comment by hadyamanisanto** [comment]
Thanks.

**Comment by hadyamanisanto** [comment]
Found it.
