### ISSUE TITLE
Exercise 5 Error 2

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#373]
<img width="233" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/24f80393-db34-44f1-a3c1-dabecc847a46">

For some reason I keep getting this error. 

<img width="233" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/2eb77915-8d8a-4fef-8e1d-690c72439912">
I tried changing the of and empty methods from static to private static to private, but gives me the same error.
Any help is appreciated.

**Comment by jpowcm** [comment]
did u create your own helper methods other than the ones they asked for?

**Comment by hadyamanisanto** [comment]
<img width="429" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/da18683c-34f5-444c-9f2c-b7535d242eaf">
run() is the only helper method, as it is necessary to implement for the Runnable interface.

**Comment by jpowcm** [comment]
oh wait but Maybe doesnt implement the runnable interface tho

**Comment by hadyamanisanto** [comment]
Found it. Thank you!
