### ISSUE TITLE
Project Test Case 3

### ISSUE THREAD

**Issue by nicklass8** [nus-cs2030/2324-s2#376]
## Description 
Hi, I cant seem to figure out why my code is failing this test case, I made sure to update the queue in the serve event and return it in a updated serverlist as well as the finish time of the server in the done event to take into account the possibility of resting

## Screenshots (if any): 
<img width="444" alt="Screenshot 2024-03-28 at 6 37 04 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163880002/76abe7c9-bff5-4a7c-b82f-30f01c42a065">

**Comment by JovanFoo** [comment]
I had the same issue, even though i did return the updated queue in my serve event. However, my done event also updates the queue when i return another done event. So what i did was to remove the updating of the queue in my done event and i could pass this test case! Hope that helps!

**Comment by nicklass8** [comment]
Hmmm but for my done event, i only updated the finish time of the server and not the queue. Essentially, in my done event, i made a new server with the same parameters apart from an updated finish time

**Comment by JovanFoo** [comment]
Did you happen to update the queue somewhere else other than serve event?

**Comment by nicklass8** [comment]
nope only in arrive and serve event

**Comment by zuoshihua** [comment]
At which event does your server rest?

**Comment by nicklass8** [comment]
@zuoshihua my server rests in the done event. In my done event, i create a new server with the updated finish time that includes the rest time and replace it with the existing server in the serverlist

**Comment by jeslynzhou** [comment]
Hi! You can try to print out the waiting queue in arrive event for debug! Maybe your waiting queue of that server get empty after done event.

**Comment by yushanedi** [comment]
I think you could try using a Rest Event to debug (with a print statement) that way you will know exactly whether the issue has to do with the addition of the rest time or not.

**Comment by nicklass8** [comment]
Update: I have managed to resolve the issue, turns out my Serve and Done event were not using the most updated server. Thanks for all the help!

**Comment by naomiiiwu** [comment]
Hi I got exactly the same error. May I know how you solved it in the end? it seems like my code IS using the updated serverlist, so I don't know what's wrong.
