### ISSUE TITLE
DISCRETE EVENT SIMULATOR AGAIN

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#378]
How to pass the last 6 test cases it is so long 

![Screenshot 2024-03-29 001820](https://github.com/nus-cs2030/2324-s2/assets/111676024/682e2d7c-d66d-4874-b7d1-75ea399fd1ab)

**Comment by jorized** [comment]
Hi Josiah, the image can't be seen.

**Comment by JosiahPraeman** [comment]
> Hi Josiah, the image can't be seen.

i updated alr

**Comment by jarrenoh** [comment]
Your customers waiting at the self check queue arent getting served by the next available self check.
For your wait event, try getting these customers/events to get polled out at the minimum next available time of self check counters

**Comment by zuoshihua** [comment]
Hint: A customer queueing for self checkout counters will immediately head to any self checkout counter once available.

**Comment by MaverickWongKeJun** [comment]
Looks like this is an issue that stems from your queue handling of self-checkout counters. Check that your logic within the queue handling is correct, such that the update of each customer in queue will be set to the soonest available time. Also see if your handling of dequeueing is correct such that a customer is dequeued each time any self checkout counter becomes available

**Comment by JosiahPraeman** [comment]
Thank you everybody i resolved the issues already.

**Comment by ZHD1987E** [comment]
@JosiahPraeman You might also want to close this issue to declutter the forum, thank you!
