### ISSUE TITLE
Lab 5 Level 5

### ISSUE THREAD

**Issue by dlkw13** [nus-cs2030/2324-s2#379]
# Summary

Having some issues with sum and f method in level5.jsh

## Description:

My sum and f method in level5.jsh unable to provide the same outputs as required. Anyone can assist for these two methods to return the correct outputs

**Comment by jorized** [comment]
Hi, if you are looking for a way to get started on level 5, maybe @ZHD1987E's thread might help. https://github.com/nus-cs2030/2324-s2/issues/293
