### ISSUE TITLE
Jshell Test Failed

### ISSUE THREAD

**Issue by ErinaTjin** [nus-cs2030/2324-s2#38]
# Summary
I have already installed openjdk17 (done up till the step scoop install openjdk17). Typing jshell into msys results in this:
$ jshell
sh: jshell: command not found

## Description 
When I open msys (windows, type msys, enter), the app that opens is msys.cmd 
Does this have to do with the problem?

**Comment by EnzioKam** [comment]
> When I open msys (windows, type msys, enter), the app that opens is msys.cmd Does this have to do with the problem?

When you say that msys.cmd is opened you mean a terminal window has opened? If yes then please type which jshell and copy-paste the output here.

If there is no output, it means that your PC cannot detect your JDK installation. Check again that you have indeed installed openjdk17 properly by running `scoop list` in your normal terminal window to see if openjdk17 appears in the output list. It it does, you need to run the following in your msys terminal

```
echo "PATH=/c/Users/your_userid/scoop/apps/openjdk17/current/bin/:\$PATH" >> ~/.profile

source ~/.profile
```

**Comment by ErinaTjin** [comment]
<img width="418" alt="jshell" src="https://github.com/nus-cs2030/2324-s2/assets/157509370/2e8cf0f1-f81f-4523-a420-5cd4bad2d4ba">
<img width="582" alt="msys" src="https://github.com/nus-cs2030/2324-s2/assets/157509370/a9b2d984-1368-4547-bbb8-dbe3026abd08">
<img width="660" alt="running" src="https://github.com/nus-cs2030/2324-s2/assets/157509370/6ae44c1b-8108-4a37-a6a2-2cbc1dc0b67e">
<img width="404" alt="scoop list" src="https://github.com/nus-cs2030/2324-s2/assets/157509370/95dbe09e-405e-48dc-a0e9-deea1201f1cb">

**Comment by EnzioKam** [comment]
`your_userid` should be replaced with your actual user id.

You can remove the original `.profile.` file by running `rm ~/.profile` and repeat the steps again with the correct user id.

(Also, I am assuming that your scoop openjdk17 installation is actually at `C:\Users\your_userid\scoop\apps\openjdk17\current\bin` on your PC. If it still does not work please check that this is also the case.

**Comment by ErinaTjin** [comment]
It works now, thank you so much!
