### ISSUE TITLE
Error "Other non-private methods in Log detected."

### ISSUE THREAD

**Issue by mmnnsskk** [nus-cs2030/2324-s2#380]
## Code Snippets
import java.util.Optional;
import java.util.function.Function;

class Log<T> {
    private final T value;
    private final String string;

    private Log(T value, String string) {
        this.value = value;
        this.string = string;
    }

    public T getValue() {
        return this.value;
    }

    public String getLog() {
        return this.string;
    }

    static <T> Log<T> of(T t) {
        return of(t, "");
    }

    static <T> Log<T> of(T value, String log) {
        return Optional.ofNullable(value)
            .filter(x -> !(x instanceof Log))
            .flatMap(x -> Optional.ofNullable(log).map(z -> new Log<T>(x,z)))
            .orElseThrow(() -> new IllegalArgumentException("Invalid arguments"));
    }

    public <R> Log<R> map(Function<? super T, ? extends R> mapper) {
        R mappedValue = mapper.apply(this.value);
        return Log.<R>of(mappedValue, this.string);
    }

    public <R> Log<R> flatMap(Function<? super T, ? extends Log<? extends R>> mapper) {
        Log<? extends R> log = mapper.apply(this.value);
        if (log.getLog() == "") {
            return Log.<R>of(log.getValue(), this.string);
        } else if (this.string == "") {
            return Log.<R>of(log.getValue(), log.getLog());
        } else {
            return Log.<R>of(log.getValue(), this.string + "\n" + log.getLog());
        }
    }

    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj instanceof Log<?>) {
            Log<?> other = (Log<?>) obj;
            if (this.getValue().equals(other.getValue())) {
                return this.getLog().equals(other.getLog());
            }
        }
        return false;
    }

    @Override
    public String toString() {
        if (this.string == "") {
            return "Log[" + this.value + "]";
        } else {
            return "Log[" + this.value + "]" + "\n" + this.string;
        }
    }
}

**Comment by joshuagde** [comment]
Your getters should be private I think like getValue() and getLog()
