### ISSUE TITLE
code crunch issue

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#381]
Hi, is there an issue with code crunch i upload my files for the discrete event simulator and i got an E and i want to view the details but it is not allowing me to do so as it keeps loading. May i know why this is the case?

**Comment by nicklass8** [comment]
Hello this happens to me as well. I think it is because the project has alot of files being uploaded, and so it takes some time to load. Just wait abit longer or try again a few minutes later

**Comment by MoeySeanJean** [comment]
Just need to wait a little longer, it takes some time to load.

**Comment by yushanedi** [comment]
Code crunch sometimes takes a while to load. I had a similar issue where I wasn't able to view the details or submit the code. Maybe you could check if your search browser is updated to the latest version. In addition, sometimes code crunch has their issues, just gotta be patient

**Comment by poipoi555** [comment]
Happens to me too especially closer to the deadlines, probably because more people uploading at that time. Just have to wait longer for it to load

**Comment by kailincoder** [comment]
keep refreshing and wait for a bit, can't help it

**Comment by ZHD1987E** [comment]
Did you manage to submit it, @JosiahPraeman?

If so, great! You can close your issues to help keep the forum clean.

Thank you!
