### ISSUE TITLE
Where did Lab Number Five go?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#382]
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/9eb9999e-505c-46a8-aa5a-ab7bccd35562)

Don't make my search Lab 5 like the MH370.

**Comment by JosiahPraeman** [comment]
I hope you find this search for lab 5 a fufilling journey haodong

**Comment by yushanedi** [comment]
Hao Dong, Lab Number 5 is on code crunch. Thanks!
