### ISSUE TITLE
Project: Updating server rest timings

### ISSUE THREAD

**Issue by xin-yi-phang** [nus-cs2030/2324-s2#383]
# Summary
Hi! I'm having difficulty trying to update the rest times of the server. What I've noticed is that the customer in the Wait Event has their getNextEvent() called before the server has updated their rest time. I'm not sure how to fix it.

## Description 
Server 1 had a rest time of 0.848... after serving customer 5 (purple)
however, customer 6's wait event had already called its getNextEvent() before the server's rest time could be reflected, hence it does not reflect the changes in the rest time

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/158749925/487bfa83-5aa3-435b-8654-0bb578cd661e)

**Comment by Lhanxi** [comment]
maybe you can check if your server rest time is updated in the done event

**Comment by xin-yi-phang** [comment]
yep, its updated. I found a workaround by adding +1 to the max queue number and dequeuing the customer at the end of the done event instead. it passes the example test cases but fails the ones on code crunch

**Comment by xin-yi-phang** [comment]
update: I have found out whr i messed up :')

**Comment by naomiiiwu** [comment]
Hi ive encountered exactly the same problem. May I know how you managed to solve it in the end? Tksss

**Comment by xin-yi-phang** [comment]
> Hi ive encountered exactly the same problem. May I know how you managed to solve it in the end? Tksss

Hi, my solution was to introduce another list to record all customers passing through the server in a list. only after done event is executed, will the customer be removed from the queue.

For the wait event to be moved onto a Serve event, it would need to check that the customer is at the front of the record list
