### ISSUE TITLE
Not sure what this test case is looking out for 

### ISSUE THREAD

**Issue by delulu04** [nus-cs2030/2324-s2#384]
# Summary
Hi, I implemented the Rest part of the project. Have tested my code with 1.in and 2.in to make sure that the part of the code that is based off lab3 is working fine, but I am unable to figure out what this test case is testing for when I try to test my Rest implementation. I also got A for Lab3 

From the ss, it seems like my server queue is not updating correctly, but if my code has worked for lab3 and 1.in/2.in and i did not touch updating the serverQueue at all in this lab, i am unsure why I am still facing this problem 

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
<img width="482" alt="Screenshot 2024-03-29 at 1 32 12 PM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/e5da245a-afa5-4b63-8785-e46372f2a14b">

Any help is appreciated, thank you!

**Comment by zuoshihua** [comment]
Check that customers can still queue even when the server is resting

**Comment by RatesLearner** [comment]
Make sure the customer queue logic matches with the server queue logic. What I suggest is to do several print statements in between your code to find out where the error is at

**Comment by proteaninja** [comment]
Maybe you can check what triggers your Leave event to activate instead of the Wait event.

**Comment by clarequek** [comment]
what i did for my wait event was that i checked whether the server was human and hence whether he was resting (i implemented this as a function in my server class), if yes, then i will trigger a waitagain event rather than a serve event. hope this helps!

**Comment by ZHD1987E** [comment]
If you managed to solve it, great @delulu04!

As a reminder, you might want to close this issue to help declutter the forum. thank you!
