### ISSUE TITLE
How to make use of rest probability

### ISSUE THREAD

**Issue by jorized** [nus-cs2030/2324-s2#387]
Hi, for the last test case on CodeCrunch, 

<img width="836" alt="Screenshot 2024-03-29 185437" src="https://github.com/nus-cs2030/2324-s2/assets/79164390/bd1ce324-23da-4eda-a713-ead4bbf2a659">

I am curious if the output would be different everytime we run it. Since the rest probability is set to 0.5, wouldn't there be a 50-50% chance that the human server goes into a state of rest? (Like in the attached image, where server 1 goes into a state of rest at 2.205, before coming back at 9.006) Then if that's the case, will we still pass the test case?

**Comment by mcjuh** [comment]
The test cases should give the same output if you use the Main.java they provided. In the code they set the seeds 3L and 4L for the randomly generated rest and its period. Calling nextDouble() on a Random initialized with a set seed will always give the same pseudorandom numbers as output, so your simulations should be fine. To test this, you can go to jshell and create a Random(1L) and store it as a variable rand like they did in the example, then call nextDouble() on it a few times. Then create another Random(1L) and store it as rand2 and repeat this. You should see that both will output the same sequence of numbers. 
You can change the set seed for fun and test other random simulations, but as long as the seed is initialized any outcome should be reproducible.
