### ISSUE TITLE
when will human servers rest

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#388]
# Summary
Put a summary of the question
yoo may i ask when will huamn servers rest? it is random right? so we do smth like
boolean willRest = random.nextBoolean(); // Decision to rest?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by LimZiXiong** [comment]
The rest time is decided by the supplier. Doing supplier.get() will do. If the supplier rolls a 0 means the server dont rest.

**Comment by kubrian** [comment]
Adding on to this, the way to use supplier for rest time is basically the same as how we get customer service time, i.e. call only once, once server is done serving. The RNG is handled by the supplier itself.

**Comment by itzsihui** [comment]
thank you all !
