### ISSUE TITLE
Self Checkout and Leave Event

### ISSUE THREAD

**Issue by jianhaosoh** [nus-cs2030/2324-s2#394]
With the self checkout in place, will there still be leave event? Let's say I have a "special server" that takes in list of server, does it mean that the max queue will be the sum of the qmax of each self checkout? or is the qmax only applicable to the human server?

**Comment by itzsihui** [comment]
human server each have thier own queue(each queue can only have qmax number of ppl)
all self checkout counters have 1 global queue(which can only have qmax number of ppl)

**Comment by iceflakes12** [comment]
There will still be leave event because of the global queue in self checkout.
This global queue is in the earliest self checkout.
This means that the earliest self checkout has the same qmax as that of each human server, but for all other self checkout qmax is 0.

**Comment by zuoshihua** [comment]
One queue for each human server. One queue for all self checkout counters.

**Comment by vanesssalai** [comment]
yes, the queue max will apply for the human server queues as well as the global queue for the self checkouts

**Comment by huangtian666** [comment]
hiii, there will still be leave events. the qmax for self-checkout is the qmax for all self-checkout counters, for example if the qmax is 2, the max number of customers queuing at all self-checkout counters is 2

**Comment by jianhaosoh** [comment]
thanks for the help!
