### ISSUE TITLE
Self Checkout Counter 

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#395]
# Summary
Put a summary of the question
yoo, may i ask how do you manage the queue for self checkout counter?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary

<img width="739" alt="Screenshot 2024-03-31 at 1 02 53 AM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/aa6b38f7-a494-4c0c-9f0d-66c17afbe05f">
<img width="767" alt="Screenshot 2024-03-31 at 1 04 23 AM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/4e9c3eaf-0bcc-4bf4-b596-c9fc89ce92e1">

**Comment by iceflakes12** [comment]
Depends on your implementation, but for me i find it easier to split into two different self-checkouts, one with the global queue and one without any queue. For self-checkouts without queues, their methods need to be able to manipulate both their own state and the state of the self-checkout with a queue, and the most straightforward way for me to do that is to have your server methods return the entire server list itself. (I think there are better ways for this)

**Comment by zuoshihua** [comment]
1. When one self checkout enqueues all self checkouts enqueue

2. When one self checkout dequeues all self checkout dequeue

3. Customer waiting at self checkout queue should always check if for any available self checkouts. If not it should wait for the soonest to be available self checkout

**Comment by Jeremythong2002** [comment]
Each of my check out counters have their own list of customers, every time I update the self-checkout counter, either serve or add to the waiting list, I will loop through all them and update their customerList accordingly

**Comment by itzsihui** [comment]
thank you all
