### ISSUE TITLE
Recursion error for test case 11

### ISSUE THREAD

**Issue by clarequek** [nus-cs2030/2324-s2#398]
# Summary
My code works fine for the rest of the test cases before, but not this one.
To explain my code:
i decided not to create an additional class for my self checkout, and just let all my customers queue at the first self checkout counter
for my wait event:
-i will check whether the customer is the first customer and check whether the server the customer is waiting at is available
-if not available, i will check whether server is a self checkout and check whether the other self checkouts are currently available
-if both conditions above are not met, then i will return a wait again event, which is essentially the same as my wait event
however i'm not sure what is causing the recursion error... can yall give me some advice

## Screenshots (if any): 

Test case 11

![Screenshot 2024-03-31 at 3 44 13 PM](https://github.com/nus-cs2030/2324-s2/assets/164228670/44868506-b1d8-404c-bc70-6a95f0a4e379)

processEvent function for wait event
<img width="689" alt="Screenshot 2024-03-31 at 3 43 26 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164228670/ea3e872e-0f7a-47bc-aef9-f877168e49ea">
<img width="626" alt="Screenshot 2024-03-31 at 3 43 34 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164228670/13bef2b0-ac7c-4856-a902-255aeb35d52e">

**Comment by ZHD1987E** [comment]
Just to be frank, you can attach a debugging session on Visual Studio Code and see if the server availability times do get updated...

**Comment by zuoshihua** [comment]
If there is no self checkout available, customer should wait for the soonest available checkout i.e. the one with the earliest possible time that it will be done.

**Comment by jiancheng37** [comment]
You could try to debug your code by inserting print statements and see where the recursion occurs
