### ISSUE TITLE
ANOTHER PROJECT TEST CASE 3

### ISSUE THREAD

**Issue by yuulim** [nus-cs2030/2324-s2#399]
Failed test case 3 for code crunch and i am not too sure why. I am able to pass the sample test case 3.in on my own device.
Appreciate any help ! thanks :)

![Screenshot 2024-03-31 191956](https://github.com/nus-cs2030/2324-s2/assets/163849598/5c3bcf3e-7085-47e7-a462-79601cfa2659)

**Comment by ZHD1987E** [comment]
Woah!

Apparently your customers get served earlier... and the servers can serve two people at one go. Never heard about this ability ~~since hearing about Kurt Tay proclaiming himself to be a god at age 44~~.

I see there is a problem when transiting from a waiting to a serving event.

**Comment by LimZiXiong** [comment]
Try to system.out.println place where you update your server queue and check if before and after updating the queue it is logical. You should not see any decrease or increase that is more than 1

**Comment by UserNameWasTakenAlreadyy** [comment]
From the looks of it, there may be an error in how u update the available servers since server 1 is serving 2 people at the same time. Maybe look to see if u have updated it correctly in the .next() of service event somewhere. Depends on your implementation tho...

**Comment by SumitShinde0702** [comment]
Similar to what others have said, I think the error may lie  in 1) when you update server list when serving, arriving 2) updating server Available time 3) comparison logic when customer arrives
