### ISSUE TITLE
How to have vim as default editor in jshell in Windows

### ISSUE THREAD

**Issue by kaiju10** [nus-cs2030/2324-s2#40]
# Summary
Would prefer to use vim instead of jshell Edit Pad in the jshell interface

## Description 
I have seen prof's lecture videos with vim being integrated in the same window as the jshell window when using the `/edit` command. However, I will open up a separate jshell Edit Pad window when I use the same command. It still works, but I find vim to be slightly more intuitive than the Edit Pad. Attached are some pictures of the differences.

I have also tried to change the default editor by using the command `/set editor vim`. Although I managed to open it up in jshell, it is really laggy as mentioned in another thread https://github.com/nus-cs2030/2324-s2/issues/37. It also does not save it as the default editor (luckily) whenever I restart the msys window and goes back to the Edit Pad.

Hence, I want to ask if anyone has managed to replicate the same way as prof's editor, and also make it workable. Thanks!

## Screenshots (if any): 
![Screenshot 2024-01-24 115516](https://github.com/nus-cs2030/2324-s2/assets/156638443/2956cca6-375f-4605-8d0b-deb09637dde1)
![Screenshot 2024-01-24 115901](https://github.com/nus-cs2030/2324-s2/assets/156638443/1defdd4f-5ada-4c0d-8584-b995a3f40c54)

**Comment by ZHD1987E** [comment]
Simple:

`/set editor -retain vim`

**Comment by kaiju10** [comment]
> Simple:
> 
> `/set editor -retain vim`

but will it cause lagging issues? Because thats what happened to me when i use vim without making it default in jshell

**Comment by ZHD1987E** [comment]
No

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
