### ISSUE TITLE
Project test case 9_03

### ISSUE THREAD

**Issue by zkdlffkdb** [nus-cs2030/2324-s2#402]
## Description 
Hi, I am failing this test case, does anyone know what might be wrong with it? I am adding rest time in my Done event.

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/129675099/60f6b6d4-dbac-4875-9765-9f9a1521a5c8)

**Comment by Jeremythong2002** [comment]
The issue  is how your programme calls and measure whether or not a server is done serving a customer. Line 38 shows that why it is returning waiting in line 39 is because it does not accurately call the Done, which cascades the issue to the rest of the programme. 

How does your programme currently check for whether a server is done serving?

**Comment by zuoshihua** [comment]
Is your server resting at the Serve event? If so, it should be resting at the Done event

**Comment by zkdlffkdb** [comment]
Hmm right now I have a Done event which does the following:
- adds rest time to the server's time (next time available)
- indicates the server is done serving by altering a boolean value in server

These changes are reflected by updating the server list in the simulator

**Comment by zuoshihua** [comment]
The boolean flag for "done serving" might be unnecessary since you have the server's next available time

You could also check if your customer is retrieving the most up to date state of the server list

**Comment by trishaa17** [comment]
assuming your rest time is added correctly, but ur timestamp for done is not updated/ added wrongly. can try looping through servers list in every event class to find most updated server

**Comment by zkdlffkdb** [comment]
Thanks for everyone's help, fixed the issue. It was a problem with checking for the case where the servers serve event ends earlier than another server, but has longer resting time, resulting in the next serve event starting later than the other server.
