### ISSUE TITLE
Booster reminder post

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#403]
Since Lab Number 5 appeared again, you might be facing issues. In that case, you can refer to #293 (the Q&A).

**Comment by ZHD1987E** [comment]
But still...

Q&A 1 APRIL 2024
---

# What do you do when you get so many `flatmaps`?

That means you can ONLY use one `flatmap` for each recursion call. I'll leave it all up to you.

**Comment by CChaosuan** [comment]
ok
