### ISSUE TITLE
Private method issue

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#404]
# Summary

Log methods not private

## Description:

How to make the methods for log private for lab 5 because they just released the lab 5 and i got an F because my log method was not private.

![Screenshot 2024-04-01 141430](https://github.com/nus-cs2030/2324-s2/assets/111676024/7e2ba1ab-76c3-48e4-abbb-ddf1dbd2b042)

**Comment by AustinKong** [comment]
Same issue here, anybody knows which method is doing this?

**Comment by LimKaiWei** [comment]
I am not sure if this will help but remove all the modifiers for `Log` class so just `class Log<T> {`
on top of that add `public` modifiers to the front of every single non-private method you have implemented inside the class, essentially have modifiers for every method
hope it helps

**Comment by LimZiXiong** [comment]
I had methods that are public inside my log i just change all of them to private and it submits successfully

**Comment by xiang-qiuyu** [comment]
i was using a getter in my Log because i wanted to get the value but i managed to fix it by adding an Integer value = n / 2; and calling this instead of using my getter function. hope this helps!

**Comment by MaverickWongKeJun** [comment]
I removed my getter function in log file and resubmitted and it passed all test cases, didnt have to change any logic

**Comment by JosiahPraeman** [comment]
> I removed my getter function in log file and resubmitted and it passed all test cases, didnt have to change any logic

Hi, Maverick, how did u just remove the getter function and pass all the test cases did your code not call the getter function in the log file?

**Comment by Bryanngu03** [comment]
I solved it by changing my getter function to private.

**Comment by AustinKong** [comment]
I tried removing the getter function which didn't do anything, but when I commented out the `toString` method the code submits.

**Comment by hadyamanisanto** [comment]
> I tried removing the getter function which didn't do anything, but when I commented out the `toString` method the code submits.

What do you mean exactly?

**Comment by AustinKong** [comment]
> What do you mean exactly?

Doing this and submitting the `Log` doesn't result in the private method issue, but of course the first test case doesn't pass 🤔:

![image](https://github.com/nus-cs2030/2324-s2/assets/69255175/7b6e4abd-7e70-4ee6-9ad8-668dbcb41ee7)

**Comment by hadyamanisanto** [comment]
Can you use isEmpty for String?

**Comment by dnardnar** [comment]
I had the same error because the log constructor was not private. Changed it to private and it worked.

**Comment by AustinKong** [comment]
> I had the same error because the log constructor was not private. Changed it to private and it worked.

This is it ⬆️⬆️⬆️ Solved my problem. Thanks everyone. (I still don't know why commenting out `toString` somehow made it work)

**Comment by ezclap02** [comment]
i changed my public getters to private and it resolved the error on codecrunch

**Comment by tzs69** [comment]
> i was using a getter in my Log because i wanted to get the value but i managed to fix it by adding an Integer value = n / 2; and calling this instead of using my getter function. hope this helps!

Hi kindest sir, perchance do you mind providing further elaboration regarding how you implemented this? I used getters myself too and would really like to know your secret to success. Thank you in advance😚😚

**Comment by zay-nin** [comment]
Hi! I solved it by changing my getter methods to private. Maybe can try that if your getters are currently declared public

**Comment by jiancheng37** [comment]
I changed my constructor from public to private and it worked

**Comment by fermentedgrapewater** [comment]
hi! can I ask if the equals method is supposed to be declared public as well since it overrides the objects method and will it cause this error too?

**Comment by ezclap02** [comment]
> hi! can I ask if the equals method is supposed to be declared public as well since it overrides the objects method and will it cause this error too?

yes, its supposed to be public

**Comment by zay-nin** [comment]
> hi! can I ask if the equals method is supposed to be declared public as well since it overrides the objects method and will it cause this error too?

Yep it's public!

**Comment by eleorakow** [comment]
just make sure that your constructor for Log is private as well

**Comment by xiang-qiuyu** [comment]
> > i was using a getter in my Log because i wanted to get the value but i managed to fix it by adding an Integer value = n / 2; and calling this instead of using my getter function. hope this helps!
> 
> Hi kindest sir, perchance do you mind providing further elaboration regarding how you implemented this? I used getters myself too and would really like to know your secret to success. Thank you in advance😚😚

hihi basically in my flatMap() i was trying to retrieve the value from Log, thus, i had a public getter. however, i didnt need to get the value from Log because the value is basically n/2 where the n is the input into the f() function. so i could remove the getter, does this clarifies?

**Comment by IYKYKY** [comment]
> hi! can I ask if the equals method is supposed to be declared public as well since it overrides the objects method and will it cause this error too?

both equals and toString should still be public

**Comment by zuoshihua** [comment]
> Can you use isEmpty for String?
> 
>
@hadyamanisanto  Can confirm. I used it and did not have to resubmit

**Comment by zuoshihua** [comment]
> > What do you mean exactly?
> 
> 
> 
> Doing this and submitting the `Log` doesn't result in the private method issue, but of course the first test case doesn't pass 🤔:
> 
> 
> 
> ![image](https://github.com/nus-cs2030/2324-s2/assets/69255175/7b6e4abd-7e70-4ee6-9ad8-668dbcb41ee7)

Because this is a naive implementation. You should add or remove newlines accordingly when the `Log` is created. Not after, like in `toString()`

**Comment by mikio13** [comment]
Hi can i check which methods should be private? Right now my 2 of methods, map , flatMap, equals and toString are public. I haven't used any getters and my constructor for Log is private. But I'm still getting the error.

**Comment by fermentedgrapewater** [comment]
@mikio13 hm not sure if itll make a difference but maybe u cld remove the public declaration for map and flatmap and try again?

**Comment by LimJiaWeng** [comment]
> Hi can i check which methods should be private? Right now my 2 of methods, map , flatMap, equals and toString are public. I haven't used any getters and my constructor for Log is private. But I'm still getting the error.

Only the constructor is private for mine and everything else is public except for the 2 of functions which I declared as just static.

**Comment by tianyiiiiiii** [comment]
> Hi can i check which methods should be private? Right now my 2 of methods, map , flatMap, equals and toString are public. I haven't used any getters and my constructor for Log is private. But I'm still getting the error.

yup same for me, only the constructor and the 2 gettor methods are private, my of methods are static and the rest are all public.

**Comment by WWYYiXuan** [comment]
i made my constructor and the getter methods private and other methods static and only toString() public
