### ISSUE TITLE
flatMap Recursion Error Test Case 10

### ISSUE THREAD

**Issue by zay-nin** [nus-cs2030/2324-s2#405]
# Summary

Hi I changed my getters to private and am now failing test case 10 even though it gives the correct output in terminal. Does anyone know what the issue is? Thank you

## Screenshots

Screenshots (if any)
<img width="271" alt="Screenshot 2024-04-01 at 4 02 57 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156638309/7c979d13-a989-41ad-9e3d-ff0c18f1371b">

**Comment by huangtian666** [comment]
hii basically this means that we only can use 1 flatMap in the `sum()` method, flatMap is called once per recursion

**Comment by zay-nin** [comment]
> hii basically this means that we only can use 1 flatMap in the `sum()` method, flatMap is called once per recursion

Ohhhh I see

**Comment by ezclap02** [comment]
hi, you can only use one flatMap in your sum method. you can try storing the recursive method call in a variable. hope this helps

**Comment by zay-nin** [comment]
> hi, you can only use one flatMap in your sum method. you can try storing the recursive method call in a variable. hope this helps

Ok will try. Thanks!

**Comment by zay-nin** [comment]
I got it :) Thanks guys for your help
