### ISSUE TITLE
DO NOT GET LAST TEST CASE

### ISSUE THREAD

**Issue by TokPinXiang** [nus-cs2030/2324-s2#406]
![Screenshot 2024-04-01 161553](https://github.com/nus-cs2030/2324-s2/assets/163707211/b62fa960-9451-4cd4-ad6e-53569b753714)
anybody have this issue

**Comment by zay-nin** [comment]
Hi i got this error too. I think it's because you called flatMap more than once in your rescursive return statement for sum. Maybe you can try assigning the recursive sum to a Log<Integer> first before calling flatMap on it

**Comment by ezclap02** [comment]
hi, you can only use one flatMap in your sum method. you can try storing the recursive method call in a variable. hope this helps

**Comment by jiancheng37** [comment]
u should only use flatmap once

**Comment by ZHD1987E** [comment]
Same.

I will now mount a Q&A for that.

**Comment by ZHD1987E** [comment]
Done. Please see #293 (the Q&A).

**Comment by lifrocszh** [comment]
Hi I got this error too when I called flatmap twice in a single line, but it passed after I fixed that

**Comment by meowmeowpeepee** [comment]
only call ur flatmap once
