### ISSUE TITLE
Cannot find symbol: method sum(int) ?

### ISSUE THREAD

**Issue by Luzimomo** [nus-cs2030/2324-s2#407]
How come codecrunch cannot invoke my methods sum() and f()?
![image](https://github.com/nus-cs2030/2324-s2/assets/164223180/119d9834-433f-4587-99b2-4ba83e20a7e9)

I submitted the two files though
![image](https://github.com/nus-cs2030/2324-s2/assets/164223180/3a71ab9e-24ab-4d9a-9b47-967a06f3de19)

and it works in my jshell
![image](https://github.com/nus-cs2030/2324-s2/assets/164223180/8e89e98c-c2dd-4abc-9b3b-def18477d21a)
 
Does anyone have this problem?

**Comment by Jett-Tan** [comment]
Yes having the same issue.

**Comment by hzhitong** [comment]
I am having the same issue too! is there a problem on codecrunch or is there an error in our code?

**Comment by ezclap02** [comment]
hi can we see your code for sum?

**Comment by Luzimomo** [comment]
I don't know if I'm suppose to but oh wells
![image](https://github.com/nus-cs2030/2324-s2/assets/164223180/99225f09-fe28-4dad-a0f9-bb4541eb8a47)

**Comment by jiancheng37** [comment]
i had this same issue but i resolved it by changing my code for my flatmap. when concatenating the strings do check how u handle different cases ie str1 is empty str2 is not empty, str1 str2 empty etc

**Comment by euuren** [comment]
I have the same issue, anyone with any suggestions? Thank you!

**Comment by zaccymomo** [comment]
I have this issue as well!

**Comment by ZHD1987E** [comment]
Alright.

If JShell deems such methods as problematic, it would not run...

If need be, try doing it in an IDE and see if it flags issues.

**Comment by Luzimomo** [comment]
Well well well, apparently I changed `<R> Log<R> flatMap(Function<? super T, Log<R>> f)` to `<R> Log<R> flatMap(Function<? super T, ? extends Log<? extends R>> f)` after I saw another issue #409 and now it works.
