### ISSUE TITLE
must i keep transporting files into the vim folder 

### ISSUE THREAD

**Issue by limbenben** [nus-cs2030/2324-s2#41]
Hello! 

Do i have to keep copying and pasting files into the vim folder to open and edit them?

![image](https://github.com/nus-cs2030/2324-s2/assets/156994767/e46d2eb6-ef9f-4c51-b51b-04a7e8209001)

coz if i dont put it in exactly this folder it just creates a new file when i call e.g. vim Point.java

**Comment by ZHD1987E** [comment]
Apparently Vim works on files on some current directory, so yes, you will have to make sure all your files you are working on are in that same directory.

**Comment by EnzioKam** [comment]
You either:

1. Move your files to your home directory.
2. Navigate from your home directory to the directory you have stored your files.

On windows, one way to make it easier for yourself is to create a shortcut to your home directory and leave it somewhere convenient like your Desktop.

**Comment by zuoshihua** [comment]
Hi,

You can access your C drive via `/c`.

For example, if your file `Point.java` is at `C:\Users\zuoshihua\Desktop` then just type:

```
vim /c/users/zuoshihua/Desktop/Point.java
```

Hope this helps.
