### ISSUE TITLE
lab 5 level 5

### ISSUE THREAD

**Issue by andrelau123** [nus-cs2030/2324-s2#410]
# Summary

Description of the question / problem here.
any idea o how to use only 1 flatmap? im unable to use only 1 without creating an additonal construtor
<img width="871" alt="Screenshot 2024-04-01 at 7 33 26 PM" src="https://github.com/nus-cs2030/2324-s2/assets/81068338/f51843cc-35e8-4f36-8e62-a77f850e20a1">

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by ZHD1987E** [comment]
Well. Pretend you already have the result of the recursion call. Do something about it.

**Comment by ZHD1987E** [comment]
Hey, I have updated the Q&A (#293). Have a look yeah?
