### ISSUE TITLE
Project Test Case 9_03

### ISSUE THREAD

**Issue by Monoji77** [nus-cs2030/2324-s2#411]
# Summary
I'm so confused and I have no idea how to debug. It seems like the issue lies with my queue logic? If my output is suppose to queue at 2 and I'm queuing at 1, it means that I failed to check whether queue 1 is full right? Is there any other explanation or maybe can someone guide me on the debugging? Been stuck on this for 2 days

## Screenshots (if any): 
![Project Help](https://github.com/nus-cs2030/2324-s2/assets/98576382/6c9c138d-33d3-4d06-a5af-7dcd733860ad)

**Comment by ZHD1987E** [comment]
I think there is an issue with you checking if the queue is full.

**Comment by ZHD1987E** [comment]
Still, you might want to attach breakpoints or logpoints on your servers and transitions if need be. That's if you're using an IDE.

**Comment by Monoji77** [comment]
Hey just to check for 9_03, there is zero self check out right?

**Comment by Monoji77** [comment]
> Still, you might want to attach breakpoints or logpoints on your servers and transitions if need be. That's if you're using an IDE.

I tested it out with edited 1.0
2 0 2 0
1.500
1.600
1.700
1.800
1.900
2.000
2.100
2.200

![image](https://github.com/nus-cs2030/2324-s2/assets/98576382/f88020dc-bc77-46fc-9a7b-e321ddf41dae)

My logic seems to be working fine though, I don't know what i'm missing out in 9_03

**Comment by jiancheng37** [comment]
yes there is 0 self check out for 03, there is probably something wrong with how u check whether ur queue is full

**Comment by Monoji77** [comment]
> yes there is 0 self check out for 03, there is probably something wrong with how u check whether ur queue is full

Correct me if i'm wrong for test case 2 Human Servers and qmax = 2
1. Make sure both servers are serving
2. if 2 human servers are both serving customers and server 1 has 1 in queue and  server 2 has 0 in queue, incoming customer queues in server 1.
3. i if 2 human servers are both serving customers and server 1 has 2 in queue and  server 2 has 0 in queue, incoming customer queues in server 2.
4.  if 2 human servers are both serving customers and server 1 has 2 in queue and  server 2 has 2 in queue, incoming customer leaves

**Comment by Monoji77** [comment]
> > yes there is 0 self check out for 03, there is probably something wrong with how u check whether ur queue is full
> 
> Correct me if i'm wrong for test case 2 Human Servers and qmax = 2
> 
> 1. Make sure both servers are serving
> 2. if 2 human servers are both serving customers and server 1 has 1 in queue and  server 2 has 0 in queue, incoming customer queues in server 1.
> 3. i if 2 human servers are both serving customers and server 1 has 2 in queue and  server 2 has 0 in queue, incoming customer queues in server 2.
> 4. if 2 human servers are both serving customers and server 1 has 2 in queue and  server 2 has 2 in queue, incoming customer leaves
> 5. only serve if current time + rest time <= customer arrival time/current time
> 6. if this customer is in queuing for server 1, it can ONLY be served by server 1 after server 1 has served every other prior to this customer
