### ISSUE TITLE
Lab 5 Level 5 Cannot find symbol

### ISSUE THREAD

**Issue by ccyenn** [nus-cs2030/2324-s2#412]
# Summary 

hi not sure why but my last test case has some issue in codecrunch but it works on jshell. is it something to do with the flatmap? Thanks!

## Screenshots
<img width="862" alt="Screenshot 2024-04-01 at 9 03 46 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163828834/b730803c-4291-401e-866e-4df5b743c032">

**Comment by kingcard02** [comment]
did u forget to submit level5.jsh?

**Comment by hzhitong** [comment]
hi! i has the same issue as you and i saw issue [#409](https://github.com/nus-cs2030/2324-s2/issues/409) and what i did was to change the method signature for flatMap from 

<R> Log<R> flatMap(Function<? super T, Log<R>> f)
 to 
<R> Log<R> flatMap(Function<? super T, ? extends Log<? extends R>> f)

Hope this helps!

**Comment by ccyenn** [comment]
> did u forget to submit level5.jsh?

nope I did!

**Comment by ccyenn** [comment]
> hi! i had the same issue as you and i saw issue [#409](https://github.com/nus-cs2030/2324-s2/issues/409) and what i did was to change the method signature for flatMap from
> 
> Log flatMap(Function<? super T, Log> f) to Log flatMap(Function<? super T, ? extends Log<? extends R>> f)
> 
> Hope this helps!

yup it did thanks!!

**Comment by Yuxin-Mellisa** [comment]
thanks I got it
