### ISSUE TITLE
map and flatmap public or private

### ISSUE THREAD

**Issue by ArkAzrael** [nus-cs2030/2324-s2#414]
# Summary

unable to understand what type of method map and flatmap is emant to be

## Description:

Trying to redo lab 5 according to the new requirements, however I am getting a map is declared private error when trying to pass the 2nd test case. Am I supposed to declare it as public static instead and make it a static function? or is it allowed to be a public method like equals and toString()? If it's meant to be private how would it be possible to call it for the test cases?

**Comment by hngkxn** [comment]
my map and flatmap methods are public! i believe the "Other non-private methods in Log detected." error would occur if u used getters or if you didn't private ur Log constructor! hope this helps!

**Comment by nicklass8** [comment]
to add on to above comment, if you did used getters you can simply just change them to private or remove your getters and change it to .value and .string

**Comment by kienanana** [comment]
as mentioned above, just making my getters and constructors private did the trick :)

**Comment by starryfieldz** [comment]
Yup, your other methods will have to be public for it to work in level5.jsh. Only your constructor needs to be private I believe

**Comment by ArkAzrael** [comment]
managed to solve it by removing excess methods, thank you everyone
