### ISSUE TITLE
project test case 2

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#417]
# Summary
Put a summary of the question

## Description 
Getting this odd output on the second test case, managed to pass all the rest of the given outputs on codecrunch.

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/6471f7e0-09ae-4103-a8ab-def9db9d8d7d)

**Comment by zuoshihua** [comment]
Customer may not be seeing the most up to date server list

Also make sure your server rests at the Done event

**Comment by niclow236** [comment]
For your customer 10's Wait Event at 9.160, a Serve Event at 10.536 is returned as Server 1's next available time is either not yet updated or the if statement condition in WaitEvent did not check for this. A new Wait Event should have been returned instead which then again checks for the condition and return a Serve Event at 10.781 (which is what Server 1's next available time should have been if updated correctly). Your error most likely is in Wait Event (the condition to return what next event) 
or in Serve Event where you did not update server list with the correct times.

**Comment by Jeremythong2002** [comment]
How does your wait event check decide how to return a new Serve event?

Currently, the wait event seems to have checked that the next time available is 10.536 and to return a new Serve event from that.

Also do check that when you take 9 out of the waiting list, the timing gets updated as well.

**Comment by tianyiiiiiii** [comment]
customer 10 is being served even though the server is not actually free, you can try to check if you are using the most updated server queues for all the events, and how you are updating them
