### ISSUE TITLE
Lab 5 - level 5 - sum() error

### ISSUE THREAD

**Issue by Xiang-le** [nus-cs2030/2324-s2#422]
<img width="202" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/101037442/61060029-54c3-4553-86db-a54f7766160a">

Hi all, I am having trouble interpreting the incorrect output. 
Is it saying that I am calling flatMap() too many times?

**Comment by ArkAzrael** [comment]
Yes that appears to be the issue. For sum(int n) you should only be calling flatMap once per recursion. Any other operatoions should be done through Map if necessary.
I am facing a similar issue with my f(int) where I am calling flatmap more than is necessary.

**Comment by mChewWW** [comment]
in addition to what was mentioned above, wrong generics for flatmap can cause this issue

**Comment by joshualek09** [comment]
hi xiangle, please refer to these threads for more detailed contextual explanations about flatmap. code previews of the actual implementations have also been included. 
[https://github.com/nus-cs2030/2324-s2/issues/421](url)

[https://github.com/nus-cs2030/2324-s2/issues/423](url)

**Comment by thebestjiaozi** [comment]
Can just use one flatMap. I did this: return sum(n - 1).flatMap(y -> Log.<Integer>(.......)

**Comment by Xiang-le** [comment]
thanks everyone for the help! 
after changing from calling flatMap() twice to once, I managed to resolve the issue
