### ISSUE TITLE
Project Fail Test Case: 9_14

### ISSUE THREAD

**Issue by SumitShinde0702** [nus-cs2030/2324-s2#424]
# Summary
Put a summary of the question
Hi everyone. Human server 1 has already supposedly reached qmax yet it is accepting customers. Then suddenly, the queue is full and then the customers start going to 2's queue. 
It has passed 14/18 so it has been working prior to this.  

## Description 
Describe the problem and code snippets if necessary 
I have tried checking if queue updates (I think it works if not I would not have passed 14 cases but somehow this one died on me)

## Screenshots (if any): 
Insert Images here if necessary
![image](https://github.com/nus-cs2030/2324-s2/assets/94443578/71366151-b34b-46a4-8c54-0e42f9d4ee07)

This is from my arrive.
![image](https://github.com/nus-cs2030/2324-s2/assets/94443578/4b7ba87b-0cd6-4227-8d8b-85ca2ddfdc86)

This is my executeEvent from wait.
![image](https://github.com/nus-cs2030/2324-s2/assets/94443578/95fd2801-7d42-45fd-a629-7e5f422b74a1)

Any help is appreciated, thanks!

**Comment by Jeremythong2002** [comment]
The issue is likely that you only update the queue at the wait event. Hence, only after the 3 waits does the queue get full. It might have been working thus far because the test cases might not have triggered such a case. 

Essentially, the issue is that only when a wait event is called, does the server register that there is a new customer in the queue. 

Updating each server's list of customer in the Arrive event will likely resolve the issue that you are facing

**Comment by SumitShinde0702** [comment]
> The issue is likely that you only update the queue at the wait event. Hence, only after the 3 waits does the queue get full. It might have been working thus far because the test cases might not have triggered such a case.
> 
> Essentially, the issue is that only when a wait event is called, does the server register that there is a new customer in the queue.
> 
> Updating each server's list of customer in the Arrive event will likely resolve the issue that you are facing

Hi, so sorry but that didnt work. Is there any other possibility you can think of?

**Comment by ZHD1987E** [comment]
You might want to see #665 for some ideas how to debug.

**Comment by ZHD1987E** [comment]
By the way if you managed to solve it, mark as closed @SumitShinde0702, let's help to declutter the forum yeah?

**Comment by SumitShinde0702** [comment]
i just ditched the rest event class and went to directly update the serverlist
