### ISSUE TITLE
Lab 5 Flatmap unable to work after setting getters to private

### ISSUE THREAD

**Issue by lifrocszh** [nus-cs2030/2324-s2#425]
# Summary
Flatmap cannot work after setting getters to private

## Description:

The logic of my flatmap was that using mapper to apply twice, and use the getters for both the value T and log  to return a new Log.of()

But now due to the regrading I cannot set the getter methods to public and flatmap does not seem to work. 

Is there any way to work around it? Or is my flatmap logic wrong to begin with? 

![image](https://github.com/nus-cs2030/2324-s2/assets/163915921/ee60943f-5aa2-4041-9437-172d34ca8c5f)

**Comment by eleorakow** [comment]
you shouldn't need to write getters for this though
maybe try to adapt your code without using getters, as for this lab they do not allow any methods, apart from those they told us to write in the lab, to be public.

**Comment by caleblowy** [comment]
what i did is
Log<? extends U> newLog = mapper.apply(this.t)
U = newLog.getT()
String = newLog.getLog()
then when constructing the new Log, instead of mapper.apply(this.t).getT() i just use U

**Comment by nicklass8** [comment]
Hi lifrocszh, you can consider splitting up your code into smaller and separate parts instead of putting all of it in the return statement to see if there is any error in the current return statements

**Comment by iceflakes12** [comment]
Your getters dont work because ? extends Log has getter methods set to private, and when you set those methods to private, only the same class can access these methods

What i mean is that Log cannot access the getter methods in mapper.apply(this.t)

Try doing something like mapper.apply(this.t).<U>map(x -> x).getT() and it should work
