### ISSUE TITLE
Understanding referential transparency 

### ISSUE THREAD

**Issue by dingus891** [nus-cs2030/2324-s2#429]
In general, to check for referential transparency, an execution of a statement of code ...e...e... is equivalent to invoking a function definition { v = e; return (...v...v...); }. Suppose we are given the function

void r(List<Integer> queue, int i) {
    queue.add(i);
}
and the statement foo(bar(r(q)),baz(r(q)));

We cannot replace this with { v = r(q); return (foo(bar(v),baz(v))); } because the state of the list q is changed after the first call to r(q), and calling r(q) again will give a different result.

to be honest i don't get this how does the state of the list q change when there have been no modifications done to it. Any explainations would be greatly appreciated thank you :)

**Comment by mChewWW** [comment]
hmmm.........

**Comment by samuelneo** [comment]
> there have been no modifications done to it

what do you mean by this? `q` is mutable, passing `q` into `r` will result in `i` being added to `q` (I presume you meant to call `r` with 2 arguments, since that's the method signature provided here). so `q` will be modified if you pass it into `r`

**Comment by x2qian** [comment]
hii i think 'foo(bar(r(q)),baz(r(q)))' should be avoided, and effect-free '{ v = r(q); return (foo(bar(v),baz(v))); }' should be used instead.

with v = r(q), you are storing r(q) to v with r(q) only being called once. this ensures that youre using the same r(q) in bar(v) and baz(v) as the argument. on the other hand, calling 'foo(bar(r(q)),baz(r(q)))' might change r(q) since bar is applied to it then passed into baz.

hope this helps!

**Comment by dingus891** [comment]
> In general, to check for referential transparency, an execution of a statement of code ...e...e... is equivalent to invoking a function definition { v = e; return (...v...v...); }. Suppose we are given the function
> 
> void r(List queue, int i) { queue.add(i); } and the statement foo(bar(r(q)),baz(r(q)));
> 
> We cannot replace this with { v = r(q); return (foo(bar(v),baz(v))); } because the state of the list q is changed after the first call to r(q), and calling r(q) again will give a different result.
> 
> to be honest i don't get this how does the state of the list q change when there have been no modifications done to it. Any explainations would be greatly appreciated thank you :)


but does r not require another int input for q to be modified

**Comment by lim-4158** [comment]
no, when u call this line "queue.add(i)" 
you are essentially modifying ur queue already by adding a new int i to the queue. 
lets say the queue.add(10). now the queue will be (... , 10). 
but if u call it again queue.add(10), now the queue will have one more number than before (... ,10, 10)
hence not effect free (state changes)

unlike ImList, nomatter how many times u call add, imlist is still the same imlist, 
hence effect free (state does not change) 

hope that clears things up
