### ISSUE TITLE
Can we update instructions to set up UNIX and Vim?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#43]
As many people faced problems (for Windows Computers) with installing msys through Scoop, I managed to find an easier way through the Windows Subsystem for Linux (WSL). Here is what I propose:

---

# Setting up your Unix Environment

If you run Windows 10 or 11, it is possible to download Microsoft's WSL app [here](https://www.microsoft.com/store/productId/9P9TQF7MRM4R?ocid=pdpshare).

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/2f30096d-5811-498e-a983-2c366b7d144b)

Click on 'Download' and it should start.

Once it is downloaded, you can run `WSL` on the start menu, through Microsoft Terminal, or through the Command Prompt.

If it is your first time, it will prompt you to key in your UNIX Username:

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/d56e91a7-64c6-41e5-ba8a-e465fda8b387)

You can just press enter for the time being.

After a while, you are ready to start installing Java into your Unix environment!

# Installing Java on your environment

Once you are on this page:
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/b90b5bfb-80af-4e51-a5f1-0988ee2241aa)

Go ahead and run this command `sudo apt install openjdk-17-jdk-headless`

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/93eab5e2-a499-486c-8906-0452e6678796)

Once prompted, type `Y` and it will start installing.

Once it is done, you have successfully installed Java and you are ready to run Java!

An important note:

As the version installed is headless, you will face problems while going to edit mode. To resolve this:

1: Open Jshell by typing `jshell`

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/226d2957-637d-4098-b5d2-8930de790d5c)

2: Enter this command: `\set editor -retain vim`, you can replace vim with any other pre-installed Unix text editors (like emacs)

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/b388c557-396c-4c3d-94ee-99e18f5df302)

Now you are ready to use your environment.

---

**Comment by hwkchia** [comment]
Yes, WSL2 is another alternative.  We tried it a few semesters ago, but realized that different machines require different setups too.

**Comment by hwkchia** [comment]
Forgot to add on... please feel free to update the wiki with an alternative installation procedure.  You shall be given credit. :smile:

**Comment by ZHD1987E** [comment]
I can't edit...

**Comment by hwkchia** [comment]
Could you try again?  Thanks.

**Comment by ZHD1987E** [comment]
Alright, I have edited the page with instructions for WSL.

Closing issue now, thank you!
