### ISSUE TITLE
SICK AND TIRED OF CODECRUNCH TELLING YOU WRONG PROJECT TEST CASES OR YOUR CODE TIMING OUT?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#431]
Never mind, generate your own test cases.

For me, what I did was the following:

1. Basic function check of server allocation (and self checkouts)
2. Basic function check of resting periods (set probability to 1)
3. Basic function check of queuing (just DDOS your DES and see how it responds)
4. Integrated testing of self checkouts and normal servers 
5. Stress testing
6. No people come
7. No servers and no checkouts

Anyway, this will be greatly needed in many other places (inc. CS2040)!

Hopefully CodeCrunch keeps quiet and passes your code!

[Just don't call CodeCrunch and scream at the void deck of Block 225 Yishun Street 21.](https://www.youtube.com/watch?v=Mkqj7EcKzC0)

Update: I get questions regarding code timing out all thanks to an infinite loop.

Here's what I suggest:
1: Trying when all customers arrive
2: Trying when all customers arrive in a short span of time (e.g. within 0.1 second)
3: Trying when all customers arrive just after a customer leaves
4: Trying when all customers arrive in a longer span of time (e.g. 10 seconds or more)
5: Attempting to DDOS your simulator

**Comment by ZHD1987E** [comment]
# BONUS: Logpoints

Are you on an IDE? Then try using logpoints!
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/a327c1a2-1ef7-4d80-90a9-7d65b1a1f48b)
Happy debugging.

**Comment by iceflakes12** [comment]
w(°ｏ°)w

**Comment by ya-en** [comment]
☆*: .｡. o(≧▽≦)o .｡.:*☆

**Comment by Jeremythong2002** [comment]
ᗒᗣᗕ

**Comment by JosiahPraeman** [comment]
w(°ｏ°)w amazing

**Comment by proteaninja** [comment]
thanks for the tips!

**Comment by Slyriss** [comment]
Thanks!

**Comment by nus2030** [comment]
oh wow thats that was really insightful!

**Comment by CChaosuan** [comment]
oh no!!!

**Comment by ZHD1987E** [comment]
## Bonus Bonus

Do you hate the default supplier time? Want to spice things up?

Then copy over the rest time supplier onto that default supplier for serving times.

Have fun!

**Comment by quadryan** [comment]
Thanks for the input!

**Comment by kziyang1207** [comment]
Thank you !!

**Comment by delulu04** [comment]
thanks for the tips!!!

**Comment by NicOre0** [comment]
wow thanks for the tip!

**Comment by NicOre0** [comment]
wow thanks for the tip!

**Comment by linguinyi** [comment]
thank you!

**Comment by yuntsingg** [comment]
Thanks a lot!!
