### ISSUE TITLE
Project Error

### ISSUE THREAD

**Issue by ZhengJie2001** [nus-cs2030/2324-s2#433]
# Summary
Error: class not found: *.class

## Description 
hi, has anyone faced this error before? 

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/158128400/22385a15-2ee0-4d29-ad84-269839b77dc7)

**Comment by ZHD1987E** [comment]
Hmm... Looks like a technical issue, try submitting again. Or try running `Checkstyle` command to see if any issues arise.

**Comment by ZhengJie2001** [comment]
weird, works when i submitted again! @ZHD1987E
