### ISSUE TITLE
Lecture 8 PDF has 4 slides per page instead of 1

### ISSUE THREAD

**Issue by chongshaohong** [nus-cs2030/2324-s2#435]
# Description

On Canvas the lecture 8 PDF has 4 slides per page like "lecture08_4on1.pdf".

**Comment by ZHD1987E** [comment]
That is for the benefit of those printing out their lecture slides…

**Comment by chongshaohong** [comment]
> That is for the benefit of those printing out their lecture slides…

I meant that both "lecture08_4on1.pdf" and "lecture08.pdf" had 4 slides on 1 page...

**Comment by chongshaohong** [comment]
But it has been fixed, thanks!
