### ISSUE TITLE
Project issue - use of restricted API

### ISSUE THREAD

**Issue by ccqie233** [nus-cs2030/2324-s2#436]
# Summary
CodeCrunch - use of restricted API detected

## Description 
Use of Random detected
I implemented a class of RestTimeSupplier which imported Random, and that is the only place where Random is used.
(This supplier is quite similar to the defaultServiceTime supplier).
Does it mean random should be used anywhere else?

## Screenshots (if any): 
<img width="486" alt="Screenshot 2024-04-03 at 10 35 05 PM" src="https://github.com/nus-cs2030/2324-s2/assets/98001460/01d5c7e1-3cf6-4a3c-91c6-ae4ab98f9bfb">
<img width="587" alt="Screenshot 2024-04-03 at 10 35 24 PM" src="https://github.com/nus-cs2030/2324-s2/assets/98001460/af3feb27-a5f7-4ac7-960d-1a8288a6ec91">

**Comment by TongZhengHong** [comment]
You don't have to create a random generator. It is already provided in the given `Main.java` file within a `Supplier`. 
You can find the file here: [Main.java](https://codecrunch.comp.nus.edu.sg/taskfile.php/5614/Main.java)
```java
import java.util.Scanner;
import java.util.function.Supplier;
import java.util.Random;

class Main {
    private static final Random RNG_REST = new Random(3L);
    private static final Random RNG_REST_PERIOD = new Random(4L);
    private static final double SERVER_REST_RATE = 0.1;

    static double genRestPeriod() {
        return -Math.log(RNG_REST_PERIOD.nextDouble()) / SERVER_REST_RATE;
    }

    public static void main(String[] args) {
        ...
        Supplier<Double> serviceTimes = () -> 1.0;
        Supplier<Double> restTimes = () -> RNG_REST.nextDouble() < probRest ? genRestPeriod() : 0.0;
        ...
    }
    ...
}
```
Just make sure you pass `serviceTimes` and `restTimes` into your `Simulator` class

**Comment by trishaa17** [comment]
yep, a new main.java is given, just need to redownload it from codecrunch

**Comment by ccqie233** [comment]
thank you!!
