### ISSUE TITLE
Final Project Test Case 3

### ISSUE THREAD

**Issue by ameliaw286** [nus-cs2030/2324-s2#439]
Hi, I can't seem to understand what I did wrong.. I only updated the rest time of the server after Done event, and ensured to use the most updated servers' list.. i managed to get A for lab3, so im not sure if this is somehow bc of how i added the rest times?

![Screenshot 2024-04-04 202812](https://github.com/nus-cs2030/2324-s2/assets/153805393/11c1ca8c-3764-4e43-80fe-bc03d4d03581)
![Screenshot 2024-04-04 202820](https://github.com/nus-cs2030/2324-s2/assets/153805393/87357853-bd08-40da-bc3b-9b1e97103c69)
![Screenshot 2024-04-04 203050](https://github.com/nus-cs2030/2324-s2/assets/153805393/f990087b-c73c-4ed2-9a5c-08be3be72fc8)

any help is appreciated, thank you!

**Comment by s4dha** [comment]
did your code pass the public testcases on code crunch? cause if it did, i think your servers are resting properly.  from lines 8,9 the issue seems like as if customer 3's arrival time is >= than server 1's finish time even after it has served customer 2, hence the serve event is linked to server 1. by right, server 1 is supposed to rest and hence the finish time is supposed to be larger. i think the issue is the fact that the most updated server with the updated timestamp is not being used, you can check 
whether you properly looped through the servers list to get the most updated server, or whether you correctly set the server in the server list after your done event, you can look at the issue that i posted cos i think i faced a similar issue.

**Comment by nicklass8** [comment]
Hi this happened to me as well, I passed lab 3 on code crunch but encountered this issue. How i solved it is that apparently my Serve and Done event were not using the updated server from the most updated server list which may have been overlooked or did not affect any test cases from lab 3 so you can check if yours is the same issue as well

**Comment by nus2030** [comment]
hi, correct me if im wrong but it seems like the servers are not resting properly. if customer 3 is being served again by 1, it looks like the rest time was not implemented right. did you check that the rest time introduced at the end of a done class properly?

**Comment by andhika2002** [comment]
Hi, I faced a similar problem. From the first screenshot, I see that your server 1 is free, when customer should be waiting at server 2 instead, perhaps your dequeueing of customers once they have been served is done wrongly? I realised that I was dequeueing customers in both the serve event, and the done event. Once I fixed the dequeueing to only happen once(in the Serve class, when I want to return a Done Pair), it solved all test cases up until test case 9. Hope this helps!

**Comment by ameliaw286** [comment]
thank u everyone for ur help!! managed to pass till test case 9!!

**Comment by ameliaw286** [comment]
@wxlee1807 hi! for me, it was mainly design issues for the Event classes, and not the rest times! basically, stuff like adding the customers to the queue in my ArriveEvent when it should have been done in my WaitEvent etc.. or another thing i changed was to have the WaitEvent return only the HoldEvent and not ServeEvent/HoldEvent, because HoldEvent should be the one in charge of updating the servers' updated timings during the HoldEvent and not the WaitEvent! i think the most important thing is ensuring that your event classes do what their name says!

if you managed to pass the public test cases in the preamble, i think the servers' rest times are implemented correctly (at least that was the case for me), the issue shld just be from ArriveEvent to ServeEvent.. maybe you can write out the logic flow from Arrive to Serve, and start from there! all the best!!
