### ISSUE TITLE
Changing primary working directory for MINGW64

### ISSUE THREAD

**Issue by ArkAzrael** [nus-cs2030/2324-s2#44]
Currently my MINGw64 defaults to the Windows home directory, how to I change it so that it points to the msys home directory instead?

**Comment by gnimnix** [comment]
Why do you need it to point to the msys home directory?

If you would like to open a terminal in a folder, you can right click on a folder and select "Open in Terminal". Alternatively, you can type `cmd` or `powershell` in the file path at the top.

![image](https://github.com/nus-cs2030/2324-s2/assets/47523729/fa9d3748-a030-4bee-90f1-f15cc1900925)
