### ISSUE TITLE
Lab 6 level 3

### ISSUE THREAD

**Issue by JovanFoo** [nus-cs2030/2324-s2#443]
![Screenshot 2024-04-05 at 6 59 54 PM](https://github.com/nus-cs2030/2324-s2/assets/133492195/18527409-14cd-4aea-954e-1687510c4ad2)
<img width="703" alt="Screenshot 2024-04-05 at 7 00 07 PM" src="https://github.com/nus-cs2030/2324-s2/assets/133492195/5869808e-042f-42ce-841e-6bcb42bd24a1">

Im not sure how to edit this so that it can take into account the scenario above. Anyone can help?

**Comment by ccyenn** [comment]
i solved this by adding an additional statement when i = 0 to just compare the first 2 in the list

**Comment by isaacyclai** [comment]
You can use conjunction with another condition in your filter function to account for the case when one of the repeating sequences starts from the first element.

**Comment by FadhilPM** [comment]
Your stream has to account for the element at index 0.

**Comment by JovanFoo** [comment]
I see okay i tried it and it works thank you!
