### ISSUE TITLE
Lab 6 level 4

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#444]
# Summary

Bad return type in lambda expression

## Description:

my IntStream cannot be converted to List<integer> inside my unary operator method so how to i rectify this compilation error.

![Screenshot 2024-04-05 191819](https://github.com/nus-cs2030/2324-s2/assets/111676024/32a6defb-eead-457c-a82e-5ce098fae555)

![Screenshot 2024-04-05 192101](https://github.com/nus-cs2030/2324-s2/assets/111676024/f853e7f0-3e99-42d3-a696-6758436ca501)

**Comment by isaacyclai** [comment]
First, use one of the IntStream methods to convert it to a Stream. After that you can just use .toList()

**Comment by Monoji77** [comment]
Hi Josiah, also consider what happens are each iteration of your map. Does your values change? Is your ternary operator giving the desired output? 

I would create a separate IntStream to store my final output.

**Comment by SumitShinde0702** [comment]
Similar to above, i created a seperate List<Integer> which contain intstream but i used mapToObj before collecting toList.

**Comment by RatesLearner** [comment]
IntStream is a specialized stream for handling primitive int values, while List<Integer> is a collection of Integer objects. When you use map with IntStream, it expects a mapping function that produces int values, not Integer objects. Therefore, you must use mapToObj instead, which allows you to map int values to Integer objects, thus converting the IntStream to a stream of Integer objects.
