### ISSUE TITLE
lab 5 cannot find symbol

### ISSUE THREAD

**Issue by Yuxin-Mellisa** [nus-cs2030/2324-s2#447]
<img width="390" alt="Screenshot 2024-04-05 at 10 56 48 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157778558/1041b337-b7f8-4ee7-aec6-b5f0ce6375b4">
I am pretty sure that I put it in my level5.jsh and the shell says ok
why does it say cannot find the method?

**Comment by kubrian** [comment]
Do check out #421, #412 and #409. Potential issue with your method signature of flatMap

**Comment by x2qian** [comment]
hii i think the error is caused by the return type of mapper Function in flatMap()

**Comment by Yuxin-Mellisa** [comment]
but my jshell works?

**Comment by Yuxin-Mellisa** [comment]
Thanks I got it all

**Comment by Yuxin-Mellisa** [comment]
Thanks I got it
