### ISSUE TITLE
Lab 6 Task 3

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#449]
I am having trouble figuring out the logic for Task 3, as I do not know what to use for the function

Here is my code
<img width="443" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/3b7557dc-9c6d-4b2c-88cc-6790a2f52280">

Output:
<img width="433" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/49599536-5673-47c1-bcb5-06b9d21d3f6c">
For some reason, it prints 3 instead of 1.

Any help is appreciated.

**Comment by ZHD1987E** [comment]
You can see #442 and #443!

**Comment by kubrian** [comment]
You might have confused the purpose of .distinct() here. filter doesn't act on the list, it does not collect the '1's, it collects the indices instead, and so .distinct() is not the right tool here.

https://github.com/nus-cs2030/2324-s2/issues/442#issuecomment-2039326929 mentions a strategy for you to filter.

**Comment by hadyamanisanto** [comment]
For #443, I have trouble figuring out the additional condition for the additional test case. Any help is appreciated.

**Comment by ZHD1987E** [comment]
@hadyamanisanto You may need to figure out the case when you are going to exceed the boundaries, in that case you may need a ternary operator to help deal with that.

It takes some experimenting, but you’ll get the hang of it.

**Comment by yewkhang** [comment]
> For #443, I have trouble figuring out the additional condition for the additional test case. Any help is appreciated.

Not sure if its the easiest way to implement but how i did it is to use ternary operators to check whether the loop is at the first index such that there is a 1 set of code for checking the first 2 elements and another to check for the remaining elements

Ternary operators
``` Java
(condition to check) ? (code to execute if true) : (code to execute if false)
```

**Comment by hanlinnnnn** [comment]
in ur code ure double counting, say its a sequence of 1, 1, 1, ur code would treat it as 2 repeated occurrence but the desired output is 1. to resolve this issue, u can add an additional .filter() to keep only the indices of the 1s whose left neighbour isnt a 1.

do note that if u do this ^, u'll have to account for the edge case of the first element as it doesnt have a left neighbour

**Comment by phantomeng** [comment]
> > For #443, I have trouble figuring out the additional condition for the additional test case. Any help is appreciated.
> 
> Not sure if its the easiest way to implement but how i did it is to use ternary operators to check whether the loop is at the first index such that there is a 1 set of code for checking the first 2 elements and another to check for the remaining elements
> 
> Ternary operators
> 
> ```java
> (condition to check) ? (code to execute if true) : (code to execute if false)
> ```

thanks for this!

**Comment by hadyamanisanto** [comment]
I finally figured it out. Thanks everybody!

FYI: To those reading this, try testing with 
(0,0,0)
(0,1,1)
(0,0,1)
(0,1,0)
-->All of them return 1 except the last one, which returns 0.

**Comment by ZHD1987E** [comment]
![FriendsPhoebeGIF](https://github.com/nus-cs2030/2324-s2/assets/140680858/e7cf1185-651f-458a-be6a-39096dfb1847)
