### ISSUE TITLE
Jshell test failure

### ISSUE THREAD

**Issue by mccqi** [nus-cs2030/2324-s2#45]
hi, I am on Mac and I followed the steps to setup, but for the jshell test, I have "The operation couldn’t be completed. Unable to locate a Java Runtime." as the output instead.

**Comment by gnimnix** [comment]
What is the output when you run `java --version` ?

**Comment by mccqi** [comment]
its the same output

**Comment by gnimnix** [comment]
Try doing 

```
echo 'export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"' >> ~/.zshrc
```
then do 
```
source ~/.zshrc
```
Then try to run the above commands again.

**Comment by gnimnix** [comment]
Seems right! try running your tests again

**Comment by mccqi** [comment]
it worked now, thanks so much 
but I have another issue with the vim setting, after renaming the extension, it reflected as document instead of VIMRC file

**Comment by gnimnix** [comment]
could u send a screenshot of what u mean?

**Comment by mccqi** [comment]
<img width="1044" alt="Screenshot 2024-01-26 at 10 47 24 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157803620/f1c3b95d-9389-42d3-9c20-876eb2be1d1a">

**Comment by gnimnix** [comment]
name it as `.vimrc` instead of `vim.vimrc`

**Comment by mccqi** [comment]
it doesn't allow me to use a name that begins with a dot?

**Comment by gnimnix** [comment]
checkout https://stackoverflow.com/a/51788836

**Comment by mccqi** [comment]
Yeap I tried it beforehand but it still reflects as document

**Comment by gnimnix** [comment]
thats fine, its also reflecting as document for me. only on Windows does it reflect as `VIMRC` file

<img width="769" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/47523729/d60ee96a-8c98-42c5-91c7-791d947748a9">

**Comment by mccqi** [comment]
oh okk, thanks for the help!
