### ISSUE TITLE
Lab 6 Level 4: Restricted API detected

### ISSUE THREAD

**Issue by mikio13** [nus-cs2030/2324-s2#451]
# Summary
My gameOfLife method is causing this error when submitting to CodeCrunch.

```
Use of restricted API detected.
> java.util.Objects
Grading terminated.
```

## Description:
I've only used methods like reduce, map , Stream.iterate. So I'm not sure what's causing this.

**Comment by zzzlou** [comment]
I think it might be because Stream.iterate? could try implementing without it

**Comment by weikiatt** [comment]
I think Stream.iterate is fine, I used it and did not encounter any issues. Could be due to whats inside your functions

**Comment by Slyriss** [comment]
You can try to just directly import java.util.stream.IntStream, import java.util.stream.Stream etc

**Comment by gnimnix** [comment]
Are you using `mapToObj`?

**Comment by mikio13** [comment]
Yep, i did use mapToObj in my `generateRule() ` is that the issue?

**Comment by gnimnix** [comment]
Yes, that could be the issue since you are typecasting each element into an `Object`, the grader detects this and throws this error. You might want to try a different approach by using `IntStream.of()` and then use `.boxed().toList()` to convert everything back into a `Stream` of `Integers`.

**Comment by mikio13** [comment]
Thanks everyone, I managed to solve it. The issue was due to using this syntax `rule::apply` inside `Stream.iterate`.
