### ISSUE TITLE
Lab 06 Level 4

### ISSUE THREAD

**Issue by hanlinnnnn** [nus-cs2030/2324-s2#452]
Hello just wanted to ask how did you guys implement gameOfLife()? I used Stream.iterate() and it passes all cases but I'm trying to implement the method without Stream.iterate() and I cannot figure out how to do it

**Comment by kohtw** [comment]
It does seem like Stream.iterate() in order to pass this specific test case since the one of the input is an UnaryOperator. I think it is possible to do a range(0, n) and use x and run them individually, however this will be very inefficient and difficult to implement.

**Comment by RatesLearner** [comment]
This method generates a stream of strings representing the successive generations of the Game of Life. It starts with the initial population, applies the given rule for each generation, and limits the stream to n generations. Each integer in a generation is mapped to either "." or "x" based on whether it represents a dead or living cell, respectively. These mappings are then joined into a single string for each generation.

**Comment by lifrocszh** [comment]
amongst all the methods in stream, only iterate takes in a UnaryOperator, so im not too sure also

**Comment by jtcones** [comment]
I believe that if you want to implement it with just a pipeline, Stream.iterate(f) is certainly the best as it returns x, f(x), f(f(x)), … which is what is desired by level 4. 

Overall, I think the pipeline is quite clean by using iterate.

**Comment by Monoji77** [comment]
initially did recursion and ended up with "check with your tutor"  in codecrunch despite getting the desired crosses and dots LOL

**Comment by iceflakes12** [comment]
I used map, reduce and boxed, not sure how Stream.iterate() really works out here but I guess as long as it works it works.

**Comment by ZHD1987E** [comment]
I hope it all worked out @hanlinnnnn...

If you can solve this issue, you might want to close this issue to help declutter the forum. Thanks!
