### ISSUE TITLE
Lab 06 Level 4 Checking of bounds

### ISSUE THREAD

**Issue by cyting01** [nus-cs2030/2324-s2#453]
Hello, I would assume for generateRule() it would go along the lines of something like this. However, I'm unsure on how to check for the cases where x == 0 or x == list.size() - 1 and hence deal with them accordingly to prevent any indexing errors. Are we allowed to use if/else statements in the middle of our pipelines? Thanks!

![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/0ed9a57f-c29e-4585-9e52-a18a8a2701f3)

**Comment by MarcusLiangg** [comment]
I have a similar solution to you, but I did check the neighbours to see if they are corners in the left corner (x > 0) and right corner (x < list.size()). If true, then list.get(x), else 0.

**Comment by kshoo-0957315** [comment]
I used Math.max() and Math.min to ensure that i do not go out of bounds

**Comment by jihyun88888** [comment]
u can try setting it like 
(x != 0 ? list.get(x - 1) : 0) + (x != (list.size() - 1) ? list.get(x + 1) : 0)) == 1

**Comment by zining2004** [comment]
hi, i used .map(x -> { if else }), to check if x ==0  and x == list.size() -1, maybe you can try that

**Comment by quadryan** [comment]
if you are using IntStream.range your range of numbers should be 0 to list.size() -1.
if you are using IntStream.rangeClosed your range of numbers should be 0 to list.size() -2.
This is because of indexing principles. Hope this helps!

**Comment by kohtw** [comment]
you can check if your x is 0 or list.size()-1, then do seperate checks (i.e. only one side) to ensure you dont check out of bounds

**Comment by JovanFoo** [comment]
I used if/else statements in my map and it works. Maybe you can try?

**Comment by ZHD1987E** [comment]
Alright, since I hate typing code I have a few pointers:
- Assume that anything beyond bounds will ALWAYS be a dead cell. But only modify your own cell yeah?
- Use a LOT of ternary operators.

**Comment by cyting01** [comment]
It works now, thank you everyone for the help! Didn't know you could use if/else statements inside a map
