### ISSUE TITLE
Lab 6 Level 4 Output

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#455]
# Summary

Description of the question / problem here.

## Description:

I dont understand this output, the question states that "If a cell is alive in one generation, it will be dead in the next."

Therefore, since the entire row is alive in the first generation should the subsequent generation all be dead?

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/0c195ea1-6412-4522-9888-a443fe0b1036)

**Comment by ZHD1987E** [comment]
Confirm something wrong with your generateRule()

What I do is:

```
public class Main {
    // your code goes here

    public static void main(String[] args) {
        generateRule().apply(List.<Integer>of([Your test list goes there]))
    }
}
```

**Comment by LimZiXiong** [comment]
Seems like the cell being alive at this generation has more priority than neighboring cells being alive. If at an index it's alive and the neighboring cell is alive, it will still die anyway as it was alive

**Comment by allis-g** [comment]
I had this error too and its because I didn't check the case for the first and last cell so do check your code to make sure u account for them

**Comment by weiyangng** [comment]
thanks all for the advice also I confused the expected output with my output so the question doesnt really make sense in hindsight haha
