### ISSUE TITLE
Lab 6 level 4 output

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#456]
Where did my output go lol and does my generaterule seem correct?

![Screenshot 2024-04-06 205524](https://github.com/nus-cs2030/2324-s2/assets/111676024/cabc86e3-80b4-4e8a-a1bb-fe3e5910805a)
![Screenshot 2024-04-06 205458](https://github.com/nus-cs2030/2324-s2/assets/111676024/053404a4-ce3f-470c-92b0-7dbf7467b55a)

**Comment by kshoo-0957315** [comment]
There seems to be missing logic for when the cell must remain 0 if left and right are 1 for generate rule. And for the method-wise your method name should be gameOfLife. (capital L)
