### ISSUE TITLE
Test Case 9

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#46]
# Summary

Details of Test Case 9

## Description:

I failed test case 9 but I don't know what went wrong. Is there a way to see the entire output on code crunch? Trying to infer from part of the output make it quite difficult to pinpoint the problem.

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="476" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156635387/a1c0ee24-0f82-420d-904a-5501de203f5c">

**Comment by ZHD1987E** [comment]
Just as your customer is about to leave, someone just stepped in.

Rather than accept that someone, you decide to kick that man out even if you are free.

you = the server

**Comment by BZAStudent** [comment]
Hello, thanks for the reply
I don't think this is the problem. I tried out with 1 server and two customer with customer A finish time = customer B arrival time. 

> Just as your customer is about to leave, someone just stepped in.
> 
> Rather than accept that someone, you decide to kick that man out even if you are free.
> 
> If that customer was Kurt Tay Foo Wei, he will label you a **HATER** and will not hesitate to **BAN** or/and **DELETE** you.
> 
> [Video of his ‘delete’ gimmick](https://m.youtube.com/watch?v=pm7rGcdnlq0)
> 
> you = the server

**Comment by ZHD1987E** [comment]
_Now that you told me that..._

You are someone directing people to the next available server. As you see one customer leave from one server, another customer comes and you direct them to the other server.

Then an argument ensued and if that customer was Kurt, he'll still **BAN** or/and **DELETE** you.

_tl;dr something is wrong with your allocation logic_

**Comment by codingtemp** [comment]
Did you try with 2 server and one customer?

If server 1 and server 2 are both avaliable to serve customer A, server 1 should be the one serving customer A. 
One way to do this is to ensure that your servers are always sorted in the right order
> Hello, thanks for the reply I don't think that is the problem. I tried out with 1 server and two customer with customer A finish time = customer B arrival time and server 1 is able to serve customer B

**Comment by wkleow123** [comment]
i would suggest doing a little bit of code tracing since the error occurs at the first 2 inputs so it should not be too difficult to see what went wrong with the logic. it may be due to using >= instead of > for comparing the server times and arrival times that is a possibility.

**Comment by BZAStudent** [comment]
> _Now that you told me that..._
> 
> You are someone directing people to the next available server. As you see one customer leave from one server, another customer comes and you direct them to the other server.
> 
> Then an argument ensued and if that customer was Kurt, he'll still **BAN** or/and **DELETE** you.
> 
> _tl;dr something is wrong with your allocation logic_

Yup, this is the problem. Thanks
