### ISSUE TITLE
Project Test Case 12/18

### ISSUE THREAD

**Issue by MarcusLiangg** [nus-cs2030/2324-s2#460]
# Summary
Does anyone know how to test or what test case 12 is testing? I solved test case 11 by taking the minimal availableTime and now I'm stuck with this. I've been trying out different test cases but can't find the error. I know it's an infinite loop, but idk how it happened.

## Screenshots (if any): 
<img width="509" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157345221/2b43b165-c61d-4cc0-b226-65a03536cd8c">

My wait code
<img width="494" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157345221/1cdde8cb-8cd7-4d2d-b02e-835e0a333e86">

**Comment by ZHD1987E** [comment]
Taken from my #431 'Q&A':

> Update: I get questions regarding code timing out all thanks to an infinite loop.
> 
> Here's what I suggest:
> 1: Trying when all customers arrive
> 2: Trying when all customers arrive in a short span of time (e.g. within 0.1 second)
> 3: Trying when all customers arrive in a longer span of time (e.g. 10 seconds or more)
> 4: Attempting to DDOS your simulator

**Comment by mikio13** [comment]
When you create the Serve event did you remove the customer from the queues of all self checkouts? From your code it seems like you only removed it from `Server s`, you could try adjusting this.

**Comment by MarcusLiangg** [comment]
@mikio13 hmm the way I implemented it is that customers will only queue for the 1st self checkout server so only 1 of them would have a queue

**Comment by JovanFoo** [comment]
Hey Marcus do you happen to have the test input for 9_11? im having trouble with that

**Comment by JovanFoo** [comment]
> @JovanFoo I don't the specific one I test for but what I did is sort of follow the codecrunch one (e.g. 0 Human 5 Self-Checks with close timings)

Alright thank you!

**Comment by jesgiveup** [comment]
ahh I think you can try to check for whether s2 is a selfcheckout before taking it's available time as minAvailableTime!

**Comment by nicthepurplejelly** [comment]
Hi! It seems that your condition to create a wait event is always true, this.getCust().getCustID() != s.getNextCustID(), hence resulting in an infinite loop?

**Comment by yishao17** [comment]
Hi, idk if my error is the same as urs but I got TLE error too. What I did was to add in print statements in my execute method of all event class and run the test case locally. It will show which part keeps executing and from there, u can see which method is wrongly implemented/ logic error. After doing that, I realised my Hold event cant move to a serve event, even though the timing changed so it kept returning another Hold event of the same timestamp, hence leading to infinite loops. Maybe u can try this printing lines method too to debug ur code! all the best, hopefully this helps!

**Comment by starryfieldz** [comment]
Hi @MarcusLiangg, can I check how did you resolve it eventually? I am currently facing the same problem as you and cannot seem to remedy it as well.

**Comment by MarcusLiangg** [comment]
@starryfieldz oh yes, it's resolved. Sorry for the late reply!! But yes, the problem was I did not check if it was a self-checkout counter before assigning the earliest available time!

Maybe check if your code checks the server type again before changing the value?
