### ISSUE TITLE
Exercise 05 Maybe Class don't understand code behaviour

### ISSUE THREAD

**Issue by cth06-Github** [nus-cs2030/2324-s2#463]
<img width="749" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/106983097/612dbaef-f32b-4407-91ff-bca75d631b2a">

For this Maybe Exercise 5, the code shown on the left is the one that allows me to compile. I tried to write the 3 lines of code into 1 line, as shown on the right. But when I do so, I can't compile anymore, giving me that error.

**Question:** Why is there an error if I squeeze the 3 lines of code into 1 line? What does the error "defined in an inaccessible class or interface" exactly mean? I thought about whether it's because the get() function in Maybe class is private, but, if so, won't there be an error for the code written with 3 lines (left part of the picture)?

Thank you!

**Comment by samuelneo** [comment]
Prof brought up something similar in class regarding the implementation of `flatMap`, and he let us go back to think about it. I added a section to [Lecture 7 on our Wiki](https://github.com/nus-cs2030/2324-s2/wiki/Lecture07) to explain this behaviour:

> In the definition of `flatMap`, you may be tempted to chain the three statements together, as follows:
> ```Java
> <R> Maybe<R> flatMap(Function<? super T, ? extends Maybe<? extends R>> mapper) {
>    if (this.isEmpty()) {
>        return Maybe.<R>empty();
>    }
>    return Maybe.<R>of(mapper.apply(this.get()).get());
>}
>```
>However, this will result in a compilation error.
>
>The key observation to make here is that `get` is a private method defined in `Maybe`, and `mapper.apply(this.get())` returns a value of type `? extends Maybe`. We cannot guarantee being able to call `get` from a subclass of `Maybe`. Hence, the result of `mapper.apply(this.get())` first has to be assigned to a variable of type `Maybe`, which we can guarantee being able to call `get` on.

The same applies to the definition of `or`: calling `supplier.get()` returns an `? extends Maybe`, which you cannot guarantee being able to call `get` on, hence you have to first assign it to a `Maybe`.

**Comment by hanlinnnnn** [comment]
cuz `mapper.apply(this.get())` returns `? extends Maybe<? extends R>`, which means not only can it return a Maybe, it can return a child class of Maybe

t can return say a `Child<T>` that extends `Maybe<T>`, in which case it cannot access the `.get()` in Maybe, since its `private`

**Comment by cth06-Github** [comment]
Ohhh I see, I understand now.  Thanks for the explanation!
