### ISSUE TITLE
Project test case 9_9

### ISSUE THREAD

**Issue by urmothergei** [nus-cs2030/2324-s2#464]
# Summary
Im stuck with project test case 9_9 but cant seem to figure out what is the problem...
Can someone provide me with some guidance? thanks!

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="490" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/126307515/a8af01a7-433f-4629-93b5-5e37fd8e1ce3">

**Comment by ZhengJie2001** [comment]
maybe you can check your DoneEvent to see if they are returning the correct customer and server?

**Comment by luckrainbow** [comment]
Kind of looks like the service time was generated in the wrong order of customers

**Comment by JovanFoo** [comment]
i think the error lies in the passing of time from serve to done

**Comment by urmothergei** [comment]
<img width="493" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/126307515/83fc365a-9559-4695-a4ae-72f1ae70ea66">
I suspected i accidentally called customer.getServiceTime() > once. I tried calling once more and it turns out to be true, the times reflected are different. Problem solved. Thanks everyone!!
