### ISSUE TITLE
Project Test Case 3 - servers not resting

### ISSUE THREAD

**Issue by kingcard02** [nus-cs2030/2324-s2#465]
Hi all, would anyone happen to know where I went wrong for my project test case 3? It appears that my server is not resting as it is supposed to for customer 10. Similarly, on 3.in, my server is supposed to rest after serving customer 5 but he serves customer 6 right away. Would greatly appreciate it if you can help to see where the problem is. Thanks!!!
![Screenshot 2024-04-07 122632](https://github.com/nus-cs2030/2324-s2/assets/163496518/7489eb6a-869d-4ba7-8bcc-4739c3aa95c2)
![photo_6093672816604986495_y](https://github.com/nus-cs2030/2324-s2/assets/163496518/1cba9180-91f9-4855-a154-bb80dcc4e8b1)
//Execute for Wait/Queue class
![Screenshot 2024-04-07 123339](https://github.com/nus-cs2030/2324-s2/assets/163496518/29ef25c4-ad1a-42be-9a52-06affa07133e)
//Execute for Done class
![Screenshot 2024-04-07 123410](https://github.com/nus-cs2030/2324-s2/assets/163496518/ec794852-8853-4289-baa3-ae7e93e4e74b)

**Comment by hadyamanisanto** [comment]
Try having the Servers rest in the Done event class.

**Comment by luckrainbow** [comment]
Could your code be calling the rest time Supplier multiple times?

**Comment by hadyamanisanto** [comment]
> Could your code be calling the rest time Supplier multiple times?

Hint: You can call it with get() like in Lab 3.

**Comment by santtoshh** [comment]
Hi! I had the exact same problem with test case 3 line 38. I solved it by tweaking the logic in my Wait/Waiting class, at the part that returns a new Serve event. Hope it helps!

**Comment by kingcard02** [comment]
okay solved alr. thanks!!

**Comment by caleblowy** [comment]
hi how did you solve this?

**Comment by kingcard02** [comment]
@caleblowy create a new rest class to update server status, create new servingStatus attribute in Server, false by default. when a customer is served this changes to true, when a server is done this status does not change until the server is DoneResting (event executed) then servingStatus changes to false. in wait event, customer is only served when servingStatus is false.
