### ISSUE TITLE
Lab 6 level 4 testcase 4

### ISSUE THREAD

**Issue by pickledpepper03033030** [nus-cs2030/2324-s2#467]
Don't understand why for this test case, the middle cell is still alive even though it was alive in the previous generation 

![Screenshot 2024-04-07 141918](https://github.com/nus-cs2030/2324-s2/assets/163503742/ecc1c7a0-e1dc-4685-822d-b70f4b411dc4)

**Comment by samuelneo** [comment]
it looks like that testcase takes in a different gamerule. your `gameOfLife` should apply whichever gamerule is passed in

**Comment by hanlinnnnn** [comment]
i think this test case tests for ur gameOfLife, how it functions with other rules, to ensure students do not implement the rule within gameOfLife itself but rather take it out as a separate function

**Comment by lifrocszh** [comment]
hi, it seems like this test case takes another rule instead of generateRule(), so it is probably that your gameoflife fails when another rule is taken in

**Comment by hadyamanisanto** [comment]
Refer to #462 for hints.

**Comment by hzhitong** [comment]
It might be a possibility that you have hardcoded the rule, so one thing you can do now is to change your gameOfLife method so that it is flexible and works for other contexts

**Comment by TongZhengHong** [comment]
Ran into this issue as well, turns out I was using `generateRule()` method instead of using the `rule` parameter from the `gameOfLife` method. Hope this helps

```java
static Stream<String> gameOfLife(List<Integer> list, UnaryOperator<List<Integer>> rule, int n) { ... }
```

**Comment by Xenonwizard** [comment]
Yep perhaps check how your gameOfLife is printing. a hint wld be to use iterate, map and reduce.
