### ISSUE TITLE
Project Test Case 9_11 Request

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#468]
Recently, I have figured out how to make the waiting customer in the self-check counter go to the nearest counter instead of being fixated at the first counter as shown here:
<img width="450" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/3ed537ef-a033-49ec-a000-02f024872697">

However, I still could not pass test case 9_11
<img width="581" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/d64ea8ef-533c-43c3-806a-9945996f5638">

What seems to be the problem here? Also, I would appreciate some test cases and expected outputs for me to test.
Any help is appreciated.

**Comment by kohtw** [comment]
16 and 17 should have waited at 3 because it has an empty queue. Does you customer wait at any other checkouts except for the first checkout?

u can try the same cat5.in file but add extra customer(s) to see if they wait at other counters

**Comment by hadyamanisanto** [comment]
> 16 and 17 should have waited at 3 because it has an empty queue. Does you customer wait at any other checkouts except for the first checkout?
> 
> u can try the same cat5.in file but add extra customer(s) to see if they wait at other counters

No actually, how I implemented it is that for the self-check counters, only the first self-check counters has a functioning queue, as the remaining self-check counters have a maximum queue length of zero. This means that all waiting customers wait at the first self-check counter.

**Comment by hadyamanisanto** [comment]
![IMG_5211](https://github.com/nus-cs2030/2324-s2/assets/158229622/39f0c04a-51bd-414d-9325-1740b44aa913)

For this, does customer 3 wait in the queue, or go to self-check 3?

**Comment by hadyamanisanto** [comment]
UPDATE: Turns out I made some changes to my Arrive and Serve functions, but forgot to submit the updated ones to CodeCrunch! I now passed all my test cases. Thank you!

For those reading this, refer to the ideal test case given above.

**Comment by leeyenkai** [comment]
Hi, can I ask what changes you made to your arrive and serve classes?
