### ISSUE TITLE
Ex 5 error unchecked cast

### ISSUE THREAD

**Issue by hzhitong** [nus-cs2030/2324-s2#469]
Hi guys does anyone know what is one way to resolve this error on codecrunch? 
![image](https://github.com/nus-cs2030/2324-s2/assets/156508021/2455b273-f373-4988-8d71-84fc6a238a74)

**Comment by ccyenn** [comment]
u can try unwrapping and assigning it to an R before wrapping it again in a maybe

**Comment by hzhitong** [comment]
It works now, thank you so much!
