### ISSUE TITLE
Multiple output detected Compilation errors in codecrunch

### ISSUE THREAD

**Issue by Jett-Tan** [nus-cs2030/2324-s2#47]
# Summary

Compilation errors upon submitting

## Description:

The codes run perfectly fine in the current terminal but not in codecrunch
Multiple output detected.

## Code Snippets

Attach code snippets (if any)

## Screenshots
![image](https://github.com/nus-cs2030/2324-s2/assets/68832631/2cda3033-15e2-43c1-96b1-874f8540d107)

![image](https://github.com/nus-cs2030/2324-s2/assets/68832631/c2bfa6ce-543f-4194-bf28-d7dcc1e0bdf4)
![image](https://github.com/nus-cs2030/2324-s2/assets/68832631/35eec216-4cd1-4f09-9392-128f7fe8d85a)
![image](https://github.com/nus-cs2030/2324-s2/assets/68832631/55eb4ffe-0dcf-4855-8ef9-3459dfc57ea2)

**Comment by LMDlifers** [comment]
Do you have multiple iterations of system.out.println? That could be a potential issue.
