### ISSUE TITLE
Lab 05 level5.jsh isn't loading

### ISSUE THREAD

**Issue by yf-yeoo** [nus-cs2030/2324-s2#470]
For some reason, level5.jsh isn't loading for me on codecrunch, but its working fine on my computer.

<img width="290" alt="s1" src="https://github.com/nus-cs2030/2324-s2/assets/164670622/3ace1080-9cde-4c29-90c6-75c3acfe9747">

<img width="379" alt="s3" src="https://github.com/nus-cs2030/2324-s2/assets/164670622/aaf3cb82-20d6-4276-a3bb-31580a6cea09">

**Comment by hzhitong** [comment]
Hi, you can refer to this [post] (https://github.com/nus-cs2030/2324-s2/issues/412)

One thing you can consider is to change the method signature for flatMap from
Log flatMap(Function<? super T, Log> f)
to
Log flatMap(Function<? super T, ? extends Log<? extends R>> f)

**Comment by Slyriss** [comment]
You might need to change your mapped log as well to <? extends R> as well

**Comment by yf-yeoo** [comment]
Thanks for the helpful comments, changing the method signature resolved the issue
