### ISSUE TITLE
Lab 6 Task 3 Indexing

### ISSUE THREAD

**Issue by kohsweehong** [nus-cs2030/2324-s2#471]
## Description:

Faced with an indexing issue when it comes to repeated numbers are the beginning for countRepeats(), how do I fix this?

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/156646904/e2aa2b45-6795-4c18-903b-ee1ba80b11e3)

**Comment by niclow236** [comment]
You may need to account for cases when ur index i == 0. Your code might have a part where it tried to compare the index of i-1 or i-2 so as to not count repeated occurrences. This causes an index out of bounds error as shown. Maybe add a || condition for when i == 0 to circumvent this issue?

**Comment by niclow236** [comment]
> ohh okay, its like the idea of "base case". Thank you!

Yep something like that where you need consider the outlier cases
