### ISSUE TITLE
.boxed() method

### ISSUE THREAD

**Issue by niclow236** [nus-cs2030/2324-s2#474]
# Summary

Hi, may i ask why only for IntStream, DoubleStream and LongStream, the .boxed() method needs to be called before calling the .toList() method to convert the stream to a list. However, for Stream, there is no need to call .boxed() and .toList() can be called directly? Thanks

**Comment by kohsweehong** [comment]
IntStream, DoubleStream and LongStream are Streams handling primitive type, i.e. for IntStream is handling primitive int. So in order to convert it to, e.g. a List<Integer>: a list of Integer Objects, you would need the boxed() method to be called to convert it Integer Object, i.e Stream.<Integer>.

**Comment by niclow236** [comment]
> IntStream, DoubleStream and LongStream are Streams handling primitive type, i.e. for IntStream is handling primitive int. So in order to convert it to, e.g. a List: a list of Integer Objects, you would need the boxed() method to be called to convert it Integer Object, i.e Stream..

Oh so basically the boxed() method puts each value in the stream into its corresponding wrapper class?

**Comment by kohsweehong** [comment]
yes, in an instance of IntStream.boxed() it would box the primitive int to an Object Integer

**Comment by HaoZeHuin** [comment]
IntStream, DoubleStream, LongStream: Streams of primitives. They do not support the .toList() method directly because they are not streams of objects. You must call .boxed() to convert them to a Stream of objects before you can call .toList().

**Comment by niclow236** [comment]
> yes, in an instance of IntStream.boxed() it would box the primitive int to an Object Integer



> IntStream, DoubleStream, LongStream: Streams of primitives. They do not support the .toList() method directly because they are not streams of objects. You must call .boxed() to convert them to a Stream of objects before you can call .toList().

Ok thanks!
