### ISSUE TITLE
Lab 5 Test 5_1

### ISSUE THREAD

**Issue by Castelle-code** [nus-cs2030/2324-s2#475]
# Description
Can't seem to pass test case 5_1. It seems to work in my code but can't seem to run on CodeCrunch?

## Screenshots
<img width="357" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157040750/2b791152-f930-4e81-80c8-a31b623c5bdc">

mine:
<img width="176" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157040750/032a3274-0795-445a-be63-d86a62b72de8">

**Comment by jaiwee** [comment]
hello i think issue #412 might be helpful for this, you can refer to it ! 

it might be an issue with the method signature, maybe u can check if it matches this:
Log flatMap(Function<? super T, ? extends Log<? extends R>> )
