### ISSUE TITLE
Lab 6 Level 4 Stream Queries

### ISSUE THREAD

**Issue by wallaacee26** [nus-cs2030/2324-s2#476]
# Summary

Hi, I am a little unsure when to use the various functions available to convert streams (e.g. into List).

## Description:

For level4's generateRule() and gameOfLife() functions, it seems that I can use .boxed() or .collect(...) to collect my results, but is there a specific scenario to choose which of the two to use? Also, are there any other methods that help to collect my stream elements into my desired type (E.g. from Stream<Object> to List<Integer>)? Thanks for any help!

**Comment by wkleow123** [comment]
boxed is a good way to convert IntStream if you're using it into a Stream which has the toList method

**Comment by kailincoder** [comment]
for collect, the method allows u to specify ur own collector , so  u can use things like Collectors.toList( ) or Collectors.toMap( ) to collect streams into your desired types. 

for .boxed( ), its better if you want to use it for primitive steams and convert them to boxed types, such as int to Integer, then you can use stream operations for the reference type

**Comment by JovanFoo** [comment]
I used boxed() and tolist() to convert the primitive int values generated by the map operation into Integer objects and then collect them into a List<Integer>.

**Comment by wallaacee26** [comment]
Thanks everyone for clarifying :)
