### ISSUE TITLE
Project Test Case 9_03

### ISSUE THREAD

**Issue by xinnyyy** [nus-cs2030/2324-s2#477]
hi all, for test case 9_03, im not quite sure of my errors. it seems that my customer 15 is waiting at the wrong server (1 instead of 2). But I thought the customer will wait at the first server with the queue size < qmax? Or assuming that server 1 queue size > q max, I did do a for loop to ensure that the customer will wait at the next server if so. My code passed all the public test cases in code crunch, and I did get an A for lab3 so I'm not quite sure of the issue. any help is appreciated thank you

<img width="383" alt="Screenshot 2024-04-08 at 10 53 34 AM" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/33fbc055-d8c0-4c2e-944e-6190f230cdae">

**Comment by samuelneo** [comment]
I had a similar issue at first. are you retrieving the most updated version of the serverList? this is usually caused by not updating the queue correctly in edge cases, or using an outdated version of serverList

**Comment by huangtian666** [comment]
^^, yea you may not be using the most updated list of servers. and depending on how you implemented your Wait event, you may need to change your condition to return a Serve event. but make sure your event time is >= serverAvailableTime then u return a Serve event.

**Comment by xinnyyy** [comment]
@huangtian666 ohhh! could it be a problem in my wait event? i am not updating the queue when a customer waits because i thought if the customer is still waiting the server queue remains the same? i checked through my arrival event and serve events, i did use the getQueue method to retrieve my queues at the start so im not quite sure of the error too

<img width="657" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/fe3ce3f0-4b68-437e-871e-63ac4f103259">

**Comment by andhika2002** [comment]
hi, i faced similar issue where customer waits at 1 instead of two. what I realised was erroneous in my code was that I was removing customers in both my **serve** event (when issuing a done event+updated serverList) and **also in my done** event. Maybe can try checking if the way you remove your customers is correct + at the right event? since your customer waits at 1 instead of 2, maybe it's because the customer in server 1 was dequeued wrongly when he should have remained in the queue, leading to the customer to wait at server 1's queue instead of server 2's queue. hope this helps!

**Comment by naomiiiwu** [comment]
> I had a similar issue at first. are you retrieving the most updated version of the serverList? this is usually caused by not updating the queue correctly in edge cases, or using an outdated version of serverList

hi  I encountered the exact same problem. May I know what the possible edge cases are? Thank you so much.

**Comment by xinnyyy** [comment]
hello! i resolved this issue alr! it turns out that my intermediate event was just returning an intermediate event and i did not check if the customer is at the front of the queue (indexOf == 0) && timeStamp > findAvailableTime! i did that in wait event but turns out that wasnt enough and i had to apply the same logic of the wait event in my intermediate event instead of my intermediate event returning serve event! not sure if we have the same implementation but making those changes resolved this issue!




> > I had a similar issue at first. are you retrieving the most updated version of the serverList? this is usually caused by not updating the queue correctly in edge cases, or using an outdated version of serverList
> 
> hi I encountered the exact same problem. May I know what the possible edge cases are? Thank you so much.

**Comment by xinnyyy** [comment]
> > I had a similar issue at first. are you retrieving the most updated version of the serverList? this is usually caused by not updating the queue correctly in edge cases, or using an outdated version of serverList
> 
> hi I encountered the exact same problem. May I know what the possible edge cases are? Thank you so much.

https://github.com/nus-cs2030/2324-s2/issues/477#issuecomment-2047902520

**Comment by xinnyyy** [comment]
> > I had a similar issue at first. are you retrieving the most updated version of the serverList? this is usually caused by not updating the queue correctly in edge cases, or using an outdated version of serverList
> 
> hi I encountered the exact same problem. May I know what the possible edge cases are? Thank you so much.

hello! i resolved this issue and the change i made was that my intermediate event was returning serve event without checking if customer is at the front of the queue and if timestamp > available time. i applied this logic only in wait event but turns out the same logic is needed for intermediate event to either return another intermediate event or a serve event. once i made those changes the issue was resolved! not sure if we have similar implementations but hope this helps!

**Comment by naomiiiwu** [comment]
> > > I had a similar issue at first. are you retrieving the most updated version of the serverList? this is usually caused by not updating the queue correctly in edge cases, or using an outdated version of serverList
> > 
> > 
> > hi I encountered the exact same problem. May I know what the possible edge cases are? Thank you so much.
> 
> hello! i resolved this issue and the change i made was that my intermediate event was returning serve event without checking if customer is at the front of the queue and if timestamp > available time. i applied this logic only in wait event but turns out the same logic is needed for intermediate event to either return another intermediate event or a serve event. once i made those changes the issue was resolved! not sure if we have similar implementations but hope this helps!

hi may I know how you checked if the customer is at the front of the queue? Cuz im using an integer to represent the queue.

**Comment by samuelneo** [comment]
> > I had a similar issue at first. are you retrieving the most updated version of the serverList? this is usually caused by not updating the queue correctly in edge cases, or using an outdated version of serverList
> 
> hi I encountered the exact same problem. May I know what the possible edge cases are? Thank you so much.

I don't remember exactly what I did to fix this, but it was something along the lines of checking that I'm always checking the server from the serverList (and not any other server which could be possibly outdated), and checking that my server.enqueue (which increments the queue length by 1) and server.dequeue (which decrements the queue length by 1) are always called at the right times. in my case I enqueued only in Arrive in the case where Arrive goes to Wait, and I dequeued only in Wait in the case where Wait goes to Serve.

according to #402, a possible issue is:

> checking for the case where the servers serve event ends earlier than another server, but has longer resting time, resulting in the next serve event starting later than the other server

**Comment by xinnyyy** [comment]
> > > I had a similar issue at first. are you retrieving the most updated version of the serverList? this is usually caused by not updating the queue correctly in edge cases, or using an outdated version of serverList
> > 
> > 
> > hi I encountered the exact same problem. May I know what the possible edge cases are? Thank you so much.
> 
> hello! i resolved this issue and the change i made was that my intermediate event was returning serve event without checking if customer is at the front of the queue and if timestamp > available time. i applied this logic only in wait event but turns out the same logic is needed for intermediate event to either return another intermediate event or a serve event. once i made those changes the issue was resolved! not sure if we have similar implementations but hope this helps!

yep i did! i used if server.getQueue().indexOf(customer) == 0 to check
