### ISSUE TITLE
EVER FANCY A TEST SCRIPT TO MAKE SURE YOU DON'T CALL SUPPLIERS MANY TIMES?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#478]
[Here you go.](https://github.com/ZHD1987E/ZHD1987E/blob/main/TestSupplier.java)

For now, this doesn't have wildcards (which means if you put a Double, it cannot support an Integer).

**Comment by ZHD1987E** [comment]
# How to use? (in the context of the project)

1: Determine how many customers there are in your simulator
```
        int count = 0;

        while (sc.hasNextDouble()) {
            arrivalTimes = arrivalTimes.add(sc.nextDouble());
            count++;
        }
```
2: Initialise this `TestSupplier` like this:
```
Supplier<Double> equipment = new TestSupplier<Double>(yourSupplierGoesHere, count);
```
3: You're ready to go!

**Comment by JovanFoo** [comment]
thank you!

**Comment by kingcard02** [comment]
thanks!!! very helpful

**Comment by nicthepurplejelly** [comment]
thanks!
