### ISSUE TITLE
Test Case 9_9 

### ISSUE THREAD

**Issue by delulu04** [nus-cs2030/2324-s2#479]
# Summary
Im facing trouble w test Case 9. 

## Description 
My method is to put in the self checkouts into the same serverImList passed through all events. Then in Arrive, I check for 
1. Idle server first 
2. Idle Self checkout counter 
3. Available server queue 
4. Available SCC queue 

However, I am facing a problem such that my customer is waiting in server queue instead of the SCC. (SS below). Since i have passed the first 9 test cases I am assuming that my queueing and updating of queues is correct thus far. Any advice on what is wrong here? Thanks!

## Screenshots (if any): 
<img width="758" alt="Screenshot 2024-04-08 at 12 27 25 PM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/90580454-24f8-40da-90c7-8f1f988fa231">

**Comment by delulu04** [comment]
<img width="861" alt="Screenshot 2024-04-08 at 12 36 16 PM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/2130d238-bf79-49ae-bceb-8ed6f7356040">
Update: I realised I didn't save the Wait file with updated toString method, but I am still facing issues with Server queue

**Comment by kee-x** [comment]
You should change your code such that all the self-checkout servers will share the same queue. Therefore, when the queue is full, the customer will leave automatically.

**Comment by JovanFoo** [comment]
you can consider adding the same customer to all SCC queues and removing index 0 of the queue from all SCC queues when the customer is served.

**Comment by delulu04** [comment]
thanks all, i realise the issue was with how i handled the serverQueue of SCC. I did not properly update and dequeue from the first SCC :O
