### ISSUE TITLE
Codecrunch indentation issue

### ISSUE THREAD

**Issue by LMDlifers** [nus-cs2030/2324-s2#48]
Hi Prof, currently CodeCrunch is flagging tabbing issues and requires us to manually space our lines one by one. May I know if this feature is intended?

**Comment by weikiatt** [comment]
I think tabbing in /edit class causes the issue, tabbing in vim shouldn't cause this issue

**Comment by leeyenkai** [comment]
If you're referring to having to type 4 spaces instead of tab then it might be intended as it's not allowed as per the style guide.

https://github.com/nus-cs2030/2324-s2/wiki/Java-Style-Guide#cs2030-coding-style

You can edit `~/.vimrc` as per the guide if vim isn't working correctly.
