### ISSUE TITLE
override error

### ISSUE THREAD

**Issue by c-510** [nus-cs2030/2324-s2#480]
# Summary
Serve.java:69: error: method does not override or implement a method from a supertype
    @Override

## Description 
what does this mean.... codecrunch kept giving me F because of this, removed the override and it works but just curious about this

**Comment by samuelneo** [comment]
that warning occurs when you've added the `@Override` annotation to a method that doesn't actually override a method in a superclass

**Comment by juelin708** [comment]
you may also  check the method signatures ie number and types of parameters, make sure it is aligning with the method in superclass

**Comment by ZHD1987E** [comment]
Did it help, @c-510?

If so, you might want to close this issue and declutter the forum yeah?

Thank you!
