### ISSUE TITLE
Test Case 9_11

### ISSUE THREAD

**Issue by notlynnnn** [nus-cs2030/2324-s2#483]
# Summary
Help Needed for Project Test Case 11

## Description 
For my WaitEvent class, if the server is a self-checkout server, i understand that i have to loop through serverList, find the self-check counter with the earliest available timing to serve the customer, and if no self-check counters are available, i generate another wait event with the self-check counter with the earliest available timing as well. However, I'm not sure why am i still getting this output or if the problem lies in the other classes. Any advice on this? Thanks!

## Screenshots (if any): 
![Screenshot 2024-04-08 at 4 31 12 PM (2)](https://github.com/nus-cs2030/2324-s2/assets/147187749/4b20aa7a-b175-445a-bf22-8a4fd87864f8)

**Comment by joshuagde** [comment]
Yes the logic is correct, so i think maybe the issue lies in the code because based on this output, it seems like the customers that are waiting in that self-checkout counter 3 is only due to pop out of the PQ when SCC 3 is next available, when it should be popping out at the earliest available timing out of all the SCCs

**Comment by hadyamanisanto** [comment]
<img width="447" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/75efb862-5a4a-450d-9791-26da6a40dbf9">

Try this test case. If 4 is served by 2 instead of 1 and it matches my output, then it usually works. If not, try checking your arrive, serve and done events.

**Comment by mcjuh** [comment]
The logic seems fine so the issue is most likely in your WaitEvent class code, delaying services later then they should occur. Do check that the queues for self-checkout counters is combined. I put that queue on the first self-check counter and no queues on the other self-check counters. Iterating through the server list, if a self-counter is identified (which is guaranteed to be the k + 1 counter with the queue) then I loop through the rest of the counters first to find the minimum available time, call the ServeEvent and update the queue accordingly. All the best, you are on the right track :)

**Comment by notlynnnn** [comment]
> <img alt="image" width="447" src="https://private-user-images.githubusercontent.com/158229622/320417356-75efb862-5a4a-450d-9791-26da6a40dbf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTc1ODMsIm5iZiI6MTcxMjY1NzI4MywicGF0aCI6Ii8xNTgyMjk2MjIvMzIwNDE3MzU2LTc1ZWZiODYyLTVhNGEtNDUwZC05NzkxLTI2ZGE2YTQwZGJmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxMDA4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTczNWZmNzNhZjY2NWE0NTUxYWI3ZGE4NDBhNGFjYmNiYjM1ZmU4MjUzNjliM2YwY2Y2YmU3MzdhMDlhZjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QaDPITjidtAbIlZ98mcVD27goh9tF9W-SaFKOgVSOHM">
> Try this test case. If 4 is served by 2 instead of 1 and it matches my output, then it usually works. If not, try checking your arrive, serve and done events.

I have used this test case to help debug and have passed it, thank you so much!

**Comment by IYKYKY** [comment]
Need to find the soonest available self-checkout counters. I write it in Wait Event so that when scc-4 is free, 13 will be served by 4 instead of keep waiting at scc-3 (but remember to update queue and scc next available time correctly)

**Comment by mChewWW** [comment]
> Yes the logic is correct, so i think maybe the issue lies in the code because based on this output, it seems like the customers that are waiting in that self-checkout counter 3 is only due to pop out of the PQ when SCC 3 is next available, when it should be popping out at the earliest available timing out of all the SCCs

i had the same issue, this is the right answer

**Comment by Bryanng41** [comment]
> <img alt="image" width="447" src="https://private-user-images.githubusercontent.com/158229622/320417356-75efb862-5a4a-450d-9791-26da6a40dbf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDg5NzIsIm5iZiI6MTcxMzE0ODY3MiwicGF0aCI6Ii8xNTgyMjk2MjIvMzIwNDE3MzU2LTc1ZWZiODYyLTVhNGEtNDUwZC05NzkxLTI2ZGE2YTQwZGJmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMjM3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjBjMWJlMjRjNTkwYzc1YjVjYmU5ZDI3ZjhmNWQ2NDE0MzgyMTRkNmU3NjZmNTE4ZDU5ZTIzOWIyMWJhZTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E7jXdDV2cr4yDSYgpy7xW7edtLmaWU2Y-VfoQMY2XIQ">
> Try this test case. If 4 is served by 2 instead of 1 and it matches my output, then it usually works. If not, try checking your arrive, serve and done events.

![image](https://github.com/nus-cs2030/2324-s2/assets/52643493/41ec3f67-f987-4421-ab04-5905e1a6b1b7)
![image](https://github.com/nus-cs2030/2324-s2/assets/52643493/94b8af7c-12bd-4735-87a7-cddbc2d0fef9)
Adding on to that test case I added more customers and self-checkout counters to test the behavior of my code and this is the test case with the expected outcome. I think if you can get your classes to behave this way you'll be able to clear all the test cases on code crunch

**Comment by kexuannn** [comment]
hello! I had the same problem, it might be because when you move from a Wait to your next Wait event, the waittime added to your customer is wrong, causing the overall time that the comparator uses to be wrong, and your event to be pushed back in the PQ. I think you can consider looping to find the self-check with the earliest available time and set that as the overall time to be used for the comparator in your Wait class instead. Hope it helps!

**Comment by IYKYKY** [comment]
> hello! I had the same problem, it might be because when you move from a Wait to your next Wait event, the waittime added to your customer is wrong, causing the overall time that the comparator uses to be wrong, and your event to be pushed back in the PQ. I think you can consider looping to find the self-check with the earliest available time and set that as the overall time to be used for the comparator in your Wait class instead. Hope it helps!

so smart, kex!

**Comment by wdgyn** [comment]
Hi, I also had the same problem. If your implementation have two wait class (eg. one wait and another wait) and also from wait class to the another wait class, you pass in the server's next avail time, then this might help you. So when going from the wait class to another wait class, you need to find the fastest avail server and also pass in the next avail time of the fastest avail server.

**Comment by isaaclim33** [comment]
i did a for loop to check for the earliest avail time for the self-checkout counters and pass it into a new wait event

**Comment by ZHD1987E** [comment]
@notlynnnn The project is over.
