### ISSUE TITLE
Lab 5 test case 5_1 too many flatmap printed

### ISSUE THREAD

**Issue by squgily** [nus-cs2030/2324-s2#485]
# Summary

anyone encountered this issue? too many flatmaps

<img width="275" alt="Screenshot 2024-04-08 at 6 09 51 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157218084/99e6819f-4122-4fa4-9af4-b3257d6458b3">

I'm getting the correct answers for the rest of the test cases

**Comment by ZHD1987E** [comment]
See #293

**Comment by squgily** [comment]
> See #293

Thanks! solved
