### ISSUE TITLE
map vs mapToObj

### ISSUE THREAD

**Issue by ezclap02** [nus-cs2030/2324-s2#487]
hi, when to use map and when to use mapToObj?

**Comment by iceflakes12** [comment]
I assume you are talking about IntStream.

mapToObj returns a Stream while map returns an IntStream, I guess you can say mapToObj is used in more generic cases when you do not want to map integers in the IntStream to an integer but rather a different object.

**Comment by nus2030** [comment]
typically this is used when your unary operator inside your map changes the values from a number to something apart from a number. x -> x.toString() for instance will change it, and it will not be a number so you should use mapToObj

**Comment by JovanFoo** [comment]
Use map() to transform elements of a stream from one type to another, and mapToObj() specifically when converting elements of primitive streams to object types.

**Comment by harvestingmoon** [comment]
mapToObj can also be used when you want to collect items together, rather then to map them individually.

**Comment by jennipho** [comment]
map can be used for streams of any type, and mapToObj can only be used with primitive streams like IntStream (and thus to transform each primitive element in the stream to objects)

**Comment by yishao17** [comment]
from what I know, map() is more general and flexible, working with streams of any type, while mapToObj() is specific to primitive streams and is used to convert them into streams of objects. hope this doesn't make it more confusing for u haha

**Comment by RatesLearner** [comment]
map is employed to transform elements of a stream into another type of stream while typically preserving the type of the elements, making it suitable for primitive streams like IntStream, LongStream, and DoubleStream. 

mapToObj is specifically designed to convert elements of primitive streams (such as IntStream, LongStream, DoubleStream) into elements of reference streams (e.g., Stream<Integer>, Stream<Long>, Stream<Double>).

**Comment by meowmeowpeepee** [comment]
mapToObj is used in the case of lab 6 level 4, because the function with argument: List<Integer> return non-Primitive Object/Integer
map only can be used on primitive types(int) or when fn returns primitives
but both still map each element of stream to another using provided fn
just that map is to another value, mapToObj is to a Object
