### ISSUE TITLE
unable to access jarfile 

### ISSUE THREAD

**Issue by mccqi** [nus-cs2030/2324-s2#49]
I had this error when going through checkstyle HelloWorld.java, i tried the command 'explorer.exe .' in the previous raised issue but it did not work out for me, is there any way I can proceed?

**Comment by gnimnix** [comment]
please provide screenshots of your terminal showing what commands you ran and the errors

**Comment by mccqi** [comment]
<img width="992" alt="Screenshot 2024-01-28 at 6 21 53 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157803620/7e91e139-34b9-4dbe-b95b-9c51a563eef9">

it shows command not found for 'explorer.exe .'

**Comment by gnimnix** [comment]
Did you place the `checkstyle-10.3.3-all.jar` file in folder `/Users/YourName/`?. I think in your previous post you placed it in a folder called `java-setup`?
