### ISSUE TITLE
Lab 6 countRepeats

### ISSUE THREAD

**Issue by Timmyneedsbzahelp** [nus-cs2030/2324-s2#491]
# Summary

Codecrunch is giving me 2367813189318 errors how do I even interpret them 😢 

## Description:

I thought I finally got it to work but now
What's with all that
yapping what do they even mean ?? how to fix >:(

## Screenshots

<img width="813" alt="Screenshot 2024-04-09 at 12 20 24 AM" src="https://github.com/nus-cs2030/2324-s2/assets/165639538/167be651-0f37-4091-81de-27c5d0282321">

**Comment by iceflakes12** [comment]
Just Index out of bounds. You are trying to access memory that doesn't exist. In simple terms let's say your list has n elements but you try to access the n+1th element then it throws you this error because the n+1th element does not exist.

**Comment by sarahquan** [comment]
I believe its because your index is out of bounds - i.e. you are looping through a number that is greater than the size of your list. If you minus 1 to your loop, it would probably fix everything. Cheers!

**Comment by sarahquan** [comment]
If you still need help, you can send a picture of your code!

**Comment by Timmyneedsbzahelp** [comment]
> Just Index out of bounds. You are trying to access memory that doesn't exist. In simple terms let's say your list has n elements but you try to access the n+1th element then it throws you this error because the n+1th element does not exist.

Oh I got the first error but what about the rest they are confusing me like I definitely do not have 500 lines of code

**Comment by iceflakes12** [comment]
> > Just Index out of bounds. You are trying to access memory that doesn't exist. In simple terms let's say your list has n elements but you try to access the n+1th element then it throws you this error because the n+1th element does not exist.
> 
> Oh I got the first error but what about the rest they are confusing me like I definitely do not have 500 lines of code

just tracing where your error occurs.

Since you are using Streams and the guy who wrote Streams probably also used some other packages so the error tracing actually goes quite far. I mean I would usually just ignore the whole thing.

**Comment by nus2030** [comment]
hi, there would be that many errors because these are operations in the stack and it is being returned back to the client as the operations were terminated somewhere down. in any case, if ure counting repeats and ure indexing, i wld suggest you to check your IntStream.range(??, ??), make sure that it is within the range of the size of the list that is the input. pretty sure the problem can be fixed if you included rangeClosed or just subtract 1 from the 2nd argument of the range(?, ?). hope it helps!
