### ISSUE TITLE
Project error

### ISSUE THREAD

**Issue by xman666888** [nus-cs2030/2324-s2#495]
# Summary
can get correct answer, but get error in codecrunch.

## Description 
COMPILATION ERRORS

Multiple output detected.
Grading terminated.

## Screenshots (if any): 
<img width="509" alt="截屏2024-04-09 17 06 17" src="https://github.com/nus-cs2030/2324-s2/assets/156694748/a5738029-4de0-4047-a787-df97aabfd291">

**Comment by feliciahmq** [comment]
try submitting without your main pair imlist pq and default service time files

**Comment by weiyangng** [comment]
just comment out your print statements it should work after that
