### ISSUE TITLE
.filter() method

### ISSUE THREAD

**Issue by proteaninja** [nus-cs2030/2324-s2#496]
<img width="405" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157028018/10df3846-3fe7-4393-b0cf-caf2ff491f72">

Why does the code above produce such an error...

<img width="635" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157028018/24125561-81e5-415d-afc1-30c5fb2d5cc3">

...but its okay when the code is as such?
<img width="414" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157028018/70a062c2-7dfa-49cc-876b-026aa1008cb2">

**Comment by wkleow123** [comment]
might be because when u put the conditions with the .get(i-2) first, the code has to run them and get(1-2) will be -1 and out of the bounds of your list, but when u put i == 1 first, it does not run the other condition since i==1 is already true

**Comment by jpowcm** [comment]
filter conditions are checked in the order that you write them so its important to place the more specific condition (i == 1 in this case) first
