### ISSUE TITLE
“ask ur tutor error"

### ISSUE THREAD

**Issue by iqour** [nus-cs2030/2324-s2#498]
Hi, anyone has encountered this error message before?
It sounds very scary.
Before task 4 everything was fine but after that it appeared.

<img width="733" alt="Screenshot 2024-04-09 at 7 39 16 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157214306/819bb7fd-f9a6-4a75-b994-b593ebb837d7">

**Comment by meowmeowpeepee** [comment]
i think you just check with your tutor bro, don't be scared

**Comment by xman666888** [comment]
maybe prof changed some test case?

**Comment by Luzimomo** [comment]
I did recursion for task 4 and encountered that. I fixed it by changing to using Stream methods instead.

**Comment by harvestingmoon** [comment]
As mentioned above, don't try to use recursion, stick to using Streams instead for that lab
