### ISSUE TITLE
Exercise 5 Maybe

### ISSUE THREAD

**Issue by iqour** [nus-cs2030/2324-s2#499]
Anyone can help me explain why the commented line does not work? 
Is it something related to Generics?
![WechatIMG7307](https://github.com/nus-cs2030/2324-s2/assets/157214306/c1ece4a5-d4c0-476d-9ab0-e4e0a96e0fc6)

**Comment by jpowcm** [comment]
The commented line will work but will not be as flexible. The uncommented line is more flexible as it allows the function to take in a supplier which can supply anything that is a subtype of Maybe, which should be allowed as a subtype of Maybe is a Maybe. So basically in our code we should always try to implement the most flexible signatures which allow for any input and output that makes sense, by using ? extends for inputs and ? super for outputs.

**Comment by iqour** [comment]
> Check the indentation of "return"
> 
> To answer your question : The difference between public Maybe or(Supplier<? extends Maybe<? extends T>> supplier) and public Maybe or(Supplier<Maybe<? extends T>> supplier) lies in the flexibility of the Supplier parameter. In the first method signature (public Maybe or(Supplier<? extends Maybe<? extends T>> supplier)), Supplier<? extends Maybe<? extends T>> means that the supplier can provide any subtype of Maybe<? extends T>. This allows for more flexibility in the types of Maybe instances that the method can accept as arguments. However, in the second method signature (public Maybe or(Supplier<Maybe<? extends T>> supplier)), Supplier<Maybe<? extends T>> restricts the supplier to only provide instances of Maybe<? extends T>. This is less flexible because it requires the exact type specified by the method signaturethis, otherwise logic looks correct.

thank you i get it now!!
