### ISSUE TITLE
Difficulty setting up vim 

### ISSUE THREAD

**Issue by jeremeyyy** [nus-cs2030/2324-s2#5]
# Summary
Could I check where to copy the files of vrimc and checkstyle? 

## Description 
I am on a Mac, I have downloaded the vrimc file and the checkstyle file, however, I am unsure where to save the files to so that I can set up vim. 

Thank you!

**Comment by ChoonHean** [comment]
In msys, type `explorer.exe .` and run it. It should open a folder and that is where to copy your files

**Comment by EnzioKam** [comment]
The .vimrc and checkstyle file should be put in your home directory following the instructions [here](https://github.com/nus-cs2030/2324-s2/wiki/Setting-Up-CheckStyle).

If you are not sure what is your home directory, it is typically the directory / folder that is the same as your username. Another easy way to do this is to open your terminal, then run `open .`.

**Comment by Siyi-Xu-Emma** [comment]
when I run checkstyle it said the java runtime environment version is too old? how do I fix that?
![image](https://github.com/nus-cs2030/2324-s2/assets/139932522/ddf7560c-f7ae-4430-ae10-c6f7828b48d4)

**Comment by EnzioKam** [comment]
> when I run checkstyle it said the java runtime environment version is too old? how do I fix that? ![image](https://private-user-images.githubusercontent.com/139932522/296729985-ddf7560c-f7ae-4430-ae10-c6f7828b48d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzMwMTgsIm5iZiI6MTcwNTMzMjcxOCwicGF0aCI6Ii8xMzk5MzI1MjIvMjk2NzI5OTg1LWRkZjc1NjBjLWY3YWUtNDQzMC1hZTEwLWM2Zjc4MjhiNDhkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxNTMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjQ2NGQwZDQ4OTFlYTFkODFjM2VmNjMwNDhkNjU4NzM1MDRmZDc1YjFkYzBlYTBjMGRhM2ZhODYzNDI5MTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WbBehvz2vP4WJnVQK9UGNnWDijF_xBp6sg5t8ZG_Ow0)

What do the commands `java --version` and `javac --version` output? Specifically, what are the version numbers?

Typically this error occurs because you may have multiple versions of Java installed, and you are compiling your program on one version and trying to execute the bytecode (class file) on different version. So my first guess would be that you may have multiple versions of Java installed, or you may have installed a version that is too recent.

The following commands may or may not list out multiple java versions if you do have them installed:
```
which java
which javac
```

**Comment by EnzioKam** [comment]
Closing the issue since there does not seem to be any more response. Please open a new issue if you still need help.
