### ISSUE TITLE
Lecture 02 Q2

### ISSUE THREAD

**Issue by wkleow123** [nus-cs2030/2324-s2#50]
# Question Description

Q2: The moveBy method specified in ~~Shape~~Movable returns Movable, but the moveBy method defined in Circle returns a Circle. Is Circle abiding by the method specification of ~~Shape~~Movable?

## Your contribution:

I believe that the moveBy method in Circle still abides by the method specification in interface Shape because a Circle is still and instance of a Movable but it may not be the best thing to do so in terms of OOP.

`

**Comment by wkleow123** [comment]
i'm not very sure about this but would it be better if the moveBy method specified in the Shape interface returns a Shape instead of a Moveable?

**Comment by wkleow123** [comment]
Oh, then in that case would it be better for the moveBy method in Circle to return a Moveable as well?

**Comment by hwkchia** [comment]
What happens to the following? `Circle c = new Circle(new Point(0.0, 0.0), 1.0).moveBy(1.0,1.0)`

**Comment by wkleow123** [comment]
sorry I am quite confused now, would an error occur from the above test line?

**Comment by hwkchia** [comment]
Why would there be an error?  `Circle`'s overriding `moveBy` method will return a `Circle` which is then assigned to variable `c`?

**Comment by hwkchia** [comment]
Discussion included in Lecture02.
