### ISSUE TITLE
exercise5 Maybe

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#500]
Hi, may I know what's the difference between the following two or methods? Both seem to compile/work, but I don't know which one is better.[
<img width="542" alt="Screenshot 2024-04-09 at 11 17 52 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/ab3c9093-31ca-4768-9194-cd53e2fa12b1">
<img width="529" alt="Screenshot 2024-04-09 at 11 18 14 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/9bb1ca46-bcc6-4d40-b905-ebe4f99b50f6">
](url)

**Comment by lim-4158** [comment]
Maybe<? extends T> would mean that the function can return Maybe of subclasses of T as well, so it would be more general thatn only Maybe<T>

**Comment by harvestingmoon** [comment]
Both method works but @pramoth20  mentioned, first method is safer as it is wrapped in a Maybe class, preventing supplier.get() from churning out a null value

**Comment by iceflakes12** [comment]
Do not ever return generics, if not you cannot do anything with your return value.
Do not ever use the second method. I am pretty sure codecrunch will reject it.

**Comment by iceflakes12** [comment]
Just like to point it out that Maybe<? extends T> is not a subclass of Maybe<T>, and is not considered "more general" than maybe. Neither can be used interchangeably.

If you were to ever return Maybe<? extends T>, you will never be able to read the value, unfortunately.

**Comment by jennipho** [comment]
I think second method has the potential to return a null so first method would be safer since it won't.
