### ISSUE TITLE
CASE 4

### ISSUE THREAD

**Issue by pramoth20** [nus-cs2030/2324-s2#501]
# Summary

Is anyone else getting this error too? Im not sure why Im getting it or how to fix it

## Screenshots
<img width="1394" alt="Screenshot 2024-04-09 at 11 35 07 PM" src="https://github.com/nus-cs2030/2324-s2/assets/155830463/ba08a42b-6857-422d-8243-3077aa3bf6ce">

**Comment by JosiahPraeman** [comment]
I think i encountered an issue like this but i just fixed my generaterule logic involving current cell and leftneighbour rightneighbour and it worked. You just need to craft the if else logic in your generate rule method such that it adheres to the rules of the game and it should be such that if current cell is 0, then if either left or right neighbour equals to 1 then only then it will return 1, but if both are 1 and 0 for the left and right assuming current cell is 0 then it will return 0. if current cell is straightaway 1 then it automatically returns 0. try implementing this logic in your generate rule method it should work.

**Comment by pramoth20** [comment]
Thanks @JosiahPraeman!! can I clarify if we are allowed to use if-else cuz iirc they said we r not, and I haven't used it for the rest of my code

**Comment by JosiahPraeman** [comment]
> Thanks @JosiahPraeman!! can I clarify if we are allowed to use if-else cuz iirc they said we r not, and I haven't used it for the rest of my code

for the generaterule method can use if-else statement for the logic of the game but do not use it anywhere else.

**Comment by lim-4158** [comment]
i think you got to consider how the cells at the edge will be, possibly can code something like if cell at corner then sth.

**Comment by kingcard02** [comment]
int helper(int left, int self, int right) {
if (self == 1) {
return 0;
} else {
return (left + right == 1);
}
}
for leftmost cell, left = 0. for rightmost cell, right = 0.
