### ISSUE TITLE
mapToObj vs. map + boxed

### ISSUE THREAD

**Issue by juelin708** [nus-cs2030/2324-s2#502]
Is mapToObj the same as map first and then boxed?

**Comment by xiang-qiuyu** [comment]
i think eventually they will get the same outcome, however, mapToObj is a method in Stream<T> so it is used to transform elements of a stream to objects of another type while map first then boxed is usually converting primitive streams into genreric streams

**Comment by SumitShinde0702** [comment]
I used mapToObj in my lab. But heres the difference in my opinion. mapToObj is more specialized for converting primitive streams directly to streams of wrapper objects, while map with boxed() provides more flexibility and can be used with any type of stream. So essentially you can use map and box for any type but for maptoobj, it has to be a primitive type

**Comment by RatesLearner** [comment]
mapToObj achieves the same result as map followed by boxed() when working with primitive streams. Both methods are used to convert elements of a primitive stream into objects within a stream.

**Comment by juelin708** [comment]
thanks all!
