### ISSUE TITLE
failed project public test case 3-- server not resting properly

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#506]
Hi it seems like the servers rest properly until it's done with serving 5. 
Before that the rest times are generated properly, but somehow after serving 5 it does not rest/no rest time is generated, which causes 6 to be served at the wrong timing. 
Has anyone encountered similar issues? My approach is to update the server's available time in the done event.
correct output:
<img width="230" alt="Screenshot 2024-04-10 at 11 58 58 AM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/8056adc7-a2a0-4fed-bbb7-b49798114c99">
my output: 
<img width="286" alt="Screenshot 2024-04-10 at 11 58 35 AM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/2746ef74-e53a-487f-9ca8-9b89ead46c70">
those on code crunch: 
<img width="463" alt="Screenshot 2024-04-10 at 1 22 39 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/a41c882a-24ba-4799-b2ee-6606b9cfcf85">

**Comment by caleblowy** [comment]
hi i encountered this same error before also. how did you implement your wait/stillWaiting event?

**Comment by naomiiiwu** [comment]
> hi i encountered this same error before also. updating the server's rest time in Done event is correct, but how did you implement your wait/stillWaiting event?

Hi tks for the reply! I have a wait event class and within the nextEvent method, I will check the server's available time and the event timestamp to see if it needed to generate another wait event, or else it will just return serve event.

**Comment by xiang-qiuyu** [comment]
hihi i am not sure if this is the issue, but perhaps your 10 serves by 1 Serve event was created before your servers are updated with the rest time?

**Comment by bbxg16** [comment]
Exactly the same problem and wrong output. I tried to adjust the condition nextEvent in stillWaiting event: when the customer is the first one in the queue and the server is available at this moment; else the customer still waits until the available time of the server. However, my output still remains the same and it seems like the server does not rest and serve the customer immediately after serving the previous one.

**Comment by caleblowy** [comment]
maybe you can change the if condition to if stillWaiting.time >= server.finishTime, return serve, else return stillWaiting.
thats what I did to fix my issue

**Comment by bbxg16** [comment]
this is what I did:
checking the conditions:
<img width="668" alt="Screenshot 2024-04-10 at 2 59 10 PM" src="https://github.com/nus-cs2030/2324-s2/assets/160305895/9d386422-7bd3-447c-be6f-d5de68669878">
check the server availableTime:
<img width="597" alt="Screenshot 2024-04-10 at 2 59 22 PM" src="https://github.com/nus-cs2030/2324-s2/assets/160305895/3b0e6a49-a684-4c51-bf39-d656f8e7ca49">

**Comment by naomiiiwu** [comment]
> this is what I did:
> checking the conditions:
> <img alt="Screenshot 2024-04-10 at 2 59 10 PM" width="668" src="https://private-user-images.githubusercontent.com/160305895/321137839-9d386422-7bd3-447c-be6f-d5de68669878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzI4OTAsIm5iZiI6MTcxMjczMjU5MCwicGF0aCI6Ii8xNjAzMDU4OTUvMzIxMTM3ODM5LTlkMzg2NDIyLTdiZDMtNDQ3Yy1iZTZmLWQ1ZGU2ODY2OTg3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzAzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmViNmIwOTNhOGY0NTVlMzA5MzdkNGI4YTExZjg4Nzg2NDM5ZjJjODdkYjZmM2I5NGJkZGE0ZjMxYWYwNmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChVPVKIfQCxEF4onxGAWRwHva7QdiKR7nRpvoNCZ0H8">
> check the server availableTime:
> <img alt="Screenshot 2024-04-10 at 2 59 22 PM" width="597" src="https://private-user-images.githubusercontent.com/160305895/321137877-3b0e6a49-a684-4c51-bf39-d656f8e7ca49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzI4OTAsIm5iZiI6MTcxMjczMjU5MCwicGF0aCI6Ii8xNjAzMDU4OTUvMzIxMTM3ODc3LTNiMGU2YTQ5LWE2ODQtNGM1MS1iZjM5LWQ2NTZmOGU3Y2E0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzAzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2NlNjgzZGUwNDYxNGVjNDA2ZDEyNjQxZDU5NjFlNzI2NzcwNDM5NDIwY2UyY2JkODQyMzEyZDVlMmVhOWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.afrRF1PBExB5HngUs_PO7WgZBe08xvDWPDpUM6nSojc">

Hi I don't know if u have solved your problem but I think ive realised where the error is. For customer 6 the rewait(or still waiting ) is added to the pq before 5 is done servin. Thus the rest time is not reflected in the server list and 6 is served straightaway.  I'm still trying to figure out how to solve this issue.

**Comment by naomiiiwu** [comment]
> hihi i am not sure if this is the issue, but perhaps your 10 serves by 1 Serve event was created before your servers are updated with the rest time?

yes I think that's the problem but I don't know how to solve it HAHAHA

**Comment by caleblowy** [comment]
> this is what I did: checking the conditions: <img alt="Screenshot 2024-04-10 at 2 59 10 PM" width="668" src="https://private-user-images.githubusercontent.com/160305895/321137839-9d386422-7bd3-447c-be6f-d5de68669878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzI5MjMsIm5iZiI6MTcxMjczMjYyMywicGF0aCI6Ii8xNjAzMDU4OTUvMzIxMTM3ODM5LTlkMzg2NDIyLTdiZDMtNDQ3Yy1iZTZmLWQ1ZGU2ODY2OTg3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzAzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjYzZjdjMjk5NmY4MTlhZmUyNjQ2MzU4ODJmNTU5MTJkMThmNmVhYTExYjBjNjY3ZTFhOWVlMjlkOWFlNTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N7E8054dRXzYkRrfb2mtjxGS3rAJoq5Ydwo5C131png"> check the server availableTime: <img alt="Screenshot 2024-04-10 at 2 59 22 PM" width="597" src="https://private-user-images.githubusercontent.com/160305895/321137877-3b0e6a49-a684-4c51-bf39-d656f8e7ca49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzI5MjMsIm5iZiI6MTcxMjczMjYyMywicGF0aCI6Ii8xNjAzMDU4OTUvMzIxMTM3ODc3LTNiMGU2YTQ5LWE2ODQtNGM1MS1iZjM5LWQ2NTZmOGU3Y2E0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzAzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTZhZTA4YmYzNWFlYWE4NTEyZWI2YWRmMjcyOTEwNzc4YzYzODU5YjNiZjc0ZDJmYmU1OWQzMTY0MzkyNjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DkQV-rJ2IgY3qZZA8l7sMf8D24xg8RA4d9mRo1Yq190">

maybe you can try removing the part before &&

**Comment by naomiiiwu** [comment]
> > this is what I did: checking the conditions: <img alt="Screenshot 2024-04-10 at 2 59 10 PM" width="668" src="https://private-user-images.githubusercontent.com/160305895/321137839-9d386422-7bd3-447c-be6f-d5de68669878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzI5MjMsIm5iZiI6MTcxMjczMjYyMywicGF0aCI6Ii8xNjAzMDU4OTUvMzIxMTM3ODM5LTlkMzg2NDIyLTdiZDMtNDQ3Yy1iZTZmLWQ1ZGU2ODY2OTg3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzAzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjYzZjdjMjk5NmY4MTlhZmUyNjQ2MzU4ODJmNTU5MTJkMThmNmVhYTExYjBjNjY3ZTFhOWVlMjlkOWFlNTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N7E8054dRXzYkRrfb2mtjxGS3rAJoq5Ydwo5C131png"> check the server availableTime: <img alt="Screenshot 2024-04-10 at 2 59 22 PM" width="597" src="https://private-user-images.githubusercontent.com/160305895/321137877-3b0e6a49-a684-4c51-bf39-d656f8e7ca49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzI5MjMsIm5iZiI6MTcxMjczMjYyMywicGF0aCI6Ii8xNjAzMDU4OTUvMzIxMTM3ODc3LTNiMGU2YTQ5LWE2ODQtNGM1MS1iZjM5LWQ2NTZmOGU3Y2E0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzAzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTZhZTA4YmYzNWFlYWE4NTEyZWI2YWRmMjcyOTEwNzc4YzYzODU5YjNiZjc0ZDJmYmU1OWQzMTY0MzkyNjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DkQV-rJ2IgY3qZZA8l7sMf8D24xg8RA4d9mRo1Yq190">
> 
> maybe you can try removing the part before &&

Hi thank you so much but I cannot see the pictures attached :'(

**Comment by caleblowy** [comment]
> > hihi i am not sure if this is the issue, but perhaps your 10 serves by 1 Serve event was created before your servers are updated with the rest time?
> 
> yes I think that's the problem but I don't know how to solve it HAHAHA

maybe you can consider making a stillWaiting event, so the sequence of events looks something like this
4.053 5 serves by 1
4.053 6 stillWaiting at 1
5.053 5 done serving by 1 (which updates 1's restTime, new finishTime 5.902)
5.053 6 stillWaiting at 1 (1's new finishTime is 5.902)
5.902 6 stillWaiting at 1 (1's finishTime is still 5.902)
5.902 6 serves by 1

**Comment by naomiiiwu** [comment]
> > > hihi i am not sure if this is the issue, but perhaps your 10 serves by 1 Serve event was created before your servers are updated with the rest time?
> > 
> > 
> > yes I think that's the problem but I don't know how to solve it HAHAHA
> 
> maybe you can consider making a stillWaiting event, so the sequence of events looks something like this 4.053 5 serves by 1 4.053 6 stillWaiting at 1 5.053 5 done serving by 1 (which updates 1's restTime, new finishTime 5.902) 5.053 6 stillWaiting at 1 (1's new finishTime is 5.902) 5.902 6 stillWaiting at 1 (1's finishTime is still 5.902) 5.902 6 serves by 1
yes but I think my if condition in generating the stillWaiting event is a bit wrong. May I know what you checked to generate a stillWaiting event?

**Comment by bbxg16** [comment]
I figured out the problem. It is due to the this.server.isAvailable() in my code since I use the server's availableTime that is not updated to check if it is available. Therefore, should use the updated time which could be got through double availableTime = servers.get(index).getAvailableAt(); and compare it with stillWaiting.time
 Hope this help :)

**Comment by ccqie233** [comment]
hiii i faced this error before, it might be due to how you execute your WaitAgain event, which returns either a serveEvent or a new WaitAgain event

In my situation the error came from not using the most up-to-date availableTime of the server when generating a new WaitAgain event, thus when there are more than one customers i.e. customer 6 being served after customer 5 done in the queue, the server actually rested - if you print out the next availableTime in doneEvent - but the restTime was not used by the new WaitAgain

**Comment by nicklass8** [comment]
Hi, maybe you can check whether all your event classes are using the most updated server from the updated serverlist as while i was doing this part, I managed to pass lab3 on code crunch but my serve and done event was not using the updated server, causing this same problem that you were facing. 

To solve this, I made sure that I had a statement Server updatedServer = serverList.get(this.server.getServerID()) in every event class just to make sure that you are using the most updated server with the updated finish timings.

**Comment by naomiiiwu** [comment]
Hi I think it's my serverList. It is not updated properly for some reason. So when customer 6 is trying generate wait again it does not use the most updated one.

**Comment by naomiiiwu** [comment]
hi thank you guys Ive solved the problem :))) realised it would be safer to use serverId - 1 instead of list.indexOf, as it sometimes gives you -1 somehow.....

**Comment by weiyangng** [comment]
hi how did you manage to ensure that the serverList gets updated properly, my serverList still does not add the rest times
