### ISSUE TITLE
Limit on getters? 

### ISSUE THREAD

**Issue by delulu04** [nus-cs2030/2324-s2#507]
# Summary
Not sure how many getters are allowed 

## Description 
Rn my SCC is a subclass of Server, so when I am trying to updateQueue() or updateAvailableTime() of SCC, I have to create a new SCC and hence, have to access its superclass Server's attributes through getters. Is this OK or will I be penalised?

**Comment by jianhaosoh** [comment]
I made use of protected for the Server's attribute instead of private so that the child class SCC can access the attributes. If I am not wrong, we are allowed to use protected for project

**Comment by jennipho** [comment]
I think it's possible to use protected! I did that as well

**Comment by delulu04** [comment]
@jianhaosoh @jennipho ok got it! thanks :))

**Comment by ZHD1987E** [comment]
@delulu04 you might want to close the issue to declutter, thanks!
