### ISSUE TITLE
Compilation Error: null value detected

### ISSUE THREAD

**Issue by jianhaosoh** [nus-cs2030/2324-s2#51]
# Summary
Faced with this error when trying submitting on codecrunch. I was able to compile and get the expected results for the sample runs of the program on terminal. What is the cause for this error to appear?

## Screenshots
![Screenshot 2024-01-29 at 12 01 58 PM](https://github.com/nus-cs2030/2324-s2/assets/142876316/c660e8cc-82ed-447c-bb5b-2a6aa4dc0f08)

**Comment by leeyenkai** [comment]
Seems like an additional restriction unique to this module, just like having to use `private final`.

https://nus-cs2030.github.io/1920-s2/contents/textbook/lecture07/Optional/Optional.html

**Comment by hwkchia** [comment]
Yes, you will learn that `null` is meaningless.  So don't use.
