### ISSUE TITLE
Test Case 9_11

### ISSUE THREAD

**Issue by UEr-nAMe** [nus-cs2030/2324-s2#510]
# Summary
i have such output for test case 9_11 where it seems that my serviceTime for customers are generated wrongly. But i have checked that i only have my getServiceTime() method called once in the Serve event class and I have passed lab 3 before. Any help would be greatly appreciated, thank you!!

## Screenshots (if any): 
output:
<img width="582" alt="Screenshot 2024-04-10 at 18 50 31" src="https://github.com/nus-cs2030/2324-s2/assets/156439185/8b326d5f-72ed-449a-ba14-181cd8521e29">

Serve Event code:
<img width="702" alt="Screenshot 2024-04-10 at 18 54 00" src="https://github.com/nus-cs2030/2324-s2/assets/156439185/967c158a-4549-408e-8a4b-ee2dfc258c0c">

**Comment by joshuagde** [comment]
Hi i think the issue is that the queue for your self checkout isnt being updated correctly thats why the customer was served when it shouldnt have been able to

**Comment by yishao17** [comment]
hello! you may want to check ur addCust/remove Cust() method to make sure that it updates the queue properly!

**Comment by nicthepurplejelly** [comment]
hello! It seems that there may be a problem with the updating of your next available time of your self checkout counter, you may want to add some debug statements at your arrive to check each of the available time of your counters after each iteration!

**Comment by UEr-nAMe** [comment]
hii thanks for the help! i manage to looked at it and it was indeed my queueing system went wrong:)
