### ISSUE TITLE
Project Test Case 11: next available SelfCheck

### ISSUE THREAD

**Issue by jian7490** [nus-cs2030/2324-s2#511]
# Summary
I encounter an issue in the test case 11

## Description 
This is the test output. Assuming self-check 3 is the first self-check counter (which holds the queue), it seems like a new customer will use self-check 4 only if it's available immediately after arrival. If the customer is in the queue, he still uses the self-check 3. My program is like this right now. ArrivalEvent -> WaitEvent only specifies the server id the customer is waiting at. At the beginning of a WaitEvent, it goes through all the self-check to find the one with the earliest ending time and assigns that one to create the corresponding ServeEvent. Is there anything I missed or is it the wrong place to do the iteration? Thank you!

## Screenshots (if any): 
Insert Images here if necessary
![image](https://github.com/nus-cs2030/2324-s2/assets/156817960/6821cf4c-4ef9-4ad3-bd2c-cae009f16720)

**Comment by jian7490** [comment]
My understanding is that: if one arrives and needs to wait, that means both self-check 3 and self-check 4 are unavailable. So, the self-checks are updated with their current ending times already in their ServeEvents before. Then the waitEvent created at the time the customer arrives should be able to find the self-check that ends the earliest.

**Comment by zay-nin** [comment]
When your customer waits at the first self-check, did you check if the rest of the self-checks are available?

**Comment by iceflakes12** [comment]
Once your self check 4 has finished serving, let it check the queue in self check3, if there is a customer in the queue, serve that customer and remove that customer from the queue in self check 3.

**Comment by jian7490** [comment]
Hi guys, thanks for your help. I think I know where the problem is. It's about "re-wait" at the self-check queue. If a customer is gonna "re-wait", or say continue waiting, it takes the first self-check id as the one it's gonna use instead of using the earliest available. Thank you!
