### ISSUE TITLE
project test case 3 --waiting at the wrong server

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#513]
hi hi I could not pass this test case but my code works for public test cases. 
What I did was to add customer in wait event and remove from serve event, and add restTime in the done event. I do not have a wait again event. Instead I used a boolean to check if the wait event is a new wait event, or a "rewait" event
My serve and done events are using the most updated server, so I don't know what's wrong with my code.
I think my queue is updated correctly as well.
<img width="510" alt="Screenshot 2024-04-11 at 1 46 51 AM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/5faa99d0-e994-4042-a8ba-6460634a2e33">

**Comment by yishao17** [comment]
i got this too at the start, did u remove/add customer from ur queue the right way? 
for me I added cust in wait event and removed them in served event!

**Comment by naomiiiwu** [comment]
> i got this too at the start, did u remove/add customer from ur queue the right way?
> for me I added cust in wait event and removed them in served event!

yes I did that! So I don't know what's wrong..

**Comment by naomiiiwu** [comment]
> Hi, I have a similar problem in my previous implementation. I solved it by removing the customer from the queue in the Wait Event to Serve Event, instead of removing them from the queue in the Serve Event

Hi hi tks for the reply. I did not really get it, did you remove the customer from the queue in the wait event instead of serve event?

**Comment by naomiiiwu** [comment]
Hi I think I know where the problem is. I indeed did not use the most updated server for my serve and done event, but still trying to figure out how to debug this.

**Comment by MarcusLiangg** [comment]
> Hi hi tks for the reply. I did not really get it, did you remove the customer from the queue in the wait event instead of serve event?

Hi, yep that's what I meant, I'm just assuming you had the same problem as me as idk your implementation or code.

**Comment by naomiiiwu** [comment]
Hi tks guys ive solved the issue :) turns out I indeed did not use the most updated server from the server list in done event.
