### ISSUE TITLE
Project Test Case: 9_04 – why is my rest time suddenly not right?

### ISSUE THREAD

**Issue by sje5398p** [nus-cs2030/2324-s2#516]
hii My code works for all the public test cases, so I’m confused as to why the rest case isn't updating correctly for this test case.

<img width="477" alt="Screenshot 2024-04-11 at 12 32 02 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/cf934a33-30c3-44d0-9295-bc360889624f">

Any insights would be super helpful! thank you

**Comment by sje5398p** [comment]
this is my done event, I know I shouldn't update my serverlist with indexOf, but when I use set instead I seem to fail test case 3..
<img width="694" alt="Screenshot 2024-04-11 at 12 42 25 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/66a68b7e-d611-4f77-b2ba-d89f6b6dd734">

**Comment by sje5398p** [comment]
this is my done event's next event. I know that using indexOf is unreliable, but when I use .getServerID() - 1, to replace the indexOf, I seem to be failing the third test case... so I m confused 
<img width="694" alt="Screenshot 2024-04-11 at 12 42 25 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/b0416ed1-67d0-4621-b4ab-942cf7ca2d77">

**Comment by vanesssalai** [comment]
It seems to me your updating of rest and server available time has some issues you can try to see whether the logic is right. 
For the below you forgot to -1 to the serverPosition

**Comment by nicklass8** [comment]
hello can i just check what is the attribute time referring to as well as what the ServerComparator does?

**Comment by sje5398p** [comment]
> hello can i just check what is the attribute time referring to as well as what the ServerComparator does?

hi, hahah ur question made me realise that my ServerComparator is a bit redundant.. initially, I used it to order the servers. 

My time attribute comes from my serveEvent class, and is essentially time + serviceTime:
<img width="652" alt="Screenshot 2024-04-11 at 3 50 32 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/2d97c05e-1911-4eeb-8b5a-8c06d19a05b4">

The serviceTime comes from the earlier event, which is either arriveEvent, waitEvent or my waitAgain. 
<img width="657" alt="Screenshot 2024-04-11 at 3 52 13 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/3cfe0d41-f925-4302-b60d-7f546ccb52e3">
This picture is my next event for my waitevent class

**Comment by zuoshihua** [comment]
You're not getting the most updated server from the server list. In your `nextEvent()` write

```java
Server theServer = serverList.get(server.getID() - 1);

// Do stuff with theServer...

serverList = serverList.set(server.getServerID() - 1, theServer);
```

**Comment by sje5398p** [comment]
> You're not getting the most updated server from the server list. In your `nextEvent()` write
> 
> ```java
> Server theServer = serverList.get(server.getID() - 1);
> 
> // Do stuff with theServer...
> 
> serverList = serverList.set(server.getServerID() - 1, theServer);
> ```

but then I end up failing Test Case: 9_03

**Comment by zuoshihua** [comment]
> but then I end up failing Test Case: 9_03

What does the output look like?

**Comment by sje5398p** [comment]
> > but then I end up failing Test Case: 9_03
> 
> What does the output look like?
<img width="480" alt="Screenshot 2024-04-11 at 5 44 42 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/a972b093-cc73-4f2f-b8ed-11e57ec70543">

this is the error!

**Comment by sje5398p** [comment]
> > but then I end up failing Test Case: 9_03
> 
> What does the output look like?

omg wait my bad, it worked. thank u sm!!!!
