### ISSUE TITLE
cannot exit jshell..

### ISSUE THREAD

**Issue by tarshalim** [nus-cs2030/2324-s2#520]
what does this mean?
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/605170c1-9a33-4f2c-847b-c65e5f53930d)

**Comment by jwoongg** [comment]
can try "fg" and then ctrl c

**Comment by Xenonwizard** [comment]
Hi I think just make sure you save everything first before closing. It is likely that there are paused processes. You could probably dble cfm that everything is there by opening the file itself before closing msys (either through the x or exit)

**Comment by tarshalim** [comment]
ahh okay i see now thanks everyone
