### ISSUE TITLE
Can't get output

### ISSUE THREAD

**Issue by sqngwdn** [nus-cs2030/2324-s2#521]
![Screenshot 2024-04-11 215013](https://github.com/nus-cs2030/2324-s2/assets/164153724/3e91d513-b585-4eb2-84d4-f527fc4e3e13)

Pretty sure my generateRule() method is wrong but I'm not sure how to fix it.

My wrong output looks like this:
![Screenshot 2024-04-11 215131](https://github.com/nus-cs2030/2324-s2/assets/164153724/96218405-7d0a-450b-9136-36ddca088617)

**Comment by huangtian666** [comment]
hii, i think u can use `collect(Collectors.joining())` instead of `reduce()` to join characters in each generation into a single string.

**Comment by vanesssalai** [comment]
I think there is a flaw in your logic as a cell is alive in the next generation if it has only one live neighbour cell but your sum == 2 seems to suggest that it can be alive if it has 2 live neighbours

**Comment by vanesssalai** [comment]
I think there is a flaw in your logic as a cell is alive in the next generation if it has only one live neighbour cell but your sum == 2 seems to suggest that it can be alive if it has 2 live neighbours

**Comment by ZHD1987E** [comment]
@vanesssalai is right: something IS wrong with your logic

**Comment by juliannxe** [comment]
Check the return of your `generateRule()`; it could be possible that you're making everything alive because of some filter / map not implemented correctly
