### ISSUE TITLE
Project: Time Limit Exceeded pls help :(

### ISSUE THREAD

**Issue by xin-yi-phang** [nus-cs2030/2324-s2#522]
# Summary
Hi!! My code runs fine on jshell, but for some reason I get a time limit exceeded on code crunch :(

## Description 
I'm not sure why or if there are any guidelines to improve the efficiency of my code :(

## Screenshots (if any): 
<img width="293" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158749925/a932342b-b0cc-4bed-9a92-516c86a6e197">

**Comment by yishao17** [comment]
i got this error just now too, how I found out which part was having an infinite loop was to add a System.out.println in every event. so they will print out in the terminal which part is running the whole time. 

also this test case is 0 2 1 0 (then can jus copy the numbers in the pic of the arrival time), then when u run it will have an infinite loop running on ur terminal (if u add the print lines correctly). then from there u can see which part causes this! 

for me, it was from hold to serve, it may be different for urs!

**Comment by xin-yi-phang** [comment]
omg thank u :')) I've found out whr my infinite loop is, 😭 tq for the advice!!!!!
