### ISSUE TITLE
project test case 4-- served by wrong server

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#523]
Hi im a bit confused here. For customer 5, isn't it supposed to be served by server 1 instead of self-check 2? As server 1 is lardy done serving the last customer and the queue is empty.
my output: 
<img width="430" alt="Screenshot 2024-04-12 at 10 25 10 AM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/20916030-844e-494c-bee4-06c340385937">
correct output:
<img width="317" alt="Screenshot 2024-04-12 at 10 25 17 AM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/28315d0f-f73a-4be0-87a4-6d049bcdcddd">

**Comment by nicklass8** [comment]
hello did your rest time implement properly? I think server 1 might be resting and hence self-check 2 should serve 5 instead

**Comment by naomiiiwu** [comment]
> hello did your rest time implement properly? I think server 1 might be resting and hence self-check 2 should serve 5 instead

thank you yes I think there is an issue there..
