### ISSUE TITLE
project test case 9_12-- customer waits instead of leaving

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#525]
Hi, I don't know why I have this issue here. If it passed the above test cases should suggest that the queue is updated correctly right..? Anyone has encountered this issue before ? I am not sure what's wrong. 
<img width="705" alt="Screenshot 2024-04-12 at 12 44 50 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/940d440f-5aa5-468e-8c54-fa42fbd93e4d">

**Comment by nicthepurplejelly** [comment]
Hi! your queue may be updated correctly, but does your algo involve checking the earliest next available time among the SCCs?

**Comment by naomiiiwu** [comment]
> Hi! your queue may be updated correctly, but does your algo involve checking the earliest next available time among the SCCs?

Hi! my wait event checks the earliest next available time to generate the wait again/another wait event!

**Comment by nicthepurplejelly** [comment]
ohhh, maybe your queue for your SCCs is not being updated properly?

**Comment by naomiiiwu** [comment]
> Hi! your queue may be updated correctly, but does your algo involve checking the earliest next available time among the SCCs?

sorry but how does this have anything to do with wait/leave event? I think there's something wrong with either my queue updating/ the nextEvent method in arrival event, but I cannot find the error :'((

**Comment by naomiiiwu** [comment]
> ohhh, maybe your queue for your SCCs is not being updated properly?

yes tks I should check again..

**Comment by KoalaLyfestyle** [comment]
Hi, I have the same problem in test case 9_12, may I ask what did you do to fix it @naomiiiwu? Thank you!

**Comment by naomiiiwu** [comment]
> Hi, I have the same problem in test case 9_12, may I ask what did you do to fix it @naomiiiwu? Thank you!

hi for my case the issues lie in my queue updating in my serve event & done event. I think you should double check your queues. If you are using a global queue, you should make sure the rest of the SCCs have a queue number of 0. Hope this helps!
