### ISSUE TITLE
Mock PA2

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#526]
Any idea why it throws this stackoverflow error?

![Screenshot 2024-04-12 163030](https://github.com/nus-cs2030/2324-s2/assets/111676024/8ea9f7cb-4cd5-4d50-ade7-15db4ed78b61)

**Comment by ZHD1987E** [comment]
Recursion error.

**Comment by mcjuh** [comment]
You can google more about Stackoverflow Error and the memory stack stuff, but in practice this usually appears because of some recursion issue. You should check your code and see how Num is calling AbstractNum.

**Comment by Monoji77** [comment]
I initially had this error as well. I was able to figure out which part of my code caused it but I don't understand how it happened also. I created a private final static field in my Num class with Num.of(-1). When I instantiated Num.of(1), Num.of(any natural number), my hunch is that it gets stuck in an endless loop. Can anyone confirm this with better reasoning? I removed the line of code and replaced it with another type of logic involving Optional.empty( ) and my code worked fine again

**Comment by ZHD1987E** [comment]
Alright. I have uploaded this onto #528 just for anyone else to refer to.

**Comment by Jeremythong2002** [comment]
Did you use a Num counter along with your loop? If you forgot to update the counter, that might result in an infinite loop.

**Comment by meowmeowpeepee** [comment]
recursion error, maybe caused an infinite loop

**Comment by nickifung** [comment]
it is probably a recursion error and likely due to an infinite loop

**Comment by Bryanngu03** [comment]
I think that's recursion error, hope u solve it..

**Comment by Timmyneedsbzahelp** [comment]
Josiah Praeman it is recursion err !
