### ISSUE TITLE
Unsure why there is a String

### ISSUE THREAD

**Issue by ArkAzrael** [nus-cs2030/2324-s2#527]
## Description 
Trying to implement Add/Mult/Sub, getting an error that my method is calling equals on a String

[
![StringError](https://github.com/nus-cs2030/2324-s2/assets/157274977/214639fb-3007-459f-8ad5-03f8358702e1)
](url)
[
![AddSub](https://github.com/nus-cs2030/2324-s2/assets/157274977/ed43ed82-b0ba-45fb-89f0-1099e9e9f7ef)
](url)

Why is it calling a String's equals method when other is a Num?

**Comment by samuelneo** [comment]
did you see "Time limit exceeded" above the outputs (possibly cropped out here)? there might be an infinite loop in `zero.sub(one)`

**Comment by ZHD1987E** [comment]
Actually, you can get trapped with `one.mul(zero)` as well...

**Comment by ArkAzrael** [comment]
Solved by relooking at logic at sub. Thanks for the help.
