### ISSUE TITLE
Q&A MOCK PA2 12 APRIL 2024

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#528]
# Q&A MOCK PRACTICAL ASSESSMENT 2, FIRST PUBLISHED 12 APRIL 2024.
>Before you say I'm sponsored by Mustafa, let me be clear: **no**.

Ah yes, the infamous PA2 widely talked about. You can't even use operators like '+', '-', '*', '/'! [Here's a Reddit rant regarding THAT PA.](https://www.reddit.com/r/nus/comments/tyxdvn/thoughts_and_opinions_on_cs2030_pa2/)

I bet you are feeling like [this](https://youtu.be/YJ5TOpRRSuE)...

That being said, this is one of the more harder PAs you get, so yeah, don't feel demoralised. I myself submitted code 16 times before I finally got an A and with heavy abuse of the debugger. Yes, you HAVE to make use of the Debugger provided on your IDE to figure out what went wrong. Print statements are prone to you forgetting to take it out, so is putting a `main` method for test purposes (I should have created `Main.java` with test code).
>![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/9c404d18-1d83-40b2-ae9a-422f456c21cb)
>Trust me bro, this is your lifesaver
>
>![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/06f02eae-36a6-4e42-9502-910f15ea6c5b)
>I dare you to count how many submissions I made...

I can see some questions coming up soon... For now, you might have these in mind:

# I DON'T KNOW WHERE TO START EVEN!!!

Thanks @azzy83 for the Telegram exchange, made me realise that many people don't know where to start!

Keep calm, and read this carefully.

You are given an 'AbstractNum', which is just a barebones implementation of what you'll do later.

If you notice `opt` has an Optional, that is because `AbstractNum` actually supports having the value or not depending on a given set of rules (e.g. you cannot have a negative number or the number cannot be zero somewhere). That is further supported by these two methods: `isValid()` and `toString()`, which checks if there is something indeed contained in the Optional.

That means you can think of how to manipulate your Optional to fit the requirements. Moreover, you may need to get creative with the three basic arithmetic functions, `add()`, `mul()`, and `sub()`. Don't worry, the question does tell you what is going on, but in case if you want an abridged version...

> - `add()` just takes in some other `Num` object and adds by one (through the `succ()` operator) on your original `Num` object by the number of times defined by your other `Num` object.
> - `sub()` just takes the other `Num` object, inverts it (with you bypassing the check) and adds that with the value contained in your `Num` object.
> - `mul()` just takes the other `Num` object, and you `add()` your own `Num` object by the value given in that other `Num` object.

As further information, **take extra caution for `mul()` and `sub()` as these can themselves generate invalid numbers, so you need a way to make sure everything you pass AND generate is valid or not.**

Even more bonus for Fractions, if you have any invalid `Num` values in that fraction you will HAVE to throw the WHOLE Fraction away since you will have to declare the type encased in AbstractNum as a `Frac` (which is actually a `Pair` of two `Nums`). What a waste of a otherwise good reaction.

Moreover, if you are given invalid numbers (or a Fraction), do NOT worry about returning such invalid numbers because NO matter how much you try to manipulate them they WILL stay invalid.

> ![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/3ad0c267-8c9e-44c0-98f2-9dec362fc54a)
> If you need some idea what is going on regarding the purpose of `Optional`

When it comes to a `Fraction`, have fun with these three operators because you will have to manipulate the `Optional` object directly, NO getting the value! In fact, you don't have to since `Optional` has ways to manipulate itself!

Anyways, regarding fraction manipulation, our dear question document tells you exactly how, but it can get messy and it takes a few tries to get it right.

# I AM GETTING ALL SORTS ERRORS ON CODECRUNCH!
Follow these steps below to make sure you know what is happening: 
## `Instance properties/constants detected.`
This means you have done something like this:
```java
class X {
    private final Y somevariable;
}
```
You do not need them at all.
## `Arithmetic operators detected`
That means you have done something like this:
```java
class X {

    public void someMethod(...) {
        ...
        atest++;
    }
}
```
Replace that `++` with any arithmetic operator you can think of. Examples can be found on the question document itself.

What should you do? Use `succ()` to replace your `++`, `add()`, `mul()` and `sub()` to replace your `+`, `*`, `-` respectively.

## `Use of restricted Optional methods`
You may have done something like this:
```java
class X{
    public X someMethod() {
        Y = something.get() //where something is an Optional
    }
}
```

To reiterate the question document, these are NOT allowed:
1: isPresent()
2: isEmpty()
3: get()
4: orElse()
5: orElseGet()
6: orElseThrow()

That means you WILL have to directly manipulate the `Optional` object directly. Here's a hint, the `filter()`, `map()` and `flatMap()` operations come in very handy.

## `Dependency of [WHATEVER BANNED PACKAGE]`

Yes, someone did get that error with #560. That means you will have to carefully check your code to see if you invoke these banned packages. For example, that chap might have used String.contains() for invalid numbers (where our dear Optional and AbstractNum has declarative ways to deal with the same thing.)

---
### As a bonus, here is what I think what CodeCrunch does:
1: `checkstyle` your code but with tweaked settings (NO magic number exclusion!)
2: Checks if you have instance properties or attributes or you have arithmetic methods
3: Checks if you have all files uploaded
4: Checks for banned `Optional` methods
5: Runs your code

# HELP! MY CODE GOT STUCK IN AN INFINITE LOOP!
It likely means that you have not set conditions to prevent infinite looping from occurring, especially if you use `.equals()` as your condition. Basically, if you start from 1 and the other value is 0, it will just count to infinity and CodeCrunch will time you out.

Take for example, this:
```java
public Num mul(Num other) {
    ...
    for (Num k = Num.zero().succ(); k.equals(Num.zero()); k = k.succ()) {
        ...
    }
}
```

It's the same as:

```java
public Num mul(Num other) {
    ...
    for (int i = 1; i != 0; i++) {
        ...
    }
}
```
...and it leads to your computer [doing something like this](https://www.youtube.com/watch?v=7Kd3R_RlXgc).

How do you prevent that? Sanitise along the way (e.g. if that number is a `Num.zero()` for a `mul()`, you know better than to pass into a `mul()` and cause your computer to freeze)...

# Wait a second, did they say `loops` somewhere for level 2?

Yes, and you CAN construct a loop by taking reference from what you usually do:

```java
for (int i = 0; i < somevariable; i++) {
}
```

Try translating that into the context of Num. As a hint, you might want to reflect on the second part of this `for` statement (`i < somevariable`) which does the same as (`i != somevariable`). Need proof?
> ![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/f7c986c2-86d0-40b3-a62c-fd9262def1ae)
> Look! No error!

# CodeCrunch rejects my submission because of missing javadocs

~~I admit, it IS a pain to add javadocs. I literally have to figure out where I have to put based on CodeCrunch's output and add. Thank god I have an IDE to autocomplete Javadocs and the Checkstyle extension fitted on Visual Studio Code to figure out what to do. I think that might be a grader problem, so @hwkchia might have to fix it. Don't worry, Checkstyle will be disarmed for your actual PE.~~

UPDATE FROM @samuelneo: Just remove the access modifier for the class, this will disarm the error e.g. `public`, `private`

# What can I do if I want to score well for such things?

**TIP: JUST WING IT. YOU CAN ALWAYS DEBUG LEISURELY AFTERWARDS IN THE LAB, OR ON YOUR IDE. PUT IT CRUDELY...**

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/6b1fbe45-b0c4-4f0b-9779-89e6d463cb0f)
_I don't have budget for a photo editor, sorry 'bout that..._

---

More questions will appear as you go along.

In the meanwhile, at least you don't have a computer that is just as bad as this:

https://github.com/nus-cs2030/2324-s2/assets/140680858/a4992bee-97eb-4039-972f-5af6046ae502

_it's a kid laptop. don't actually use it to code. it can't run vim or intellij or visual studio code. whatever._

Your feedback matters: [click here](https://forms.office.com/Pages/ResponsePage.aspx?id=Xu-lWwkxd06Fvc_rDTR-giNfQK0R8TNLso0Soymm0w1UOFZOSVQzMzBWREsxQ1I1WTAwNzBUQjNEVi4u) for the feedback form regarding this Q&A. Just 3 questions.

**Comment by samuelneo** [comment]
> CodeCrunch rejects my submission because of missing javadocs

which methods gave you that error? I didn't have to add any javadocs for my submission

**Comment by ZHD1987E** [comment]
From what I know, ALL my public classes required Javadocs. I guess that’s something to do with declaring my class explicitly as Public…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by samuelneo** [comment]
yes, I declared classes without specifying any access modifier (following the convention in this course). that might be the reason then

**Comment by ZHD1987E** [comment]
Thanks @samuelneo. Your tip has been included.

**Comment by azzy83** [comment]
Thanks!

**Comment by ZHD1987E** [comment]
# BONUS: What numbers should you NEVER press on a kid's toy in quick succession?
- 9-3-5-3
- 5-3
- 5-7
- 5-2
- 4-2

**IF YOU GO TO MUSTAFA, FIND A KIDS TOY PHONE AND ASK ME TO PUT ANY OF THESE INPUTS... I'M NOT RESPONSIBLE FOR WHAT HAPPENS TO YOU NEXT**

**Comment by Timmyneedsbzahelp** [comment]
Thank you _**ZHD1987E**_

**Comment by hadyamanisanto** [comment]
Thank you Hao Dong!

**Comment by justinwong2** [comment]
thanks g will make use of your tips while working on this project!

**Comment by ZYZY2727** [comment]
tks ZHD!!

**Comment by JovanFoo** [comment]
Thank you!

**Comment by donregan9** [comment]
thanks for your tips bro

**Comment by azzy83** [comment]
@azzy83  🤝 @ZHD1987E

**Comment by jyheng02** [comment]
what a solid lad hao dong thanks for your help!

**Comment by iceflakes12** [comment]
Just like to add on that for this practical, it is important to read the constraints defined in the task. Unlike pa1, pa2 usually comes with its own unique set of constraints that vary for different practical assessments, hence it is important to read carefully to know what you can do and what you cant do.

**Comment by CSnoobCS** [comment]
You're so good with CS sia!

**Comment by AustinKong** [comment]
thanks for the tips hao dong!

**Comment by kaywoon** [comment]
thank you for your tips!

**Comment by yuntsingg** [comment]
Thanks for the tips!

**Comment by zkdlffkdb** [comment]
Thanks for the tips, was super helpful!

**Comment by itzsihui** [comment]
thank you a lot !! it helped me so much

**Comment by tianyiiiiiii** [comment]
Thank you for the tips!

**Comment by lifrocszh** [comment]
Thanks Zhang for the helpful tips!

**Comment by Jiahui-liew** [comment]
thank you this is rlly helpful!

**Comment by hadyamanisanto** [comment]
Thank you, Hao Dong!

**Comment by ziyingg** [comment]
thank you!

**Comment by travistan2003** [comment]
thanks! your tips really helped

**Comment by juelin708** [comment]
Thank you for the tips!

**Comment by Castelle-code** [comment]
Thank you so much!

**Comment by zi-yii** [comment]
thank you! your tips are very helpful

**Comment by xavierhua0129** [comment]
Thanks for the tips!!!

**Comment by kziyang1207** [comment]
Thank you!

**Comment by anqixxxx** [comment]
thanks haodong!

**Comment by NCTSVT** [comment]
thanks a lot for the tips!!

**Comment by ka10252** [comment]
thanks for the tips! it helped me a lot

**Comment by HoSCD** [comment]
thank you Hao Dong
