### ISSUE TITLE
Lecture 3 Question 2 Why doesn’t overriding methods counts as a violation of the principle of coding to an interface and not an implementation? 

### ISSUE THREAD

**Issue by Jeremythong2002** [nus-cs2030/2324-s2#53]
# Description
For instance, if I want multiple types of filled circles that have a different pattern each (spotted, striped, other patterns etc), then it would make sense that Circle has the function fill colour so that it can be inherited by subclasses. However, this would mean that I would have to recode and override the implementation of fill colour for each of those circles. 

Even if we consider using an abstract class, wouldn’t that still require each subclass to define the method? 

Essentially, what is the best way to implement methods in the case where (i) multiple subclasses will want to inherit it, (ii) however they will need to override them to implement what they actually want to do?

Thank you. 

Thong Cheng Han
## Topic:

OOP

**Comment by hwkchia** [comment]
If `Circle` knows that it may be filled, then it would not be just a `Circle` isn't it?

**Comment by samuelneo** [comment]
I'm not sure I understand the question correctly. Is each type of filled circle meant to have a different implementation of `fillColor`? If so, implementing `fillColor` in each subclass seems inevitable, and `fillColor` doesn't need to be a method in `Circle`, it can just be defined in the subclasses.

If you would like the different types of filled circles to share the same implementation of `fillColor`, you could define an `abstract class AbstractFilledCircle extends Circle` with `fillColor` implemented, then have your specific types of filled circles extend from `AbstractFilledCircle`.

**Comment by Jeremythong2002** [comment]
Perhaps the example that I used was poor or the issue is something else.

Say I have a parent `class Student`, with subclasses `StudentBasketballer` , `StudentTrackAndField`, `StudentLibraryClub`. All them can `run`, but say both `StudentBasketballer` and `StudentTrackAndField`, when running will run fast but `StudentLibraryClub` runs slow. 

In that case, I would have to recode run fast twice, once for each implementation of `StudentBasketballer` and `StudentTrackAndField`. I was wondering if there's a way to do this better without recoding it twice.

Thank you.

**Comment by hwkchia** [comment]
Closed as issue has expired.
