### ISSUE TITLE
project test case 9_11

### ISSUE THREAD

**Issue by Bryanng41** [nus-cs2030/2324-s2#530]
![Screenshot 2024-04-12 202509](https://github.com/nus-cs2030/2324-s2/assets/52643493/1bdc77e0-9ba1-4f2d-bcd2-ec0a74c490f8)

## Description 
Did anyone identify the problem in my output? I am not sure which part is wrong :'(

**Comment by samuelneo** [comment]
14 was in the SCC queue before 15, so 14 should be served instead of 15 on line 37

**Comment by niclow236** [comment]
Maybe you can check the part of your code where you enqueue your customers when they start to wait for self-checkout counters. It seems that customer 15 was added to the front of the queue instead of the end, so it was dequeued and served first before customer 14.

**Comment by nicthepurplejelly** [comment]
It seems like there is a problem with your SCC queue, perhaps, instead of checking the first person in the queue, you are checking who is the last person added in the queue. That may be why you are serving customer 15 first instead of 14

**Comment by naomiiiwu** [comment]
Hi I think one of the useful tips I used to help myself debug is to add in System.out.println(whatever you want to print, lets say customer ID/queue), before and after the operations on customer ID/queue in the nextEvent method to check if they are manipulated correctly. You can try using public test cases/ setting up your own test cases by modifying the current public test cases. Also can try multiple positions in the nextEvent method to see exactly where the error lies. Hope this helps!

**Comment by IYKYKY** [comment]
it seems that you haven't updated your scc queue correctly. when customer is waiting at the first in the scc's queue, check which is the soonest next available scc that will serve the customer. After that, update the queue at first scc as well as the soonest scc's next available time. Also, this soonest next available time needs to be passed to the other customers waiting at the same queue.(update the wait/keepwaiting occurtime)

**Comment by kryst-ll** [comment]
in Wait, if no scc is ready to serve the customer, the continued wait event generated should have the soonest available server time, but the server id should still be the first scc's server id so that the continued wait events for all the custs in the scc queue are sorted correctly in the pq

**Comment by yishao17** [comment]
I think the problem is that your customers are queued to a particular self-checkout counter rather than a common one. Maybe ur wait -> serve method for SCC has a bit of error? 

I think something useful for me is to add print lines in the execute method of the events (to describe each event in greater details). I also added them in the simulate method to see which events get polled and how it leads to the next execute! 

hope this helps :))

**Comment by JovanFoo** [comment]
I think if you just include a method to find the earliest self check out server into ur wait event, it should work!

**Comment by Bryanng41** [comment]
Thank you everyone for your help!!! I managed to identify the problem <3
