### ISSUE TITLE
mock pa2 sub method

### ISSUE THREAD

**Issue by ndartem** [nus-cs2030/2324-s2#531]
how do i use the add method in sub without invalidating it?

**Comment by Yuxin-Mellisa** [comment]
for me only my of method has the invalidate part the constructor does not have so just us the constructor

**Comment by weikiatt** [comment]
its possible to do the sub method without using the add method, try using s and n from AbstractNum

**Comment by wkleow123** [comment]
you can filter it again to check if it gets invalidated

**Comment by Monoji77** [comment]
I have one constructor that does not invalidate the creation of a new Num object. I used this new pseudo Num object with the add as guided by the question. After that we must check whether the resultant value fits the predicate using something that's provided in AbstractNum. BAM, question solved. All the best :)

**Comment by ZHD1987E** [comment]
Step 1: Invert that other `Num` object. There's a variable onboard `AbstractClass` called `n` for that.
Step 2: For the number of times this object has (which is why you do checking of inputs carefully!), you `succ()` that other `Num` you have on step 1
Step 3: Make sure that result is still valid. If I am not wrong I filtered that Optional and did some stuff to it.

**Comment by RatesLearner** [comment]
make use of both n and valid from AbstractNum

**Comment by LimZiXiong** [comment]
I created an optional with value 0 and put it into a num. Each time i increase the negated value, i increment the counter until the num with counter optional is equals to the num passed in.

**Comment by mcjuh** [comment]
I used Streams iteration using x -> n.apply(s.apply(n.apply(x))), idea is that you negate the value first, add 1 and negate that again to decrement by 1 overall. You can access and modify the value in the Optional via flatMap and map
