### ISSUE TITLE
MockPA2: Level 1

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#532]
My output works on jshell but im getting this error when i submit to codecrunch

![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/2f8a7604-45a6-4ba5-9d6d-7c5c8e44fab4)

**Comment by weiyangng** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/80fc35e4-456d-42a6-8f11-343d140ecafa)

**Comment by FadhilPM** [comment]
Num is not a generic type, lose the <T>.

**Comment by jwoongg** [comment]
no need for <> for Num just abstractnum

**Comment by Jeremythong2002** [comment]
You need to tie AbstractNum to a particular type though

**Comment by Monoji77** [comment]
Given your current implementation, Pair will look like Pair<Num<Integer>, Num<Integer>>

There are quite a few clues to show you that Num is not a generic type. First, Pair takes the generic form Pair<Num, Num>, secondly, in your static instance methods, you are only creating Num of type Integer. All your Optionals and AbstractNum take on <Integer> form as well, so you can assume that you do not need a "generic" type

**Comment by pramoth20** [comment]
class Num extends AbstractNum<Integer> {

    private Num(AbstractNum<Integer> abstractNum) {
        super(abstractNum.opt);
    }

    static Num of(int i) {
        if (!valid.test(i)) {
            return new Num(new AbstractNum<Integer>(Optional.empty()));
        }
        return new Num(new AbstractNum<Integer>(i));
    }

}
this is how I extended from AbstractNum, I replaced the generic with <Integer> and so my constructors are different too

**Comment by weiyangng** [comment]
ok @pramoth20 wasnt asking you

**Comment by pramoth20** [comment]
@weiyangng I don't get asked, I just tell
