### ISSUE TITLE
Mock PA 2 Fraction

### ISSUE THREAD

**Issue by xinnyyy** [nus-cs2030/2324-s2#533]
hello, how do i define of for fraction? if of returns a frac and if i check if denominator and numerator is not valid after doing Num.of(n) and Num.of(d) and return Frac.of(Num.of(-1), Num.of(-1)), the output will be NaN : NaN instead. how do i make it return just a NaN? currently my Fraction extends AbstractNum<Pair<Num, Num>> and my of in Fraction returns a Frac class

**Comment by FadhilPM** [comment]
of in Fraction should not return a Frac class. 

I'm not absolutely sure about this, but consider making Fraction extend AbstractNum<Frac>, and ensure that if either input is invalid, an Optional.empty is passed to the AbstractNum constructor

**Comment by CSnoobCS** [comment]
Hi, I'm also having the same issue, just wondering how did u solve it?

**Comment by xinnyyy** [comment]
> Hi, I'm also having the same issue, just wondering how did u solve it?

what i did was to make of return a fraction. i first check if the numerator and denominator is valid / if denominator is 0 after doing new Num(n) = numerator, new Num(d) = denominator. i then return fraction(frac.of(numerator, denominator)). hope this helps!
