### ISSUE TITLE
Mock PA2 Level 2

### ISSUE THREAD

**Issue by ashleypengsy** [nus-cs2030/2324-s2#534]
I am currently using a for loop and keep calling succ(), but how do i determine the range for this for loop without calling other.opt.get()?
=
![Screenshot 2024-04-12 at 10 59 53 PM](https://github.com/nus-cs2030/2324-s2/assets/156221043/b4267fc1-9b71-431c-be64-f5be1c8abd04)

**Comment by Yuxin-Mellisa** [comment]
u can define another num for counting times

**Comment by weikiatt** [comment]
try using optional's .map() method

**Comment by ZHD1987E** [comment]
If you think about it...
```
for (int i = 0; i != aValue; i++)
```
achieves the same as...
```
for (int i = 0; i < aValue; i++)
```
Just that the latter has greater 'safety' in the event `i` is manipulated dangerously.

**Comment by RatesLearner** [comment]
i introduced 2 variables, start and result , do a while loop until start is no longer the input Num, which succ/+1 to result. and return result

**Comment by codingtemp** [comment]
Hi, note that the operator ++ is not allowed in this task, as such you should not be using for loops. Consider using the ".equals" method along with a counter variable, such as Num or AbstractNum. The loop should continue until the counter is equal to the target value using the ".equals" method.

**Comment by mcjuh** [comment]
I used Streams iteration and for the limit I did another iteration from zero() up till it .equals(other) and .count()

**Comment by meowmeowpeepee** [comment]
using ++ is not allowed in this lab

you can consider the method, let the valueToAdd be zero
then while it is not equal to the Natural Num u should be adding to,
continue to succ the ValueToAdd
and the result you wish to add to will also continue to succ

**Comment by wowwwp** [comment]
hi! i had a another variable check which starts from zero and while check is not equal to other(num to be added) u can call succ and increment the check

**Comment by LimJiaWeng** [comment]
Similar to what others did, I created a new Num that starts at zero. I used a while loop to loop through and called succ() for this and the new Num until the new Num and your input are the same (using the equals method defined to check).

**Comment by JovanFoo** [comment]
I used a while loop too, you can consider using that! initially i used a for loop and i faced the same problems so i changed to a while loop instead and it worked well!

**Comment by T-HL16** [comment]
hii! you can use a while loop or if you want to try using streams. I used the .iterate method in streams that contains the predicate to mimic a for loop for the number of times u have to add and then use .reduce method with .succ() to actually add
