### ISSUE TITLE
Mock PA2 sub()

### ISSUE THREAD

**Issue by xinnyyy** [nus-cs2030/2324-s2#535]
hello, this is my current implementation, it doesnt seem to work when this = 0 and other = 1 . for my implementation, i put 0 and 1 map them to negative so 

Num result = new Num(other.opt.map(AbstractNum.n)) = -1
Num counter = new Num(this.opt.map(AbstractNum.n)) = 0

since counter == 0 it will not go to the for loop and result would be Num with a negative 1 inside. if its -1, i check for validity so i thought it would return NaN after proceeding to  but it just returns -1? anyone knows how to resolve this

   if (!result.isValid()) {
            return new Num(Optional.empty());
        }

<img width="540" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/4a3e44aa-dd30-41c0-ba6e-b2689fcf97e8">

**Comment by samuelneo** [comment]
if you examine the definition of `isValid`, it just checks that the Optional isn't empty. you may want to make use of the `valid` predicate provided.

**Comment by omgacai** [comment]
hii i think isValid() if ur using the one defined in AbstractNum class it only checks whether the optional is empty or not. & i think it depends on how u instantiate your Num too whether u checked its valid using the valid predicate, so if u make ur Num -1, it should be an empty optional

**Comment by xinnyyy** [comment]
solved thank u all! solved by using valid to filter out negative ones so negative ones would be empty. then used isValid() to check for emptiness and return Num(Optional.empty()) if not isValid
