### ISSUE TITLE
MOCK PA 2 LEVEL 3

### ISSUE THREAD

**Issue by pramoth20** [nus-cs2030/2324-s2#536]
![image](https://github.com/nus-cs2030/2324-s2/assets/155830463/8b29366f-2526-4dfa-9c62-f640377506e0)

does anyone know what that means?

**Comment by RatesLearner** [comment]
// Lambda expression
Function<String, Integer> parseFunction = s -> Integer.parseInt(s);

// Method reference
Function<String, Integer> parseFunction = Integer::parseInt;

Use lambda to express

**Comment by pramoth20** [comment]
@RatesLearner got it thanks
