### ISSUE TITLE
Mock PA2 Level 5 "NaN" 

### ISSUE THREAD

**Issue by delulu04** [nus-cs2030/2324-s2#537]
hello, im stuck on level 5 of mockpa2, specifically for the cases where the add/mul/sub doesnt return a natural number and NaN is output 
<img width="438" alt="Screenshot 2024-04-13 at 10 09 53 AM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/31ab1497-419b-440a-941e-4b0de0f2577d">

i tried to do 
<img width="642" alt="Screenshot 2024-04-13 at 10 14 46 AM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/f0e82bed-08d4-4f44-9e9e-7bcf5f781a33">

but i got 
<img width="321" alt="Screenshot 2024-04-13 at 10 11 08 AM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/ee0f00c7-fec4-49a6-93fa-bef82d67cc9e">
when i ran on cc

could anyone give me a hint on how to check for the validation of the numerator and denominator of the result since i cannot use the toString() to check? any help is appreciated thanks!

**Comment by ZHD1987E** [comment]
You are NOT supposed to manipulate the String!

You ARE supposed to manipulate the values in the `Fraction`.

What I did was the following:
- Literally map the two Optionals (representing each fraction) into another Optional
- Then I filtered the Optional through a validity check
- Then I used a Private constructor to pass in that Optional and generate a new `Fraction`

**Comment by zuoshihua** [comment]
What does your `Fraction` class declaration look like?

**Comment by delulu04** [comment]
@ZHD1987E  hm i dont rlly understand, you're mapping the two optionals before computing the result? (result as in two Num (one for the numerator and one for the denominator)

**Comment by delulu04** [comment]
@zuoshihua i have this rn
<img width="520" alt="Screenshot 2024-04-13 at 10 30 27 AM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/da75907f-2e56-45bc-a5f7-a21ded0a8225">

**Comment by ZHD1987E** [comment]
@delulu04 I just combined two Optionals into a new Optional by directly manipulating the values.

1. My two Optionals represent the two fractions, and my resulting Optional is the result of what happens after the computation
2. After generating that result, I then passed it through a filter as a condition check.
3. Then I passed it into a private constructor which you already have

**Comment by zuoshihua** [comment]
> @zuoshihua i have this rn

Do you validate your numerator and denominator before instantiating a `Fraction` object? 

Here's my approach to implementing the `Fraction` class. It may give you some ideas.

```java
static Fraction of(int numer, int denom) {
    // create Frac object and pass to private constructor
}

private Fraction(AbstractNum<Frac> frac) {
    // validate numerator and denominator
}
```

**Comment by Jeremythong2002** [comment]
One of your Fraction private constructors should take in an Optional<Frac> which is also the attribute for your Fraction class. 

The key thing is how do you access the numerator and denominator to use `valid` on them? 

However, before that you need to first create a way to access the numerator and denominator of the current Fraction and the other Fraction that you want to subtract. 

1. Use the form this.opt.flatMap(x -> otherFrac.opt.map(y -> ...)) which will allow you access the numerator and denominators of both Fractions, where you can carry out your functions and create a Frac with those results. 
2. Still within the Optional, remember that Frac is a form of the Pair class. So now you have an Optional<Frac>. Hence use `.filter()` to keep the Frac only if both the numerator and denominator is valid. If not, you will be returned with an Optional.empty() as everything in the Optional will be filtered out. 
3. Finally remember that the aim of the sub operation is to create a new Fraction. Again, recalling the constructor of the Fraction is an Optional<Frac> pass the result of the second step into the constructor. If the second step results in an Optional.empty(), it will return NaN based on how the method is implemented in AbstractNum

**Comment by pramoth20** [comment]
I think it would be good for you to create a private constructor/of that takes in 2 optionals to return a fraction

**Comment by delulu04** [comment]
thank you all!! have solved the qn :))
