### ISSUE TITLE
project: distinguishing between counter and human server

### ISSUE THREAD

**Issue by eggrrrr** [nus-cs2030/2324-s2#538]
Is this allowed? or is it considered type checking?:

I have a pair where the 'key' is a list of servers (both human servers and counter) and the 'value' is an integer which refers to the index of the first counter in my list. this is so that i am able to distinguish which index onwards is a self check out counter. thank you!

**Comment by ZHD1987E** [comment]
That's implicit type checking, which can be bad in case you may need to implement something in the future.

**By the way, your coding style is graded as well so this may not reflect well on you.**

**Comment by ZHD1987E** [comment]
Actually... you can. Up to you 100%.

**Comment by Jeremythong2002** [comment]
No it is not considered type checking

**Comment by yishao17** [comment]
thats what I did too, i dont think it is type checking.

**Comment by JovanFoo** [comment]
I dont think that is type checking too!
