### ISSUE TITLE
Mock PA2 Level 5 : How to get Numerator and Denominator out?

### ISSUE THREAD

**Issue by xinnyyy** [nus-cs2030/2324-s2#539]
<img width="424" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/bff34daa-1ad9-47ac-9c54-5b7592adedbe">

how to get the numerator and denominator out? i used the map so i get Num(Optional<Num>) but my constructor for Num takes in Optional< Integer > and not Optional < Num >

<img width="424" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/3345750f-d2dc-437d-b780-7a941a8c71eb">

**Comment by omgacai** [comment]
here Num takes in Optional<Integer> however, when u map the frac into frac.first/second() it will return a Num so it becomes new Num(Optional<Num>) but Num takes in Optional<Integer> , so maybe u can just leave the numerator in denominator as Optional<Num> instead of Num

**Comment by jpowcm** [comment]
i think its quite difficult to work with Optional\<Num> since we cant use getters, maybe you can try to do all the computations for numerator and denom through one line of code containing nested pipelines to get an Optional\<Frac> as ur result instead

**Comment by RatesLearner** [comment]
Perhaps consider tertiary operators to store it in Frac, and return Optional<Frac> in Fraction class

**Comment by meowmeowpeepee** [comment]
just assign them to Optional<Num>, your mul sub and add methods can make use of maps and flatmaps to get your answer

**Comment by kubrian** [comment]
Since a Num is a AbstractNum<Integer> and therefore has an Optional<Integer>, we can use flatMap to extract this, then construct a new Num as you have done.

**Comment by ZHD1987E** [comment]
You're gonna have a lot of fun with `flatMap` and `map`...

**Comment by mikio13** [comment]
The `Fraction` class has an `Optional<Frac>` inside it, so you can try using `flatMap` and `Map` to manipulate the Frac (numerator and denominator) inside the Optional.

**Comment by hadyamanisanto** [comment]
> Since a `Num` is a `AbstractNum<Integer>` and therefore has an `Optional<Integer>`, we can use flatMap to extract this, then construct a new `Num` as you have done.

I tried, but you can't as Num(Optional<Integer>) has private access

**Comment by kubrian** [comment]
> > Since a `Num` is a `AbstractNum<Integer>` and therefore has an `Optional<Integer>`, we can use flatMap to extract this, then construct a new `Num` as you have done.
> 
> 
> 
> I tried, but you can't as Num(Optional<Integer>) has private access

I made the constructor non-private (like the poster did), was able to pass on CodeCrunch.

**Comment by xinnyyy** [comment]
solved! used a lot of maps and flatMaps!
