### ISSUE TITLE
Mock PA 2: Instance properties/constants detected.

### ISSUE THREAD

**Issue by HoSCD** [nus-cs2030/2324-s2#540]
Hi, i got this error after adding constants into my Num class as response to the Magic Number error.
<img width="141" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158131860/d5d0980f-5b9f-42e5-b0bc-19c30ad7ce98">
<img width="230" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158131860/c8d66bc8-37d6-487c-bed5-5a4e6648ac11">
Does anyone know how to resolve this?

**Comment by azzy83** [comment]
I'm guessing you're trying to return NaN by doing return Num.of(-1) or something, try Optional.empty() instead

**Comment by samuelneo** [comment]
you can't use numbers in this mock PA. use the successor function to implement `one()`.

**Comment by HoSCD** [comment]
Thanks guys, resolved
