### ISSUE TITLE
Mock Pa 2: what is this error

### ISSUE THREAD

**Issue by Timmyneedsbzahelp** [nus-cs2030/2324-s2#541]
<img width="1038" alt="Screenshot 2024-04-13 at 3 41 54 PM" src="https://github.com/nus-cs2030/2324-s2/assets/165639538/15a02aa9-4aca-4c47-b6d4-c2dc9acbef88">

Help!!! what's this error and how do i correct it 😢

**Comment by meowmeowpeepee** [comment]
did you consider for zero.mul(zero)?
i ran into the same error because i forgot to consider for that case

**Comment by Timmyneedsbzahelp** [comment]
ooo thanks meowmeowpeepee !!! 👬 🌚
