### ISSUE TITLE
Exercise 5 flatMap generic declaration

### ISSUE THREAD

**Issue by blacksesamezongzi** [nus-cs2030/2324-s2#542]
# Summary

![image](https://github.com/nus-cs2030/2324-s2/assets/157393222/7293453a-264b-4f77-8c14-a4d169f12a28)

## Description:

according to the screeenshot, why is the code in comment part wrong? i found the error saying that Maybe<? extends R> cannot match the type Maybe<Object>

**Comment by kubrian** [comment]
I think the problem lies with `Maybe.get()` having private access. A subclass of Maybe will not have access to `Maybe.get()`. The mapper gives `? extends Maybe<? extends R>`, which could subclass Maybe, so accessing `.get()` is problematic, unless we explicitly set it to `Maybe<? extends R>`

**Comment by blacksesamezongzi** [comment]
> I think the problem lies with `Maybe.get()` having private access. A subclass of Maybe will not have access to `Maybe.get()`. The mapper gives `? extends Maybe<? extends R>`, which could subclass Maybe, so accessing `.get()` is problematic, unless we explicitly set it to `Maybe<? extends R>`

oh it makes sense, so what we do in assigning value to mr is just casting the result of mapper.apply() to Maybe, such that get() can be called
