### ISSUE TITLE
mock pa2 part 3 :(

### ISSUE THREAD

**Issue by yuulim** [nus-cs2030/2324-s2#543]
Anyone knows what is happening in this test case ?
im able to pass all the given cases on my own device, appreciate any help ♥

![image](https://github.com/nus-cs2030/2324-s2/assets/163849598/ea6b3dfd-bd9c-4d83-9a9f-f08d2b17bffd)
![image](https://github.com/nus-cs2030/2324-s2/assets/163849598/03f7c77e-5856-4048-9c52-bc1d61902fbc)

**Comment by ZHD1987E** [comment]
1: Did you check if any of the values put in is invalid? If so, you may have to return the invalid item in concern to make sure ALL future operations with that invalid item cannot take place at all.
