### ISSUE TITLE
mock pa2 codecrunch error 

### ISSUE THREAD

**Issue by jennipho** [nus-cs2030/2324-s2#544]
does anyone know what this error means? codecrunch won't run my codes because of this error :( 

<img width="451" alt="Screenshot 2024-04-13 at 5 38 38 PM" src="https://github.com/nus-cs2030/2324-s2/assets/148960828/22f7e038-a699-4783-8149-a0d90c0056be">

**Comment by AustinKong** [comment]
You can't use any properties, even if they are declared `private final`.

**Comment by ZHD1987E** [comment]
You can NOT have any of these:

```java
public class X {
    private final X aProperty; //NO!
    private final X A_CONSTANT = SOMETHING; //NO AS WELL!
}
```

**Comment by pramoth20** [comment]
Try not to declare anything as private final static. for example I assume you used it for either your 'one' method or any other methods to check if the number isEquals to 0. Instead you can check the validity or if it is .equals(Num.zero())

**Comment by jennipho** [comment]
thanks all!

**Comment by jennipho** [comment]
thanks :)
