### ISSUE TITLE
Project indexoutofbound exception in public test case 4

### ISSUE THREAD

**Issue by WWYYiXuan** [nus-cs2030/2324-s2#545]
# Summary
Put a summary of the question

## Description 
hi I tested my code against the cat 4.in in codcrunch and it shows indexoutofbound error. the code says the error appears at Serve class when updating the queue. the index of queue is 2 where there should be only two queues (one human and one selfcheckout) hence the max index should be only 1. i checked my initialiseQueue and it is initilaised correctly. I am now confused if there is any other areas that i can check for? any suggestions would be appreciated! 
## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/163511252/7724fa9c-854a-4416-8afc-1097d5c73cf5)

**Comment by samuelneo** [comment]
have you checked the lines specified in the stacktrace?

**Comment by kryst-ll** [comment]
if you used any loops to loop through the queues, maybe you can check if your terminating conditions are correct, e.g. if you used something like  `index <= queue.size()` instead of `index < queue.size()`

**Comment by yishao17** [comment]
I had this error for test case 11 too. what I realised was sometimes my +- 1 had some error, maybe review those parts if u have?

**Comment by ThamudayaWinBerry** [comment]
can check through all the loops you did in Serve (maybe each human queue and self check out queue). perhaps you can add print statements on the size of the whatever you're looping through and using that, see if there's any clash in logic with the number of loops you're doing in all the loops. hope this helps :)

**Comment by anqixxxx** [comment]
yepp i think it's cuz you're trying to access something that is outside of whichever list you're looping through!

**Comment by Yiting55** [comment]
can add some print statements in your updateQ to check which part goes wrong, the problem I had is the index I use to get queue went out of bound

**Comment by WWYYiXuan** [comment]
thank everyone! my error appears to be i did not return a self checkout server in one of the update servers method so the servers were turned into human servers eventually.
