### ISSUE TITLE
Mock PA2 level 3

### ISSUE THREAD

**Issue by JovanFoo** [nus-cs2030/2324-s2#546]
![Screenshot 2024-04-13 at 10 20 57 PM](https://github.com/nus-cs2030/2324-s2/assets/133492195/15326ce4-8473-4381-a7c9-3216f55aecc3)
Hi, anyone encountered this time limit exceeded error? i have no idea how to overcome this.
![Screenshot 2024-04-13 at 10 21 46 PM](https://github.com/nus-cs2030/2324-s2/assets/133492195/1ec5d7a9-0481-4c7b-a7fd-811d2b98e332)

**Comment by xiang-qiuyu** [comment]
did you use null in your code? it's weird that you are encountering a NullPointerException since code crunch will terminate your code if you use null

**Comment by ZHD1987E** [comment]
You are adding negative values! If you have a loop 100% sure it will infinitely loop!

**Comment by JovanFoo** [comment]
i resolved it alr thanks all!
