### ISSUE TITLE
mockpa2: level 3

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#547]
program works fine but doesnt return NaN when the final answer is less than 0. Not sure what the issue is but its likely to do with the second if statement

![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/2e77f4a5-d026-494e-8b6f-2ec92a9f9261)

**Comment by ZHD1987E** [comment]
What I suggest: put debugging breakpoints, then step around to figure out what is happening.

Looks to me that your sub() method is fine.

**Comment by LimJiaWeng** [comment]
Might be an issue with your add method, maybe check whether your add method filters out the integer if the result is a negative number.

**Comment by weiyangng** [comment]
yup it returns a negative number but for some reason it still triggers the isValid function

**Comment by LimJiaWeng** [comment]
> yup it returns a negative number but for some reason it still triggers the isValid function

you could try adding another filter(x) to remove the negative number from result to get an empty optional because isValid() only returns true is the optional is empty and not when the optional contains a negative number.

**Comment by LimZiXiong** [comment]
I faced this issue before. Basically before returning Num(Optional) I filter the optional to check if it's valid

**Comment by andhika2002** [comment]
faced this issue too! at the ned of ur code, filter result to return numbers >=0 (using the valid function provided in AbstractNum), then maybe you could pass the filtered result into another new Num(...) to return the new Num

**Comment by weiyangng** [comment]
how do i filter result when it is a type of Num, or should I change the type of result so that I can run filter on it

**Comment by ZHD1987E** [comment]
No sir. You make the Num check itself it is vlaid

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andhika2002** [comment]
> how do i filter result when it is a type of Num, or should I change the type of result so that I can run filter on it

result is Num, but we need Optional to use filter. what I did was to do result.opt.filter(.....), so that the types align. hope this helps! idt u need to change the result type cuz u can just access using .opt

**Comment by LimZiXiong** [comment]
Yea all Num comes with opt declared in abstractNum so you can just filter opt then return new Num(opt) after opt is filtered

**Comment by weiyangng** [comment]
thanks all appreciate the comments they all helped a lot!
