### ISSUE TITLE
Mock PA2 Level 5: Getting a, b, c, d

### ISSUE THREAD

**Issue by qeuif** [nus-cs2030/2324-s2#549]
Hi, I'm currently stuck at level 5 for mock PA2 and can't really figure out how to get a, b, c, d values for add, sub, mul operations.

How I have implemented Fraction so far:
I'm able to get the values as Optionals but not very sure how to add/multiply them to get ad/bc etc.
![image](https://github.com/nus-cs2030/2324-s2/assets/166937424/80bab827-df56-4f28-846b-207a4be3eee9)

Any help would be greatly appreciated, thank you :)

**Comment by MoeySeanJean** [comment]
My implementation is to use a chain of map and flatMap of Optional to access all a, b, c, d and return the final value in an Optional.

**Comment by qeuif** [comment]
Ohh okay I shall try thank you!

**Comment by xiang-qiuyu** [comment]
> Hi one way is to use flatMap then map to create a new Frac and hence a new Optional, this is so that you can access both fractions' optionals at the same time

i did this and it worked! thank you. for the rest still struggling, by using this.opt.flatMap(x -> other.opt.map(y -> ..., you will be able to access all the a,b,c,d in the two different Frac. hope this helps!

**Comment by yeeejieee** [comment]
^^ you can filter to check for its validity afterwards as well

**Comment by CSnoobCS** [comment]
I'm still a bit confused, is what he did in the screenshot on the right track?

**Comment by TongZhengHong** [comment]
> I'm still a bit confused, is what he did in the screenshot on the right track?

Yes I used the above implementation, its just that I can be shorter if you chain everything together

**Comment by ZimoSyndrome** [comment]
Dont forget to change your line 22 to second() as well @qeuif

**Comment by qeuif** [comment]
> Hi one way is to use flatMap then map to create a new Frac and hence a new Optional, this is so that you can access both fractions' optionals at the same time

I used this method too and it worked! Thanks everyone!
