### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by yuntsingg** [nus-cs2030/2324-s2#55]
I managed to pass the test cases for Lab 1, but I was given this compilation warning. May I ask what is the cause?

Thank you!

![image](https://github.com/nus-cs2030/2324-s2/assets/142105948/25f801ce-30da-4e08-8623-163364ad0d29)

**Comment by mingzheMOG** [comment]
"Holy Shit" - Java Compiler probably
![holyshit](https://github.com/nus-cs2030/2324-s2/assets/158056179/69ef7954-6a54-4099-ad4d-7177739c8389)

**Comment by ZHD1987E** [comment]
Nothing to worry about, it's something to do with their checkstyle breaking...

**Comment by mingzheMOG** [comment]
Update:
"Holy Shit" - Checkstyle probably
![holyshit](https://github.com/nus-cs2030/2324-s2/assets/158056179/66acdd08-fb6e-4b54-a229-14affaed73f3)

**Comment by hansneddyanto** [comment]
Probably some checkstyle issues?

**Comment by hwkchia** [comment]
Issue expired.
