### ISSUE TITLE
Mock PA2 Level 5 sub operation

### ISSUE THREAD

**Issue by wassilililily** [nus-cs2030/2324-s2#551]
![image](https://github.com/nus-cs2030/2324-s2/assets/110512886/a0d216da-16e3-4bb0-9909-2e538770544d)

![image](https://github.com/nus-cs2030/2324-s2/assets/110512886/e65363db-4d12-45d9-8201-7879507ca219)

I'm not sure how to properly implement the sub operation so that a negative numerator returns an invalid Fraction. Anyone able to provide some tips?

**Comment by ZHD1987E** [comment]
I hope that you read #528...

**Comment by TongZhengHong** [comment]
You can call the `isValid` method on the numerator and denominator `Num`s. If either one is invalid, then return an empty optional.

**Comment by meowmeowpeepee** [comment]
ur else statement should have another if else, where if numerator or denominator is invalid, return Optional.empty()

**Comment by kaywoon** [comment]
> The numerator is `x.first().mul(y.second()).sub(x.second()).mul(y.first())` and the denominator is `x.second().mul(y.second())`. Both are `Num` objects which you can call the `isValid` method upon. If either one is invalid, then return an empty optional.

how do you create the Num objects for the numerator and denominator? I'm currently facing the issue of Type mismatch: cannot convert from Optional<Object> to Optional<? extends Integer> when I try to create

**Comment by zuoshihua** [comment]
> @kaywoon 
> how do you create the Num objects for the numerator and denominator? I'm currently facing the issue of Type mismatch: cannot convert from Optional to Optional<? extends Integer> when I try to create

You should deal with `Optional<Num>` objects instead

**Comment by kaywoon** [comment]
okk i will give it a try, thank you!

**Comment by CSnoobCS** [comment]
Use a filter to check for validity on your optional may be helpful

**Comment by hanlinnnnn** [comment]
i did a .filter() in my constructor to save me the trouble in checking for validity in the methods

**Comment by yishao17** [comment]
i encountered the same problem, what i did was to work with optional num first, then checked for its validity using map and isValid(), then create Frac.of()/Fraction from there! hope this helps

**Comment by LuXLemonade** [comment]
What if it is invalid? What do you return?

**Comment by TongZhengHong** [comment]
> What if it is invalid? What do you return?

You can return `Optional.<Frac>empty()` and pass to a new `Fraction`. Since `Fraction` is an `AbstractNum`, the printed result will be `NaN` for an invalid Frac (where either `Num` are invalid).

**Comment by LuXLemonade** [comment]
If I follow the code snippet above, and check the validity within the map, I would need to return a ``Frac.of(...)`` and can't return a ``Optional.<Frac> empty()`` or should I check the validity before following the map shown above?

**Comment by kryst-ll** [comment]
i think you can add a filter here after your flatMap: `this.opt.flatMap(......).filter(...)` (so you filter the final optional) and inside the filter use .isValid() and && to make sure both Num are valid. This way if either Num is invalid the Optional will be empty

**Comment by ZHD1987E** [comment]
@wassilililily I hope that your issue has been solved. If so, you might want to close the issue. Thank you!
