### ISSUE TITLE
Mock PA2 Level 3 .sub()

### ISSUE THREAD

**Issue by kohsweehong** [nus-cs2030/2324-s2#555]
hello, on the requirement on Num.sub(), how should I deal with the subtraction as my code seems to not work although I negated the the argument by passing in .n and adding.
![image](https://github.com/nus-cs2030/2324-s2/assets/156646904/e0efffbf-08d0-4c2a-993a-5c6b24b1a9f6)

Output:
![image](https://github.com/nus-cs2030/2324-s2/assets/156646904/98464490-cb48-47a6-9801-62f5c92e94f2)

**Comment by niclow236** [comment]
You should be applying the n method on sb instead of st, as for example 2-1 = 1, it is actually 2+(-1) = 1 and not -2+1 which is -1

**Comment by kohsweehong** [comment]
ohh ok, so that means that i should not use AbstractNum.s in this case? like should make use of the .add() but dealing with a negative input?

**Comment by sje5398p** [comment]
> AbstractNum.s in this case? like should make use of the .add() but dealing with a negative input?

yes that's right!

**Comment by yushanedi** [comment]
> You should be applying the n method on sb instead of st, as for example 2-1 = 1, it is actually 2+(-1) = 1 and not -2+1 which is -1

Yup this is right!!

**Comment by kohsweehong** [comment]
alright have got it, thanks :)
