### ISSUE TITLE
mock pa2 test case 3_1

### ISSUE THREAD

**Issue by sje5398p** [nus-cs2030/2324-s2#557]
<img width="1261" alt="Screenshot 2024-04-14 at 6 00 28 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/a5dcdb1a-1177-4509-8ccf-b32111184603">
Hi, does anyone know how to fix this?

**Comment by joshuagde** [comment]
Hi, it is likely that in your mul implementation you didnt account for 0 x 0 which may result in an infinite loop

**Comment by LimZiXiong** [comment]
There is infinite loop going on. Strange codecrunch doesn't give time limit exceeded though

**Comment by yishao17** [comment]
did you check for 0s? maybe can add an if-else statement to account for any zeros!

**Comment by sje5398p** [comment]
<img width="326" alt="Screenshot 2024-04-14 at 6 20 30 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/1f7f80ec-2cd1-4c5d-804d-9c50501ae033">
I did account for 0s, and it seems to be working fine on jshell

**Comment by weiyangng** [comment]
you need to account for the situations that have either variable as 0, not just when both are zero

**Comment by sje5398p** [comment]
> you need to account for the situations that have either one of the variables as 0, not just when both are zero

do you mean in the cases like zero.mul(one) or one.sub(zero)? because those seem to work too on jshell

**Comment by LimZiXiong** [comment]
Check your multiplication try both one.mul(zero) and zero.mul(one)

**Comment by meowmeowpeepee** [comment]
did you consider for zero.mul(zero)?
i ran into the same error because i forgot to consider for that case
so my loop with .equals() method became an infinite loop

**Comment by sje5398p** [comment]
I tried all of this but it all seems to work fine on jshell.. maybe I’m misunderstanding what you guys are suggesting? lemme know if I tried it all, I attached screenshots below

nested mul:
<img width="293" alt="Screenshot 2024-04-14 at 10 00 24 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/a0e39d60-7611-4b98-a090-0aa15a9fec9f">

zero.mul(zero), and either one being zero: 
<img width="307" alt="Screenshot 2024-04-14 at 10 02 48 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/6f7c3a22-1c08-4b0b-a495-1f901f1804ce">

**Comment by zuoshihua** [comment]
Check your `add()` and `sub()` methods

**Comment by hanlinnnnn** [comment]
did u try a.mul(b.mul(c))? if it doesnt obey the associative rules its likely a mistake within ur subtract method

**Comment by quintenksh** [comment]
Hey @sje5398p, I am facing the same problem unfortunately. Did you manage to figure it out maybe?

**Comment by zuoshihua** [comment]
Notice that lines 69 and 71 tests the quadratic equation formula, where `b` is in fact negative. Hence, check your `add()` and `sub()` methods again

**Comment by sje5398p** [comment]
> Hey @sje5398p, I am facing the same problem unfortunately. Did you manage to figure it out maybe? I think that the problem lies in the fact that time limit gets exceeded, but I wouldn't know how to deal with that.

hello, I haven't figured it out yet, will lyk when I do!

**Comment by sje5398p** [comment]
> Notice that lines 69 and 71 tests the quadratic equation formula, where `b` is in fact negative. Hence, check your `add()` and `sub()` methods again

then how come b is not invalid?

**Comment by sje5398p** [comment]
> @sje5398p Hey! I managed to fix my code! I hope this will solve your issue as well, but: In my mul() method I first had "result = this.add(result);" in each iteration of my while loop. Using your values of a, b, and c, I noticed that the operation a.mul(c.mul(b)) took considerably longer than a.mul(b).mul(c). So, then I changed my code to "result = result.add(this);", which solved the problem of one taking longer than the other! I hope this helps!

Hii, thank u for reaching out haha, my mul() method already incorporates "result = result.add(this);"

<img width="450" alt="Screenshot 2024-04-15 at 4 07 03 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/999a0da4-fe0b-46ce-8be3-e90c917fcf8b">
do you spot anything else that could be the problem?

**Comment by zuoshihua** [comment]
> @sje5398p 
> pls lmk if u spot anything wrong.... thank you sm

It is evident in your `mul()` you did not check if `other` is zero

**Comment by zuoshihua** [comment]
How does your `sub()` method look like?

**Comment by sje5398p** [comment]
> How does your `sub()` look like?
like this :) thank u for ur all help 
<img width="608" alt="Screenshot 2024-04-15 at 4 47 54 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/07d40f8a-987e-40b9-a9fa-e71da549787d">

**Comment by sje5398p** [comment]
> Line 76 `new Num(newOther)` may be evaluating to an invalid `Num`

I tested for this, it seems to be valid?

<img width="503" alt="Screenshot 2024-04-15 at 5 02 16 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/6d9f92de-bd77-470d-8d97-bc73d87c32ee">

**Comment by zuoshihua** [comment]
Now try calling `add()` on `minusTwo`

**Comment by sje5398p** [comment]
> Now try calling `add()` on `minusTwo`

<img width="340" alt="Screenshot 2024-04-15 at 5 13 46 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/52eae004-b628-4dd3-86d4-573fdf9f6544">


realised it will give me all valid outputs even if it is negative.. maybe that is the problem?

**Comment by zuoshihua** [comment]
It is highly probable this is the problem. Your `add()` should always check if the final result is valid
