### ISSUE TITLE
mock pa2 level 2 add()

### ISSUE THREAD

**Issue by tannorine** [nus-cs2030/2324-s2#558]
jshell> Num result = zero.add(one).add(zero).add(one)
result ==> 2

jshell> result.add(result)
$.. ==> 4

somehow when I call result.add(result), it gives me an infinte loop as seen by the printing of infinite "one"s :( would like to know what causes this issue.

**Comment by zuoshihua** [comment]
Your code please...

**Comment by tannorine** [comment]
<img width="578" alt="Screenshot 2024-04-14 at 7 19 19 PM" src="https://github.com/nus-cs2030/2324-s2/assets/121949603/d387ccda-2191-4ecf-8bcd-f4f68a4bd1ad">

**Comment by joshuagde** [comment]
hi the issue could be in your .succ() method where its filtering if its valid when it doesnt need to

**Comment by hansneddyanto** [comment]
If it is infinite loop, you might want to check your for loop (if you use loops). At least that's what happened to me.

**Comment by yishao17** [comment]
Maybe u can check ur previous method to see if its implemented correctly. I think may need to see ur succ() method!
