### ISSUE TITLE
why do we need UnaryOperator if we have Function?

### ISSUE THREAD

**Issue by tarshalim** [nus-cs2030/2324-s2#559]
it seems that Function can do what UnaryOperator does and more? I dont see why we will ever need to use UnaryOperator?

**Comment by zuoshihua** [comment]
A quick google search gives the following answers

https://stackoverflow.com/questions/54441751/use-of-unaryoperator-and-binaryoperator-when-i-have-function-in-java-8

**Comment by tarshalim** [comment]
i see thank you!
