### ISSUE TITLE
MOCK PA2 LEVEL 4

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#561]
# Summary
Put a summary of the problem here
All my other classes are not problematic, but my Fractions class is vv problematic. it's throwing al l sorts of error, and now codecrunch says i used arithmetic operators. may i ask why is my code wrong, i see no arithmetic operators

## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
<img width="797" alt="Screenshot 2024-04-14 at 10 05 08 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/7af07ef6-d130-4359-8fbf-41be6d94e7f1">

<img width="336" alt="Screenshot 2024-04-14 at 10 05 16 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/b404a081-84c0-4820-a70c-521d756071c9">

**Comment by sje5398p** [comment]
if I’m not wrong it might be because we're not allowed to use orElse

**Comment by itzsihui** [comment]
ooyaaa thank you !

**Comment by hngkxn** [comment]
similar to the above comment^ idt we are allowed to use orElse and also we are not supposed to be creating our own toString methods iirc!
