### ISSUE TITLE
mock pa2 compilation errors

### ISSUE THREAD

**Issue by KayaT0ast** [nus-cs2030/2324-s2#563]
![image](https://github.com/nus-cs2030/2324-s2/assets/163643706/d929b999-57f6-42ca-ad07-edd0a83c6608)
i wrote my zero() based on the lab given code but this happens, is it something to do with the constructor of Num?

![image](https://github.com/nus-cs2030/2324-s2/assets/163643706/b3c298d0-8c87-4623-960c-6ef3cf282e65)

**Comment by ZHD1987E** [comment]
I think so...

**Comment by zuoshihua** [comment]
Do you call `super()`?

**Comment by CSnoobCS** [comment]
I dont think it should be public?

**Comment by hanlinnnnn** [comment]
your constructors should be private, also perhaps u wanna check ur usage of super() and this()

**Comment by walkaround54** [comment]
Probably to do with the way your Num(AbstractNum...) constructor is, can try initialising it using super(optional), so you'll need to get the Optional from your num input.

**Comment by hohinnn** [comment]
I think your constructors should be private, only the of() methods which calls your constructors should be public!

**Comment by lifrocszh** [comment]
I think there is something wrong with your constructor of num

**Comment by KayaT0ast** [comment]
oh i didnt think of using super(opt) and tried to put AbstractNum as a property thanks for the suggestions
