### ISSUE TITLE
Project Test Case 9_03

### ISSUE THREAD

**Issue by wangjiakng** [nus-cs2030/2324-s2#564]
Hiii I encounter this problem regarding test case 3. My code was able to pass all the public cases but not this private case. I was looking through other questions on test case 3 and mostly because of not updating the queues properly, but my test output looks different from theirs, so im not sure what causes my error.

My approach was creating a doneTime attribute in server. nextAvailableTime of server will be updated with the restTime and doneTime will not, then time for Done event will be the doneTime of server. I basically did not change much from previous lab until this stage.
<img width="468" alt="Screenshot 2024-04-14 at 23 35 27" src="https://github.com/nus-cs2030/2324-s2/assets/163487050/adaa0f81-eaa5-4d03-839b-ba488c7c8a1a">

**Comment by zuoshihua** [comment]
You may not need a `doneTime` attribute in `Server`, since when you instantiate a `Done` event, you call the constructor with the time done. Only when 

1. a `Done` event is retrieved from the priority queue
2. its `next()` method is called

Then should the `rest()` method be called on the server

**Comment by wangjiakng** [comment]
> You may not need a `doneTime` attribute in `Server`, since when you instantiate a `Done` event, you call the constructor with the time done. Only when
> 
> 1. a `Done` event is retrieved from the priority queue
> 2. its `next()` method is called
> 
> Then should the `rest()` method be called on the server

hii thx for the reply! does it mean that i should write a separate rest() method which is only called when done event is retrieved and next() on done is called?

**Comment by zuoshihua** [comment]
Would recommend `Server` to have a `rest()` method so that you can tell a server to rest. Just like `Customer` with `getServiceTime()` you should take care not to call `rest()` multiple times

**Comment by wangjiakng** [comment]
> Would recommend `Server` to have a `rest()` method so that you can tell a server to rest. Just like `Customer` with `getServiceTime()` you should take heed not to call `rest()` multiple times

ok! i'll try that, tysm!

**Comment by ThamudayaWinBerry** [comment]
from your output, it seems like the server's nextAvailableTime is not being updated correctly with restTime because 10 is being served immediately after 9 is done (lines 33-34) and also because 12 doesn't get served until line 47 although server 2 is already done in line 39 of your output. or it could also be that the time you're checking against in isAvailable method for the server is mismatched.

**Comment by wangjiakng** [comment]
> from your output, it seems like the server's nextAvailableTime is not being updated correctly with restTime because 10 is being served immediately after 9 is done (lines 33-34) and also because 12 doesn't get served until line 47 although server 2 is already done in line 39 of your output. or it could also be that the time you're checking against in isAvailable method for the server is mismatched.
> 
> since you pass the public test cases, you might wanna consider crafting your own test case and use print statements to trace where the error is. personally I didn't create an additional attribute but hope this helps :)

tyyy berry!!! i got it alr!

**Comment by mirainokimi** [comment]
hi can i ask how you managed to resolve this issue i also am stuck here with the exact same errors

**Comment by wangjiakng** [comment]
> hi can i ask how you managed to resolve this issue i also am stuck here with the exact same errors

hii! I followed what zuoshihua commented above! I removed my doneTime attribute and wrote a rest() method in Server. the server will rest when next() is called on Done event. hope this helps!

**Comment by Partillay** [comment]
> You may not need a `doneTime` attribute in `Server`, since when you instantiate a `Done` event, you call the constructor with the time done. Only when
> 
> 1. a `Done` event is retrieved from the priority queue
> 2. its `next()` method is called
> 
> Then should the `rest()` method be called on the server

May I ask why can't next available time of server be updated together with the rest time all inside Serve? Cuz I did that and have the same test case failure as op

**Comment by zuoshihua** [comment]
The server has to be dequeued when it is _done serving_ not done resting. IMHO the easiest way is to dequeue the server in the `Serve` event and update the server's next available time in the `Done` event. Otherwise, your customer won't queue at a server when it is resting (although it is perfectly fine to do so)
