### ISSUE TITLE
Mock PA2 

### ISSUE THREAD

**Issue by niclow236** [nus-cs2030/2324-s2#565]
[2024-04-14_232033.pdf](https://github.com/nus-cs2030/2324-s2/files/14971258/2024-04-14_232033.pdf)
[2024-04-14_231834.pdf](https://github.com/nus-cs2030/2324-s2/files/14971259/2024-04-14_231834.pdf)

Hi can i check how do ensure that the output is a single Nan when either numerator and denominator is not valid? Mine comes out as Nan:8

**Comment by kohsweehong** [comment]
You could consider using Optional.filter and check using isValid() for both your numerator and denominator to get a single NaN output

**Comment by CSnoobCS** [comment]
I used filter on the Optional<Frac> to check for valid

**Comment by zuoshihua** [comment]
Use `.filter()` with `&&` for multiple criteria

**Comment by ZHD1987E** [comment]
Ahem... There's a reason #528 exists... Check it out.

**Comment by alterVega** [comment]
Your output NaN: 8 is because your Num class is supplying a NaN. You need your Fraction class to supply NaN if either of the Nums are NaN so use .filter()

**Comment by hanlinnnnn** [comment]
ur fraction has an optional(frac) right? u can call .filter() on the opt to check if its .first() is valid and if its .second() is valid and not 0

**Comment by yishao17** [comment]
i worked with 2 optional Num and if any of them is not valid (ie <0 or denominator ==0), it will return Fraction Optional empty, else it will return the normal fraction. oh btw, I checked with isValid() instead of filter, you may want to consider which one works best for u! hope this helps!

**Comment by meowmeowpeepee** [comment]
I checked with isValid() for both numerator and denominator, and if either is not, will return NaN

**Comment by ethanmanzz** [comment]
Also came across this issue. To deal with this, as the numerator may be negative, you need handle this case with an if statement to check if the numerator in the Optional<Frac> is valid. I did this by calling equals to an Optional with a boolean true inside.  Something like this where o is the optional<Frac>

if (o.map(x -> x.first()).map(y -> y.isValid()).equals(Optional.of(true))) {

**Comment by niclow236** [comment]
Thanks everyone!
