### ISSUE TITLE
IS THE MOCK PA GIVING YOU A HARD TIME?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#566]
Then go read #528!

**Comment by CSnoobCS** [comment]
I feel that could have given more advice on the Fraction part. Anyway thx.

**Comment by ZHD1987E** [comment]
Thanks @CSnoobCS. Will add more advice soon, for now since I get a big barage of Fraction, I have added more content regarding Fraction.
