### ISSUE TITLE
Mock PA2 Level 1 Compilation Issue

### ISSUE THREAD

**Issue by cyting01** [nus-cs2030/2324-s2#568]
Hi all, this is currently my code for the Mock PA2. I'm not sure why I run into this compilation error. My approach is since Optional<T> is already an attribute in AbstractNum, I would like to call the super constructor and pass in the optional(as AbstractNum's constructor has one that takes in an optional). May I know what the issue is with this? Thanks!
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/19db6206-0604-46c7-b2f8-8d40136e8215)
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/9626174e-f9f0-43ec-bc6c-d050560c7f8b)

**Comment by samuelneo** [comment]
`Num` should extend `AbstractNum<Integer>`

**Comment by cyting01** [comment]
Thanks! It works now. Do you have an explanation of why I have to bind <Integer> to AbstractNum?

**Comment by meowmeowpeepee** [comment]
I think it is like, the super(opt) is of type Optional<Frac>

one one way i came to this conclusion is

![image](https://github.com/nus-cs2030/2324-s2/assets/164331190/bee3dedb-2c17-4fd3-83eb-aaf078937800)

looking at this, since you can't change the toString method, i figured out that opt should be of type Optional<Frac> too, since u unwrap then call the toString of Frac to get the output shown in the pdf

**Comment by zuoshihua** [comment]
Your implementation is rather complicated. You may want to refactor your code to something like:

```java
class Num extends AbstractNum<Integer> {

    static Num of(int i) {
        return new Num(Optional.<Integer>of(i));
    }

    private Num(Optional<Integer> o) {
        super(i.filter(valid));
    }

    private Num(AbstractNum<Integer> a) {
        super(a.opt);
    }
}
```

**Comment by zuoshihua** [comment]
> @cyting01 
> Thanks! It works now. Do you have an explanation of why I have to bind to AbstractNum?

`AbstractNum` is a generic class, meaning it can contain objects of any type. Here, we want to `AbstractNum` to contain `Integer` objects

**Comment by cyting01** [comment]
Thank you! I get it now.
