### ISSUE TITLE
Lab 1 Can a class have a mutable attribute

### ISSUE THREAD

**Issue by darylchen46** [nus-cs2030/2324-s2#57]
So we have learned that all the attributes of a class has to be given the `private final` keyword. But let's say I want to add an attribute to the `Server` class `availableTime` that gives each server the time when the next customer can arrive and be served by the server. If I want this attribute to be constantly changing, is there a way I can go about doing this without violating the `private final` keyword for all class attributes?

**Comment by rental12** [comment]
Yea creating and returning a new server is allowed in this case as shown in the lecture. ImList has a useful method called set that sets the element at that index and returns back a new ImList with the modification done.

**Comment by LimZiXiong** [comment]
Yea creating and returning a new server is allowed in this case as shown in the lecture. ImList has a useful method called set that sets the element at that index and returns back a new ImList with the modification done.

**Comment by darylchen46** [comment]
oh so can this be applied to any situation?

**Comment by LimZiXiong** [comment]
> oh so can this be applied to any situation?

Unfortunately since everything must be private final you can't modify the value after they are set. So the only way if we need to change something is to return a new item back and reassign the variable with the new return value.

**Comment by hwkchia** [comment]
Issue expired.
