### ISSUE TITLE
Tips to pass MOCKPA Test Cases

### ISSUE THREAD

**Issue by jiayingtjy** [nus-cs2030/2324-s2#570]
# Summary
Here are some tips to pass the MOCK PA2 given all the constraints stated 

## Constraints
No Arithmetic Operators, No Optional Getters, No isPresent, isEmpty, No toString or String dependecy in your new classes created 

## Question 1: Validity Checks and handling invalid cases without using orElse
How can you return Optional.empty() or manage invalid cases based on specific conditions without using orElse()? For instance, when validating fractions, you can use the .filter() method effectively. By applying .filter() directly on Optional<Num> instances for both the numerator and the denominator, you ensure that Optional.empty() is returned whenever a number fails the validity criteria. This method effectively flags an invalid fraction when any component does not meet the validity requirements.

**Implementation Tip:** Convert your data into Optional<T> so that .filter() can be used, which inherently returns Optional.empty() for invalid cases

## Question 2: How to print out the fraction even though you are not allowed to use toString and ensure that the output of a fraction does not display as "NaN: NaN" or "2: NaN?
 You can implement a validFrac check within the Fraction class and utilize .map and .filter to scrutinize the validity of both the numerator and the denominator. The use of .filter() here will lead to Optional.empty() for invalid fractions, signaling to the AbstractNum class that the fraction is not valid.

**Output Handling:** There is no need to implement another toString method to display the fraction output. Since Fraction extends AbstractNum<Frac>, the toString method in AbstractNum will handle the output, displaying "NaN" when detected as Optional.empty (invalid) and correctly rendering the fraction's toString when it is valid.

## Question 3: How to pass test case 5/10? 
There will be a stream test case to further validate your` .add()` and `.mul()` to see if it is working perfectly. Hence even if you pass the test case stated on the paper it wont work for this round if there is some logic error in your code: 
It will look something like this:

```
java.util.stream.Stream.generate(() -> one).limit(999).reduce(
java.util.stream.Stream.generate(() -> one).limit(999).reduce(zero, (x,y) -> x.add(one)), (x,y) -> x.mul(one))
```
First, it calculates the sum 999 by adding 1 to 0 a total of 999 times. Second, it multiply the 999 with one for 999 times.  Result should be 999

If your implementation in CodeCrunch fails to produce any output, it may indicate an issue with the .mul() method, potentially causing an infinite loop. To prevent this:
1. Initialization: Ensure that the starting number for the multiplication isn’t set to the current number, as this could unintentionally double the result with each iteration rather than correctly accumulating the sum.
2. Accumulation : Instead of incrementally modifying the result itself in each iteration, initialize your starting number as zero and add the otherNum to this zero for the current number of times. 

Hope this helps!

**Comment by yishao17** [comment]
thank you for this :)

**Comment by kaiju10** [comment]
thank you

**Comment by nickifung** [comment]
thank you for the help!

**Comment by proteaninja** [comment]
thanks!!

**Comment by ZYZY2727** [comment]
tks alot!!!

**Comment by tanbeng123** [comment]
thank you for the helpp!

**Comment by yminnnx** [comment]
thank you for the tip!

**Comment by Jeremythong2002** [comment]
thank you!

**Comment by frdyli** [comment]
thank you its very clear!

**Comment by Jiahui-liew** [comment]
thank you so much!

**Comment by ZHD1987E** [comment]
Thanks @jiayingtjy. The mock PA2 is over, you might want to close it.
