### ISSUE TITLE
Mock PA2 iteration difference

### ISSUE THREAD

**Issue by proteaninja** [nus-cs2030/2324-s2#571]
Hi just wondering why are these two sets of code giving different results?

```
Stream.iterate(Num.zero(), x -> !x.equals(other), x -> x.succ())
```
and
```
for (Num i = Num.zero(); !i.equals(other); i = i.succ()) {
    result = result.add(this);
}
```
Does this mean that for stream iterations it does not reach the predicate's final value?

**Comment by samuelneo** [comment]
how are you terminating the stream?

**Comment by proteaninja** [comment]
> how are you terminating the stream?

I used 
```
.reduce(thisNum, (a, b) -> a.succ());
return Num.of(numStream.opt);
```

**Comment by erichugy** [comment]
Just curious, wouldn't the first one add `1` to the result `other`-times to the result whereas the second (the for loop) adds the value of `this` to the result `other`-times? So unless `this` is an instance of `Num.one`, these two solutions shouldn't equal one another.

**Comment by proteaninja** [comment]
oh yes my bad, I used them for add and mul respectively. I was more confused about how stream's iteration and for's iteration are handled differently. If I were to use the stream's iteration for mul and add (instead of only using it for add in this case), it would give me wrong outputs.
