### ISSUE TITLE
Project IllegalFormatConversionException

### ISSUE THREAD

**Issue by Yuxin-Mellisa** [nus-cs2030/2324-s2#578]
<img width="1101" alt="Screenshot 2024-04-15 at 9 19 15 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157778558/b03fb106-2533-4d59-afd7-c4c22e65ef9c">

I don't understand what is wrong with it?

**Comment by Yuxin-Mellisa** [comment]
I changed the $s to %s still like this

**Comment by Jeremythong2002** [comment]
Does your Wait object contain the entire serverList? Could be an issue with the arguments passed into String.format()

**Comment by yishao17** [comment]
does ur Wait event gets initialised with the entire serverList? If it doesn't, it wont have the serverList to use the .get() method and thus, the .toString() method. What I did was to pass the serverNum around the events and used it in the .toString() method! hope this helps :)
