### ISSUE TITLE
Lecture 02 Q3

### ISSUE THREAD

**Issue by HoSCD** [nus-cs2030/2324-s2#58]
# Question Description

Q3: There is a design principle called Interface Segregation Principle (one of the five SOLID principles). How does ISP relate to our discussion above?

## Your contribution:

The Interface Segregation Principle (ISP) states that no code should be forced to depend on methods it does not use, thus a class should not be forced to implement methods it doesn't need. In this example, having separate interfaces (Shape and Movable) allows for flexibility in implementation. This adheres to the ISP because classes like Point can choose to implement only the methods that they need without being burdened by unnecessary ones.

The example with the MovableShape interface combines both getArea and moveBy methods. Eventhough it might seem more convenient to have a single interface, it violates the ISP if there are classes (eg. Point) that only need one of the methods. By keeping interfaces separate, we allow classes to adhere to the principle, implementing only what they need and avoiding unnecessary dependencies on methods that are irrelevant to their function.
`

**Comment by hwkchia** [comment]
Included into Lecture02
