### ISSUE TITLE
Ungraded exercise 2: Are we suppose to create a join(Point) method in Str class.

### ISSUE THREAD

**Issue by donregan9** [nus-cs2030/2324-s2#580]
# Summary
The question says "Since we do not expect the client to know how to use map and flatMap, we need to facilitate joining to a String or Str object using join instead."

It says join a String or Str object, must we create a join(Point) method in Str class?

## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
![Screenshot 2024-04-15 220335](https://github.com/nus-cs2030/2324-s2/assets/166942109/bf4528cd-6e3a-46ac-bd29-432e0da1cd90)

**Comment by xinnyyy** [comment]
hii what i did was to have 3 join methods each of them accepting different argument types. like join(Point point), join (Str str) and join(String string) then have the respective implementations! it worked on jshell, but i havent submit to cc yet. hope this helps! :)

**Comment by ArkAzrael** [comment]
No you do not need a Join(Point), any point they make calls a toStr() to convert it into a Str object, so only 2 join methods are required.

**Comment by Yuxin-Mellisa** [comment]
the circle class given and the one written there is different
I just change the this.center to this.center.toStr()
<img width="517" alt="Screenshot 2024-04-15 at 11 02 28 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157778558/4c236142-a607-4f50-b1e1-d6543ce45899">
I think it is their typing error though

**Comment by omgacai** [comment]
<img width="537" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/134914115/96eb7b73-4c46-4c9d-abe1-380dffbac37f">

im not sure if its an error i realised the Circle.java file they gave us to download was different from the one here shown, so they actually converted the point to Str object already (this.centre.toStr()), I modified the Circle class they provided to the one here and my join method passed the test cases on cc

**Comment by donregan9** [comment]
Oh ya seems like the file we downloaded was missing the to.Str() behind the this.centre as stated in the question, ill just modify the Circle.java file... thanks all.

**Comment by ZHD1987E** [comment]
@hwkchia Please check if what we're given on CodeCrunch and on the actual file is different, thanks.

**Comment by yishao17** [comment]
I had only 2 join method if that helps! :)

**Comment by hwkchia** [comment]
My apologies.. fixed `Circle.java`
