### ISSUE TITLE
Ungraded Exercise 2: How do we do flatMap?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#581]
Yep, it also tells me:
> Note that value caching is not required.

So how do you guys do it?

**Comment by zuoshihua** [comment]
Get and get again

**Comment by ZHD1987E** [comment]
More specifically?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zuoshihua** [comment]
Invoke the supplier in `mapper.apply()` then on the result

**Comment by ZHD1987E** [comment]
So something like this heh: () -> mapper.apply(() -> whatever) ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zuoshihua** [comment]
Yeah somewhat

**Comment by ZHD1987E** [comment]
Solved it, thanks.
