### ISSUE TITLE
Ungraded Exercise 2: Struggling with Trace()

### ISSUE THREAD

**Issue by ArkAzrael** [nus-cs2030/2324-s2#582]
I have been trying to get Trace to work for hours now and have already stopped understanding how or why it doesn't seem to work.
My order for the Trace Log is completely messed up with no discernable pattern whatsoever.

![Trace2](https://github.com/nus-cs2030/2324-s2/assets/157274977/ad5255ff-e936-4ca3-a209-183966db5e48)
![Trace1](https://github.com/nus-cs2030/2324-s2/assets/157274977/213ece75-5754-4c65-83d2-bf2c4fcf9328)
![TraceError](https://github.com/nus-cs2030/2324-s2/assets/157274977/f09cd0f2-0567-4e78-b242-8738ef7aea4a)

I'm hoping someone could help me out. I'm pretty sure the issue is somewhere in these 4 methods.

**Comment by hadyamanisanto** [comment]
Excuse me, can you explain what is the call(Str other) method?

**Comment by ZHD1987E** [comment]
That's like trying to deal with a lot of suppliers. Wrap and unwrap galore!

**Comment by samuelneo** [comment]
same, I don't know how we're supposed to get both the trace and output with a single evaluation without value caching

**Comment by ZHD1987E** [comment]
My lab TA sent me this:
[Uploading PA2 Practice 2.zip…]()

**Comment by ZHD1987E** [comment]
My lab TA sent me this: 
[PA2 Practice 2.zip](https://github.com/nus-cs2030/2324-s2/files/14987633/PA2.Practice.2.zip)

**Comment by zuoshihua** [comment]
> My lab TA sent me this: [PA2 Practice 2.zip](https://github.com/nus-cs2030/2324-s2/files/14987633/PA2.Practice.2.zip)

I thought `Optional.ifPresent()` isn't allowed but since the it was not specifically mentioned...

**Comment by ArkAzrael** [comment]
Thanks guys, seems my approach was wrong
