### ISSUE TITLE
Mock PA2 Level 2 Stream

### ISSUE THREAD

**Issue by sendhelpps** [nus-cs2030/2324-s2#583]
# Summary

## Description:
hello i am not sure how to incorporate a counter to my stream iterate function such that it is able to terminate the stream when the counter = last element. any help would be appreciated!!

## Code Snippets

![Screenshot 2024-04-16 at 11 54 27 AM](https://github.com/nus-cs2030/2324-s2/assets/87869357/e161f477-eaa5-4d3e-8c4d-bede36f607cf)

## Screenshots

Screenshots (if any)

**Comment by BZAStudent** [comment]
What i did was create a negative counter where the negative number is stored in a AbstractNum. Then i while loop and add it by 1, stopping only when it is 0. In the while loop then i will add my Num by 1.

**Comment by zuoshihua** [comment]
Pass in `Num.zero()` instead of `this` as the identity for `Stream.iterate()`

**Comment by anqixxxx** [comment]
yep! i made 2 variables (one for the result and one as a counter) and had a while loop where i updated the variables each time

**Comment by tanbeng123** [comment]
what i would suggest for you to do is to introduce a Num counter = Num.zero() as a start

**Comment by W-WJ-Ryan** [comment]
for me i used a counter to count how many succ() it takes to get to the n added, and apply the same number to the current Num object. I believe you could make it a one liner if you wanted to but i did not see the point of complicating it further :)

**Comment by E0968235** [comment]
i used a counter to check how many times i must call succ() and used a while to loop to check if the counter == num for which it breaks out of the while loop and stops calling succ()

**Comment by timc5nn** [comment]
thanksss

**Comment by ZHD1987E** [comment]
Did it work @sendhelpps? If it did, great! You can close the issue.
