### ISSUE TITLE
Use of restricted Optional methods

### ISSUE THREAD

**Issue by erichugy** [nus-cs2030/2324-s2#586]
# Summary
I get the following error from the PA2 grader: `Use of restricted Optional methods`
I have no clue what methods aren't allowed. Is there any way to see the list?

## Idea's
I use `Optional.of()` and `Optional.empty()`. I can't say for sure, but I'm fairly certain the TAs used `Optional.empty()`  in their solution and I also can't see why`Optional.of()` would be restricted...

**Comment by jianhaosoh** [comment]
![Screenshot 2024-04-16 at 4 25 54 PM](https://github.com/nus-cs2030/2324-s2/assets/142876316/a0346aa3-0a72-42bd-9e07-2639ce33f243)
These are the methods that are not allowed for the mock PA2. I did make use of Optional.of() and Optional.empty() and had no issues.

**Comment by erichugy** [comment]
Hmmm,
