### ISSUE TITLE
Where to get test cases

### ISSUE THREAD

**Issue by hansneddyanto** [nus-cs2030/2324-s2#59]
# Summary

Where to get test cases

## Description:

May I know where I should obtain the test cases for both lab 1 and exercise 1?

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by hadyamanisanto** [comment]
I think you can submit the code into CodeCrunch and see the resulting output.

**Comment by timothyngcy** [comment]
I think you are supposed to write them yourself typing in the terminal:

`vim exampleinput.in`

then create your own set of inputs.

**Comment by wkleow123** [comment]
the page with the problem has some of the test inputs and expected outputs already at the bottom of the page I think those should suffice for testing

**Comment by ZHD1987E** [comment]
Alternatively, you can create some of your own test cases as a sanity check.

For example, this below checks that it can basically function.
```
1
1.0 1.0
```

And I create this to check if the leaving is handled correctly.
```
1
1.0 1.0
1.5 1.0
```

Once I am all done, I create larger test cases, or borrow them from the task themselves.
