### ISSUE TITLE
Ungraded Ex 2

### ISSUE THREAD

**Issue by nus2030** [nus-cs2030/2324-s2#594]
How am I able to trace each step of the way for Level 4? I am not sure how it is possible to include a trace in each step of the way. Any help is appreciated!!

![Screenshot 2024-04-16 at 10 46 13 PM](https://github.com/nus-cs2030/2324-s2/assets/156705766/e99f4a96-9a6d-4dee-8956-f5e2e4996711)

**Comment by Timmyneedsbzahelp** [comment]
im cooked 😭

**Comment by samuelneo** [comment]
you might want to take level 5 into account for this. the Consumer (which performs the printing in this case) should be performed on each individual traced step, rather than letting the whole trace accumulate and printing that

**Comment by frdyli** [comment]
you can let Constructor be Str(Supplier<String> s, Function<Consumer<String>, String> f)

and also update the Consumer<String> in map and flatMap so as to update the consumer whenever all any of methods and constructor are called to capture the tracing.

an example can be Function<Consumer<String>, String> f = x -> {String v = s.get(); 
                            x.accept(tstr + v);  
                            return v;};
