### ISSUE TITLE
Exercise 4 - Generics: Error from grader: Main.<Integer>testing(1, x -> x == 0)

### ISSUE THREAD

**Issue by erichugy** [nus-cs2030/2324-s2#596]
# Summary

From my own testing, I've passed all the example test cases, but I still get this error from the online grader:
` Main.<Integer>testing(1, x -> x == 0)`. 

## Description:

Why is the grader passing a lambda function to `Main::testing`? Isn't the function signature supposed to be `static <R> boolean testing(R val, Tester<? super R> tester)`?

## Code Snippets
I've tried using both `Tester::testing` and `Tester::test` in `Main::testing` and neither work. I also tried overloading `Main::testing` with `static <R> boolean testing(R val, Function<? super R, ? extends Boolean> tester)`
```
static <R> boolean testing(R val, Tester<? super R> tester) {
        return tester.test(val);
    }
```

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/110847840/c5bbebac-3d93-4416-bb2f-ddc412d4a622)

**Comment by samuelneo** [comment]
> Why is the grader passing a lambda function to `Main::testing`?

lambda expressions can be implicitly converted to functional interfaces; this is how you've been able to using `filter`, `map`, `flatMap`, etc. when working with Optionals (or other classes that make use of higher-order methods)

> argument mismatch; Tester is not a functional interface
> multiple non-overriding abstract methods found in interface Tester

you may want to relook at your Tester interface

**Comment by erichugy** [comment]
If anyone else encounters this issue, a functional interface is an interface that contains exactly one abstract method.
