### ISSUE TITLE
Project test case 9_11

### ISSUE THREAD

**Issue by bmok02** [nus-cs2030/2324-s2#598]
Hi I have been stuck on this test case for a while now. Do you know how I should approach this? I think the issue is with the Wait event since 13 and 14 are both being served at the same time while they are waiting in the shared Self Customer Queue?

![Screenshot 2024-04-17 at 1 18 03 AM](https://github.com/nus-cs2030/2324-s2/assets/133203299/c071d68d-1228-4ea6-bced-1f2e33972ca5)

**Comment by timothyngcy** [comment]
Hello! This happened to me too. Essentially, the customer should "check the queue again" at the earliest time a self-checkout is done. You can do this by looping through all the SCOs then finding the earliest time an SCO is done and taking that time and updating the customer's time (or Wait time, depending on how you implemented it).

**Comment by marvinchoo-mh** [comment]
you can do a a simple test by priniting the nextavailable time of the selfcheckout when you update your severList. Like what @timothyngcy said the nextAvailableTime for the selfcheckout needs to be the earliest time out of all the selfcheckout servers.  and updating your servers nextAvailableTime properly. I hope this helps!

**Comment by yishao17** [comment]
I think it may be an error from wait->wait/hold. make sure if its waiting at a self checkout, u find the earliest self checkout timeAvail and update the wait timestamp to that (not the server u are waiting at)! u can add print statements to see how it changes too then can pinpoint which part of ur code has a logic error! hope this helps

**Comment by ezclap02** [comment]
hi like what others have said, you would have to check for the earliest available time among ALL the self check outs, and then assign your next event to that self check out.

you could potentially do this by looping through your list of servers and finding the earliest available time.

**Comment by Bryanng41** [comment]
I think this happened to me too! You have to sort of call the server available time again for it to refresh instead of using the one passed to it.
