### ISSUE TITLE
Project Codecrunch submission "Multiple output detected"

### ISSUE THREAD

**Issue by Durpfish** [nus-cs2030/2324-s2#599]
# Summary
Hello does anyone know what I should do abt my code for this case?
Would it have to do with me calling the restTimes.get() too many times? (i mean i only called it once, like i did in the prev submission)
So far I'm passing the public test case but I have no idea what the problem I'm running into is, so it would be great if anyone who faced a similar issue can let me know! Thankyou

**Comment by marvinchoo-mh** [comment]
hello when I got this error it was due to my code having some print line which I used to debug my codemaybe you want to check and remove them?

**Comment by MarcusLiangg** [comment]
Hi, I usually get this if I forgot to remove system.out.print somewhere

**Comment by jennipho** [comment]
Try to find places where you put in print lines! Doing this usually removes the error for me.

**Comment by Durpfish** [comment]
okay that worked thanks everyone! even though the print statement was never called i think codecrunch didnt let me submit my code regardless :")
