### ISSUE TITLE
Suitable alternatives to Lab 01 output

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#60]
# Summary
I'm Hady, and I am looking for a simple alternative solution to Lab 01.

## Description:
I wanted to print the [2 1] value at the back, but since all values have to be private final, I have to return a new, smaller class within the Stimulator class. Is there a simpler alternative?

## Code Snippets
<img width="260" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/3d39f673-9743-4741-ab49-5c6308c671da">

**Comment by zuoshihua** [comment]
Just to check, you are not writing any print statements inside the Simulator's simulate method right?

**Comment by hadyamanisanto** [comment]
Yes

**Comment by hadyamanisanto** [comment]
> Just to check, you are not writing any print statements inside the Simulator's simulate method right?

yes

**Comment by zuoshihua** [comment]
I guess you could treat them as two variables inside the simulate method

**Comment by hadyamanisanto** [comment]
Without violating the private final keyword, can I create and return a new Stimulator?

**Comment by hadyamanisanto** [comment]
> I guess you could treat them as two variables inside the simulate method

Can they not be attributes?

**Comment by zuoshihua** [comment]
What does your simulate method return?

**Comment by hadyamanisanto** [comment]
Also, whenrunning, i found this compilation error
<img width="585" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/d4f89dc5-241d-467f-8234-e6c5def9174f">
 Any help is appreciated.

**Comment by hwkchia** [comment]
Issue expired.
