### ISSUE TITLE
Ungraded Exercise 2

### ISSUE THREAD

**Issue by pramoth20** [nus-cs2030/2324-s2#600]
<img width="1171" alt="Screenshot 2024-04-17 at 10 24 06 AM" src="https://github.com/nus-cs2030/2324-s2/assets/155830463/769fea2d-33be-43dc-9e90-d25e20ecd222">
does anyone else get that error too?

these are the join methods I have written but I wasn't told to write one for point:
 38     public Str join(Str other) {
 39         return new Str(this.string + other.string);
 40     }
 41 
 42     public Str join(String other) {
 43         return new Str(this.string + other);
 44     }

**Comment by ZHD1987E** [comment]
I recall there was one other issue here, #580

**Comment by pramoth20** [comment]
Thank you! for future reference, the circle class provided is different from the one in codecrunch, so just edit accordingly.
