### ISSUE TITLE
Ungraded Exercise 2 Level 2

### ISSUE THREAD

**Issue by Bryanngu03** [nus-cs2030/2324-s2#605]
I'm abit stuck at the flatMap part since i cannot use the get() and also toString() method, is there any alternative way?
 
29     public Str map(Function<String,String> mapper) {
 30         Optional<String> newopt = this.opt.map(mapper);
 31         return new Str(newopt); 
 32     }   
 33 
 34     public Str flatMap(Function<String,Str> mapper) {
 35         Optional<Str> newopt = this.opt.map(mapper);
 36         Optional<String> newstr = newopt.map(x -> .....
 37         return new Str(newopt);
 38     }
tysm guys.

**Comment by Jeremythong2002** [comment]
Once it returns the Str from the function passed into flatMap(), you can use a map on the new Str returned from that function

**Comment by Bryanngu03** [comment]
Alright Thanks guys, solved it.
