### ISSUE TITLE
Rec 5 reduce() method

### ISSUE THREAD

**Issue by xinnyyy** [nus-cs2030/2324-s2#607]
<img width="652" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/ba8ff285-2d2e-41d7-85bb-740d749bbf0d">
hello, im having trouble understanding how list.reduce(1, bif) will give 11. I thought that 1 + one.length() (which is 3) = 4, 4 + two.length() = 7, 7 + three.length() = 7 + 5 = 12? Am I having a mistake in my understanding of how reduce works?

**Comment by samuelneo** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/24467645/4e532e89-cd89-4cce-9d39-9cdfc70016be)
looks like you're right, it should be 12 instead

**Comment by quadryan** [comment]
I think so too, it should be 12.
