### ISSUE TITLE
ungraded exercise 2--level 2

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#608]
How do we do map/flatmap without calling get() ?
My Str has a supplier as its attribute
<img width="558" alt="Screenshot 2024-04-17 at 7 17 27 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/3a0ebc91-ce1e-454b-a9bb-dcc965ea1fc6">

**Comment by samuelneo** [comment]
you may want to refer to lecture 7, particularly the implementation of `map` for a `Lazy` Supplier. the implementation here is quite similar

**Comment by naomiiiwu** [comment]
<img width="472" alt="Screenshot 2024-04-17 at 7 36 29 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/1efc6e71-0f4a-417f-8112-8e75a4499f12">
My join methods are like this... but failed this test case:
<img width="619" alt="Screenshot 2024-04-17 at 7 36 57 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/5d0d1462-13ab-4777-b644-182a0e18723d">
I think its because I called get() in my map method..thats why beep is evaluated

**Comment by samuelneo** [comment]
`join(Str)` should make use of both `map` and `flatMap`

**Comment by naomiiiwu** [comment]
> you may want to refer to lecture 7, particularly the implementation of `map` for a `Lazy` Supplier. the implementation here is quite similar

Oh but they implemented get() differently.. with an optional & orElseGet()..

**Comment by naomiiiwu** [comment]
> the implementation of `get` doesn't matter, what matters is that it's wrapped in a lambda so it doesn't eagerly evaluate

Thank u! I will try!

**Comment by LimZiXiong** [comment]
> > you may want to refer to lecture 7, particularly the implementation of `map` for a `Lazy` Supplier. the implementation here is quite similar
> 
> Oh but they implemented get() differently.. with an optional & orElseGet()..

The use of optional is to cache the result. The problem without caching is even though the result has been evaluated, it will still evaluate again when the user use get() on the lazy. Since for this question they mentioned that no caching is required, you can safely ignore the Optional part. In fact, i don't think is PA is doable with Optional

**Comment by lim-4158** [comment]
for your join method, the one that takes in a str, u should make use of both flatmap and map method, which is identical with an example that they provided within the exercise code chunk.

**Comment by naomiiiwu** [comment]
guys so sorry I changed my code to this but the output does not change at all :"((( Any help would be great :"(
<img width="567" alt="Screenshot 2024-04-18 at 12 08 29 AM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/eb432838-eea1-41b0-bf5c-b8206d3e5405">

**Comment by naomiiiwu** [comment]
OH WAIT IT WORKED!!JUST CHANGED MY FLATMAP TO THIS BUT LOOKS A BIT WEIRD.. NOT SURE IF IT IS CORRECT, CAN ANYONE HELP ME SEE MY FLATMAP()... 
cuz apparently I get() then stored in another supplier. I don't think its ideal, but do we hv any other approach for this?
<img width="620" alt="Screenshot 2024-04-18 at 12 13 47 AM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/2aebbda0-6cbb-4af3-a9b8-dbf75695bf15">

**Comment by LimZiXiong** [comment]
> guys so sorry I changed my code to this but the output does not change at all :"((( Any help would be great :"( <img alt="Screenshot 2024-04-18 at 12 08 29 AM" width="567" src="https://private-user-images.githubusercontent.com/156983070/323299078-eb432838-eea1-41b0-bf5c-b8206d3e5405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzA0NzEsIm5iZiI6MTcxMzM3MDE3MSwicGF0aCI6Ii8xNTY5ODMwNzAvMzIzMjk5MDc4LWViNDMyODM4LWVlYTEtNDFiMC1iZjVjLWI4MjA2ZDNlNTQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmY2Y2QxM2RlYjQ5YTUzNzNiMzFkNTQwNmI3NzM0ZjlkMzJhZjhiODk1NjAxNDEzNDE1ZjRjMTY5YTI5MDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E-JpKOLJCpfLWv-HLUG9W3U2fy2OjALvOcbYQfzI47M">

Your flatMap is evaluating eagerly. This question is nice (lol) in a sense that your flatMap mapper always return Str, not ? extends Str so you can just 1 liner it. Just do return new Str(() -> mapper.apply(this.s.get()).s.get());

**Comment by naomiiiwu** [comment]
> > guys so sorry I changed my code to this but the output does not change at all :"((( Any help would be great :"( <img alt="Screenshot 2024-04-18 at 12 08 29 AM" width="567" src="https://private-user-images.githubusercontent.com/156983070/323299078-eb432838-eea1-41b0-bf5c-b8206d3e5405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzA0NzEsIm5iZiI6MTcxMzM3MDE3MSwicGF0aCI6Ii8xNTY5ODMwNzAvMzIzMjk5MDc4LWViNDMyODM4LWVlYTEtNDFiMC1iZjVjLWI4MjA2ZDNlNTQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmY2Y2QxM2RlYjQ5YTUzNzNiMzFkNTQwNmI3NzM0ZjlkMzJhZjhiODk1NjAxNDEzNDE1ZjRjMTY5YTI5MDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E-JpKOLJCpfLWv-HLUG9W3U2fy2OjALvOcbYQfzI47M">
> 
> Your flatMap is evaluating eagerly. This question is nice (lol) in a sense that your flatMap mapper always return Str, not ? extends Str so you can just 1 liner it. Just do return new Str(() -> mapper.apply(this.s.get()).s.get());

yes thank you so much I just realised that as well!! HAAHAH

**Comment by mChewWW** [comment]
hi im having similar issues, can i check how you implemented the static Str of(Supplier<String>) method?

**Comment by naomiiiwu** [comment]
> hi im having similar issues, can i check how you implemented the static Str of(Supplier) method?
> 
> nvm, i got it to work, can someone just confirm that im on the right track that there at least until level 3, the only attribute needed for Str is a supplier?

yes I did this but I'm still on level 3

**Comment by naomiiiwu** [comment]
tks guys solved it
