### ISSUE TITLE
Compilation error in 

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#61]
# Summary

Basically, I received a compilation error when trying to add values to the ImList<customer> to check which customer can be stored.

<img width="585" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/7b61900c-866e-4455-9823-a1c5e00e569d">

Any solution is appreciated.

**Comment by weikiatt** [comment]
I don't think you're allowed to change final variables, can maybe try reassigning the updated values to the same object?

**Comment by timothyngcy** [comment]
> I don't think you're allowed to change final variables, can maybe try reassigning the updated values to the same object?

Agree @hadyamanisanto, you can try passing this ImList into a method and create a new ImList then set/remove the elements with the updated elements.
