### ISSUE TITLE
Mock PA2 Level 5 Sub NaN : 8 issue

### ISSUE THREAD

**Issue by andhika2002** [nus-cs2030/2324-s2#610]
Hi all, getting the Nan : 8 issue in my sub method. 

![image](https://github.com/nus-cs2030/2324-s2/assets/105861910/d0e782b8-e564-4b93-8907-a1d19b13d898)

Not too sure how I can use .filter(isValid()??) or even use the AbstractNum.valid method. A little confused because I thought the optional passed into my Of method would have cleared the isValid() check? Why would I need to do another round of valid checks?

![image](https://github.com/nus-cs2030/2324-s2/assets/105861910/4e8d9395-61f8-493d-8267-c5fcfe3ee378)

![image](https://github.com/nus-cs2030/2324-s2/assets/105861910/a5c1e44c-2ab3-4471-961e-2d4236661a81)

**Comment by kohtw** [comment]
your sub method uses a different constructor with, Frac.of(Num, Num) instead of Fraction.of(int, int)

**Comment by MaverickWongKeJun** [comment]
i did the filter within my sub class as it is the only function that might produce an invalid result despite having 2 valid inputs. what i did was i filtered the output fraction to check if the numerator is a valid input, then returned that result

**Comment by OthnielChang** [comment]
if you want to filter here, you should create a new predicate for when num can be a denominator, but a better idea is to probably filter in the sub class instead

**Comment by Xiang-le** [comment]
i think a simple fix is to just use an if-else in your sub method. 
If the resulting numerator is valid, return what you have, else return new Fraction(Optional.empty())

**Comment by kaiju10** [comment]
to add on from @MaverickWongKeJun, it will be to add `filter()` after `map()` from `other.opt`. This will valid check the new Frac and will auto return Optional.empty() if it fails the valid, else it will return Optional<Frac> with the new Frac inside

**Comment by LimJiaWeng** [comment]
I think its becuase in your sub function, you're generating a new Fraction using your private constructor Fraction(Optional<Frac>) and not the function Fraction.of() so it doesn't filter the optional. What you could do is filter the optional again before finally returning the new Fraction.

**Comment by ZYZY2727** [comment]
check for the validiity again otherwise return opt empty

**Comment by andhika2002** [comment]
Hi everyone, thanks for the help! I'll post what I did to fix it here in case anyone else faces the same issue. 

![image](https://github.com/nus-cs2030/2324-s2/assets/105861910/8bfb08e2-b305-4377-a2d8-ae6769ff1af4)

@kaiju10 also advised to add a .filter() to check validity of **only the numerator.** since only numerator undergoes the sub function defined earlier, and could be negative.
