### ISSUE TITLE
MOCK PA2 add() issue

### ISSUE THREAD

**Issue by WWYYiXuan** [nus-cs2030/2324-s2#612]
# Summary
hi i tried to implement the add() method but it turns out the add() is not adding anything?
any insights are appreciated! thx!

## Description 
Describe the problem and any details if neceesary

## Screenshots (if any): 

![image](https://github.com/nus-cs2030/2324-s2/assets/163511252/ca471ef8-30f8-4258-99d4-8baf2acb5c8b)
![image](https://github.com/nus-cs2030/2324-s2/assets/163511252/a0cd723d-dc0b-4aa1-802d-86b1138894fb)

**Comment by marshchxstxrmello** [comment]
can consider using `.reduce(this, (x, y) -> x.succ()) ` instead of just y.
This will allow `this` to increase by 1 for each iteration.
`limit`, `long counts` and `Num counter` is not necessary because the hasNext condition `x -> !x.equals(n)` will terminate the iterate. Hope this helps

**Comment by WWYYiXuan** [comment]
thank yall for the comments! i tried accordingly and it works :)
