### ISSUE TITLE
PA2 help!!!

### ISSUE THREAD

**Issue by jaslyntay** [nus-cs2030/2324-s2#618]
ive been having trouble studying for PA2!! how did you guys go about revising? it took me a whole day to finish mock PA2 omg.... jiayou everyone~~~~

**Comment by yewyaorui** [comment]
oh noQ!Q!!!! maybe try restarting? from understanding Maybe and Log classes. dont worry 1 day is not too bad you have 1 week for pa2 :))

**Comment by ji3jieee** [comment]
omg i think im just going to spam all my previous codes for Maybe and Log on a cheatsheet and just pray for the best that i can dump some stuff inside T.T jiayous too

**Comment by ZHD1987E** [comment]
As my lab TA said... just turn up. Whether or not you get wrecked is up to the day itself.

**Comment by iceflakes12** [comment]
Understanding and writing map, flatMap and lazy evaluation without referring to any notes/chatgpt. Then understanding how to use map/flatMap in pipelines. Once you can do this, anything else is pretty much out of your control anyways.

**Comment by donregan9** [comment]
Just try the practice papers should be fine

**Comment by sohsohsiying** [comment]
look through past practicess

**Comment by CSnoobCS** [comment]
you'll score at least 50% :)
