### ISSUE TITLE
magic numbers

### ISSUE THREAD

**Issue by kat-font** [nus-cs2030/2324-s2#621]
might be a stupid question, but when is something considered a magic number? i was doing my mock PA2 and my checkstyle didn't flag anything, but codecrunch said '1' in my one() method and '0' in my zero() method are magic numbers. but so far i thought i've used 0 and 1 before without getting this checkstyle error?

**Comment by tarshalim** [comment]
i think if you write 0 and 1 in your code, its a magic number, unless you define it as a static attribute but the question doesnt allow that

**Comment by nhptrangg** [comment]
You are getting the error because the goal of the mock prac is to make natural numbers ourselves (numbers like 0 and 1) So using 0 and 1 defeats the purpose of the whole assignment.

**Comment by oneday578** [comment]
I think it's just for this mock PA :( . zero() was defined for us in level 1.

**Comment by meowmeowpeepee** [comment]
dn to worry about magic numbers for the actual PA though!

**Comment by starryfieldz** [comment]
I think it depends on the context and restrictions of the question. The main purpose of the Mock PA is to restrict the usages of 0s and 1s or natural numbers in general, whereas for example the Project does not detect 0 and 1 as magic numbers
