### ISSUE TITLE
Ex 2 Level 3

### ISSUE THREAD

**Issue by oneday578** [nus-cs2030/2324-s2#622]
Hi, I'm a little confused about how the lazy evaluation will be carried out for Level 3 of Ex 2. Does this level expect me to edit the rest of the code as well? The issue i'm facing is that the beep will still be printed, which means it isnt a lazy evaluation. Thank you! :)

Test case:
jshell> Str.of(() -> { System.out.print("beep..."); return "$0 ==> ";}).
   ...> join(new Point(1.0, 1.0).toStr())
$.. ==> Str@...

My code:
public static Str of(Supplier<String> supplier) {
    return new Str.of(supplier.get());
}

My output:
beep...$12 ==> Str@4ccabbaa

**Comment by OthnielChang** [comment]
What I did was to create a Str constructor that takes in a supplier and pass in the supplier as a property of the Str object, and apply lazy evaluation in the methods that require it using lambda expressions, (join, map, flatmap etc.) hope this helps!

**Comment by ykwong2002** [comment]
hi! you can refer to lecture 7 slide 9 for an example of how to use supplier to lazily evaluate. then only call the .get() in places where you want it to eagerly evaluate

**Comment by UEr-nAMe** [comment]
hi i think you can try modify your constructor where Str can be initiated using Supplier<String> and modify all other methods accordingly

**Comment by oneday578** [comment]
ooh i got it thank you all :)
