### ISSUE TITLE
Mock PA2 level2 add()

### ISSUE THREAD

**Issue by tarshalim** [nus-cs2030/2324-s2#623]
# Summary
Put a summary of the problem here
my add() keeps returning 0 but im not sure why

## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
my code for add():
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/282e8397-cc31-4e42-b0d8-80a5e4cd81ef)

my output: 
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/2a0d8f4e-9047-4407-a026-47e0f3d55ccf)

**Comment by oneday578** [comment]
Hmm i think seed change to zero() instead could work (i'm not sure tho). i did iterate(this, x+1).limit(xxx.count()) instead haha. It might be easier if you had another Num constructor that takes in an empty optional. Hope this helps.

**Comment by tarshalim** [comment]
thank you it works now! but can i ask the rationale for using zero() instead of one(), because i thought that i have to loop for as many times as Num other? like if the user inputs 3, then i need to succ() 3 times? so 1 to 3?

**Comment by tarshalim** [comment]
oh wait i get it now, its because x -> !x.equals(other) means x < other!
