### ISSUE TITLE
Ungraded Exercise 2 Level 5

### ISSUE THREAD

**Issue by jpowcm** [nus-cs2030/2324-s2#626]
Can anyone help me with this test case? I'm not quite sure what the side effects refer to. thanks!

output:
<img width="969" alt="Screenshot 2024-04-18 at 6 37 18 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156867299/487cff91-0e7c-4b6e-ac36-fe48b81213f1">

My of methods:
<img width="357" alt="Screenshot 2024-04-18 at 6 39 48 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156867299/10da6cc4-2674-41b0-b569-61cb0bd04342">

**Comment by kryst-ll** [comment]
had the same error and for me it was bc of my print method and i had to edit it to use run, not sure if that'll solve it for u too

**Comment by ykwong2002** [comment]
hi! i think it will help if ur print() method is changed to utilise run by taking in a higher order function to print out x.
hope this helps!

**Comment by jpowcm** [comment]
> had the same error and for me it was bc of my print method and i had to edit it to use run, not sure if that'll solve it for u too

hi! not sure if this is what you mean but currently my print method already makes use of run :(
<img width="313" alt="Screenshot 2024-04-18 at 8 46 30 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156867299/588feaff-e7fd-4d1d-a5d7-659019722707">

**Comment by jpowcm** [comment]
solved! for others with the same problem, i solved mine by removing any line that starts with System.out.println(..) and changed it to a consumer that accepts the string instead instead.
