### ISSUE TITLE
Mock PA fraction sub

### ISSUE THREAD

**Issue by ErinaTjin** [nus-cs2030/2324-s2#627]
![image](https://github.com/nus-cs2030/2324-s2/assets/157509370/a970d6d0-2be9-4db9-81a4-3e5646543a71)
I think my if statement to check for invalid Num is not right, but I'm not sure what to put instead
![image](https://github.com/nus-cs2030/2324-s2/assets/157509370/20961e20-a287-483d-8078-0c192b6cac0c)

**Comment by Luzimomo** [comment]
I think you need to check the numerator if it is a natural number. Since under Num, opt is an Optional<Integer>. If you just pass it into the Optional<Frac>, both of the opt in the Num in the Frac will have something inside regardless of whether is negative or not.

**Comment by bryanjr09** [comment]
i think you need to check if the calculated fraction's numerator and denominator isValid() and return a fraction with an empty optional if either of them do not have a natural number
