### ISSUE TITLE
PA2 revision and notes help

### ISSUE THREAD

**Issue by dlkw13** [nus-cs2030/2324-s2#630]
anyone has any tips on how to study for PA2 and which topics to focus on, also what would be beneficial to bring along to PA2

**Comment by andong0909** [comment]
Yepp. What I did for PA1 is to print out the past exercises / mockpa to refer to during the exam.

**Comment by nus2030** [comment]
Optionals, Functions, Suppliers, Consumer, Streams. Should look into how you can use the methods that are available.

**Comment by lifrocszh** [comment]
be familiar with the Optionals and java.util.function.* package

**Comment by hadyamanisanto** [comment]
> Yepp. What I did for PA1 is to print out the past exercises / mockpa to refer to during the exam.

Same here.

**Comment by CSnoobCS** [comment]
Print whatever u think u'll need :)

**Comment by hohinnn** [comment]
I think its beneficial to read through the API for supplier, function, consumer, and optionals and be familiar with the methods

**Comment by ccqie233** [comment]
Maybe prepare for lazy evaluation? like the Optionals, Streams, Function, Predicate, Unary / Binary Operators, Consumers and Suppliers

**Comment by timc5nn** [comment]
yea Optionals are important

**Comment by JovanFoo** [comment]
I printed code from previous labs but it didnt help at all! HAHAHA
