### ISSUE TITLE
Mock PA2 Level 5

### ISSUE THREAD

**Issue by tarshalim** [nus-cs2030/2324-s2#634]
# Summary
Put a summary of the problem here
i dont have compilation error but jshell cannot find my Fraction class so im guessing my of() or add() method is wrong? 
## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
error: 
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/3bb20114-89b3-46c7-a3a1-0e0c47b31a7d)

of():
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/808606af-b865-4921-b094-c2806f786652)

add():
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/d4ab2a7f-2201-46ed-9007-056571357155)

**Comment by samuelneo** [comment]
it looks like you didn't open `Num.java` in jshell?

**Comment by tarshalim** [comment]
oh yea thanks for spotting!
