### ISSUE TITLE
Q&A REAL PRACTICAL EXAM 19 APRIL 2024

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#636]
# The last ever Q&A series!

Here's one question that you may have...

# How do you implement `flatMap`?

Well, since you're using the result of the application to pass into another of these `StateM` objects, you can consider this following code:
```
public class Test {
    public static void main(String[] args) {
        StateM<String, String> test = StateM.unit("A");
        Pair<String, String> test2 = test.accept("B");
        String toGo = test2.first();
        StateM<Integer, String> test3 = StateM.unit(toGo.length());
        System.out.println(test3.accept("ESM"));
    }
}
```

Also as a reminder, while the type of output has changed, the value getting accepted remains the same!

**Comment by ZHD1987E** [comment]
Other than that, I'm absolutely roasted for that PA2.

**Comment by CSnoobCS** [comment]
i am more roasted than you!
