### ISSUE TITLE
PA2 Level 5 maxDepth (test case 5_1)

### ISSUE THREAD

**Issue by samuelneo** [nus-cs2030/2324-s2#639]
# Summary
![image](https://github.com/nus-cs2030/2324-s2/assets/24467645/9b0fc1da-ec93-4536-9a28-700b806dfe1f)

## Description 
The main idea behind my depth tracking is:
- if `m == 0`, no recursive call: increment depth by 1, update maxDepth, decrement depth by 2 (this is done instead of just decrementing depth by 1 since this function call may result in the maxDepth increasing if this is the deepest call)
- if `n == 0`, one recursive call: increment depth by 1, update maxDepth
- otherwise, two (one nested within the other) recursive calls: increment depth by 1, update maxDepth

The idea is that I have to record the increase in depth whenever a recursive call is made, and decrement it whenever the function returns without any recursive calls. maxDepth will then be the max value that depth has at any point. However, I'm failing this test case with `ack(4, 0)`, and I'm not sure where I'm going wrong here.

**Comment by chinwn** [comment]
To calculate depth of recursion, you need to increase depth on (recursive) method entry and decrease depth on (recursive) method exit.

**Comment by samuelneo** [comment]
Thank you prof! I've just figured it out, was hoping I didn't have to modify my code too much but seems like it's inevitable, since modifying the state requires another round of `get` and `put` calls before rewrapping the value
