### ISSUE TITLE
PA2 Test Case 3_1

### ISSUE THREAD

**Issue by craezydodo** [nus-cs2030/2324-s2#641]
Hi guys, I have this output, but I am not sure what the extra apply means, is it because I called apply too many times in flatMap?

![Screenshot 2024-04-19 at 10 19 21 PM](https://github.com/nus-cs2030/2324-s2/assets/157350945/e055bb52-b9f9-4b56-a20b-016eaee8a3b2)

**Comment by ArkAzrael** [comment]
Yep too many function calls to flatMap
