### ISSUE TITLE
How come is CodeCrunch complaining that I have `non-private methods`?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#642]
I do NOT know what methods should be made private. I literally do NOT have private helper methods and CodeCrunch is complaining about it!

**Comment by ZHD1987E** [comment]
I did declare Nothing() as private. And I am getting the same error. How?

**Comment by ArkAzrael** [comment]
Only flatMap should be public
Constructors should be protected/private
put get unit inc should be static

**Comment by ZHD1987E** [comment]
@ArkAzrael It's still complaining the same thing...

**Comment by ArkAzrael** [comment]
Did you declare extra methods in Nothing class?

**Comment by ZHD1987E** [comment]
Oh yes: I did delcare a toString(), is that supposed to be private?

**Comment by ArkAzrael** [comment]
You can use lambdas in StateM, it's not an issue

**Comment by ZHD1987E** [comment]
@ArkAzrael Another case of CodeCrunch going cuckoo?

**Comment by ArkAzrael** [comment]
Your accept is the problem. You are not suppsoed to overwrite it. Use the one from AbstractState

**Comment by ZHD1987E** [comment]
Solved: thanks!
