### ISSUE TITLE
NEW Q&A REAL PA2 20 APRIL 2024

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#643]
# After a lot of pain, referencing from ArkAzarel's code (especially for level 5) and frustrating moments with ChatGPT, I finally figured out what is going on. I present to you, the final Q&A in the CS2030 series. Now this pertains to the real PA2, which I myself faced issues.
Alright, you may have these questions:

# I DON'T KNOW WHAT TO DO AT ALL!!!
To put it simply, I kind of agree with you. That means you will have to wait for the walkthrough videos (and the corresponding files) to be uploaded in case you can't do much.

But anyway, calling such monads is like chaining commands upon the acceptance of a value and this can be where things go straight down. Here's an example:

```java
StateM.<Integer, Integer>unit(5).flatMap(s -> StateM.<Integer, Integer>unit(2 + s));
```

What that means is that upon accepting a state (let's say 100), the following things happen:
- You first create a StateM object where the value is 5 and the state is 100
- That StateM object becomes another StateM object where the value is now 7 and the state remains as 100.

So in summary, here's what I think happens for the four function:
- `unit()` just stores the value, ready for you to issue the command to load the state
- `get()` takes out the state, and stores the value AND the state in another StateM object (VERY helpful if you want to modify your state WITHOUT so many `put()` calls.
- `put()` puts your state into a StateM object and ERASES your values!
- `flatMap()` converts your **VALUE** to another StateM object (really?!)
- `accept()` is what it is, issues a command to put that state into the command chain.

# WHAT KIND OF ABDOMINATION IS `flatMap`?!

Thing here is, you are just merely trying to convert the value of one result to another. The type of value being applied remains the same, of course for compatability reasons.

In other words, try to think of this (taken from my rejected #636 Q&A):
```java
public class Test {
    public static void main(String[] args) {
        StateM<String, String> test = StateM.unit("A");
        Pair<String, String> test2 = test.accept("B");
        String toGo = test2.first();
        StateM<Integer, String> test3 = StateM.unit(toGo.length());
        System.out.println(test3.accept("ESM"));
    }
}
```

In any way, if you try to call `accept()` on `test` and `test3` in these examples above, you get the same second value, but different first values!

# WHICH COMES FIRST? CHANGING THE STATE OR THE VALUE?

Actually, due to how things are engineered, you will have to change the state before you attempt to change the value. That is because after setting the new state, your value actually gets erased! To install your value, you will have to call `flatMap` and install the value manually (through the `unit` method). Yes, it is 100% ugly, I get it, I myself see so many flatMaps to the point that I had to let ChatGPT guide the way.

That means when you want to do recursive calls, make sure you update your state BEFORE you start manipulating the values.

# Heard there was commotion regarding #638, what is it about?

1: See @ArkAzrael
2: @ArkAzrael replied:

>Hao Dong, you have to increment the depth before calling because you need to compare whether the new depth exceeds the current maxDepth, that's why you can't only update the state at the end of the recursive call as you suggested, otherwise maxDepth is not correctly compared.
>
>Process is ->
>
>Increment currentDepth on entry
compare currentDepth+1 against maxDepth, update maxDepth if needed
decrement currentDepth on exit
If you combine 1 and 3 as you suggested and not touch the currentDepth at all, you would not be able to compare currentDepth+1 against maxDepth, so maxDepth will be inaccurate

# What exactly is a `Nothing`?

Simply put, it's just an empty class. Nothing happens to it.

# I have too many `apply` (especially for levels 4 and to some extent level 5)

That means you are using `flatMap` too liberally. I myself can't figure out what to do as well :/

# Still lost?

I have one thing to tell you:
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/2e7bab89-61af-4721-9a0a-c702d2373cee)
Use this. Trust me on that. Keep prompting it.

Alternatively, wait for the solution to appear this Wednesday. Then copying galore.

Still, I myself feel the difficulty of this PA2, reminds me of this:

![FightGIF (2)](https://github.com/nus-cs2030/2324-s2/assets/140680858/4624bd16-977c-4d85-b016-68660293674b)

**Comment by ArkAzrael** [comment]
Just to add on, as with prof's hint you need to update the state BEFORE and AFTER the recursive calls.

So what does this mean? 
flatMap/put to update the state, then flatMap to call the recursive method then flatMap/put to update the state again and then flatMap to return the actual StateM object.

Whoever can come up with this during the PA is unreal.

**Comment by ZHD1987E** [comment]
@ArkAzrael 

It's the same as doing nothing to the state AT ALL. So what I do is I just update the state for the last case.

**Comment by samuelneo** [comment]
> It's the same as doing nothing to the state AT ALL. So what I do is I just update the state for the last case.

can you elaborate? you mean you've done the depth tracking without having to update both before and after the recursive calls?

**Comment by ZHD1987E** [comment]
Yep.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by samuelneo** [comment]
so if the input is `ack(1, 0)`, how is your depth updated? it never reaches the last case, but the maxDepth is supposed to be 2

**Comment by ZHD1987E** [comment]
Nvm then, guess I’m still stuck. Will edit the Q&A in due course.

I can’t really seem to finish level 4 and level 5 to be honest…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ArkAzrael** [comment]
Hao Dong, you have to increment the depth before calling because you need to compare whether the new depth exceeds the current maxDepth, that's why you can't only update the state at the end of the recursive call as you suggested, otherwise maxDepth is not correctly compared.

Process is ->
1) Increment currentDepth on entry
2) compare currentDepth against maxDepth, update maxDepth if needed
3) decrement currentDepth on exit

If you combine 1 and 3 as you suggested and not touch the currentDepth at all, you would not be able to compare currentDepth+1 against maxDepth, so maxDepth will be inaccurate

**Comment by CSnoobCS** [comment]
I am just waiting for the walkthrough video now.

**Comment by ZHD1987E** [comment]
# UPDATE: They mounted the walkthrough video.
All the best in fixing your code!
