### ISSUE TITLE
PA2 level4

### ISSUE THREAD

**Issue by JovanFoo** [nus-cs2030/2324-s2#644]
![Screenshot 2024-04-20 at 1 00 36 AM](https://github.com/nus-cs2030/2324-s2/assets/133492195/b3a4c668-6723-45c3-b49c-0c4a79f1d4b5)
![Screenshot 2024-04-20 at 1 01 29 AM](https://github.com/nus-cs2030/2324-s2/assets/133492195/9ef39fae-e1a3-4552-82fa-7ba6f367a5f0)

Anyone knows how to do the inc() method?
I am not sure what to return for this, because if i were to return 

new StateM<Nothing, Integer>

i will get an error because the constructor for StateM is private

**Comment by ArkAzrael** [comment]
you can make constructors protected

**Comment by TongZhengHong** [comment]
The increment function only deals with the state S, and hence you can simply use `get` and `put` methods to manipulate its state value. Recall that `get` accesses the state value and `put` allows you to modify the state value. 

In fact, there is a hint in the examples of level 3 `flatMap`:
```java
jshell> StateM<Integer, Integer> bar(StateM<String, Integer> sm) {
   ...>     return sm.flatMap(x -> StateM.<Integer>get()
   ...>         .flatMap(y -> StateM.<Integer>put(y + 10))
   ...>         .flatMap(z -> StateM.<Integer, Integer>unit(x.length())));
   ...> }
|  modified method bar(StateM<String, Integer>)

jshell> bar(StateM.<String, Integer>unit("init")).accept(1)
$.. ==> (4, 11)
```
Here you can see that `StateM.<Integer>get().flatMap(y -> StateM.<Integer>put(y + 10))` is basically incrementing the value from `accept` by 10, so you can do the same for `inc()`

**Comment by JovanFoo** [comment]
> you can make constructors protected, otherwise you can do return StateM.get().flatMap(y -> StateM.put (y+1))

Thank you for the hint! it did work!

**Comment by JovanFoo** [comment]
> The increment function only deals with the state S, and hence you can simply use `get` and `put` methods to manipulate its state value. Recall that `get` accesses the state value and `put` allows you to modify the state value.
> 
> In fact, there is a hint in the examples of level 3 `flatMap`:
> 
> ```java
> jshell> StateM<Integer, Integer> bar(StateM<String, Integer> sm) {
>    ...>     return sm.flatMap(x -> StateM.<Integer>get()
>    ...>         .flatMap(y -> StateM.<Integer>put(y + 10))
>    ...>         .flatMap(z -> StateM.<Integer, Integer>unit(x.length())));
>    ...> }
> |  modified method bar(StateM<String, Integer>)
> 
> jshell> bar(StateM.<String, Integer>unit("init")).accept(1)
> $.. ==> (4, 11)
> ```
> 
> Here you can see that `StateM.<Integer>get().flatMap(y -> StateM.<Integer>put(y + 10))` is basically incrementing the value from `accept` by 10, so you can do the same for `inc()`

Thank you for the hint! you are right, i need to use get, flatmap and put!
