### ISSUE TITLE
PA2 FuncStat

### ISSUE THREAD

**Issue by wkleow123** [nus-cs2030/2324-s2#645]
Hi, anyone has any clue on how to write the FuncStat class? I cant wrap my head around how to make a custom state within it and then to increment the values within it.

**Comment by ZHD1987E** [comment]
I did it this way:

- Upon initialisation of that class, the count and depth is zero.
- Each time you try to update the state, you create factory methods to increment either the count OR the depth.

**Comment by samuelneo** [comment]
I had three instance properties: count, depth, and maxDepth
