### ISSUE TITLE
Failure at the 12th test case

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#646]
Hi everyone, these are some screenshots of what I got wrong for that test case. Has anyone encountered the same situations like this before in your project?
I believe that my direction is probably correct, yet I suspect that I compared two double values wrongly (as I use "<" instead of some threshold - I don't know how to apply that in case of a "smaller comparison") when I tried to find the best self-checkout counter for the customer to serve. Does anyone know how to resolve that? I would appreciate all your helps!
![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/9067aeec-13c4-4ab3-9854-5856f0a300ad)
![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/c0ad9717-b7ca-481d-b4d8-68bce306e649)

**Comment by W-WJ-Ryan** [comment]
it is a bit hard to see exactly what is the problem as there are some missing outputs, but I believe based on what i see and experienced for myself, it could be either 1 of 2 things:
1) You are calling serve event and getting service times in the wrong order from the supplier, hence the diff start end times and maybe even service times
2) Your queue mechanism does not update correctly; hence you have the wrong customers leaving and staying 

if what you say about your finding the best self check out is the case then you might want to see what could be the issue with that. could consider using a comparable or even just the in build equals to find the self check out. All the best

**Comment by frdyli** [comment]
I think I have the same error before, I am not sure it is due to the same error, but you can try:

1. ensure that you get the most updated server for your method that execute the event 
2. this is done by ensuring you retrieve your server from the serverlist that get constantly updated after each execution 
3. also check the sequence of your code, ensuring that you update your server

**Comment by kaiju10** [comment]
helloo, i have the same exact error, which I have made in #686 . The issue doesnt solve the sorting error, but it can be how you create the event time for the next Event for counters. For me, I passed on the event time for the FIRST counter, instead I should pass on the event time for the EARLIEST counter. Maybe you can try this and see if it helps

**Comment by minhkiwi14** [comment]
By the way, I managed to solve that issue. It is due to my incorrect update of the queue in the list of self-checkout counters, not due to the comparison of the `double` values. But thank you for all your inputs!
