### ISSUE TITLE
PA2 Level 5

### ISSUE THREAD

**Issue by SmellyCat223** [nus-cs2030/2324-s2#647]
# Summary
My maxDepth is calculated wrongly and I'm not sure how to fix this.

## Description 
My FuncStat has 2 methods, one to increase count and another to increase maxDepth, each by 1. But it seems like maxDepth is increased every time ack is called instead of reflecting the maximum depth of recursion. Does anyone know how to fix this?

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/163517405/1ce47c37-711d-457b-bece-4be68bd04c86)

**Comment by samuelneo** [comment]
depth should be incremented before a recursive call and decremented after a recursive call. maxDepth will be the max value that depth has at any point

**Comment by SmellyCat223** [comment]
ahh okay i will try that. thanks!

**Comment by MoeySeanJean** [comment]
I got the same issue because of flatMap carrying over the FuncStat from the recursive call, making the depth adding together at the end. You might need to remove this effect by doing accept on recursive call.

**Comment by samuelneo** [comment]
for my solution, I didn't have any accepts in level5. I did have a lot of flatMaps though, and two rounds of get/put to modify depth for the cases with recursive calls

**Comment by BZAStudent** [comment]
Hello did you find out whats your issue?

**Comment by SmellyCat223** [comment]
Thank you for the suggestions! I am still stuck at level 5 but now my maxDepth seems to be lesser than the correct maxDepth by 1. For the 2 recursive cases, i increase current depth by 1 before recursive call and update max depth, then after that i decrease current depth by 1. For the first case i don't increase max depth but i update it.
![Screenshot 2024-04-21 155245](https://github.com/nus-cs2030/2324-s2/assets/163517405/04e687ae-20a9-4591-87f2-40c9cb8f9ed7)
![image](https://github.com/nus-cs2030/2324-s2/assets/163517405/9cf5cbfb-545a-4c80-b40a-bd34c152706c)

**Comment by samuelneo** [comment]
the first case can possibly increment maxDepth if depth == maxDepth since you have to take into account that function call too
