### ISSUE TITLE
pa2 flatmap

### ISSUE THREAD

**Issue by andrelau123** [nus-cs2030/2324-s2#648]
# Summary
Put a summary of the problem here
how do i implement flatmap where it updates the state while having the value constant. having problems as my flatmap returns a diff type of statem<R,S>.
## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary

**Comment by BZAStudent** [comment]
make use of the accept() method to return urself a Pair. Then use that to gain access to your value(.first()) and state(.second())

**Comment by andrelau123** [comment]
<img width="419" alt="Screenshot 2024-04-20 at 4 16 15 PM" src="https://github.com/nus-cs2030/2324-s2/assets/81068338/fdc23b44-0751-4fa8-a787-e031aae4262e">
im having issues w this line when i need to return the same value when the state is being updated

**Comment by BZAStudent** [comment]
flatMap returns a StateM not a Pair

**Comment by andrelau123** [comment]
<img width="489" alt="Screenshot 2024-04-20 at 6 44 43 PM" src="https://github.com/nus-cs2030/2324-s2/assets/81068338/9006c248-f626-4ad4-a65a-27928b7c8027">

**Comment by ArkAzrael** [comment]
Why do you need a if else block?
Just do
return new StateM<>(s -> { Pair<T, S> initial = f.apply(s); StateM<R, S> newStateM = mappy.apply(initial.first()); return newStateM.accept(initial.second())
