### ISSUE TITLE
PA2 too large maxDepth

### ISSUE THREAD

**Issue by wkleow123** [nus-cs2030/2324-s2#649]
![Screenshot (2626)](https://github.com/nus-cs2030/2324-s2/assets/122266559/1205ccdc-7484-4058-9dce-3a5d6867b852)
Hi, im facing this wrong output where my maxDepth is too large

![Screenshot (2628)](https://github.com/nus-cs2030/2324-s2/assets/122266559/b090e7f9-1517-4b53-886f-49a0309accae)
this is my current ack method and I understand that we should increment depth before a recursive call and decrement depth after a recursive call which i think i have tried to take into account so im not sure why it still gives too large of a maxdepth

![Screenshot (2627)](https://github.com/nus-cs2030/2324-s2/assets/122266559/59c98ad9-0d2d-4b78-964c-84d2462812e8)
this is how the incrementing and decrementing is implemented in my FuncStat

any help with what is wrong with the tracking im doing is greatly appreciated!

**Comment by samuelneo** [comment]
the first case with no recursive call should not have depth incremented, but it can possibly update maxdepth if the current depth is equal to maxDepth

**Comment by wkleow123** [comment]
thanks a lot for the help

**Comment by JovanFoo** [comment]
Hello, dont mind if i ask, my put is returning <Nothing, S> which will then be passed to the next flatmap(...... unit(x)). I am facing this error 

The parameterized method <Integer, FuncStat>unit(Integer) of type StateM.StateM is not applicable for the arguments (Nothing)

wonder if you faced the same error, if so how did you overcome it?
