### ISSUE TITLE
Are we allowed to access the PE nodes outside the lab times?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#65]
Tried it, did not work.

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/262a1e84-793f-40b6-878c-a3eea4225106)

**Comment by zuoshihua** [comment]
If that was possible one could not attend lab sessions and still get full attendance

**Comment by ZHD1987E** [comment]
@zuoshihua True, true...

**Comment by ZHD1987E** [comment]
Learnt the hard way: it is a **BIG FAT NO**
