### ISSUE TITLE
PA2 Level 4 Inc

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#650]
## Description 

I am slightly confused about what is going on, isnt my type S an Integer already?

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/a7df1669-e22d-4321-927d-a75257593c75)

![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/d45500bb-7392-4146-96d9-a1f6e14bfeac)

**Comment by kryst-ll** [comment]
should be `StateM.<Integer>put(...)` instead, the error message is just telling you that you should have 1 type argument only instead of 2

**Comment by weiyangng** [comment]
oh whoops dk how i missed that thank you!
