### ISSUE TITLE
PA2 private methods

### ISSUE THREAD

**Issue by kienanana** [nus-cs2030/2324-s2#654]
sorry guys just wondering which methods you made private in your classes? 

![Screenshot 2024-04-20 at 10 28 10 PM](https://github.com/nus-cs2030/2324-s2/assets/119132853/c21a6dca-fee9-4b72-a14c-d74a0df1154d)

**Comment by ZHD1987E** [comment]
Please see #642.

**Comment by kienanana** [comment]
thanks!
