### ISSUE TITLE
PA2 Level 4 test case 4_1

### ISSUE THREAD

**Issue by hzhitong** [nus-cs2030/2324-s2#655]
![image](https://github.com/nus-cs2030/2324-s2/assets/156508021/65e72d85-56a5-4c57-b1d2-6b78c853dacb)
i get the results for the fib() but then i encounter this error. How do i resolve this? Do I need to use flatmap for my implementation?
![image](https://github.com/nus-cs2030/2324-s2/assets/156508021/3ac89082-1b8b-4d12-9ec6-4d94995aceaa)

**Comment by aNNexh** [comment]
the apply is printed whenever accept method is invoked. flatmap should be used in inc()

**Comment by hzhitong** [comment]
I understand now, thank you so much!
