### ISSUE TITLE
Exercise #6 Incompatible Type Issue

### ISSUE THREAD

**Issue by khooxr** [nus-cs2030/2324-s2#656]
![Screenshot 2024-04-21 014616](https://github.com/nus-cs2030/2324-s2/assets/163562737/c1126acb-aaf1-4bee-b616-c74694bd4ca4)
![Screenshot 2024-04-21 014637](https://github.com/nus-cs2030/2324-s2/assets/163562737/33f6961c-db23-4354-b3e3-c26365468252)
![Screenshot 2024-04-21 014702](https://github.com/nus-cs2030/2324-s2/assets/163562737/36b8fcc6-7f8d-4caa-aef8-2ae4ed1903b7)

I came across this incompatible type issue while doing Level 3 of Exercise 6. It says BusRoutes cannot be converted to CompletableFuture but the findBusServicesBetween method in BusSg returns a BusRoutes object and I used supplyAsync to convert the BusRoutes object into CompletableFuture<BusRoutes> already as shown above so the types should match. Does anyone have any idea what the issue is?

**Comment by ZHD1987E** [comment]
It happens: especially when CodeCrunch has special Main.java scripts.

**Comment by TongZhengHong** [comment]
The `findBusServicesBetween` needs to return `CompletableFuture<BusRoutes>` instead of `BusRoutes`.

**Comment by khooxr** [comment]
> The `collect` method returns a `Map<BusService, CompletableFuture<List<BusStop>>>`  object and hence you cannot call `join`  on it. In fact, I don't think this implementation will pass code crunch since you will be calling `findBusServicesBetween` multiple times and this would result in multiple `join` calls which are restricted. 
> 
> Consider changing the return type of the `findBusServicesBetween` method to `CompletableFuture<BusRoutes>` instead of `BusRoutes`. Within `Main`, combine or compose each returned `CompletableFuture<BusRoutes>` object together into one CF and call `join` once on it. 

Got it! Thanks for your help!
