### ISSUE TITLE
Exercise 6 level 3

### ISSUE THREAD

**Issue by Bryanngu03** [nus-cs2030/2324-s2#658]
Did anyone encounter this?
**Use of multiple joins detected
Grading terminated**

IN the main method i first created a List CompletableFuture of BusRoutes, then convert each of those to List CompletableFuture of String
```
        List<CompletableFuture<String>> cfstring = brlist.stream()
            .map(br -> br.thenCompose(route -> route.description())) 
            // description() returns CompletableFuture<String>
            .collect(
                () -> new ArrayList<>(), // Supplier: creates a new ArrayList
                (list, element) -> list.add(element),
                (list1, list2) -> list1.addAll(list2));

        cfstring.forEach(cf -> System.out.println(cf.join()));
```
Is there any way to solve this issue?
Thanks guys

**Comment by ZHD1987E** [comment]
Did you use `.join()` anywhere else?

**Comment by Bryanngu03** [comment]
Nope, i used .join() only at the cfstring.forEach(cf -> System.out.println(cf.join())) in the Main.java;

**Comment by ZHD1987E** [comment]
That's odd... Try submitting again.

**Comment by Bryanngu03** [comment]
Still have the same issue hmmm
<img width="711" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/138638759/cae96af7-fa89-499a-92dd-f1ddc4744ac8">

**Comment by Bryanngu03** [comment]
or maybe is because i used that in BusRoute; opps

```
    public CompletableFuture<String> description() {
        CompletableFuture<String> result = CompletableFuture
            .completedFuture("Search for: " + this.stop + " <-> " + name + ":\n" + 
            "From " +  this.stop + "\n");

        for (BusService service: services.keySet()) {
            CompletableFuture<List<BusStop>> stops = services.get(service);
            result = result.thenCombine(stops.thenApply(x -> describeService(service, x)
                .join()),(r1, r2) -> r1 + r2);
        }
        return result;
    }
```

**Comment by ZHD1987E** [comment]
@Bryanngu03 Yes, you did. You used two joins()

What I propose is for you to pass the values around in CompletableFutures instead.

**Comment by Bryanngu03** [comment]
Alright Thank you!! will work on it
