### ISSUE TITLE
Local Class and variable capture

### ISSUE THREAD

**Issue by OthnielChang** [nus-cs2030/2324-s2#660]
Hello, can a kind soul explain what a local class and variable capture is for (Slide 14 of Lecture 07)? Why are closures and capturing variables important? Thank you in advance!

**Comment by c-510** [comment]
A local class is a class defined within a block of code, typically within a method. These classes are not visible outside the block where they are defined, making them useful for handling implementation details of a method without exposing them as part of the broader class's public interface. 
Example:
```
class Outer {
    public void performAction() {
        final int x = 100;

        class LocalClass {
            void printX() {
                System.out.println(x); // Accesses the final variable 'x' from the enclosing method
            }
        }

        LocalClass local = new LocalClass();
        local.printX();
    }
}
```

Variable capture refers to the concept where an inner class (this includes local classes, anonymous classes, and lambda expressions) accesses variables from its enclosing scope.
Example:
```
public void doSomething() {
    int a = 10; // Effectively final variable
    new Thread(() -> System.out.println(a)).start(); // 'a' is captured by the lambda
}
```
