### ISSUE TITLE
Yes, you may be worried about the damn hard PA2, the Exercises and the Finals, but here is one thing...

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#662]
You've came that far. Give yourself a clap.

You have done the following throughout this entire course:

- [x] 6 self-practice exercises
- [x] 6 lab sessions
- [x] 1 medium-scale project
- [x] 2 practical examinations
- [x] 2 ungraded exercises (which I got a C and E for) 
Total: 20 exercises in CodeCrunch, plus 11 recitations.

Pretty soon what looms after you for this course is the Final written exam, so I wish you all the best.

Also see #720.

# You after PA2 (including me)

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/bd1f91e1-8a21-4825-8a7b-0d204906817c)

**Comment by ZHD1987E** [comment]
# As a bonus, here's one tip for Exercise 6
Pass CompletableFutures around, use the `thenApply` or `thenCompose` methods and only call .join() at the end.

**Comment by quadryan** [comment]
thanks Hao Dong

**Comment by CSnoobCS** [comment]
Thanks Hao Dong for giving consistant tips on the forum.

**Comment by anqixxxx** [comment]
thanks hao dong!

**Comment by mChewWW** [comment]
nah its over change course

**Comment by dingus891** [comment]
bruh

**Comment by yushanedi** [comment]
Thank you Hao Dong for your service!

**Comment by zenlxy** [comment]
thank you!

**Comment by jianhaosoh** [comment]
thanks hao dong

**Comment by yeeejieee** [comment]
thank u brother

**Comment by ezclap02** [comment]
thank you Hao Dong!

**Comment by HQ2100** [comment]
thank you bro!

**Comment by tianyiiiiiii** [comment]
Thank you Haodong!

**Comment by itsokkk** [comment]
Thank you Hao Dong. Your tips have been extremely helpful for my revision.

**Comment by tzs69** [comment]
Thank you ZHD1987E😍😍

**Comment by frdyli** [comment]
thank you!

**Comment by JovanFoo** [comment]
thanks hao dong

**Comment by HoSCD** [comment]
thanks hao dong

**Comment by HoSCD** [comment]
Thanks hao dong

**Comment by IvanSawSQ** [comment]
thank you haodong

**Comment by khooxr** [comment]
thanks so much hao dong!

**Comment by x2qian** [comment]
thank you!! :D

**Comment by bryanjr09** [comment]
Thank you!

**Comment by isaaclim33** [comment]
thank you!

**Comment by Jiahui-liew** [comment]
thank you!!

**Comment by donregan9** [comment]
thanks bro

**Comment by ZHD1987E** [comment]
# Triple bonus

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/55f0d8c1-3203-4457-b876-111d23ccb5e9)

**Comment by joashlim22** [comment]
love u haodong
