### ISSUE TITLE
PA2 Codecrunch error

### ISSUE THREAD

**Issue by c-510** [nus-cs2030/2324-s2#663]
# Summary
What does this error mean on codecrunch?? my code works but Codecrunch keeps failing it because of the error below.

Declaration of additional properties/constants.
Grading terminated.

**Comment by iceflakes12** [comment]
Is this pa2? you are supposed to use attributes inside abstractStateM and not create any attributes in StateM if it is.

**Comment by ZHD1987E** [comment]
You call super() instead.

**Comment by c-510** [comment]
Hi to those commenting, i did not create any attributes in StateM... not sure where else the error might be coming from

**Comment by ZHD1987E** [comment]
Did you write an overriding accept method?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iceflakes12** [comment]
Did you create any constants outside of the requested methods?

**Comment by JovanFoo** [comment]
I think theres a cap to the number of constants that can be declared

**Comment by ZHD1987E** [comment]
...which by the way @JovanFoo, is ZERO.
