### ISSUE TITLE
Fail test case 4_1

### ISSUE THREAD

**Issue by SumitShinde0702** [nus-cs2030/2324-s2#664]
# Summary
Put a summary of the problem here
I am getting this error where the output of 'apply' does not match the required number. 

## Idea s
Describe the approach used (if applicable)
On my end, I tried my code and the fib and fib.accept work with different numbers but for some reason, this test case fails. Anyone knows why? 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://github.com/nus-cs2030/2324-s2/assets/94443578/8645a318-6d02-41c9-9521-4e200d43c89d)

**Comment by iceflakes12** [comment]
inc is not concise enough. you are calling more flatMaps/accepts than needed. I think try to avoid repetitive/useless code while also not trying to destroy the similarity thing too much

**Comment by aNNexh** [comment]
apply print statement is inserted in the accept method of abstractStateM. you should use flatmap in inc(), assuming it calls accept twice.

**Comment by Bryanng41** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/52643493/dc2fd52d-3895-4cd1-b78d-393af846151a)
Hi sorry I'm facing the same problem here is my inc() it works in Jshell but I face the same problem in codecrunch

**Comment by SumitShinde0702** [comment]
> you can share your inc() method for us to help

![image](https://github.com/nus-cs2030/2324-s2/assets/94443578/f3a4d323-ed21-4e2d-8c12-33a820e4c5bf)

**Comment by SumitShinde0702** [comment]
okay thanks guys, flatmap using get() and put() works. 

.get() then flatmap then finally put

**Comment by SumitShinde0702** [comment]
okay thanks guys, flatmap using get() and put() works.

.get() then flatmap then finally put
