### ISSUE TITLE
To all those complaining about the project...

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#665]
# Here's one thing you can do:

Attach breakpoints/logpoints. This means you can check if your script is functioning properly (e.g. the availability time is updated correctly, the events in the PriorityQueue are queued correctly)

**Comment by ZHD1987E** [comment]
As a bonus, here is my `README.md` file.

---

# CS2030 Discrete Event Simulation System


Welcome to the landing page! This is part of the Discrete Event Simulator project that all students taking **CS2030** [Programming Methodology II] will have to undertake.

## Change-logs:

### VERSION 1

1.0 - Intial version, based off the original code which is written without *Object-Oriented Programming*. **(The `OldMain.java` file was since removed)**

This has 4 classes:

- Main: The driver class that instatinates a simulation

- Simulation: The class that simulates customers arriving, and making decisions on which server to take (or leave)

- Customer: The class that simulates a customer's behaviour; it announces its actions

- Server: The class that simulates a server and has a time it is available.


1.1 - The customer decision-making mechanism now is within the Customer class instead of the Simulation.

1.2 - The customer now updates the server instead of the simulation doing so.

### VERSION 2

2.0 - A queue mechanism through an 'Priority Queue' data structure is created, and operates in the following way:

- The earliest events get returned
- Should there be similar events, then those with a smaller customer ID (as they arrived earlier) will get returned
- If the customer number is the same, the order in which the events are returned are as follows:
  1: Being done with serving
  2: Arriving and waiting to be served
  3: Being served by a server
  4: Having to leave as all servers are full

>Previousy, a queue of 'dones' were implemented which was **VERY** unstable as it fails to consider **ALL** event types: this has since been fixed as the code was reset to Version 1.2 and redone following the full details of the requirements which required logging of ALL events. Now, the events are logged on the fly when the simulation (the logic is retained)  in run, and are returned in order for the output.

### VERSION 3

>This is a massive revision, this time treating all occurances as Events, with `Simulator` now only storing the server state and dynamically managing the events as it go along. Welcome to the event based simulator (EBS), now with dynamic scheduling driven by a priority queue!
>
> Now, 4 event classes are created based on what happens in this simulation:
>
> 1: An arriving customer will check for any available servers.
> 
> 2A: If there are no servers available, then it will leave.
>
> 2B: Otherwise, it accepts a server.
>
> 3: Once the services of the server is done, then it leaves.
>
> This now allows scheduling of various types of events in the simulation!

3.0 - Converted verison 2 which was VERY clunky into a fully Event-Based System.

3.1 - Improved ranking logic due to concerns about customer arrival identitiy being able to mask arrival timings which can be marginal.

3.1.1 - Updated the comparator for better event comparison, and to better handle cases where customers may arrive near instataneous (e.g. within 0.0001 or even 0.00001 seconds!)

3.2 - Added Queuing functionality through a hidden 'QueueMoreEvent' that will keep quiet. Both of these events will check if servers are available for them. If not, then it will call 'QueueMoreEvent' and would otherwise call 'Serve' if an server is available for them.

**This is after a lot of stress, a lot of revisions and deletions, and having to search on GitHub for this.**

### VERSION 4

This last iteraton of the EBS requires the addition of self-checkouts, which handles **very** differently than normal servers. As such, the 'Self-Service' version of the original human-based events have been created specifically to handle such cases.

**How so?**
Unlike a normal server which has one queue for one server, all the self-checkouts share a same common queue. That means for the customer who is unlucky to get queued up, the customer will check which machines are available at the next earliest opportunity, and go to that machine. All others would do the same and find the servers getting occupied, and so have no other choice but to wait further for their turn.

---

Moreover, with the inclusion of rest periods given in an `Supplier`, the original human-based events now pass on said `Supplier` to the time the (human) server is done serving a customer, which will then get the rest time for the server (either blocking the use of the server and forcing a queue or making the customer leave in case the queue if full or there is no way to queue, or continue as normal)

4.0 - Implemented rest periods for (human) servers. Also implemented self-checkouts.

4.1 - Removal of unnecessary classes. Also includes random service timings generator to throw in unpredictability.

4.1.1 - Random service time generator has been removed for simplicity.

What has been removed:
- `QueueMoreEvent` for Servers and Self-Checkouts
- `ServeFromQueueEvent` for Servers and Self-Checkouts

---
©️ ZHD1987E, 2024

`ImList.java`, `Pair.java` and `PQ.java`:
© CS2030, National University of Singapore, 2024. Used with permission.

> If you find any issues, please raise them to the developers (ZHD1987E) as soon as possible. Thank you.

**Comment by JovanFoo** [comment]
THank you!

**Comment by khaixuen** [comment]
thank you for the tips!

**Comment by azzy83** [comment]
THANK YOU!

**Comment by CSnoobCS** [comment]
very insightful.

**Comment by yushanedi** [comment]
Thank you!

**Comment by thebestjiaozi** [comment]
thanks!

**Comment by 763312** [comment]
Thanks Hao Dong!

**Comment by hohinnn** [comment]
thanks Hao Dong!

**Comment by Partillay** [comment]
What does a README.md file mean (I seriously don't know)

**Comment by ZhengJie2001** [comment]
thank you!

**Comment by ZHD1987E** [comment]
@Partillay I mount such files as documentation.

**Comment by frdyli** [comment]
thank you!

**Comment by Gracesong146** [comment]
thank you :D

**Comment by Castelle-code** [comment]
thank you

**Comment by isaaclim33** [comment]
thank you!

**Comment by khooxr** [comment]
thanks for the advice!

**Comment by jaydenntann77** [comment]
thank you so much for your help!
