### ISSUE TITLE
Invalid symbol ? detected.

### ISSUE THREAD

**Issue by xman666888** [nus-cs2030/2324-s2#666]
I only use ? as the  ternary conditional operator, does it allowed?

**Comment by jorized** [comment]
Nope. The PA do not allow the use of ternary operators.

**Comment by TongZhengHong** [comment]
Just use `if else` statements

**Comment by mChewWW** [comment]
not allowed

**Comment by yushanedi** [comment]
> not allowed

Thank you for that comment mChew!

**Comment by mChewWW** [comment]
> > not allowed
> 
> Thank you for that comment mChew!

no problem yushanedi :)

**Comment by pinkhydroflask** [comment]
if else statements can be used instead!

**Comment by xman666888** [comment]
Thanks guys, Ive changed it to if else.
