### ISSUE TITLE
Project Test Case 9_03 (updated)

### ISSUE THREAD

**Issue by kongshiting** [nus-cs2030/2324-s2#668]
This is a cry for help. 

I have issues with passing project test case 9_03.

![image](https://github.com/nus-cs2030/2324-s2/assets/121602217/df64c070-3d2e-4ee9-a5d2-dbcf7e1255c6)

From above, it seems that the issue is in my rest event.

My server is an interface
- HumanServer
- SelfCheckOut

My events include 
Arrive
Leave
Done
- above are standard implementations

Wait
WaitIntermediate
- above are standard implementations. 

PreServe
Serve
- my preserve is an event that triggers serve. this preserve event was created to fix my wait+waitintermediate by checking if the server is available first and returning a serve at the server's available time (solves the issue of wait+waitintermediate happening before rest, so the rest time is considered) 
so far no issues w public test cases
- so the flow is
ARRIVE -> SERVE
ARRIVE -> WAIT -> PRESERVE -> SERVE
ARRIVE -> WAIT -> WAITINTERMEDIATE -> PRESERVE -> SERVE

Preserve.java
import java.util.function.Supplier;

class PreServe extends Event {

    PreServe(double time, Customer customer, Server server, Supplier<Double> serviceTime,
        Supplier<Double> restTime, int qmax, int noOfServers) {
        super(time, customer, server, serviceTime, restTime, qmax, noOfServers);   
    }

    public Pair<Event, ImList<Server>> execute(ImList<Server> serverList) {

        int index = getServer().getServerNumber() - 1;
        Server newServer = serverList.get(index);

        double time = newServer.getAvailTime();
        
        return new Pair<Event, ImList<Server>>(new Serve(time, getCustomer(), newServer, 
                getServiceTime(), getRestTime(), getQmax(), getNoOfServers()), serverList);

    }

}

Serve.java

    Serve(double time, Customer customer, Server server, Supplier<Double> serviceTime,
        Supplier<Double> restTime, int qmax, int noOfServers) {
        super(time, customer, server, serviceTime, restTime, qmax, noOfServers);   
    }

    public Pair<Event, ImList<Server>> execute(ImList<Server> serverList) {
        int index = getServer().getServerNumber() - 1;
        Server newServer = serverList.get(index);
        
        if (getCustomer().getQueueNo() > 0) {
            newServer = newServer.leaveQueue();
        }

        double time = getTime() + getServiceTime().get();
        newServer = newServer.setAvailTime(time);
        serverList = serverList.set(index, newServer);

        return new Pair<Event, ImList<Server>>(new Done(time, getCustomer(), newServer, 
            getServiceTime(), getRestTime(), getQmax(), getNoOfServers()), serverList);
    }

Wait
WaitIntermediate
- above are standard implementationS

Rest
- Rest is always returned after Done

Done.java
    Done(double time, Customer customer, Server server, Supplier<Double> serviceTime,
        Supplier<Double> restTime, int qmax, int noOfServers) {
        super(time, customer, server, serviceTime, restTime, qmax, noOfServers);   
    }

    public Pair<Event, ImList<Server>> execute(ImList<Server> serverList) {
        int index = getServer().getServerNumber() - 1;
        Server newServer = serverList.get(index);

        return new Pair<Event, ImList<Server>>(new Rest(getTime(), getCustomer(), 
            newServer, getServiceTime(), getRestTime(), getQmax(), getNoOfServers()), serverList);
    }
   
Rest.java

    Rest(double time, Customer customer, Server server, Supplier<Double> serviceTime,
        Supplier<Double> restTime, int qmax, int noOfServers) {
        super(time, customer, server, serviceTime, restTime, qmax, noOfServers);
        this.restTime = restTime;   
    }

    public Pair<Event, ImList<Server>> execute(ImList<Server> serverList) {

        int index = getServer().getServerNumber() - 1;
        Server newServer = serverList.get(index).rest(restTime); // call rest() method of servers 

        serverList = serverList.set(index, newServer);

        return new Pair<Event, ImList<Server>>(new Rest(-1, getCustomer(), newServer, 
            getServiceTime(), getRestTime(), getQmax(), getNoOfServers()), serverList);

    }
    
 rest method in HumanServer.java
     public HumanServer rest(Supplier<Double> restTime) {

        double rest = this.availableTime + restTime.get();

        return new HumanServer(this.serverNumber, rest, this.queueNo, this.maxQueue);
    }
    
 rest method in SelfCheckOut.java (returns itself without calling restTime.get())
     public SelfCheckOut rest(Supplier<Double> restTime) {
        return new SelfCheckOut(this.serverNumber, this.getAvailTime(), 
            this.getQueueNo(), this.getMaxQueue());
    }
    
    
 *note: there should be no issues with returning Rest(-1...) as my criteria for adding an event to eventlist is based on it not being -1 (had no issues with Done(-1..) for previous labs etc so Rest event should not be called erroneously)
 
 I have also considered if the issue is with my WaitIntermediate and Wait
 But I have ran through this modified test case
 
 1 0 2 0.5
0.000000
0.313508
1.204910
2.776499
3.876961
3.909737
9.006391
9.043361
9.105379
9.159630

and received this output (which I check with a friend and got the same output)
note: printed additional statements for clarity

0.000 1 arrives
0.000 1 serves by 1
0.314 2 arrives
0.314 2 waits at 1
1.000 1 done serving by 1
Rest 1.0 1
1.000 2 pre-served by 1
1.000 2 serves by 1
1.205 3 arrives
1.205 3 waits at 1
2.000 2 done serving by 1
Rest 2.0 1
2.000 3 pre-served by 1
2.776 4 arrives
2.776 4 waits at 1
3.877 5 arrives
3.877 5 leaves
3.910 6 arrives
3.910 6 leaves
5.139 3 serves by 1
5.139 4 intermediate waits at 1
6.139 3 done serving by 1
Rest 6.138762160491117 1
6.139 4 pre-served by 1
6.987 4 serves by 1
7.987 4 done serving by 1
Rest 7.986566138639537 1
9.006 7 arrives
9.006 7 serves by 1
9.043 8 arrives
9.043 8 waits at 1
9.105 9 arrives
9.105 9 waits at 1
9.160 10 arrives
9.160 10 leaves
10.006 7 done serving by 1
Rest 10.006391 1
10.006 8 pre-served by 1
10.006 9 intermediate waits at 1
10.855 8 serves by 1
10.855 9 pre-served by 1
11.855 8 done serving by 1
Rest 11.855358572937094 1
11.855 9 serves by 1
12.855 9 done serving by 1
Rest 12.855358572937094 1
[1.913 7 3]

Another common issue is updating the server after every event 
in every event I do this
int index = getServer().getServerNumber() - 1;
Server newServer = serverList.get(index)
...
serverList = serverList.set(index, newServer);

I would greatly appreciate any help :')

**Comment by W-WJ-Ryan** [comment]
actually looking at the above test cases i think there could be an issue of you calling the customer service times in the wrong order also. I suspect that it could be an issue with your wait, serve and preserve events. Not too sure why you need an additional preserve event, maybe could be the reason why its calling certain customer service times in the wrong order hence your time might be messed up, can try seeing if you really need that and remove it if you don't
Also maybe might help if you put the rest logic in done since that it should be completed right after the server is done serving. All the best!

**Comment by TongZhengHong** [comment]
Hi, this is a long question, it would be good to format your code with markdown formatting so that it is easier to understand the issue. Surround code keywords in backticks ` and specify Java for the code blocks for syntax highlighting.

**Comment by kongshiting** [comment]
thank you everyone for your help! my preserve event had the correct direction but I was missing the condition that I might need another preserve before returning serve by checking if availtime is more than or equal to the time.
