### ISSUE TITLE
Indentation error in Lab 1

### ISSUE THREAD

**Issue by shaokangster** [nus-cs2030/2324-s2#67]
# Summary

My Code crunch returns the following error message regarding indentation issues, any idea how to go about fixing this? Any help is much appreciated. 

<img width="1347" alt="Screenshot 2024-02-01 at 5 11 01 PM" src="https://github.com/nus-cs2030/2324-s2/assets/142829277/7fbebfc7-2036-4f3c-aa68-27816f661879">

**Comment by samuelneo** [comment]
you should be indenting with [spaces](https://github.com/nus-cs2030/2324-s2/wiki/Java-Style-Guide#cs2030-coding-style), not tabs

if you aren't already, you should also be using CS2030's `.vimrc`, which includes quality-of-life configurations such as automatically converting tabs into spaces when you press `Tab`

to quickly auto-indent your code in vim, press `gg=G` in command mode
