### ISSUE TITLE
PA2 Level 5 Test case

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#671]
Why is my depth wrong for the level 5 test case? 

![Screenshot 2024-04-22 015754](https://github.com/nus-cs2030/2324-s2/assets/111676024/6138fc61-6ee9-471e-a003-8e90972e6532)

![Screenshot 2024-04-22 015746](https://github.com/nus-cs2030/2324-s2/assets/111676024/07da5e5e-20d2-45b4-8f3f-a2d539179213)

**Comment by TongZhengHong** [comment]
Remove the square brackets in the `toString` method of `FuncStat`

Need to see your `FuncStat` implementation to give exact suggestions but you can consider this approach for keeping track of maxDepth: 
Since this entire PA involves keeping track of global variables, you should have a `depth` variable that tracks the **current** depth of a function call. As a result, as prof mentioned in #639:
> To calculate depth of recursion, you need to increase depth on method entry and decrease depth on method exit. This would then help you keep track of the call stack's depth.

However, this `depth` variable only tracks the current recursive function call's current depth. Hence, you need to track the maxDepth as well in `FuncStat` which updates when the current depth is greater than the maxDepth. 

You can consider looking at #649, but you will have to add a simple fix as mentioned by @samuelneo to get everything to work.

**Comment by JosiahPraeman** [comment]
> Remove the square brackets in the `toString` method of `FuncStat`
> 
> Need to see your `FuncStat` implementation to give exact suggestions but you can consider this approach for keeping track of maxDepth: Since this entire PA involves keeping track of global variables, you should have a `depth` variable that tracks the **current** depth of a function call. As a result, as prof mentioned in #639:
> 
> > To calculate depth of recursion, you need to increase depth on method entry and decrease depth on method exit. This would then help you keep track of the call stack's depth.
> 
> However, this `depth` variable only tracks the current recursive function call's current depth. Hence, you need to track the maxDepth as well in `FuncStat` which updates when the current depth is greater than the maxDepth.
> 
> You can consider looking at #649, but you will have to add a simple fix as mentioned by @samuelneo to get everything to work.

My funcstat looks like this.

![Screenshot 2024-04-22 022023](https://github.com/nus-cs2030/2324-s2/assets/111676024/588978a6-5664-4891-a604-07ce2d9fa28a)

**Comment by TongZhengHong** [comment]
Yes, you can consider the approach above. 

Create another variable `depth` in `FuncStat`. You need to increment `depth` on the function entry and then decrement when it exits. So you need to increment first before calling the `ack` method, then apply a decrement after.

So it would be something like: `incrementDepth.flatMap(ack(m-1,1)).decrementDepth`.

**Comment by JosiahPraeman** [comment]
> Yes, you can consider the approach above.
> 
> Create another variable `depth` in `FuncStat`. You need to increment `depth` on the function entry and then decrement when it exits. So you need to increment first before calling the `ack` method, then apply a decrement after.
> 
> So it would be something like: `incrementDepth.flatMap(ack(m-1,1)).decrementDepth`.

where would  incrementDepth.flatMap(ack(m-1,1)).decrementDepth be in the level 5 jshell

**Comment by walkaround54** [comment]
> > Yes, you can consider the approach above.
> > Create another variable `depth` in `FuncStat`. You need to increment `depth` on the function entry and then decrement when it exits. So you need to increment first before calling the `ack` method, then apply a decrement after.
> > So it would be something like: `incrementDepth.flatMap(ack(m-1,1)).decrementDepth`.
> 
> where would incrementDepth.flatMap(ack(m-1,1)).decrementDepth be in the level 5 jshell

This would correspond to the if n==0 case.

You would have to have similar logic for your m==0 case, and m and n > 0 cases. Try doing the m==0 case first.

You are on the right track, just need to decrementDepth after ack(xxx) for each of your cases.
