### ISSUE TITLE
PA2 level 5

### ISSUE THREAD

**Issue by JovanFoo** [nus-cs2030/2324-s2#672]
<img width="673" alt="Screenshot 2024-04-22 at 11 42 37 AM" src="https://github.com/nus-cs2030/2324-s2/assets/133492195/2b25fb06-0c5b-41a7-b9c3-2ed41ec94c13">
<img width="819" alt="Screenshot 2024-04-22 at 11 43 15 AM" src="https://github.com/nus-cs2030/2324-s2/assets/133492195/7c29217a-1f0b-48ba-8466-e09cabf75123">

i have been trying to debug but i cant seem to find the error. anyone can help?

**Comment by walkaround54** [comment]
Hi, you will also need to decrement depth everytime you call ack in your if elses. 

Consider having methods in your FuncStat, incrementDepth, decrementDepth and incrementCall to make the process easier.

You can take a look at #671, and TongZhengHong's comment on "increment depth on the function entry and then decrement when it exits. So you need to increment first before calling the ack method, then apply a decrement after.

So it would be something like: incrementDepth.flatMap(ack(m-1,1)).decrementDepth."

**Comment by JovanFoo** [comment]
> Hi, you will also need to decrement depth everytime you call ack in your if elses.
> 
> Consider having methods in your FuncStat, incrementDepth, decrementDepth and incrementCall to make the process easier.
> 
> You can take a look at #671, and TongZhengHong's comment on "increment depth on the function entry and then decrement when it exits. So you need to increment first before calling the ack method, then apply a decrement after.
> 
> So it would be something like: incrementDepth.flatMap(ack(m-1,1)).decrementDepth."

Hi, thank you for the advice. however, i am constantly getting this error which i am not sure how to overcome. 
<img width="525" alt="Screenshot 2024-04-22 at 12 03 37 PM" src="https://github.com/nus-cs2030/2324-s2/assets/133492195/6cc2962b-d915-4a9c-a88e-179a7f506fa7">
i am only supposed to provide one type which should be FuncStat but theres always this error

**Comment by walkaround54** [comment]
Try declaring types for all your unit and put, i.e

StateM.<Integer, FuncStat>unit(xxx)

For m==0, consider decrementing before mapping unit(n+1). To map your updatedStats, you will have to use get() and put() to update the StateM. 

For n==0 and the else, you can then follow the "increment depth, ack(xxx) and decrement depth" framework. Once again, I think you can look to #671 to understand how this might be implemented.
