### ISSUE TITLE
Exercise 6: Level 2 and beyond Issues

### ISSUE THREAD

**Issue by walkaround54** [nus-cs2030/2324-s2#673]
Hi everyone, I followed Prof Henry's walkthrough for exercise 6. Unfortunately, I am only able to pass level 1 on codecrunch.

![Screenshot 2024-04-22 at 11 37 51 AM](https://github.com/nus-cs2030/2324-s2/assets/137716280/940009d1-61b7-4003-9a49-61a8b8e71d61)

![Screenshot 2024-04-22 at 11 37 59 AM](https://github.com/nus-cs2030/2324-s2/assets/137716280/c83aa7b0-2833-4c65-80a2-8d4a9b2264fa)

My outputs for level 2 do not include the "Search for... From..." lines, and when reading what is required of the level 2 task, it seems Prof has already made the necessary changes in the video. 

Besides what prof has done in his walkthrough, what can I implement/change? I recognise that the "Search for... From" is from the description method in BusRoutes, but it seems to have already been implemented.

![Screenshot 2024-04-22 at 11 42 11 AM](https://github.com/nus-cs2030/2324-s2/assets/137716280/48b9b017-7521-4a96-81ea-693692af4d86)

Any help is greatly appreciated!

**Comment by HQ2100** [comment]
its supposed to be : (res, stops) -> res + describeService(service, stops));
You're missing "res +"

**Comment by walkaround54** [comment]
> its supposed to be : (res, stops) -> res + describeService(service, stops)); You're missing "res +"

Thank you so much!

**Comment by JovanFoo** [comment]
> > its supposed to be : (res, stops) -> res + describeService(service, stops)); You're missing "res +"
> 
> Thank you so much!

hey do you mind sharing your describeService method? i followed prof's walkthrough too and i am facing a similar problem where the part from 'can take ....' onwards is not printing and i am sure the problem is most likely from describeservice.

**Comment by walkaround54** [comment]
> > > its supposed to be : (res, stops) -> res + describeService(service, stops)); You're missing "res +"
> > 
> > 
> > Thank you so much!
> 
> hey do you mind sharing your describeService method? i followed prof's walkthrough too and i am facing a similar problem where the part from 'can take ....' onwards is not printing and i am sure the problem is most likely from describeservice.

![Screenshot 2024-04-23 at 2 00 47 PM](https://github.com/nus-cs2030/2324-s2/assets/137716280/bf0cfb77-f1e4-4658-8e52-ac7a75d99ce6)
Hmm I don't recall changing anything here, might be something else...
