### ISSUE TITLE
Exercise 6 Bus help

### ISSUE THREAD

**Issue by w1nsl** [nus-cs2030/2324-s2#674]
Im not sure how to do the last level. I tried using CompletableFuture.allOf() and I had 
```
List<CompletableFuture<String>> slst = sc.useDelimiter("\n").tokens()
            .map(s -> processQuery(s))
            .map(x -> x.thenCompose(y -> y.description()))
            .collect(Collectors.toList());
        sc.close();
        CompletableFuture<Void> check = CompletableFuture.allOf(
                slst.toArray(new CompletableFuture[0]));
```
but using java.util.stream.Collectors and the toArray is not allowed , any tips?

**Comment by TongZhengHong** [comment]
You can just use `.toList()` directly.

Also, don't use `allOf` as the order of the print statement is dependent on whichever promise finishes first. You should just `reduce` the `List<CompletableFuture<String>>` into a single `<CompletableFuture<String>` using `thenCombine`

**Comment by w1nsl** [comment]
okay thank you
