### ISSUE TITLE
PA2 level 5 testcase 8

### ISSUE THREAD

**Issue by ziyuanchong** [nus-cs2030/2324-s2#675]
<img width="629" alt="Screenshot 2024-04-22 at 11 53 46 AM" src="https://github.com/nus-cs2030/2324-s2/assets/158278997/e9684f20-f53b-4acb-b768-ce89c5f0e714">
<img width="733" alt="Screenshot 2024-04-22 at 12 21 11 PM" src="https://github.com/nus-cs2030/2324-s2/assets/158278997/764cd0e8-61b2-4213-bf5f-53badc0fd328">

i cant seem to get the correct depth even though i have called ack(m,n) before decrementing depth in (n==0) and else.

**Comment by TongZhengHong** [comment]
The `depth` variable only stores the current depth of the current `ack` call. You should have another variable `maxDepth` that store the maximum depth recorded across all the recursive calls. Can take a look at #649 but you will have to add a simple fix as mentioned by @samuelneo to get everything to work.

**Comment by ziyuanchong** [comment]
> The `depth` variable only stores the current depth of the current `ack` call. You should have another variable `maxDepth` that store the maximum depth recorded across all the recursive calls. Can take a look at #649 but you will have to add a simple fix as mentioned by @samuelneo to get everything to work.

Thank you ! solved it
