### ISSUE TITLE
PA2 level 5?

### ISSUE THREAD

**Issue by iceflakes12** [nus-cs2030/2324-s2#676]
To give context, the way I did this question was to start from the StateM returned by the recursive ack calls, so even for the else if part of the code, I cant seem to trace how doing StateM.put("funcstat").flatMap(x -> ack("recursivecall") even works. By the way the terms in quotation are just placeholders.

And then, everyone is doing decrement depth after increment depth, but I completely dont understand the logic behind it. Can someone explain in simple terms why do I need a decrement depth? So far every post seems to be saying to just do it, but I dont even understand why I need an increment depth, much less why I need a decrement depth?

**Comment by iceflakes12** [comment]
For context, this is a snippet of code sent to me by my friend, I have no idea whether it works or not. But can someone explain how do i trace anything here? Especially the line of code within the else if statement, I dont get why it returns the StateM that I want
![image](https://github.com/nus-cs2030/2324-s2/assets/106156502/c51d2bdf-ee4e-45db-87ca-6fd184984041)

**Comment by iceflakes12** [comment]
My understanding is that in the above code snippet when you do x.inc(), x is whatever that has been passed by the accept statement of the test cases given, in the context of the public test cases, its a new FuncStat() which initialises count and maxDepth to 0. Increment calls in this case just makes it a funcstat of (1,1). When I put this funcstat inside a stateM, i get a stateM with functstat of (1,1) as my state, then when you flatMap over, how does flatMap know how to combine the funcstat of (1,1) with the funcstat returned inside the state returned by ack?

**Comment by iceflakes12** [comment]
Nvm I got it the flatMap part already, can someone explain the decrement depth?

**Comment by iceflakes12** [comment]
Nvm solved.

**Comment by TongZhengHong** [comment]
The idea is that you want to use a global variable to track the current depth of the current `ack` method function call. Let's look at a simple example `ack(1, 0)` first:
```
1. ack(1, 0) current depth: 1
└── 2. ack(0, 1) current depth: 2
    └── returns 2
```
When you call line 1, you increment depth by one so you know that function call is of depth 1. When you are in line 2, you increment depth from 1 to 2 so you know that at line 2 you are at depth 2. So why decrement then? You need that when you have the nested `ack` call where there is "branching" of the ack statements. Let's look at a slightly more complicated example `ack(1,1)`
```
1. ack(1, 1) DEPTH 1
├── 2. ack(0, ack(1, 0)) DEPTH 2
│   └── 3. ack(0, 1) DEPTH 3 (returns 2)
└── 4. ack(0, 2) DEPTH 2 (returns 3)
```
At line 4, the only way for `ack(0, 2)` to know that its depth is 2 is if you decrement depth after line 3 `ack(0, 1)`. This is so that if line 4 has any other `ack` method calls, they know what their corresponding depth is. 
```
ack(4,0) DEPTH 1
ack(3,1) DEPTH 2
ack(2, ack(3,0)) DEPTH 3
├── ack(2,1) DEPTH 4
│   ├── ack(1, ack(2,0) DEPTH 5
│   │   └── ack(1,1) DEPTH 6
│   │       ├── ack(0, ack(1,0)) DEPTH 7
│   │       │   └── ack(0,1) DEPTH 8
│   │       └── ack(0,2) DEPTH 7
│   └── ack(1, 3) DEPTH 5
│       ├── ack(0, ack(3, 2)) DEPTH 6
│       │   └── ...
│       └── ... DEPTH 6
└── ... DEPTH 4
```

**Comment by iceflakes12** [comment]
@TongZhengHong Can check if my understanding is correct? The main idea is using depth to capture the current depth of each method, then each time upon incrementing depth, check if there is a need to update maxDepth and update accordingly if need be. Once function exits, decrement depth because im going back up the tree for every ack closure. So depth accurately reflects the current depth that my function is, while maxDepth reflects what is the maximum depth i have come across at this point. And then somewhere along the chain, maxDepth just gets passed all the way up and my final answer will reflect that maxDepth correctly.

**Comment by TongZhengHong** [comment]
yes, you got it :)👍

**Comment by TongZhengHong** [comment]
An explanation for `flatMap` can be found [here](https://github.com/nus-cs2030/2324-s2/issues/679#issuecomment-2068593309).
