### ISSUE TITLE
PA2 DecreDepth doesnt work properly

### ISSUE THREAD

**Issue by yeeejieee** [nus-cs2030/2324-s2#678]
# Summary
## Description 
I get this as an output even though i alredy increased and decreased after every ack 
## Idea s
thanks for the help!
## Screenshots (if any): 
<img width="909" alt="Screenshot 2024-04-22 at 12 41 16 PM" src="https://github.com/nus-cs2030/2324-s2/assets/124174479/5756772f-ff95-4636-be13-4aedf5bfdc41">
<img width="1401" alt="Screenshot 2024-04-22 at 12 43 47 PM" src="https://github.com/nus-cs2030/2324-s2/assets/124174479/d3e73374-9618-498b-bd6f-260fb6fc3886">

**Comment by TongZhengHong** [comment]
Looks like you are on the right track, can take a look at your `FuncStat` implementation?

**Comment by yeeejieee** [comment]
> Looks like you are on the right track, can take a look at your `FuncStat` implementation?
<img width="1010" alt="Screenshot 2024-04-22 at 1 45 41 PM" src="https://github.com/nus-cs2030/2324-s2/assets/124174479/0a21edd1-d8b8-4f9d-bf6b-d2492527d10d">
my funcstat looks like this

**Comment by iceflakes12** [comment]
purpose of decreDepth() should be to negate the shorter side of the tree. subtracting by 1 does not negate that side of the tree if it branches more than once.
