### ISSUE TITLE
Exercise 02 Level 6 Error when Running Last Line

### ISSUE THREAD

**Issue by AustinKong** [nus-cs2030/2324-s2#68]
# Summary

In exercise 02 level 6, getting an error when running line `shape = solid` in last line of example output.

## Description

When it comes to level 6, everything works fine except for the last line (in the example output), this is pretty confusing. Intuitively, trying to assign a `Solid` to a `Shape3D` shouldn't work as they are both interfaces. After trying to run the code, it doesn't work, as expected, and throws the error:

```
Error:
incompatible types: Solid cannot be converted to Shape3D
```

However, in the example output given, the assignment works without error. Anyone know why it is so?

Step-by-step analysis of each assignment given in "Code Snippets" below.

## Code Snippets

```java
SolidCuboid solidcuboid = new SolidCuboid(2.0, 2.0, 2.0, 0.5);

// Works because SolidCuboid extends Cuboid
Cuboid cuboid = solidcuboid;

// Works because SolidCuboid extends Cuboid, which implements Shape3D
Shape3D shape = solidcuboid;

// Works because SolidCuboid implements Solid
Solid solid = solidcuboid;

// Works because Cuboid implements Shape3D
shape = cuboid;

// Actual problematic line, Solid and Shape3D are both interfaces, they neither implement nor extend each other
shape = solid;
```

**Comment by samuelneo** [comment]
> they neither implement nor extend each other

you might want to reconsider that, interfaces can extend from other interfaces :)

**Comment by AustinKong** [comment]
> > they neither implement nor extend each other
> 
> you might want to reconsider that, interfaces can extend from other interfaces :)

Okay it works now, I didn't consider extending interfaces. Thanks for the quick reply!
