### ISSUE TITLE
Ex6 Lvl 3 Nosuchelementexception

### ISSUE THREAD

**Issue by fermentedgrapewater** [nus-cs2030/2324-s2#680]
![Screenshot 2024-04-22 140354](https://github.com/nus-cs2030/2324-s2/assets/126336985/59488a36-f604-40b2-bcfd-ff66899ac238)
hii I got this error while trying to test this level3 case, was wondering if anyone can tell where this error could have originated from?
$ cat test.in
17009 NUS
17009 MRT
15131 Stn
 The other cases at least available on the question worked fine for me, thanks!

**Comment by TongZhengHong** [comment]
Hi, please show code in Main since the error is coming from Scanner

**Comment by fermentedgrapewater** [comment]
> Hi, please show code in Main since the error is coming from Scanner

![Screenshot 2024-04-22 150823](https://github.com/nus-cs2030/2324-s2/assets/126336985/d1da5778-3a7e-465e-a14b-5a80ab10ab82)
Thanks!

**Comment by jeslynzhou** [comment]
hiii may I know how u manage to solve this issue? I m facing the same issue now...

**Comment by fermentedgrapewater** [comment]
> hiii may I know how u manage to solve this issue? I m facing the same issue now...

hii i honestly don’t know why this happened the first time i ran it the code above is correct though, I just closed it and ran it again a few hours later and it suddenly worked ahh

**Comment by jeslynzhou** [comment]
> > hiii may I know how u manage to solve this issue? I m facing the same issue now...
> 
> hii i honestly don’t know why this happened the first time i ran it the code above is correct though, I just closed it and ran it again a few hours later and it suddenly worked ahh

hahahahaha ok!!! thanksss! hope my code will work tmr HAHAHA
