### ISSUE TITLE
COMPILATION ERRORS

### ISSUE THREAD

**Issue by Bryanng41** [nus-cs2030/2324-s2#681]
# Summary
I encountered a Declaration of additional properties/constants error. Does anyone know 
what properties or constants are not allowed?

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/52643493/8fb608bd-1632-4548-b01d-ba50ac26ebd2)

**Comment by tianyiiiiiii** [comment]
Hi are you referring to the project?

**Comment by HQ2100** [comment]
Check if you delcared any constants.
Like for example : private static final int ONE = 1;

**Comment by 763312** [comment]
Hello! Is this for PA2? I think you can't declare any instances properties/constants in StateM!

**Comment by hohinnn** [comment]
If its for PA2 they said you can't declare any instance properties/constants in StateM

**Comment by ZHD1987E** [comment]
If you need to store properties, try calling `super()`.

**Comment by c-510** [comment]
If this is for the project, dont declare any magic numbers! not sure why they banned that but that might be the issue

**Comment by Bryanng41** [comment]
Sorry I forgot to mention that this is regarding the PA2 

I have attached an image of my StateM code is there anything that should be declared private?
![image](https://github.com/nus-cs2030/2324-s2/assets/52643493/4d3bb380-b61e-4123-b03a-553a713ed15b)

**Comment by hzhitong** [comment]
Hi! I faced this issue just now and my mistake was that my FuncStat class was written in my level5.jsh file instead of creating a FuncStat.java file. The error is resolved when i moved my FuncStat code from level5.jsh to a new FuncStat.java file!

**Comment by Bryanng41** [comment]
> Hi! I faced this issue just now and my mistake was that my FuncStat class was written in my level5.jsh file instead of creating a FuncStat.java file. The error is resolved when i moved my FuncStat code from level5.jsh to a new FuncStat.java file!

OMG you were right thank you everyone for your help <3
