### ISSUE TITLE
PA2 level 2

### ISSUE THREAD

**Issue by ezclap02** [nus-cs2030/2324-s2#682]
hi why do i get the error on line 10?  im trying to implement get(). below is the error message and my code

![image](https://github.com/nus-cs2030/2324-s2/assets/111750139/49579fa0-f264-4a19-9813-e13aec2abd6f)
![image](https://github.com/nus-cs2030/2324-s2/assets/111750139/a5d2a696-91ff-4cbd-bec5-78f14edfb0f2)

**Comment by tianyiiiiiii** [comment]
Hi ezclap, you can try returning a new StateM?

**Comment by ZHD1987E** [comment]
You might want to read #643 to see what `get()` really does...

**Comment by iceflakes12** [comment]
can you remove that constructor completely? believe that solves your problem

**Comment by ZHD1987E** [comment]
finals is over you can close this issue
