### ISSUE TITLE
Exercise 6 Level 0

### ISSUE THREAD

**Issue by zwz1707** [nus-cs2030/2324-s2#683]
# Summary

Hi, I followed the instructions by modifying the BusAPI and Main.java (screenshot 1). I run java Main several times but the output of bus stops of service 96 still always comes after service 95, like the synchronous way. 
The instructions say that you will notice that the output of bus stops of service 96 may come before those of service 95, or vice-versa. 
I tried running program by removing the join statements and it now works asynchronously without the join statements (screenshot 2)
But since the Main method given has the join statements, I am confused about what is the correct Main method to use.

## Screenshots 
<img width="516" alt="Screenshot 2024-04-22 at 4 13 35 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157106837/861af8b0-78d5-4ec6-aa1f-c1f4baa0aae5">

<img width="508" alt="Screenshot 2024-04-22 at 4 15 31 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157106837/121b46f0-014c-4b8f-95d3-95339ec8671a">

**Comment by ZHD1987E** [comment]
You're only supposed to use one .join()...

**Comment by ZHD1987E** [comment]
Remember to close this issue~
