### ISSUE TITLE
PA2 Non-private methods detected. Grading terminated.

### ISSUE THREAD

**Issue by aNNexh** [nus-cs2030/2324-s2#685]
FuncStat class
private FuncStat(int count, int depth, int maxDepth)
FuncStat()
FuncStat incCount()
FuncStat incDepth()
FuncStat decDepth()
public String toString()

Nothing class
static Nothing nothing()
public String toString()

StateM class
private StateM(Function<S, Pair<T, S>> f)
private StateM(T t)
static <T, S> StateM<T,S> unit(T value)
public String toString()
static <S> StateM<Nothing, S> put(S s)
static <S> StateM<S, S> get()
static StateM<Nothing, FuncStat> incr()
static StateM<Nothing, FuncStat> decreaseDepth()
<U> StateM<U, S> flatMap(Function<T, StateM<U, S>> mapper)

level5
ack(int m, int n)

level4
inc()
fib(int n)

what could be the issue?

**Comment by ZHD1987E** [comment]
```java
static StateM<Nothing, FuncStat> incr()
static StateM<Nothing, FuncStat> decreaseDepth()
```

Is the problem.

**Comment by ZHD1987E** [comment]
Also see #642.

**Comment by aNNexh** [comment]
> ```java
> static StateM<Nothing, FuncStat> incr()
> static StateM<Nothing, FuncStat> decreaseDepth()
> ```
> 
> Is the problem.

you were right! thank you!

**Comment by ZHD1987E** [comment]
You can close the issue now.
