### ISSUE TITLE
Project Test Case 9_11 Event Time not printed in order error

### ISSUE THREAD

**Issue by kaiju10** [nus-cs2030/2324-s2#686]
# Summary
Skip in event times for a small portion.

## Description 
I understand that there are similar issues regarding this, where the `0.862 13 serves by self-check 4` will spawn out of nowhere. I can see that the main issue is because of this jump, serviceTimes and restTimes are not gotten in order, and it will mess up the entire sequence. This is similar to #589 and #408. I have also looked through all suggestions, and it seems that I have already gotten them correct, such as 
1) checking Event Comparator
2) checking if self-checkout counters will scan for the next customer in queue once it is available

Below are the few screenshots of the same issue, and also some test cases that I run by myself. I did not change any codes at all.

## Screenshots (if any): 
The same error
![Screenshot 2024-04-22 160854](https://github.com/nus-cs2030/2324-s2/assets/156638443/f6a7532c-2aa7-4b27-9582-f7f1b053fa60)

Test case example 1 (With human and self check counters)
![Screenshot 2024-04-22 161925](https://github.com/nus-cs2030/2324-s2/assets/156638443/095d1843-de73-4dde-8fd7-108f0fa39ce9)

Test case example 2 (Just self check counters)
![image](https://github.com/nus-cs2030/2324-s2/assets/156638443/f0f21622-a506-4941-b79d-2138ba8ea1cf)

Based on the 2 test case examples, you can observe that:
1) All event times are printed in order
2) Self-checkout counters will get the next customer that is waiting in line **immediately** once it is finished serving the previous customer. 

Hence I am wondering, how is the PQ fails to print event times in order even though the event comparator works in my own test cases. Any help will be greatly appreciated.

**Comment by ZHD1987E** [comment]
Your queue might have an issue.

**Comment by W-WJ-Ryan** [comment]
Speaking from personal experience, it could be likely that the queue of self check outs and human servers do not update properly or that certain events are not created in the correct order as well. Could I ask what is your flow of events (i.e. arrive -> wait -> serve -> done) for different scenarios and also where do you update your queues (i.e. do you add customers to queue in wait and remove in done)? These are personally where i experienced problems with in the past as well. Hope this helpful! All the best

**Comment by c-510** [comment]
perhaps you can check the method/logic u use to update the event queue? I had a similar issue and i had to tweak my simulate method.

**Comment by kaiju10** [comment]
Okay guys, I managed to solve it after going through one entire detailed breakdown of my codes. I think the issue was in the creation of another Wait Event for those that queued in the counter queue. Instead of passing on with the event time of the fastest counter, I pass on with the event time of the first counter. 

Im still not sure how that results in the sorting to fail, but it seems this is the issue. Thank you guys still for giving your inputs @ZHD1987E @W-WJ-Ryan @c-510
