### ISSUE TITLE
PA2 Test Case 4_1

### ISSUE THREAD

**Issue by Durpfish** [nus-cs2030/2324-s2#687]
# Summary
Failing test case 4_1 of PA2

## Description 
Hello, I have passed all the public test cases and seem to have gotten the correct output for the private test cases. However, I ran into this error for a private test case and don't know how to interpret where I went wrong. Would appreciate any ideas/suggestions on what I can do from here on out. Thanks!

## Screenshots (if any): 
<img width="155" alt="pa2help" src="https://github.com/nus-cs2030/2324-s2/assets/123231253/15cbd67f-ad75-40a5-a23e-7e236342d768">

**Comment by yeeejieee** [comment]
did you use any flatmap method for your inc()? could be the reason

**Comment by Durpfish** [comment]
> did you use any flatmap method for your inc()? could be the reason

nopee but i did use a constructor from my StateM class. flatMap was only used in fib

**Comment by ZHD1987E** [comment]
That was why, @Durpfish.

**Comment by hzhitong** [comment]
I had the same issue before, i added flatmap() into inc() and it will help to pass this private test case! I think the prof wants us to use flatMap in our code in level 4

**Comment by Durpfish** [comment]
okie thanks all it was as yall said regarding the flatMap! added it in and i passed that test case :")
