### ISSUE TITLE
PA2 FuncStat Representation

### ISSUE THREAD

**Issue by sarahquan** [nus-cs2030/2324-s2#690]
![Screenshot 2024-04-22 at 10 40 52 PM](https://github.com/nus-cs2030/2324-s2/assets/154739486/ee98ffaf-cc32-4c34-92a9-0a18b96a5607)
![Screenshot 2024-04-22 at 10 41 14 PM](https://github.com/nus-cs2030/2324-s2/assets/154739486/448fdd17-072b-403c-a469-e07c7c7645c7)

Hi on CodeCrunch the string representation for FuncStat is [count = .., maxDepth = ...] , with square brackets, hence I tried to include an additional class in the exam, but in the private test cases, the string representation is without square brackets. Were the square brackets a typo?

**Comment by ZHD1987E** [comment]
@hwkchia please check

**Comment by yeeejieee** [comment]
i think it will work
 without the square brackets
