### ISSUE TITLE
PA2 Level 4_1 test case

### ISSUE THREAD

**Issue by HQ2100** [nus-cs2030/2324-s2#691]
# Summary
Any idea where the problem might be?
Is it the way i crafted Inc() or does it have to do with something else
![image](https://github.com/nus-cs2030/2324-s2/assets/165252843/d1a7f873-2d6a-4c15-aca5-fab080ec35f4)

![image](https://github.com/nus-cs2030/2324-s2/assets/165252843/39ad02ea-7a5c-46f2-9772-b1bc033d6519)

**Comment by tianyiiiiiii** [comment]
you can try using flatMap in your inc representation!

**Comment by HQ2100** [comment]
Owh I GOT IT, Thankss
