### ISSUE TITLE
Project Test Case 9_9

### ISSUE THREAD

**Issue by HoSCD** [nus-cs2030/2324-s2#694]
Hi i am lost as to why this error is happening. (SCC not showing up as self-check after Waiting despite it working when there is no waiting). 

<img width="264" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158131860/51bab812-28ca-4937-84f0-70015af3261a">

**Comment by ezclap02** [comment]
you will have to update your server lists correctly in the wait event. probably you are not updating your server list with SCC in the wait event

**Comment by E0968235** [comment]
your wait event to string method might not have taken into account the SCC

**Comment by W-WJ-Ryan** [comment]
I think that you might have an method in your server which you invoked in waiting which returns a server. Hence, when it is called, it will change the self check out from a self check out to human server, resulting in the error you see. Try checking the server and self check out classes and override the correct methods. All the best!

**Comment by HoSCD** [comment]
> I think that you might have an method in your server which you invoked in waiting which returns a server. Hence, when it is called, it will change the self check out from a self check out to human server, resulting in the error you see. Try checking the server and self check out classes and override the correct methods. All the best!

Thanks this helped me solve the issue!
