### ISSUE TITLE
Declaration of additional properties error

### ISSUE THREAD

**Issue by jianhaosoh** [nus-cs2030/2324-s2#699]
I got this error when submitting to codecrunch and was wondering is it because my nothing class has an attribute declared? I do realise there is no need for this additional declaration but was wondering if I can keep it to not affect the similarity score...

![Screenshot 2024-04-23 at 10 35 13 AM](https://github.com/nus-cs2030/2324-s2/assets/142876316/c1dc3fb3-4db2-451a-9fda-8da5d48ed601)
![Screenshot 2024-04-23 at 10 35 24 AM](https://github.com/nus-cs2030/2324-s2/assets/142876316/3c06f1ef-2c03-465d-af61-9afa36c47830)

**Comment by nus2030** [comment]
Nothing class should not have any properties as it does nothing meaningful other than just creating a dummy type. So if should not have a `this.opt`.

Dont think it's possible to keep it else this error will not be gone
