### ISSUE TITLE
Indentation still considered as compilation errors

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#70]
Hi, can I ask why indentation errors are also counted as compilation errors here? We have never been told about that before.
Would there be any manual review and regrading?

![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/bc18b124-a25b-44fc-b7e6-15b8e35644e5)

**Comment by samuelneo** [comment]
it's not a compilation error, it's CodeCrunch checking that your code follows the [CS2030 style guide](https://github.com/nus-cs2030/2324-s2/wiki/Java-Style-Guide#cs2030-coding-style)

**Comment by minhkiwi14** [comment]
> it's not a compilation error, it's CodeCrunch checking that your code follows the [CS2030 style guide](https://github.com/nus-cs2030/2324-s2/wiki/Java-Style-Guide#cs2030-coding-style)

Yes I know but I don't understand why it is counted as an error which makes the grade remain at F. Like noone has told us this thing.

**Comment by hwkchia** [comment]
Issue expired.
