### ISSUE TITLE
project logic

### ISSUE THREAD

**Issue by citronwhitetea** [nus-cs2030/2324-s2#703]
any tips on how to update server and the servers list without explicit / implicit type checking?

**Comment by tianyiiiiiii** [comment]
you can implement a manager class to handle the server list too

**Comment by joashlim22** [comment]
I let my Server classes do the actual updating of servers itself, but my Events have an abstract method of updateServers, where it calls the servers's updating methods in its implementation

**Comment by citronwhitetea** [comment]
thank you all!!!!
