### ISSUE TITLE
Project Test Case 9_9

### ISSUE THREAD

**Issue by Gracesong146** [nus-cs2030/2324-s2#704]
# Summary
I'm not sure why this has an error

## Screenshots:
<img width="390" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/62082817/12cd4cf5-8c67-4bc7-ad84-6c26dedc4056">

**Comment by meowmeowpeepee** [comment]
u can only queue at the 1st self check out, try setting qmax of remaining to 0

**Comment by zay-nin** [comment]
customers shouldnt be queuing beyond the first self-check! if you alr set qmax to 0, maybe you can check if you are updating everything properly. eg if you are incorrectly deducting q number from your other self-checks, this might cause their queue num to be negative (less than 0) which might be why customers are able to queue there

**Comment by sophielluo** [comment]
adding on to the above, something that i did when i was stuck on this test case was to try testing a case where there are no human servers and only self check out counters. for example, something like:
0 2 2 0 
0.500
0.600
0.700
1.500
1.600
1.700

**Comment by Gracesong146** [comment]
thank you everyone, i was able to pass test case 9_9 thanks to all of yall :D
