### ISSUE TITLE
Exercise 6 Test Case 1 

### ISSUE THREAD

**Issue by jianhaosoh** [nus-cs2030/2324-s2#707]
I am getting this error when I used thenApplyAsync when I modify my getBusStops() and findStopsWith() methods in BusService class. Managed to pass this TC when I make use of thenApply instead. I thought we should use thenApplyAsync since we are supposed to make the program asynchronous. What is the difference between thenApply and thenApplyAsync and when to use which?

<img width="356" alt="Screenshot 2024-04-23 at 3 24 58 PM" src="https://github.com/nus-cs2030/2324-s2/assets/142876316/94a7ca0a-42ca-4599-96b0-b611fad18561">

**Comment by tianyiiiiiii** [comment]
Hi jianhaosoh, theres a walkthrough for the exercise on canvas!

**Comment by NJiHin** [comment]
I think a good rule of thumb is to only use thenApplyAsync when you want to open a new thread and handle it to avoid blocking, and thenApply is used when non-blocking transformations of results within the same thread.

But yes, if you are really stuck, the walkthrough is the first video posted under the videos/Panopto section in canvas from about 5 months ago.
