### ISSUE TITLE
Exercise 6 level 3 (unable to complete query)

### ISSUE THREAD

**Issue by JovanFoo** [nus-cs2030/2324-s2#708]
<img width="1280" alt="Screenshot 2024-04-23 at 3 52 46 PM" src="https://github.com/nus-cs2030/2324-s2/assets/133492195/d912ff2a-c386-4fbf-a5c3-4bd68928967c">
Anyone knows what this means? and how to solve this?

**Comment by ArkAzrael** [comment]
Did you submit your modified Main.java file along with the other 5 files?

**Comment by JovanFoo** [comment]
> Did you submit your modified Main.java file along with the other 5 files? If you followed Prof's walktrhough it works

@ArkAzrael 
Hello, yea i did and i followed the walkthrough but it shows this error. really not sure why

**Comment by hanlinnnnn** [comment]
hi i might be dumb, im also facing this issue, may i know where Prof's walkthrough is?

**Comment by JovanFoo** [comment]
> hi i might be dumb, im also facing this issue, may i know where Prof's walkthrough is?

@hanlinnnnn 
hello u can find it under videos > web lectures > scroll all the way down!

**Comment by CSnoobCS** [comment]
wow thanks! i didnt know there's a walkthrough and spent so much time thinking about how to even do...

**Comment by nus2030** [comment]
@JovanFoo hi can i check how did u manage to solve this error ?
