### ISSUE TITLE
Project Test Case 9_11

### ISSUE THREAD

**Issue by dillonph34** [nus-cs2030/2324-s2#709]
# Summary
Hi does anyone know how I can fix this issue? seems like customer 13 is supposed to be served directly by self-check 4 after it is freed up as it is next in line, but it doesnt recognise that.

Thanks!

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
<img width="647" alt="Screenshot 2024-04-23 at 3 55 24 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156598447/f168c644-d2b1-4691-965a-d69ddbef636d">
<img width="675" alt="Screenshot 2024-04-23 at 4 10 14 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156598447/4561c2ea-c370-4eea-9791-f0beafa1b5d5">
<img width="675" alt="Screenshot 2024-04-23 at 4 10 37 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156598447/27113391-e034-4ce8-98d6-da7688e5a0ac">

**Comment by tianyiiiiiii** [comment]
could it be possibly how you handle the queue for SCCs, ive implemented a manager class to handle 1 list to handle the queue for all the the self check-outs

**Comment by yf-yeoo** [comment]
I ran into a similar issue just now, checking the difference between how you handle wait events for SCCs and normal servers might help!

**Comment by dillonph34** [comment]
Thank you for the suggestions I fixed it!
