### ISSUE TITLE
Lecture 03 Q1

### ISSUE THREAD

**Issue by HoSCD** [nus-cs2030/2324-s2#71]
# Description

Q1: Why does Java not allow multiple inheritance? Think of a situation where an ambiguity arises.

## Your contribution:

The main reason why Java does not allow multiple inheritance is to avoid the diamond inheritance problem which is a common issue in languages ​​that support multiple inheritance. The diamond inheritance problem occurs when a class inherits from two classes with a common ancestor. If both parent classes have methods with the same name, it is difficult to determine which method the derived class should inherit.

for example:
```java
class A {
    void printClass() {
        System.out.println("Class A");
    }
}

class B extends A {
    void printClass() {
        System.out.println("Class B");
    }
}

class C extends A {
    void printClass() {
        System.out.println("Class C");
    }
}

class D extends B, C { 
}
````
If class D was allowed to inherit from both class B and class C and both class B and class C overrides the printClass method from class A, it would cause ambiguity to arise for class D. This is because we have to determine which printClass method class D should inherit.

**Comment by ZHD1987E** [comment]
Agreed, that's how it makes it less frustrating compared to Python, where they have a Method Resolution Order that can get mind-boggling at times.

At least you can implement multiple contracts (as interfaces) and that helps standardise code across these contracts.

**Comment by hwkchia** [comment]
Contribution included in Lecture 03.
