### ISSUE TITLE
Project - Design violation. Too many constants declared.

### ISSUE THREAD

**Issue by Xiang-le** [nus-cs2030/2324-s2#710]
<img width="349" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/101037442/defd5df4-177a-452b-a52b-f919e8244793">

has anyone encountered the same issue? 
im not sure what qualifies as "too many" in this case...

**Comment by minhkiwi14** [comment]
> You are only allowed to define 2 constants. You should also leave out Main.java in your submission files as it contains 3 constants.

Actually I submitted my files containing Main.java but it still works...

**Comment by ZhengJie2001** [comment]
try removing the number of constants that you may not need! yeah i think, we are only allowed to define 2 constants

**Comment by Xiang-le** [comment]
thanks guys, I managed to resolve it

**Comment by EhYongE** [comment]
> thanks guys, I managed to resolve it

Hi Can I ask how you solved the issue? I currently have only two constants declared, but I will still get the error.

**Comment by EhYongE** [comment]
> > thanks guys, I managed to resolve it
> 
> Hi Can I ask how you solved the issue? I currently have only two constants declared, but I will still get the error.

Sorry I'm dumb I found one more constant declared
