### ISSUE TITLE
project grading criteria

### ISSUE THREAD

**Issue by kohweien** [nus-cs2030/2324-s2#711]
# Summary
hi, just curious if anyone used other functional programming concepts (optionals, streams etc) in their project? also, does anyone know how the project will be graded? is it graded based on completion or will the quality of the code be judged (degree of abstraction and encapsulation, number of getters etc)

**Comment by jihyun88888** [comment]
From what I heard, it is not simply completion and the quality of the code matters

**Comment by ArkAzrael** [comment]
From what my TA said, if your project works it will be minimal 13/15, if you violated any concepts like Tell-Don't Ask for example you'll get -1 but won't go below 13.

**Comment by iceflakes12** [comment]
No need but if it makes you feel better I used optionals so ye.

Also think everyone who gets an A in codecrunch will score roughly the same anyway, so no need to keep redoing it over and over again (just do until you happy can alr)

**Comment by naomiiiwu** [comment]
based on my ta they won't mark efficiency but they do mark design so try to adhere to good design practices it shouldn't be bad.

**Comment by W-WJ-Ryan** [comment]
I dont think there is a need to include optionals and streams etc, as that leans more towards the FP side of the course, and the project from what i feel is a display of what you learn in OOP practices, so theoretically just OOP knowledge should be enough to get you through it.

**Comment by Wanft11** [comment]
I didn't use optionals and streams in the project and it works. So I don't think it is necessary to use it. Its simply based on the OOP stuff taught in the lecture.

**Comment by CSnoobCS** [comment]
I heard there is design marks...

**Comment by lim-4158** [comment]
nobody knows the marking scheme for sure, but if you minimally scored A, and you mainly kept to the principles thought i think it is more worthwile to put in more effort to revise for finals, cuz projecct wont be a score differentiator but finals most definitely will, so dont worry too much. if you really are paranoid, can try get your TA to look at your code and give feedback.
