### ISSUE TITLE
Project SCC Global queue

### ISSUE THREAD

**Issue by squgily** [nus-cs2030/2324-s2#712]
Hi everyone, i'm currently failing test case 9_11: 
<img width="602" alt="Screenshot 2024-04-23 at 6 47 49 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157218084/34735325-54f9-4fc7-982f-edb821a60abf">

Think it's most likely a problem with my global queue updating for self checks, here's the code i'm using to update each server in the serverlist for Arrive, Wait and Serve events... Not sure what i'm missing
<img width="666" alt="Screenshot 2024-04-23 at 6 49 24 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157218084/ebf5584c-7259-45ee-a478-052161df6d9e">

Thanks!

**Comment by nicklass8** [comment]
Hi, can I check what does getSelfCheckQ() do?

**Comment by squgily** [comment]
> Hi, can I check what does getSelfCheckQ() do?
hi, it's supposed to check if that server is the one holding the global queue for all self checks. But i'm not sure if that's the way i'm supposed to be coding it either

**Comment by nicklass8** [comment]
Hmmm, not really sure how to make your global queue implementation work but you can consider all SCCs having the same exact queue as each other and each time a customer joins or leaves a SCC queue, you loop through all the SCC queues to update all of them

**Comment by squgily** [comment]
> Hmmm, not really sure how to make your global queue implementation work but you can consider all SCCs having the same exact queue as each other and each time a customer joins or leaves a SCC queue, you loop through all the SCC queues to update all of them

Hmm okay, i'll try it and update the issue if it works. thanks!

**Comment by azzy83** [comment]
Agreed with nicklass8 !

**Comment by iceflakes12** [comment]
> > Hi, can I check what does getSelfCheckQ() do?
> > hi, it's supposed to check if that server is the one holding the global queue for all self checks. But i'm not sure if that's the way i'm supposed to be coding it either

your way of doing this should work, but again it depends on which you think is easier to change to. As for your issue, you second for loop updates your own server with the extracted queue, but does not update the global queue anywhere, you still need an extra method to update that global queue and then pass that global queue back into the server containing that global queue.

**Comment by iceflakes12** [comment]
Again up to you which way you want to commit to, but make sure every queue is updated accurately no matter how many versions you store/where you store it

**Comment by MaverickWongKeJun** [comment]
You can also consider creating another class that extends Servers as a manager of the queue. The list of servers will contain human servers and a Manager server (which stores a list of SCC). Doing it this way will only require you to update the SCC queue once, which I think is easier for queue management

**Comment by dillonph34** [comment]
Hi I had the same issue as yours. You should check your visible Wait event to see if in that Event, you are passing the right timing to the next hidden Wait Event (the earliest amongst SelfChecks, and not the available timing of that one SelfCheck).

I suggest you could also create your own test case of a lot of customers queuing at self check out to see whether the queue is processed correctly.

**Comment by squgily** [comment]
resolved with global queue, thanks all :) I looped through all the servers after making to changes to the queue and updated the SCCs
