### ISSUE TITLE
project 9_11 incorrect output

### ISSUE THREAD

**Issue by zenlxy** [nus-cs2030/2324-s2#713]
# Summary
my code runs on jshell but i've got this incorrect output error on codecrunch, does anyone know how to solve? is this error the same as time limit exceeded error? any help is appreciated, thank you!

## Description 
<img width="392" alt="Screenshot 2024-04-23 at 7 02 13 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157443693/29d79970-754f-44de-8d5f-6c6d012296f3">

**Comment by JovanFoo** [comment]
its either an infinite loop or you are not printing the result

**Comment by W-WJ-Ryan** [comment]
if it is an infinite loop, might want to check either the mechanism of your server times updating or your wait event generating. Likely either one is the issue
