### ISSUE TITLE
PA2 Error: Declaration of additional properties/constants.

### ISSUE THREAD

**Issue by ZhengJie2001** [nus-cs2030/2324-s2#714]
# Summary
hi, does anyone hv any idea what i may have done wrongly?

## Description 
CodeCrunch: Declaration of additional properties/constants.

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/158128400/ddc1414e-eedd-498c-8375-776fe6252d3f)

**Comment by ArkAzrael** [comment]
Nothing should not have any properties declared

**Comment by ZhengJie2001** [comment]
yeahh thanks @ArkAzrael found my error!

**Comment by CSnoobCS** [comment]
Had the same problem here. I thought nothing is the only part that i got correct lol.
