### ISSUE TITLE
Public vs Private Test Cases

### ISSUE THREAD

**Issue by Partillay** [nus-cs2030/2324-s2#715]
# Summary
I went from (Scenario 1) passing public test cases but failing 9_03 to (Scenario 2) failing public test case 4 but passing 9_03 (still failed 9_04 though).

## Description 
For Scenario 1, I updated nextAvailableTime of the server by adding time of event occurred + serviceTime of the customer inside the Serve Event when calling Serve.next().

For Scenario 2, I updated nextAvailableTime of the server by adding time of event occured+ getRestTime inside the Done Event when calling Done.next(). I observed that after the "2.205 3 done serving by 1", server 1 gets updated in the servers' list (I made the simulator print nextAvailableTime for every server after each event), but the nextAvailableTime of server 1 remained as 10.006 after the "10.006 7 done serving by 1" which caused customer 10 to get served immediately after. Does anyone have any idea what happened?

## Screenshots (if any): 
Scenario 1 test case 9_03:
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/772f76ed-d639-45ae-aecc-4815b8182d51)
Scenario 2 public test case 4:
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/aab90721-7e01-4945-9f8a-72831aafa357)
Scenario 2 test case 9_04:
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/b0ab7a34-aeb0-4948-88b1-566d9f264e1d)

**Comment by azzy83** [comment]
From test case line 39 and 40 (for expected output), 14 should be being served by 2, but instead goes to wait at 1. Likely means somewhere early the queuing logic did not perform as expected, so perhaps the problem could lie in how you dequeue

**Comment by Partillay** [comment]
> From test case line 39 and 40 (for expected output), 14 should be being served by 2, but instead goes to wait at 1. Likely means somewhere early the queuing logic did not perform as expected, so perhaps the problem could lie in how you dequeue

I think the issue lies after line 33 cuz it was expected that server 1 should've rested while mine didnt. At the same time, in line 68/69 my server 1 rested though, I think that's the main reason why I was mazed?

**Comment by Shazard07** [comment]
> From test case line 39 and 40 (for expected output), 14 should be being served by 2, but instead goes to wait at 1. Likely means somewhere early the queuing logic did not perform as expected, so perhaps the problem could lie in how you dequeue

yeah same
