### ISSUE TITLE
[Exam] Is a (physical) question paper provided on the table?

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#718]
Hi profs (or anyone else knows), my question is in the title. I have read the announcement and watched last week's revision, but I cannot find any detail about this.

**Comment by LimKaiWei** [comment]
i dont think so, the exam paper should only be on examplify along with a partial copy of java API

**Comment by yolotouch** [comment]
it will be attached as a document in Examplify

**Comment by ZHD1987E** [comment]
As much as the Java API in `.pdf` form sucks (no interactivitiy, I have to scan through the entire API to find what I need to find), that is what they give you on Examplify. So I don't think you will be given hardcopy API documentations.

Of course, if need be, try emailing `hwkchia@comp.nus.edu.sg`

**Comment by CSnoobCS** [comment]
All on examplify if i'm not wrong.

**Comment by NJiHin** [comment]
I doubt they will provide anything physical but I am positive that rough paper and pens are allowed to be brought in to help with planning

**Comment by kongshiting** [comment]
hi! referring to the recorded lecture "CS2030 Lecture on 4/15/2024 (Mon)". at about 1h30min prof henry went through an exam briefing and showed how examplify would work. essentially, the question paper would be a pdf on the right of your screen and you can type your answer in on the left. the Java API will be attached as an exam attachment on examplify and not everything will be inside but prof henry said smth about including what he thinks is necessary for the questions. from this, I don't think there will be a hardcopy question paper on the table.

**Comment by lohkeyyy** [comment]
Nope its not, go to the middle portion of the last lecture, prof goes through his announcement on the final exams and explains the details he has included in the announcement.

**Comment by azzy83** [comment]
No sir, it'll be on examplify !

**Comment by ZHD1987E** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/24e680a5-d98e-467d-9052-201a63973cf2)
OK, I have emailed Henry Chia on this.

**Comment by ZHD1987E** [comment]
@hwkchia got back, there is nothing hard copy provided.

**Comment by ZHD1987E** [comment]
![IMG_8901](https://github.com/nus-cs2030/2324-s2/assets/140680858/5b606bcb-31d4-4bd1-8070-a4aaa8f4ed15)

**Comment by KoalaLyfestyle** [comment]
> As much as the Java API in `.pdf` form sucks (no interactivitiy, I have to scan through the entire API to find what I need to find), that is what they give you on Examplify. So I don't think you will be given hardcopy API documentations.
> 
> Of course, if need be, try emailing [hchia@comp.nus.edu.sg](mailto:hchia@comp.nus.edu.sg)

@ZHD1987E if needed you may download the java API in html format for use offline, since the examination is open book. You can find the link [here](https://www.oracle.com/java/technologies/javase-jdk17-doc-downloads.html).

Once you download the html you can just open it in any browser of choice during the examination without internet connection.

Note: It is a relatively big file though, at 330mb after unzipping.

**Comment by ZHD1987E** [comment]
Huh? I thought it is secure locked down mode?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KoalaLyfestyle** [comment]
Nope, the announcement says EXAMPLIFY-SECURE OPEN-BOOK.

![image](https://github.com/nus-cs2030/2324-s2/assets/146793482/59a8fb02-ffe4-4aa2-b77c-84e4d4cfac27)

**Comment by ZHD1987E** [comment]
Have you even tried the practice assessment?

They COMPLETELY lock down your system. No IDE, no Microsoft Word, no .pdf reader, no Microsoft Edge

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KoalaLyfestyle** [comment]
Oh mann I haven't actually tried the practice one but I thought secure was referring to the internet access haha. My bad.

**Comment by minhkiwi14** [comment]
Thank you guys, I asked Prof. Henry and he indeed said there would be no physical paper.
