### ISSUE TITLE
PA2 inc() method

### ISSUE THREAD

**Issue by nicklass8** [nus-cs2030/2324-s2#719]
## Description 
Can I check what is the problem with my current implementation of inc() as when I tried to open my level4.jsh, it keeps telling me AssertionError

## Screenshots (if any): 
![Screenshot 2024-04-23 at 11 00 02 PM](https://github.com/nus-cs2030/2324-s2/assets/163880002/f287fc6d-d0c4-4956-8c96-75c978667636)

**Comment by Xenonwizard** [comment]
Hi I'm not sure about you but my put does not accept a Function but a T value

**Comment by nicklass8** [comment]
Hi, my put accepts a T value as well but shouldnt function.apply() give me a T value?

**Comment by ArkAzrael** [comment]
Just do 
return StateM.<Integer>get().flatMap(x -> StateM.<Integer>put(x+1));
You don't have to specify a seperaate function above

**Comment by Bonguu01** [comment]
There is no need to have a define a function before you return. eg.You can go ahead with
return StateM.<Integer>get().flatMap(x -> StateM.<Integer>put(x + 1));

**Comment by quadryan** [comment]
If you did include function, youd have to use the generic T instead
