### ISSUE TITLE
It might be VERY painful to type stuff out on Examplify...

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#720]
Watch this and see if you can relate to it! (That's also why I do my CS2040 pseudocode ENTIRELY in English because it would be much easier to type it out)

TL;DR - Examplify should implement a code text editor.

https://github.com/nus-cs2030/2324-s2/assets/140680858/c5260920-5850-4164-a531-a282d445e343

Still, I'm pretty sure @hwkchia would understand that we're working on Examplify, so in essense we should not worry if we paragraph our lines or just creating new lines.

**Comment by ZHD1987E** [comment]
#By the way...

Walkthrough video for PA2 is up. Hope that the video clears up queries. If that did solve your issues, you can consider closing them.

**Comment by samuelneo** [comment]
personally I switch the font to comic sans MS and typing the code feels more fun

**Comment by ZHD1987E** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/750f01a2-14cb-47a8-85cc-e6f71e6bffbe)
heh...

But I like this, it's very grown up:
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/2119116a-d015-4396-9bf5-ee3821a1c106)

bye bye Cascadia Code!!!

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/85652d61-ee10-4b7d-a435-0215f5d11887)

**Comment by CSnoobCS** [comment]
I think my grade would be more painful.

**Comment by ArkAzrael** [comment]
At this point as long as it's not an F I'll take whatever grade I get
