### ISSUE TITLE
Project Test Case 9_03

### ISSUE THREAD

**Issue by andong0909** [nus-cs2030/2324-s2#721]
# Summary
The customers are getting served in wrong ways I don't really understand. :(

## Description 
Please help me explain which part of my code is wrong? Is it how I get my restTime is not correct?
Currently, my restTime is under Server class and i will call for server.getRestTime() to get the rest times.

## Screenshots (if any): 
<img width="453" alt="Screenshot 2024-04-24 at 3 56 20 AM" src="https://github.com/nus-cs2030/2324-s2/assets/157519678/98a9f55d-c5f1-4af4-9792-bff8e7768159">

**Comment by Wanft11** [comment]
Hi, I implemented a separate Rest class (extends Event) and it passed this test case, maybe you can try this?

**Comment by MaverickWongKeJun** [comment]
From the output, it seems that you are not updating the resting time when you finish serving the customer. Perhaps you can consider the process where before servers had to rest, both the events Done and Leave are terminating events (such that you do not have to return a new event after processing this event). However, with the introduction of resting, the event Done is no longer a terminating event as you now have to check if the server needs to rest. Perhaps you could consider an implementation that is somewhat like this
getRestTimes() is a method defined in Server class that returns you a Supplier<Double>
In the case of customer 10 (the issue at hand), the event flow should look something like this
Arrive -> Wait (might have multiple waits) -> Serve -> Done -> Rest (terminating event)
In this event flow, you will not call the .get() on the restTimes supplier until you reach the event Done. In done, you should update the next available time of the server using the restTime generated from the supplier and return an updated server. Hope this helps

**Comment by anqixxxx** [comment]
hello! i had a similar issue last time and it was due to my rest times not being detected properly in my  class; i think it was because my conditions weren't written properly, which resulted in the getRestTimes() not being called properly. not sure if you did the same, but if you did then maybe you can check that part! but otherwise i passed the case by getting restTimes and updated server's nextAvailableTime in my done event and returning that event but with an updated time

**Comment by meowmeowpeepee** [comment]
I might be wrong but based on what they said, server only rests after he done, not after he serves, so my rest came in only in `updateEvent` of Done Event, but maybe you can wait to see if what the others who implemented it in Serve Event says

**Comment by Xiang-le** [comment]
> I might be wrong but based on what they said, server only rests after he done, not after he serves, so my rest came in only in `updateEvent` of Done Event, but maybe you can wait to see if what the others who implemented it in Serve Event says

 I think this comment is correct. I faced the same exact error and my issue was fixed by shifting my call of getRestTime() of the Server into the Done event instead of the last step of the Serve event. So probably different "random" rest times are generated depending on which event you call it from.

**Comment by yishao17** [comment]
I got the same error too! but instead of shifting it into Done event, I moved it to simulate instead (may not be the best) but it was a lot easier because I only called .get() there which helped a lot in terms of designwise . Hope this helps :)

**Comment by kohweien** [comment]
i implemented the rest in my Done event, so when the server first finishes serving, i get the restTimes and use that to create another Done event (with no string output), with the second Done event being the terminating event

**Comment by isaaclim33** [comment]
in done.java, i got the rest time and updated it for the server followed by updating the servers list, then return a new done event which will not be executed again

**Comment by absfsd** [comment]
> i implemented the rest in my Done event, so when the server first finishes serving, i get the restTimes and use that to create another Done event (with no string output), with the second Done event being the terminating event

hi can i ask ur second Done event how do u terminate the event

**Comment by isaaclim33** [comment]
> > i implemented the rest in my Done event, so when the server first finishes serving, i get the restTimes and use that to create another Done event (with no string output), with the second Done event being the terminating event
> 
> hi can i ask ur second Done event how do u terminate the event

i have a isCompleted() method in all my event classes which returns the completion status of the event. in my simulator if event is completed it will not be executed.

when i return the second done event, i will set the completion status to true (by using constructor) to prevent it from being executed again

**Comment by Chrisallan29** [comment]
Hi, just to chime in, i think you should adopt the above tips, if you are still facing some issues, if it helps, my mistake was not updating the serverlist properly in my simulator class for terminating events like leave done etc., perhaps it may be the case for you

**Comment by joshualek09** [comment]
hi, i was stuck at this exact test case and section for a long time too. 

my implementation was that each server has a customerQueue.
when a customer arrives, regardless of wait / serve, the customer is added into the customerQueue.
this means that the 1st customer to be served will be customerQueue[0], and by extension, if the server is resting, then customerQueue[0] will be delayed, since the server's nextServiceTime > customerQueue[0] arriveTime.

consqeuently, those that are waiting will be customerQueue[1] and customerQueue[2], hence my boolean isQueueFull() will return true when customerQueue().size() > qmax (ie. 3 > 2, since customerQueue has 0, 1, 2)

hence, what helped me clear it was when i realised that customerQueue[0] should only be removed from customerQueue AFTER the server has finished resting. So, at my DoneEvent i simply computed the restTime, then updated the nextService and updated the serverList. Once the server has finished resting, then i removed customerQueue[0], ie. the customer that it had js served.

**Comment by kohweien** [comment]
> > i implemented the rest in my Done event, so when the server first finishes serving, i get the restTimes and use that to create another Done event (with no string output), with the second Done event being the terminating event
> 
> hi can i ask ur second Done event how do u terminate the event

hi, it depends on your implementation, basically just terminate it the way you normally terminate Done and Leave. for me, my events return a pair<event, serverlist>, so for the second done event, i reassign this into the constructor for the next event. then in my simulator class, if the next event is the same as the previous event, it is terminated.

**Comment by hohinnn** [comment]
i implemented the rest in my Done event, so when the server first finishes serving, i use restTimes to update my server's next availability!

**Comment by lohkeyyy** [comment]
you can check if your wait event is calling the next serve properly

**Comment by ErinaTjin** [comment]
My mistake was calling getRestTime() in the serve event. Shifting it to DoneEvent solved it!

**Comment by andong0909** [comment]
Thanks guys for the responses! I moved getRestTime() in EventDone at first. But it did not work as expected because I put the getRestTime() as a property of the EventDone, which incurred some error which I'm not sure the reason.. If you experience the same issue, maybe you wanna check with that!
