### ISSUE TITLE
Exercise 6 FileNotFoundException

### ISSUE THREAD

**Issue by nus2030** [nus-cs2030/2324-s2#722]
Hi, I am getting this error for level 3. When I run the same code and compile it in my Mac's terminal it is working fine and prints out the required outputs. Does anyone have a fix for this ?

![Screenshot 2024-04-24 at 11 35 49 AM](https://github.com/nus-cs2030/2324-s2/assets/156705766/89dca9df-f34f-4680-a13d-a307ce69f7fd)

**Comment by NJiHin** [comment]
Did you implement any exception handling in your BusSG file?

If you really are stuck, check the first video on the CS2030 video lectures posted 5 months ago, which is a walkthrough of this excercise. All the best!

**Comment by c-510** [comment]
Did you look at prof's code? He added some stuff to help us better understand the code but it is not meant to be there.
