### ISSUE TITLE
Project Test Case

### ISSUE THREAD

**Issue by starryfieldz** [nus-cs2030/2324-s2#723]
![Screenshot 2024-04-24 at 12 02 52 PM](https://github.com/nus-cs2030/2324-s2/assets/164198764/a4f20246-04d9-4ea1-89e5-d5c25641aff9)

Hi everyone, does anyone faces similar issues like the last few output outputing "done serving by 2.... done serving by 3...." instead of "done serving by self-check 2.... done serving by self-check 3...." when all previous lines output correctly? Thank you in advance!!

**Comment by jennipho** [comment]
What I did was to have an if-else in my toString that checked if the server was a self check or a human server! Maybe you can try it out? But then you need to have a boolean or variable that checks for this as well in your events

**Comment by starryfieldz** [comment]
Yup I did have those parts as well, i check via index to see if it was self-check or human. Similarly, I used index to check in my several events. The only weird thing I obtained from this test case is that my previous lines all output correctly but only last few output is incorrect. Did you use index to check if it was self-check or human, or other boolean statement? Thanks!!

**Comment by Partillay** [comment]
If you happen to let selfcheck be subtype of Server, when updating the server list you needa make sure your RTT of creating updated selfcheck is selfcheck and not server

**Comment by quadryan** [comment]
What @Partillay said is true.
If your implementation was as such, I suggest @Overriding the method previously made in human Server, in SC to create a new SC counter instead. You are quite possibly creating new human servers in place of your SC's that have served when updating your server list.

**Comment by W-WJ-Ryan** [comment]
Yep, from my experience it is also what they said above ^^. Likely when you invoke certain methods in your self check out that updates something, you return a Server instead of SelfCheckOut cause your methods did not override properly. Need to make sure all methods which create a new object return SelfCheckOut and not Server

**Comment by lifrocszh** [comment]
i created separate events like SelfServe and SelfDone, they have selfcheck in their toStrings

**Comment by isaaclim33** [comment]
i have an if-else condition for the toString() method in Done.java to check if it is a human server or self checkout counter

**Comment by starryfieldz** [comment]
Thank you everyone, it really helped me massively. Cheers!
