### ISSUE TITLE
Project Test Case 12

### ISSUE THREAD

**Issue by jwoongg** [nus-cs2030/2324-s2#724]
# Summary
Hi, Im not sure why my server timings are being printed but at the wrong timing(i.e. customer 514) and Im not sure why I am having a self check-out 1. Thanks in advance!
<img width="565" alt="Screenshot 2024-04-24 at 12 11 32 PM" src="https://github.com/nus-cs2030/2324-s2/assets/158253939/f72172d4-2b04-4d23-9a4b-14e105a43ae5">

(My arrival class)
<img width="870" alt="Screenshot 2024-04-24 at 12 16 09 PM" src="https://github.com/nus-cs2030/2324-s2/assets/158253939/82d9c57c-3d0f-49d1-a7d5-bed06f265528">

**Comment by W-WJ-Ryan** [comment]
I think you could be invoking the wrong serviceTimes for each customer because you are creating the Serve events in the wrong order. You could try to look into your Wait chain of events and see where is causing this wrong order of Serve events to be printed

**Comment by iannntsw** [comment]
you could track whether your code is correctly adding and assigning servers in ur simulator class by poll.first and second and from there see where the issue starts/is going wrong. thats how i debugged most of my issues!

**Comment by jwoongg** [comment]
> you could track whether your code is correctly adding and assigning servers in ur simulator class by poll.first and second and from there see where the issue starts/is going wrong. thats how i debugged most of my issues!

hi!what test cases did you use to test

**Comment by iannntsw** [comment]
3 2 3 0.500000
0.0
0.14617563814065818
0.2281918004390985
0.2697347687010419
0.3362781798929442
0.5298293617777683
0.5310527982309206
0.7237937576355621
0.911766835391944
1.1012058189245828
1.2886222487037768
1.3680571171407179
1.4375607229813399
1.4963721293821473
1.5976688548473943
1.620862272453926
1.7749694484697613
1.9069479902084454
1.9382973683224147
2.0139377773866256
2.0418903139673756
2.180879909887874
2.3419254641826166
2.342930499381107
2.4475575305387736
2.596354427786237
2.6247589684294224
2.721104628744542
2.830015590523277
2.9454356427981323

0.000 1 arrives
0.000 1 serves by 1
0.146 2 arrives
0.146 2 serves by 2
0.228 3 arrives
0.228 3 serves by 3
0.270 4 arrives
0.270 4 serves by self-check 4
0.336 5 arrives
0.336 5 serves by self-check 5
0.530 6 arrives
0.530 6 waits at 1
0.531 7 arrives
0.531 7 waits at 1
0.724 8 arrives
0.724 8 waits at 1
0.912 9 arrives
0.912 9 waits at 2
1.000 1 done serving by 1
1.000 6 serves by 1
1.101 10 arrives
1.101 10 waits at 1
1.146 2 done serving by 2
1.228 3 done serving by 3
1.270 4 done serving by self-check 4
1.289 11 arrives
1.289 11 serves by self-check 4
1.336 5 done serving by self-check 5
1.368 12 arrives
1.368 12 serves by self-check 5
1.438 13 arrives
1.438 13 waits at 2
1.496 14 arrives
1.496 14 waits at 2
1.598 15 arrives
1.598 15 waits at 3
1.621 16 arrives
1.621 16 waits at 3
1.775 17 arrives
1.775 17 waits at 3
1.907 18 arrives
1.907 18 waits at self-check 4
1.938 19 arrives
1.938 19 waits at self-check 4
2.000 6 done serving by 1
2.000 7 serves by 1
2.014 20 arrives
2.014 20 waits at 1
2.042 21 arrives
2.042 21 waits at self-check 4
2.076 15 serves by 3
2.181 22 arrives
2.181 22 waits at 3
2.289 11 done serving by self-check 4
2.289 18 serves by self-check 4
2.342 23 arrives
2.342 23 waits at self-check 4
2.343 24 arrives
2.343 24 leaves
2.368 12 done serving by self-check 5
2.368 19 serves by self-check 5
2.448 25 arrives
2.448 25 waits at self-check 4
2.596 26 arrives
2.596 26 leaves
2.625 27 arrives
2.625 27 leaves
2.721 28 arrives
2.721 28 leaves
2.830 29 arrives
2.830 29 leaves
2.945 30 arrives
2.945 30 leaves
3.000 7 done serving by 1
3.076 15 done serving by 3
3.076 16 serves by 3
3.289 18 done serving by self-check 4
3.289 21 serves by self-check 4
3.368 19 done serving by self-check 5
3.368 23 serves by self-check 5
3.849 8 serves by 1
4.076 16 done serving by 3
4.076 17 serves by 3
4.285 9 serves by 2
4.289 21 done serving by self-check 4
4.289 25 serves by self-check 4
4.368 23 done serving by self-check 5
4.849 8 done serving by 1
5.076 17 done serving by 3
5.076 22 serves by 3
5.285 9 done serving by 2
5.285 13 serves by 2
5.289 25 done serving by self-check 4
6.076 22 done serving by 3
6.285 13 done serving by 2
6.285 14 serves by 2
7.285 14 done serving by 2
8.712 10 serves by 1
9.712 10 done serving by 1
9.712 20 serves by 1
10.712 20 done serving by 1
[1.852 24 6]

**Comment by jwoongg** [comment]
Thanks!

> 3 2 3 0.500000 0.0 0.14617563814065818 0.2281918004390985 0.2697347687010419 0.3362781798929442 0.5298293617777683 0.5310527982309206 0.7237937576355621 0.911766835391944 1.1012058189245828 1.2886222487037768 1.3680571171407179 1.4375607229813399 1.4963721293821473 1.5976688548473943 1.620862272453926 1.7749694484697613 1.9069479902084454 1.9382973683224147 2.0139377773866256 2.0418903139673756 2.180879909887874 2.3419254641826166 2.342930499381107 2.4475575305387736 2.596354427786237 2.6247589684294224 2.721104628744542 2.830015590523277 2.9454356427981323
> 
> 0.000 1 arrives 0.000 1 serves by 1 0.146 2 arrives 0.146 2 serves by 2 0.228 3 arrives 0.228 3 serves by 3 0.270 4 arrives 0.270 4 serves by self-check 4 0.336 5 arrives 0.336 5 serves by self-check 5 0.530 6 arrives 0.530 6 waits at 1 0.531 7 arrives 0.531 7 waits at 1 0.724 8 arrives 0.724 8 waits at 1 0.912 9 arrives 0.912 9 waits at 2 1.000 1 done serving by 1 1.000 6 serves by 1 1.101 10 arrives 1.101 10 waits at 1 1.146 2 done serving by 2 1.228 3 done serving by 3 1.270 4 done serving by self-check 4 1.289 11 arrives 1.289 11 serves by self-check 4 1.336 5 done serving by self-check 5 1.368 12 arrives 1.368 12 serves by self-check 5 1.438 13 arrives 1.438 13 waits at 2 1.496 14 arrives 1.496 14 waits at 2 1.598 15 arrives 1.598 15 waits at 3 1.621 16 arrives 1.621 16 waits at 3 1.775 17 arrives 1.775 17 waits at 3 1.907 18 arrives 1.907 18 waits at self-check 4 1.938 19 arrives 1.938 19 waits at self-check 4 2.000 6 done serving by 1 2.000 7 serves by 1 2.014 20 arrives 2.014 20 waits at 1 2.042 21 arrives 2.042 21 waits at self-check 4 2.076 15 serves by 3 2.181 22 arrives 2.181 22 waits at 3 2.289 11 done serving by self-check 4 2.289 18 serves by self-check 4 2.342 23 arrives 2.342 23 waits at self-check 4 2.343 24 arrives 2.343 24 leaves 2.368 12 done serving by self-check 5 2.368 19 serves by self-check 5 2.448 25 arrives 2.448 25 waits at self-check 4 2.596 26 arrives 2.596 26 leaves 2.625 27 arrives 2.625 27 leaves 2.721 28 arrives 2.721 28 leaves 2.830 29 arrives 2.830 29 leaves 2.945 30 arrives 2.945 30 leaves 3.000 7 done serving by 1 3.076 15 done serving by 3 3.076 16 serves by 3 3.289 18 done serving by self-check 4 3.289 21 serves by self-check 4 3.368 19 done serving by self-check 5 3.368 23 serves by self-check 5 3.849 8 serves by 1 4.076 16 done serving by 3 4.076 17 serves by 3 4.285 9 serves by 2 4.289 21 done serving by self-check 4 4.289 25 serves by self-check 4 4.368 23 done serving by self-check 5 4.849 8 done serving by 1 5.076 17 done serving by 3 5.076 22 serves by 3 5.285 9 done serving by 2 5.285 13 serves by 2 5.289 25 done serving by self-check 4 6.076 22 done serving by 3 6.285 13 done serving by 2 6.285 14 serves by 2 7.285 14 done serving by 2 8.712 10 serves by 1 9.712 10 done serving by 1 9.712 20 serves by 1 10.712 20 done serving by 1 [1.852 24 6]
> 
> i used this test case! if you pass this one, you shd be able to pass all 18 alr!
