### ISSUE TITLE
Non-private methods detected

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#725]
Hi everyone, I followed most of what was in the PA2 walkthrough, but I still got the error in the title. Has anyone encountered it and how did you fix it? (I tried to make most of the constructors and methods private, but still...)

**Comment by quadryan** [comment]
Which are your public methods, if i may ask?

**Comment by minhkiwi14** [comment]
> Which are your public methods, if i may ask?
I will consider all public methods and methods with no access modifiers.
In `StateM`, they are `get, put, unit, toString, accept, flatMap`.
In `FuncStat`, they are `toString, in, out` (implementations of `in` and `out` are in the video).

**Comment by yishao17** [comment]
i had something like this too! maybe can check ur constructors, mine was because of that

**Comment by minhkiwi14** [comment]
> i had something like this too! maybe can check ur constructors, mine was because of that

For `StateM` and `FuncStat`, each of these I believe that there must exist a constructor that cannot be declared private, as I follow the walkthrough closely.

**Comment by MoeySeanJean** [comment]
what about the nothing class, the constructor should be private there if there is any.

**Comment by minhkiwi14** [comment]
> what about the nothing class, the constructor should be private there if there is any.

I even did not declare any fields or constructors there...

**Comment by MoeySeanJean** [comment]
Then should be ur StateM constructors? Are they private? As StateM does not need any public constructor only 3 static methods, toString and flatMap.

**Comment by minhkiwi14** [comment]
> Then should be ur StateM constructors? Are they private? As StateM does not need any public constructor only 3 static methods, toString and flatMap.

But I should get what I want since I followed the walkthrough closely and the head TA did not declare the two constructors private there. The question does not ask us to declare the constructors private (only the helper methods).
![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/f6f4af71-6cab-4bcd-aadb-9930766bf8a1)

**Comment by MoeySeanJean** [comment]
Ok... For me, the only difference I can see between my code and your code is the constructors being not private. But, did you overwrite accept in StateM? If you did, maybe that is the reason.

**Comment by minhkiwi14** [comment]
> Ok... For me, the only difference I can see between my code and your code is the constructors being not private. But, did you overwrite accept in StateM? If you did, maybe that is the reason.

Oh yes, I managed to solve it. I should have not override the `accept` method (which has already been in `AbstractStateM`), so that is the only method that I need to delete or change. Thank you very much!
