### ISSUE TITLE
Finals PYP with Answer Key?

### ISSUE THREAD

**Issue by ezclap02** [nus-cs2030/2324-s2#727]
hi anyone know where we can get past year papers for finals that come with the answer key?

**Comment by CSnoobCS** [comment]
I guess google and try find bah

**Comment by c-510** [comment]
i think prof should release? if not i think most can only do q1 and q2

**Comment by jennipho** [comment]
u can try asking ur TAs for any help! they might have some

**Comment by ZHD1987E** [comment]
Alternatively, you might want to ask ChatGPT.

Anyway @hwkchia did release a walkthrough of one of the final exam papers, have a watch!

**Comment by Shazard07** [comment]
chatgpt/google

**Comment by proteaninja** [comment]
gemini works too and I feel that its responses are easier to understand

**Comment by ZHD1987E** [comment]
Moreover, you should get your hands dirty, so actually try using your Java IDE and code from there.

VSCode can simulate the Examplify experience also, just switch to plain text and voila.

**Comment by AxeRaye** [comment]
maybe can try searching on studocu? or the holy grail

**Comment by Bryanngu03** [comment]
> Alternatively, you might want to ask ChatGPT.
> 
> Anyway @hwkchia did release a walkthrough of one of the final exam papers, have a watch!

Where is it arh? or the prof haven't release yet?

**Comment by qeuif** [comment]
> > Alternatively, you might want to ask ChatGPT.
> > Anyway @hwkchia did release a walkthrough of one of the final exam papers, have a watch!
> 
> Where is it arh? or the prof haven't release yet?

Its on Canvas, under Video/Panopto >> Web Lectures

**Comment by dlkw13** [comment]
there are walkthrough review videos for the two past year papers uploaded under videos > web lectures, for other pyp maybe you can google or check studocu for any answers

**Comment by ZHD1987E** [comment]
finals is over you can close this issue
