### ISSUE TITLE
Project Testcase 9_12

### ISSUE THREAD

**Issue by Gracesong146** [nus-cs2030/2324-s2#728]
# Summary
Everything is correct but somehow all the 4 and 5 are flipped

## Screenshots (if any): 
<img width="392" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/62082817/b7927467-9b8c-4972-b34f-4ac99b959ebb">

**Comment by lifrocszh** [comment]
i created a method that looks at the earliest next available time and returns index and earliest next available time, if the customer is first in line, it will be transferred to serve with the selfcheckout index and time

**Comment by iannntsw** [comment]
not sure how u implemented your server class but i think u could check whether your code is creating new servers at each event correctly in terms of the server id and index. alternatively, you could track whether your code is correctly adding and assigning servers in ur simulator class. thats how i debugged most of my issues

**Comment by EhYongE** [comment]
I solved the error by fixing by canServe() method!

Initially I allocated the SSC that has the fastest available time, 
but now I changed to go through from the first SSC to see which SSC is available at the given timing.

**Comment by ZimoSyndrome** [comment]
Hi, not sure if you have resolved this already, but I encountered a similar issue. Try streamlining the assignments to self checkout counters process by checking through the list of self checkout counters again instead of assigning customers prematurely, hope this helps!

**Comment by ZHD1987E** [comment]
Did you solve it @Gracesong146? If so, you may close the issue.
