### ISSUE TITLE
same marks for everyone?

### ISSUE THREAD

**Issue by ihavetinypp** [nus-cs2030/2324-s2#731]
will everyone get the same 15% ? 

what are the grading criteria? what to do to get the max marks possible

**Comment by NJiHin** [comment]
From what I heard, not everyone will get max marks and the project will be remarked for any glaring mistakes.
Mistakes such as breaking polymorphism in a very obvious way or making a self-checkout version of all the events for the latest lab.
I think most people will get the full 15% though? Hopefully.

**Comment by CSnoobCS** [comment]
There is definitely a design component in the marks.

**Comment by c-510** [comment]
according to my TA, our code has to follow the principals taught in lecture, he said the code should be as readable as possible too

**Comment by JosiahPraeman** [comment]
Buddy i think dont worry about them penalising for marks if you pass all the test cases i think you should be proud of yourself already do not need to worry what others say.

**Comment by meowmeowpeepee** [comment]
Bro i think dont worry about them penalising for marks if you pass all the test cases i think you should be proud of yourself already .

**Comment by donregan9** [comment]
> Buddy i think dont worry about them penalising for marks if you pass all the test cases i think you should be proud of yourself already do not need to worry what others say.

thanks for the encouragement pman

**Comment by Shazard07** [comment]
> Buddy i think dont worry about them penalising for marks if you pass all the test cases i think you should be proud of yourself already do not need to worry what others say.

yes  be proud of yourself man you came far

**Comment by quadryan** [comment]
congrats on passing all test cases! just remember that finals is 40% :)

**Comment by ihavetinypp** [comment]
thanks guys
