### ISSUE TITLE
Project Test Case 9_9 leave not wait

### ISSUE THREAD

**Issue by andhika2002** [nus-cs2030/2324-s2#732]
# Summary
Customer 3 does not enter self check queue but leaves instead.

## Description 

Customer does not enter self check queue (global queue), but **leaves** instead.

![image](https://github.com/nus-cs2030/2324-s2/assets/105861910/0d674620-342b-426e-9f00-39d4e022b6f7)

In my Arrive class, I have the following clauses:
If HumanServer(HS) and canServe, serve.
If HS and can queue, queue into individual server's customer queue.
If SCC and can queue, queue into global queue.
(If not any,) issue leave event.

![image](https://github.com/nus-cs2030/2324-s2/assets/105861910/d6caa4df-f3f3-44de-b9fd-ceb2f4aa4b56)

From this test case, seems like I only have 0 HS and 2 SCCs, at which point in time both SCCs are busy serving. This should lead the customer to my 3rd if clause.

Seems like customer 3 does not meet any of these conditions at all, which is weird because my global queue is not involved in any of the processes before customer 3 arrives.

Anyone faced this issue?

**Comment by andhika2002** [comment]
> I had the same issue (in test case 9, 11, and 13). It has to do with your queue handling logic, specifically how you're queueing or dequeueing the server because it thinks the queue is full when it should not be.

where did you make your change at? I've scanned through my code for all points where queue is changed/ queue is used to check

**Comment by Chrisallan29** [comment]
Hi andhika2002, i was facing this issue earlier, perhaps you could take a look at your Simulator class, if you have exhausted looking at your other classes. If not, I think the order in adding servers to queue may be the issue behind this

**Comment by andhika2002** [comment]
thanks both, it was a bug where my global queues were fed with the customers in the simulator class. @Chrisallan29 @leeyenkai
