### ISSUE TITLE
PA2 level 4, get hit with warnings with model code

### ISSUE THREAD

**Issue by xin-yi-phang** [nus-cs2030/2324-s2#735]
# Summary
I tried using the TA's code and got hit with warnings. is this ok I'm scared

## Screenshots (if any): 
<img width="831" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158749925/1f443a0c-44c4-442b-a1d7-bbcf27946522">
<img width="487" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158749925/dc24cfa5-1231-42f9-ba75-a6211a6928a6">

**Comment by c-510** [comment]
my code looks the same as yours, maybe it is something in ur StateM? it seems like the StateM class and the methods get(), flatMap(), put(), and inc() are not being used with proper generic parameters that ensure type safety.

**Comment by zzhengweii** [comment]
should be an issue of generic parameters

**Comment by cherollyy** [comment]
u can try checking your return types for the methods that raised an error, or check your constructors also

**Comment by xin-yi-phang** [comment]
hi all, i discovered i did not declare the flatMap variables correctly. tq everyone for ur help!! :)
