### ISSUE TITLE
Project test case 9 how to find best available self checkout in SCC list

### ISSUE THREAD

**Issue by tarshalim** [nus-cs2030/2324-s2#736]
# Summary
Put a summary of the question
how do we find best available self checkout in manager, are we suppsoed to use streams or..?
## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/6c8f83b5-c659-450e-8afc-f985ec82dc48)

**Comment by nus2030** [comment]
Hi, how I did it was to just choose the one that is immediately, or just to make the customer continue waiting, and to be tagged with the "manager". If there are no automated servers ready, just continue waiting. The moment one is ready, the "manager" will direct the first person waiting in line to the automated server. I didnt use streams or optionals, so I cant really provide much advice on that. Hope it helps !

**Comment by nicklass8** [comment]
Hello, what I did was that I created an additional method call findFastestSCC() which loops through a list of all the SCCs and see which one has earliest finish time before calling a serve event on that SCC

**Comment by tarshalim** [comment]
i see thanks everyone
