### ISSUE TITLE
project is the manager a selfcheckout or not 

### ISSUE THREAD

**Issue by tarshalim** [nus-cs2030/2324-s2#737]
# Summary
Put a summary of the question
i heard that one implementation is serverlist consisting of human servers and manager, and manager contains self-checkouts. 

in this case, is the manager also a self checkout, such as being the 1st self checkout? 
is it if my manager is the 1st self checkout, then it should have attributes such as server number, availableAt, customerQueue(), qmax? and my remaining self-checkouts just have server number and availableAt?

im a bit lost on the logic and would appreciate some help thank you
## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by meowmeowpeepee** [comment]
for me manager is a server, and it stores list of sccs

**Comment by zzhengweii** [comment]
instead of manager maybe you can try simultaneously updating the queues of self checks within your events to represent them sharing a single queue
