### ISSUE TITLE
Not sure why nextAvailableTime is 'sometimes' not updated

### ISSUE THREAD

**Issue by Partillay** [nus-cs2030/2324-s2#738]
# Summary
For public test case 4, (1st pic) my Done event was able to update my nextAvailableTime of Server 1 after Customer 3 is done serving by them but (2nd pic) after serving customer 7, my Server 1's nextAvailableTime was not updated (idk if it's that they did not rest? in a way) causing Customer 10 to be served immediately.

## Description 
For context, my SelfCheck subtypes Server which has a rest time supplier: () -> 0.0, my Serve event updates nextAvailableTime of Server by adding service time and duration of service, then Done event updates the nextAvailableTime of Server by adding resting time obtained from supplier. Does anyone have any idea which part could possibly went wrong?

The 3 doubles after each event execution is the updated nextAvailableTime of each Server / SelfCheck.
The line that was missing between 10.006391 in the 2nd picture was a "rewait" event of Customer 10 that did not get outputted

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/64f4964a-204e-4c64-bb95-a44857bd73f3)
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/89839645-aaef-460f-b953-2743370cdf80)

**Comment by Partillay** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/f1465338-5536-4303-9304-10d5d7b86a54)
I tried to find out the outcomes from the rest time supplier and found out that my Server never got the 3rd rest time and got the 4th instead (could it haven been reset to the first again?), which is why it served Customer 10 immediately. However, I checked my code thoroughly and I made sure the supplier is always the same supplier when updating the server in server list, does anyone have any insight on this?

**Comment by Partillay** [comment]
And to add, my rest() method for Server is only invoked in next() method under Done event

**Comment by gnimnix** [comment]
Since your server got 4th rest time when it should get the 3rd rest time, means your rest time supplier might have been called twice?

Try changing your supplier to 
```java
() -> {
    System.out.println("Supplier called here");
    return ...
}

Then count how many times it was called and slowly debug from there.

**Comment by Partillay** [comment]
> Since your server got 4th rest time when it should get the 3rd rest time, means your rest time supplier might have been called twice?
> 
> Try changing your supplier to
> 
> ```java
> () -> {
>     System.out.println("Supplier called here");
>     return ...
> }
> ```
> 
> Then count how many times it was called and slowly debug from there.

I checked and the number of calls was correct. I think the problem lies within the Supplier getting resetted, causing the 3rd call to result in 0.0 (first result), what do you think could have happened instead hmm
