### ISSUE TITLE
Opening multiple tabs of different classes using Vim 

### ISSUE THREAD

**Issue by davidsonchua** [nus-cs2030/2324-s2#74]
Good Saturday Afternoon Everyone, 

I was working on Lab 02 when I realised there are quite a few more classes that I am working with as compared to the previous exercises and lab. Does anyone here happen to know how to open multiple "tabs" of classes together in one screen on Vim ? 

I am using Vim on my Macbook's Terminal by the way. 

Have a pleasant weekend everyone !

**Comment by darylchen46** [comment]
I'm not sure about Macbook but I think you could just open multiple msys.bat files to work on your classes. Hope this helps

**Comment by JingLeEa** [comment]
I'm using Windows, and the shortcut keys are:
Ctrl + W + v  to split vertically
Ctrl + W + s to split horizontally
Ctrl + W + hjkl to navigate around splits, and :edit to open and edit (other) files in new tab 
Maybe you could try using the command key instead of Ctrl key to see if it works.

**Comment by codingtemp** [comment]
These commands work for Windows; you can give them a try and see if they work with Mac.

After opening vim using ```vim [file name]```, you can use ```:tabnew [file name]``` to open multiple tabs.
For example, ```:tabnew main.java```.
To save all tabs, you can type ```:wa```.
Once you have multiple tabs, you can use ```gt``` or ```gT``` in command mode to navigate between tabs.

**Comment by andrelau123** [comment]
You can try using command T to open new tabs then drag the tabs out side by side to be able to see it in 1 window

**Comment by EnzioKam** [comment]
There are two ways in general if you want to "open" multiple files at the same time in vim: _Splits_ and _Tabs_. You can look at the documentation to learn more:

Splits: https://vimdoc.sourceforge.net/htmldoc/windows.html#windows
Tabs: https://vimdoc.sourceforge.net/htmldoc/tabpage.html#tab-page

**Comment by zuoshihua** [comment]
Open all source files in tabs

```
$ vim -p *.java
```

Open specific files in tabs

```
$ vim -p Simulator.java Customer.java Server.java
```

| Action | Keystroke |
| ---- | ---- |
| Open file in new tab e.g. Event.java | `:tabe Event.java` |
| Next tab | <kbd>g</kbd> <kbd>t</kbd> |
| Previous tab | <kbd>g</kbd> <kbd>shift</kbd> <kbd>t</kbd> |
| Next $n$th tab e.g. 4 | <kbd>4</kbd> <kbd>g</kbd> <kbd>t</kbd> |
| Previous $n$th tab | <kbd>4</kbd> <kbd>g</kbd> <kbd>shift</kbd> <kbd>t</kbd> |
| Toggle between current and previous tab | <kbd>g</kbd> <kbd>tab</kbd> |

> *"I actually wrote a Vim versus IDE comparison. Do you know how much faster Vim was? 4.3 seconds. 4.3 seconds I save every day. All those months learning Vim were totally worth it.*"
> [Interview with a VIM Enthusiast](https://www.youtube.com/watch?v=9n1dtmzqnCU)

**Comment by davidsonchua** [comment]
Thanks all for the helpful tips !!
