### ISSUE TITLE
Excercise 6 Calling Exception rather than printing any string

### ISSUE THREAD

**Issue by blacksesamezongzi** [nus-cs2030/2324-s2#742]
# Summary

I have passed level1 and finished modification of level2 and 3, however, when I try to run the code in jshell, it returned only Exception but not any String, did anyone face the same problem? Appreciate for any help!

## Code Snippets

![image](https://github.com/nus-cs2030/2324-s2/assets/157393222/551f38e3-2df0-4972-83a1-85a52699bd3a)

**Comment by hanlinnnnn** [comment]
you may want to look at the video prof uploaded on canvas by the videos/panopto folder and digest it

**Comment by blacksesamezongzi** [comment]
> you may want to look at the video prof uploaded on canvas by the videos/panopto folder and digest it

okie thanks a lot! I have dealt with the prb
but tbh the vedio is just like a model answer and makes my previous 1 day thinking like a joke hhh
