### ISSUE TITLE
error in ImList

### ISSUE THREAD

**Issue by rkr7395** [nus-cs2030/2324-s2#747]
anyone else encountered the same error?

<img width="990" alt="Screenshot 2024-04-25 at 2 12 54 PM" src="https://github.com/nus-cs2030/2324-s2/assets/166832711/04e10f05-ccad-49d5-809f-f238fa2d8db9">

**Comment by gnimnix** [comment]
Which lab/exercise is this?

Try submitting with a different `ImList.java` file, you might have made changes accidentally.

**Comment by lohkeyyy** [comment]
This error indicates that there is an issue with how the <p> HTML tags are used in the Javadoc comments in your Java source files. To resolve this, just download another ImList.java from code crunch and use the new one instead.

**Comment by quadryan** [comment]
Is this for one of the practice papers?

**Comment by rkr7395** [comment]
nope, its for the project.
