### ISSUE TITLE
Multiple output detected

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#75]
# Summary

Submitted my lab2 classes for grading but keep getting Compilation error: Multiple output detected.

Anyone know why?

Thanks in advance.

## Screenshots
<img width="960" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156635387/aba51723-ba78-4247-9f0c-51d1ff6a73db">

<img width="210" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156635387/f03d59ce-4251-4b07-9381-9c445a08abf8">

**Comment by xin-yi-phang** [comment]
bump

**Comment by weikiatt** [comment]
are you printing multiple statements? try saving the outputs into one variable instead

**Comment by BZAStudent** [comment]
Turns out i didn't remove some print statements that I used for debugging. Thanks all.
