### ISSUE TITLE
Exercise 6 Level 3

### ISSUE THREAD

**Issue by mirainokimi** [nus-cs2030/2324-s2#750]
![image](https://github.com/nus-cs2030/2324-s2/assets/34067045/17f73092-54c9-4a33-a566-9b5e2e178e21)
![image](https://github.com/nus-cs2030/2324-s2/assets/34067045/9d49124d-1a62-448e-9a9f-086eaeee0a14)

Hi I'm not sure what went wrong over here, is anybody else facing this issue as well?

**Comment by joashlim22** [comment]
not quite sure, but u can reference the walkthrough video to see where u went wrong, its prob some typo error somewhere in ur code

**Comment by mirainokimi** [comment]
i got this issue after referencing the walkthrough video though, i tried rewatching and checking again but couldnt find the error

**Comment by ZHD1987E** [comment]
Seems like your code has difficulties adding every stop. Try going through the logic again and see where did you miss out.

**Comment by mirainokimi** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/34067045/381e0e6a-8f62-442c-acf1-1c6e84735448)

i have checked and its because of the filter within the describeService method in BusRoutes, removing the filter solves the issue.
