### ISSUE TITLE
PRO TIP EXAMPLIFY VERSION

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#756]
Sick and tired of indenting by tabbing manually?
Use the indent buttons!
![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/ad438d06-6367-4180-8c33-2e3fbaac9c4c)
I do wish Examplify can implement shortcuts for indenting and un-indenting though... how cool is that?

**Comment by lohkeyyy** [comment]
where are the indent buttons

**Comment by CSnoobCS** [comment]
do they actually care if missing a spacing or two? I remember hearing somewhere it's not important.

**Comment by ChounRH** [comment]
Are the indentation buttons the one next to the search icon on the right top? Will we get penalised for improper indentations?

**Comment by quadryan** [comment]
Indent button is top right the one highlighted blue @lohkeyyy

**Comment by lohkeyyy** [comment]
wow! thank u brother <333 @quadryan

**Comment by lohkeyyy** [comment]
@ChounRH yes we will definitely be penalised for improper indentation that's why I'm trying to figure out where is the indent button :(( . Plus indentation will help make our code neater for ourselves and the marker :D

**Comment by ChounRH** [comment]
@lohkeyyy Okay thanks for clarifying :)

**Comment by quadryan** [comment]
no problem bro @lohkeyyy 
Admire you for helping out on github a lot!

**Comment by hohinnn** [comment]
didn't know about this tip, thanks so much!

**Comment by Partillay** [comment]
thanks slayer hao dong!

**Comment by ZHD1987E** [comment]
# BONUS

You can have SOC-RT delete your CodeCrunch account after the course.

**Comment by ZHD1987E** [comment]
Anyway on 1 May 2024, all my open issues will be closed in preparation for decluttering.

Since this forum will be closed, why not get together and clean up the forum by closing ALL our open issues?

**Comment by travistan2003** [comment]
oh wow thanks hao dong!

**Comment by w1nsl** [comment]
thank you

**Comment by azzy83** [comment]
THANK YOU!
