### ISSUE TITLE
Project Testcase 9_03

### ISSUE THREAD

**Issue by T-HL16** [nus-cs2030/2324-s2#757]
![Project 9_03](https://github.com/nus-cs2030/2324-s2/assets/153625920/aabeeb59-769a-4f80-a45e-c7cf0159f48e)

Hii anyone faced this problem before? Any form of help and advice is greatly appreciated here.

Some context:
- my rest time is implemented in the DoneEvent by just updating the server's next available time
- my WaitEvent will return ServeEvent when queue length == 0 (ie next in queue), with serving time equals to the servers next available time

**Comment by Tayjunzhi** [comment]
I think you might want to check if your server is available when your WaitEvent returns a ServeEvent because your server might be resting and your WaitEvent might not get the most updated servers list

**Comment by lohkeyyy** [comment]
I faced a similar issue and i implemented things in a similar way, ensure that when your server is resting, it is being updated that he is indeed resting

**Comment by ChounRH** [comment]
On top of all the advice given thus far, do check your Serve class. It seems like based on the failed test case that serve has created a Done event that has a time that includes the rest time. This also means that the rest time is being called prematurely.

**Comment by nicolenahh** [comment]
I agree with ChounRH! Check your Serve Event to make sure that the nextEvent which is a Done Event has the correct time.

**Comment by yf-yeoo** [comment]
I agree, it looks like there is something wrong with the time given to the done/rest event. Check your Serve and Done events to make sure that the time is updating correctly. If that doesn't work, try checking the events for customer 12

**Comment by T-HL16** [comment]
Thank you so much everyone! I managed to found my error.

For those who might need it ...
Problem: WaitEvent returns ServeEvent with servers most updated nextAvailTime when queuelength ==0. However, this ServerEvent is generated prior to the completion of the previous customer in the same queue, which means the server's rest time hasn't been determined when it was updated.
