### ISSUE TITLE
Project: Supplementary Test Cases w Expected Output

### ISSUE THREAD

**Issue by joshualek09** [nus-cs2030/2324-s2#758]
# Summary
Hi, this post provides supplementary test cases with expected output that I have compiled from different people and also created. If you are able to clear all of it, there is an extremely high chance your code clears all 18 test cases. I personally have put in a couple hundred hours into this project so I know firsthand the struggle (especially when lacking test cases). Hence, I hope these test cases help you to find all logic bugs in your code. Cheers and atb :)

(p.s.: clearing a longer test case DOES NOT necessarily mean you can clear a shorter one and vice versa. Especially so if two or more seem "similar". So be sure to check as many cases as possible whenever you edit your implementation)

## Description
**10.in | no self checkout, rest prob set to 0.9**
2 0 2 0.9
0.000000
0.313508
1.204910
2.776499
3.876961
3.909737

output:
0.000 1 arrives
0.000 1 serves by 1
0.314 2 arrives
0.314 2 serves by 2
1.000 1 done serving by 1
1.205 3 arrives
1.205 3 waits at 1
1.314 2 done serving by 2
2.776 4 arrives
2.776 4 serves by 2
3.776 4 done serving by 2
3.877 5 arrives
3.877 5 waits at 1
3.910 6 arrives
3.910 6 waits at 2
4.139 3 serves by 1
4.625 6 serves by 2
5.139 3 done serving by 1
5.625 6 done serving by 2
9.002 5 serves by 1
10.002 5 done serving by 1
[1.462 6 0]

**11.in | no human server, qmax 1**
0 2 1 0.5
0.000
0.035
0.046
0.124
0.126

output:
0.000 1 arrives
0.000 1 serves by self-check 1
0.035 2 arrives
0.035 2 serves by self-check 2
0.046 3 arrives
0.046 3 waits at self-check 1
0.124 4 arrives
0.124 4 leaves
0.126 5 arrives
0.126 5 leaves
1.000 1 done serving by self-check 1
1.000 3 serves by self-check 1
1.035 2 done serving by self-check 2
2.000 3 done serving by self-check 1
[0.318 3 2]

**12.in | no human server, qmax 2**
0 2 2 1
0.500
0.600
0.700
1.500
1.600
1.700

output:
0.500 1 arrives
0.500 1 serves by self-check 1
0.600 2 arrives
0.600 2 serves by self-check 2
0.700 3 arrives
0.700 3 waits at self-check 1
1.500 1 done serving by self-check 1
1.500 3 serves by self-check 1
1.500 4 arrives
1.500 4 waits at self-check 1
1.600 2 done serving by self-check 2
1.600 4 serves by self-check 2
1.600 5 arrives
1.600 5 waits at self-check 1
1.700 6 arrives
1.700 6 waits at self-check 1
2.500 3 done serving by self-check 1
2.500 5 serves by self-check 1
2.600 4 done serving by self-check 2
2.600 6 serves by self-check 2
3.500 5 done serving by self-check 1
3.600 6 done serving by self-check 2
[0.450 6 0]

**13.in | similar to 12.in but double the SCCs and qmax and more Cust**
0 4 4 1
0.500
0.600
0.700
0.800
0.900
1.000
1.100
1.200
1.300
1.400
1.500
1.600
1.700
1.800
1.900
2.000
2.100

output: 
0.500 1 arrives
0.500 1 serves by self-check 1
0.600 2 arrives
0.600 2 serves by self-check 2
0.700 3 arrives
0.700 3 serves by self-check 3
0.800 4 arrives
0.800 4 serves by self-check 4
0.900 5 arrives
0.900 5 waits at self-check 1
1.000 6 arrives
1.000 6 waits at self-check 1
1.100 7 arrives
1.100 7 waits at self-check 1
1.200 8 arrives
1.200 8 waits at self-check 1
1.300 9 arrives
1.300 9 leaves
1.400 10 arrives
1.400 10 leaves
1.500 1 done serving by self-check 1
1.500 5 serves by self-check 1
1.500 11 arrives
1.500 11 waits at self-check 1
1.600 2 done serving by self-check 2
1.600 6 serves by self-check 2
1.600 12 arrives
1.600 12 waits at self-check 1
1.700 3 done serving by self-check 3
1.700 7 serves by self-check 3
1.700 13 arrives
1.700 13 waits at self-check 1
1.800 4 done serving by self-check 4
1.800 8 serves by self-check 4
1.800 14 arrives
1.800 14 waits at self-check 1
1.900 15 arrives
1.900 15 leaves
2.000 16 arrives
2.000 16 leaves
2.100 17 arrives
2.100 17 leaves
2.500 5 done serving by self-check 1
2.500 11 serves by self-check 1
2.600 6 done serving by self-check 2
2.600 12 serves by self-check 2
2.700 7 done serving by self-check 3
2.700 13 serves by self-check 3
2.800 8 done serving by self-check 4
2.800 14 serves by self-check 4
3.500 11 done serving by self-check 1
3.600 12 done serving by self-check 2
3.700 13 done serving by self-check 3
3.800 14 done serving by self-check 4
[0.533 12 5]

**14.in | 3 human servers 2 SCCs qmax 3**
3 2 3 0.500000
0.0
0.14617563814065818
0.2281918004390985
0.2697347687010419
0.3362781798929442
0.5298293617777683
0.5310527982309206
0.7237937576355621
0.911766835391944
1.1012058189245828
1.2886222487037768
1.3680571171407179
1.4375607229813399
1.4963721293821473
1.5976688548473943
1.620862272453926
1.7749694484697613
1.9069479902084454
1.9382973683224147
2.0139377773866256
2.0418903139673756
2.180879909887874
2.3419254641826166
2.342930499381107
2.4475575305387736
2.596354427786237
2.6247589684294224
2.721104628744542
2.830015590523277
2.9454356427981323

output: 
0.000 1 arrives
0.000 1 serves by 1
0.146 2 arrives
0.146 2 serves by 2
0.228 3 arrives
0.228 3 serves by 3
0.270 4 arrives
0.270 4 serves by self-check 4
0.336 5 arrives
0.336 5 serves by self-check 5
0.530 6 arrives
0.530 6 waits at 1
0.531 7 arrives
0.531 7 waits at 1
0.724 8 arrives
0.724 8 waits at 1
0.912 9 arrives
0.912 9 waits at 2
1.000 1 done serving by 1
1.000 6 serves by 1
1.101 10 arrives
1.101 10 waits at 1
1.146 2 done serving by 2
1.228 3 done serving by 3
1.270 4 done serving by self-check 4
1.289 11 arrives
1.289 11 serves by self-check 4
1.336 5 done serving by self-check 5
1.368 12 arrives
1.368 12 serves by self-check 5
1.438 13 arrives
1.438 13 waits at 2
1.496 14 arrives
1.496 14 waits at 2
1.598 15 arrives
1.598 15 waits at 3
1.621 16 arrives
1.621 16 waits at 3
1.775 17 arrives
1.775 17 waits at 3
1.907 18 arrives
1.907 18 waits at self-check 4
1.938 19 arrives
1.938 19 waits at self-check 4
2.000 6 done serving by 1
2.000 7 serves by 1
2.014 20 arrives
2.014 20 waits at 1
2.042 21 arrives
2.042 21 waits at self-check 4
2.076 15 serves by 3
2.181 22 arrives
2.181 22 waits at 3
2.289 11 done serving by self-check 4
2.289 18 serves by self-check 4
2.342 23 arrives
2.342 23 waits at self-check 4
2.343 24 arrives
2.343 24 leaves
2.368 12 done serving by self-check 5
2.368 19 serves by self-check 5
2.448 25 arrives
2.448 25 waits at self-check 4
2.596 26 arrives
2.596 26 leaves
2.625 27 arrives
2.625 27 leaves
2.721 28 arrives
2.721 28 leaves
2.830 29 arrives
2.830 29 leaves
2.945 30 arrives
2.945 30 leaves
3.000 7 done serving by 1
3.076 15 done serving by 3
3.076 16 serves by 3
3.289 18 done serving by self-check 4
3.289 21 serves by self-check 4
3.368 19 done serving by self-check 5
3.368 23 serves by self-check 5
3.849 8 serves by 1
4.076 16 done serving by 3
4.076 17 serves by 3
4.285 9 serves by 2
4.289 21 done serving by self-check 4
4.289 25 serves by self-check 4
4.368 23 done serving by self-check 5
4.849 8 done serving by 1
5.076 17 done serving by 3
5.076 22 serves by 3
5.285 9 done serving by 2
5.285 13 serves by 2
5.289 25 done serving by self-check 4
6.076 22 done serving by 3
6.285 13 done serving by 2
6.285 14 serves by 2
7.285 14 done serving by 2
8.712 10 serves by 1
9.712 10 done serving by 1
9.712 20 serves by 1
10.712 20 done serving by 1
[1.852 24 6]

**Comment by joshualek09** [comment]
Disclaimer: I would like to emphasise that credit is given where it's due. Regrettably, I didn't keep track of the users who provided some of the test cases mentioned earlier. To those contributors, if you come across this post, please feel free to leave a comment or share a link to the post where you presented the test case. Your contributions are greatly appreciated and have personally helped me out too.

Thank you :)

**Comment by mChewWW** [comment]
GOAT

**Comment by lohkeyyy** [comment]
saviour

**Comment by weiyangng** [comment]
josh you are a legend

**Comment by CSnoobCS** [comment]
wow must have taken you a long time to track all these data

**Comment by pramoth20** [comment]
thanks josh

**Comment by hohinnn** [comment]
thank you!

**Comment by ZHD1987E** [comment]
If you don't like reading such things, try this instead #431...

**Comment by heokieee** [comment]
<img width="1470" alt="Screenshot 2024-04-27 at 00 49 41" src="https://github.com/nus-cs2030/2324-s2/assets/157129844/7050e5fe-0572-4151-bc6f-a31df7aa0e28">
hi i followed the test case for 14.in but failed miserably. Customer 18 queues at self check out 4 but it gets served by server 2. does anyone knows my mistake??

**Comment by frdyli** [comment]
thank you!

**Comment by quadryan** [comment]
Cheers, Josh!

**Comment by LuXLemonade** [comment]
Thank you, this really saved me.

**Comment by ZHD1987E** [comment]
Hey @heokieee, you need to make sure that those enqueued in the self checkouts... only go to the self checkouts.

**Comment by ZHD1987E** [comment]
Project is over, you may close this issue now @joshualek09
