### ISSUE TITLE
PA2 Walkthrough Question

### ISSUE THREAD

**Issue by kaiju10** [nus-cs2030/2324-s2#761]
# Summary
Using `StateM.<Integer>` when the input arguments are `StateM<T,S>`

## Description 
Hello, I just want to clarify how is it possible that StateM can accept one input type even though there is T and S? I know it is used for `StateM<S,S>`, but still it is 2 arguments.

**Comment by arinng5** [comment]
M is the input type and S is the output type

**Comment by ChounRH** [comment]
It can be done in this scenario because both the state and output type in this case is the same (both are Integer). Therefore, you only have to declare that the static method will operate with one generic type Integer (which is the "One input" you are referring to)

**Comment by lohkeyyy** [comment]
It is possible that your StateM can take in one type parameter as if you look at your code for this static method, you only put one type parameter. e.g. static <T> StateM<T,T> ... There is only one type parameter after static, this means this method only requires one type parameter to operate.

**Comment by kaiju10** [comment]
@arinng5 I dont think I have mentioned M as one of the variables. But in all I get all of your explanations, and I guess then there is a degree of flexibility inside java. Thank you @ChounRH @lohkeyyy @weitsang, and @arinng5 for helping!
