### ISSUE TITLE
project sharedqueue efficiency

### ISSUE THREAD

**Issue by citronwhitetea** [nus-cs2030/2324-s2#763]
in your opinion, what is the most efficient way to implement the sharedqueue for scos (for those who did not create an additional manager class)

**Comment by quadryan** [comment]
One way is as such:
you could implement such that when a customer waits at the SC,
- you +1 the queue in all SC.
- when customer gets served by any SC, -1 the queue in all SC.

**Comment by jennipho** [comment]
the way i designed my queue was that when looping through your queue, looping until the first self check out and handling the queues just at this first self check out!

**Comment by lohkeyyy** [comment]
For me, i only created one instance of a SelfCheckOut and in it, there is an overall ServerID and an ImList of all the available times of the checkouts in it. This way, this one object handles the shared queue. When serving, my one SelfCheckOut instance will search the ImList inside it to see which specific counter should serve the customer.

**Comment by ccqie233** [comment]
i created a getQueue() method in my server, then all the SelfCheck counters reads queue from the first self check-out counter; when updating, the first SC queue is updated, all other SCs refer to the queue for generating events

**Comment by jianhaosoh** [comment]
For my implementation, I only initialised the first SCC with a queue and set the max queue of the rest of the SCC to be zero. This way, customer can only queue at the first SCC and each time they arrive and wait at the first SCC, it will check to see if there is any available SCC that can serve (if yes it will be assigned to that SCC)

**Comment by hanlinnnnn** [comment]
^Mine is very similar to jianhao's. When seaching for available queues, the method would always ignore sccs except the first since their qmax is 0. Just remember to assign customers in the first scc's queue to other sccs when they become available (you may need your wait or other wait event to check for the earliest available scc)

**Comment by ZHD1987E** [comment]
I felt that queuing has to be handled separately, so I ended up making a Queue Management class.

You can read #665 to learn more about my project implementation.

**Comment by travistan2003** [comment]
I simply iterated through all the self checkouts when updating their queues

**Comment by hohinnn** [comment]
I also initialized my first SCC with a queue, and the rest have a queue of 0

**Comment by absfsd** [comment]
how does the waiting time works for SCC? when do i add waiting time to my hidden wait , because all my queues are in the first SCC, if i add waiting time it only accounts for the serving time in first SCC and not the rest resulting in other scc being available but unable to serve waiting customer due to changed customer arrival time

**Comment by ZHD1987E** [comment]
Also @citronwhitetea, this is not CS2040 where they are particular about time complexities. The time limits are set in such a way that it only catches infinite loops, not inefficient code.

**Comment by azzy83** [comment]
For me, I checked if the server was an SCO, if it was, then increase/decrease queue for all the other SCO, and that isn't too hard as you know that all servers to the right of the last human server are all SCOs

**Comment by frdyli** [comment]
In my design, I have a single instance of a SelfCheckOut class. Within this instance, there exists a shared queue managed by an overall ServerID. Additionally, there is an ImList containing all available checkout times. This setup allows the SelfCheckOut instance to efficiently handle the queue. When serving a customer, the instance searches its internal ImList to determine which specific counter should attend to the customer.

**Comment by ZHD1987E** [comment]
Project is over, @citronwhitetea...

**Comment by citronwhitetea** [comment]
thank you all for your insightful povs!
