### ISSUE TITLE
If you are having issues compiling your project when it should be working... (and it works on codecrunch)

### ISSUE THREAD

**Issue by mChewWW** [nus-cs2030/2324-s2#764]
One of the labs/assignments we did used a slightly different Pair class. If you have all your files in the same working directory, you may be using the wrong pair class causing your code to not compile. In that case, redownload the project version of the Pair class and replace the incorrect one.

**Comment by lohkeyyy** [comment]
I started my project with the files i submitted from lab3 and did not face any issues. I think the Pair class in lab 3 is fine, which is where most people started their project from.

**Comment by mChewWW** [comment]
> I started my project with the files i submitted from lab3 and did not face any issues. I think the Pair class in lab 3 is fine, which is where most people started their project from.
the wrong pair class that some people ive talked to had mistakenly used is from one of the exercises, not the labs

**Comment by hohinnn** [comment]
no wonder I couldn't compile, thought there was something wrong, thanks!

**Comment by ZHD1987E** [comment]
Project (and all those relating to CodeCrunch) is over... You may close the issue @mChewWW

**Comment by ZHD1987E** [comment]
finals is over you can close this issue
