### ISSUE TITLE
Test Case 9_01

### ISSUE THREAD

**Issue by Castelle-code** [nus-cs2030/2324-s2#765]
# Summary
What might be the possible reasons for this? Anyone encountered this before?
I'm able to pass the test cases in codecrunch but not this hidden test case.

## Screenshots (if any): 
<img width="420" alt="Screenshot 2024-04-26 at 3 17 28 AM" src="https://github.com/nus-cs2030/2324-s2/assets/157040750/8f54c5bb-7288-49cf-84f1-b66c9cc9394e">

**Comment by Partillay** [comment]
The rest time supplier supplies values in a sequenced order, your rest time supplier for Server 1 supplied a 0.245 instead of 0.000, which means you either called the supplier more or less times than you should've

**Comment by lohkeyyy** [comment]
Looks like an issue with your rest time, ensure for each server, that throughout the entire serving processes, the rest time supplier is only called once, wherever you chose to get the rest time.

**Comment by pramoth20** [comment]
can you provide your rest method? and where it is being called. is it being called in ur done event?

**Comment by jianhaosoh** [comment]
For me I only called the get rest time in supplier once in my done event

**Comment by hanlinnnnn** [comment]
rest time is supplied in a pseudo-random way that is of a specific sequence, calling the .get() more than once would result in having the wrong rest time

**Comment by wxlee1807** [comment]
i only called the rest time once in the done event when it is a human server as well~

**Comment by JosiahPraeman** [comment]
i also called the rest time in the done event when its for human....

**Comment by TokPinXiang** [comment]
Depends where u passed in ur Rest Supplier as arguments, and its better to call rest ie .get() on Done event when server is done serving, and update ur server lists with updated next server avail time. For me i passed in the Supplier as arguments in my execute() so i can use it whenever i want. Also dun forget to update ur event timing with the updated restTime, so when u do PQ on the events, the events will be executed sequentially with the resttime updated.

**Comment by jaydenntann77** [comment]
It seems there's a problem with how rest times are handled. Make sure that for each server, the rest time supplier is invoked only once during the entire serving process, at the point where you decide to fetch the rest time.


I have also made sure to call the rest time only once in the Done event, specifically for human servers only.

**Comment by frdyli** [comment]
I think you can check if your restTime is generated in Done Event to ensure it is called the correct number of times

**Comment by weiyangng** [comment]
you should print out all of your rest times using System.out.println and you will be able to see if you are generating too many rest times

**Comment by ZimoSyndrome** [comment]
Hi, ive encountered a similar problem before when doing the project. I addressed it by monitoring the number of times i retrieved the restTime as well as where I retrieved the restTime, by centralising the supplier of rest time and ensuring that i only get from that same supplier each time i require a rest time. Hope this helps!
