### ISSUE TITLE
Laws for functors and monads 

### ISSUE THREAD

**Issue by travistan2003** [nus-cs2030/2324-s2#768]
When doing one of the practice finals papers, I encountered difficulties with a question asking about whether a specific class is a functor/monad. For clarification, are these the correct laws for functors and monads and am I missing any?

Functors:
1. Preserve identity: functor.map(x -> x) is the same as functor 
2. Preserve composition: functor.map(x -> f(x)).map(x -> g(x)) is the same as functor.map(x -> g(f(x)))

Monads:
1. Has an of method that creates a new monad 
2. Associativity law: this.flatMap(f).flatMap(g).flatMap(h) is the same as this.flatMap(f).flatMap(x -> g(x).flatMap(h))
3. can use flatMap

**Comment by kongshiting** [comment]
hi the laws for functors looks right! 

based on the lecture by prof, monads have two laws (the identity law and the associativity law).

![Screenshot 2024-04-11 at 4.20.13 PM.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/4d3de6b2-b77d-486d-ac15-c820c2f375d5/f305543a-54df-405c-87d3-c071886826bc/Screenshot_2024-04-11_at_4.20.13_PM.png)

this is further broken down into the left identity law, the right identity law and the associativity law. 

Left Identity Law: (unit x).flatMap(f) ≡ f(x)
- if we create a new monad and bind it to the function, the result should be the same as applying the function to the value

Right Identity Law: this.flatMap(unit) ≡ this
- the result of binding a unit function to a monad should be the same as the creation of a new monad

Associativity Law (this.flatMap(f).flatMap(g)).flatMap(h)) ≡ this.flatMap(f).flatMap(x→g(x).flatMap(h))
- in the chain of function applications, it should not matter how functions are nested

you can refer to the wiki for the lecture notes 
https://github.com/nus-cs2030/2324-s2/wiki/Lecture09

i also looked up additional explanation on this and i think this helped me understand monads a little better!
https://dzone.com/articles/what-is-a-monad-basic-theory-for-a-java-developer

**Comment by travistan2003** [comment]
oh wow okay thank you so much!
