### ISSUE TITLE
Updating of wait time

### ISSUE THREAD

**Issue by pinkhydroflask** [nus-cs2030/2324-s2#770]
Hello! Does anyone have any advice on how to check why the wait time is not updating when the `getWaitTime` is called in my simulator class? In my implementation, the wait time is only calculated in my serve event where i take the current timeStamp - customer arrival time, while the rest of the event classes have an empty implementation.
here is my current method call in the simulator:
<img width="593" alt="Screenshot 2024-04-26 at 4 40 47 PM" src="https://github.com/nus-cs2030/2324-s2/assets/167305015/66437170-1ef7-4acf-8cc4-49f19c811a03">

however in my output the sequence of events seems to be correct but the waitTime remains as 0 resulting in the final `avgWaitTime` to also be 0.000:
<img width="593" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/167305015/2b877b33-832d-48fa-a46b-c81245f9a106">

**Comment by W-WJ-Ryan** [comment]
hi can i ask what does your getWaitingTime(waitTime) method do? Does it pass the waitTime into the event and then gets the event to preform the update on it?

**Comment by xinnyyy** [comment]
hello! for ur serve event, i think u need to do 
waitingTime = waitingTime + timeStamp - this.customer.findArrivaltime();

instead of just current timeStamp - customer arrival time, because the waiting time needs to be passed down from arrival event all the way to done event

**Comment by pinkhydroflask** [comment]
> hello! for ur serve event, i think u need to do waitingTime = waitingTime + timeStamp - this.customer.findArrivaltime();
> 
> instead of just current timeStamp - customer arrival time, because the waiting time needs to be passed down from arrival event all the way to done event

i see okay! thanks for your help it works now :)
