### ISSUE TITLE
project time limit exceeded

### ISSUE THREAD

**Issue by mccqi** [nus-cs2030/2324-s2#779]
<img width="1438" alt="Screenshot 2024-04-27 at 4 02 35 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157803620/6f42face-da04-4e54-975c-7f063aaa1531">

hii, im facing this error for the project, is there any possible test cases i can run on my side? I have tried to adjust service timings, but I currently don't get an infinite loop.

**Comment by starryfieldz** [comment]
Hi, you can check this out https://github.com/nus-cs2030/2324-s2/issues/758, also you can try checking the Wait/TransitWait classes as those were the areas where I discovered bugs. Hope this helps!

**Comment by mccqi** [comment]
Yepp, I was aware of the #758. I tried out all the provided test cases, and my output all matches, so I dont know how to get around this specific issue

**Comment by starryfieldz** [comment]
Perhaps you can try printing some statements, especially in areas where ur customer is waiting to be served at SCCs

**Comment by mccqi** [comment]
i think for 9_04, the SCC arent involved yet?

**Comment by c-510** [comment]
check your execute for the final events! if u used any loops, is it also possible that you might have accidentally initiated an infinite loop? @starryfieldz suggestion is rly good, thats what i did too

**Comment by mccqi** [comment]
will consider that, thanks!
