### ISSUE TITLE
Can we get other checkers (that check for banned keywords)?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#78]
Otherwise, we submit into Codecrunch and cause it to waste resources because of banned words (e.g. `Optional.of()`, `null` or even `isinstance`)...

**Comment by samuelneo** [comment]
if you've set up checkstyle, you can just run `checkstyle` on your java files, it does the same thing :)

**Comment by ZHD1987E** [comment]
Let me go back and prove your theory. Read the source code and I don’t think it does…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by samuelneo** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/24467645/b632dd9f-056c-41c8-afea-81a57709b33b)
looks fine for me. first checkstyle was with all the files following CS2030's code style, then I modified `Server.java` to have a magic number, ran checkstyle again and it pointed out the magic number

**Comment by ZHD1987E** [comment]
Ran that:

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/1ebd6f49-74bd-4c4d-8d37-c3edb0a05faa)

It does not pick up any banned words.

**Comment by hwkchia** [comment]
You shouldn't need checkers.  You should have self-discipline. 🖖
