### ISSUE TITLE
AY2122S2 finals help

### ISSUE THREAD

**Issue by w1nsl** [nus-cs2030/2324-s2#782]
<img width="492" alt="Screenshot 2024-04-27 at 9 36 00 PM" src="https://github.com/nus-cs2030/2324-s2/assets/148077346/f7531d90-f083-47e4-a46f-30e8dad128e2">
<img width="522" alt="Screenshot 2024-04-27 at 9 36 13 PM" src="https://github.com/nus-cs2030/2324-s2/assets/148077346/2603e037-cd4c-4e0a-9175-b1861a0ba7ee">

can someone help me out with this question, i have no clue how to do it

**Comment by LimZiXiong** [comment]
This question is very similar to one of the PA2 question (Stringable). I used the same method and it seem to work. I used Optional<Function<Consumer<String>, String>>

**Comment by LimZiXiong** [comment]
`import java.util.List;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Iterator;
import java.util.stream.Stream;

/**
 * An immutable implementation of the {@code ArrayList} using an 
 * immutable delegation design pattern.
 *
 * @author  cs2030
 * @param <E> the type of elements in this list
 */
public class ImList<E> implements Iterable<E> {
    private final ArrayList<E> elems;
    private final Optional<Function<Consumer<String>, String>> f;
    /**
     * Constructs an empty list.
     */
    public ImList() {
        this.elems = new ArrayList<E>();
        this.f = Optional.empty();
    }

    /**
     * Constructs a list containing the elements of the specified list of
     * type {@code List}, in the order they are returned by the latter's
     * iterator.
     *
     * @param list the list whose elements are to be placed into this list
     * @throws NullPointerException if the specified list is null
     */    
    public ImList(List<? extends E> list) {
        this.elems = new ArrayList<E>(list);
        this.f = Optional.empty();
    }

    public ImList(List<? extends E> list, Function<Consumer<String>, String> f) {
        this.elems = new ArrayList<E>(list);
        this.f = Optional.of(f);
    }

    /**
     * Appends the specified element to the end of this list.
     *
     * @param elem element to be appended to this list
     * @return the list with the element added
     */
    public ImList<E> add(E elem) {
        ImList<E> newList = new ImList<E>(this.elems, x -> {
            this.f.map(a -> a.apply(x));
            String hold2 = "Adding: " + elem.toString();
            x.accept(hold2);
            return hold2;
        });
        newList.elems.add(elem);
        return newList;
    }

    /**
     * Appends all of the elements in the specified immutable list to
     * the end of this list, in the order that they are returned by the
     * specified list's Iterator.  
     *
     * @param list list containing elements to be added to this list
     * @return the list with the all elements of the specified list appended
     * @throws NullPointerException if the specified collection is null
     */
    public ImList<E> addAll(ImList<? extends E> list) {
        return this.addAll(list.elems);
    }

    /**
     * Appends all of the elements in the specified (@code List) list to
     * the end of this list, in the order that they are returned by the
     * specified list's Iterator.  
     *
     * @param list list containing elements to be added to this list
     * @return the list with the all elements of the specified list appended
     * @throws NullPointerException if the specified collection is null
     */
    public ImList<E> addAll(List<? extends E> list) {
        ImList<E> newList = new ImList<E>(this.elems);
        newList.elems.addAll(list);
        return newList;
    }

    /**
     * Compares the specified object with this immutable list for equality.
     * Returns {@code true} if and only if the specified object is also an
     * immutable list having the same size, and all corresponding pairs of
     * elements in the two lists are <i>equal</i>.  (Two elements {@code e1}
     * and {@code e2} are <i>equal</i> if {@code Objects.equals(e1, e2)}.)
     * In other words, two immutable lists are defined to be
     * equal if they contain the same elements in the same order.  
     *
     * @param obj the object to be compared for equality with this list
     * @return {@code true} if the specified object is equal to this list
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        } else if (obj instanceof ImList<?> otherList) {
            return this.elems.equals(otherList.elems);
        } else {
            return false;
        }
    }

    /**
     * Returns the element at the specified position in this list.
     *
     * @param  index index of the element to return
     * @return the element at the specified position in this list
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public E get(int index) {
        Consumer<String> ff = x -> System.out.println(x);
        f.orElseThrow().apply(ff);
        return this.elems.get(index);
    }

    /**
     * Returns the hash code value for this list.
     *
     * @return the hash code value for this list
     */
    @Override
    public int hashCode() {
        return this.elems.hashCode();
    }

    /**
     * Returns the index of the first occurrence of the specified element
     * in this list, or -1 if this list does not contain the element.
     * More formally, returns the lowest index {@code i} such that
     * {@code Objects.equals(obj, get(i))},
     * or -1 if there is no such index.
     *
     * @param obj element to search for
     * @return the index of the first occurrence of the specified element in
     *         this list, or -1 if this list does not contain the element
     */
    public int indexOf(Object obj) {
        return this.elems.indexOf(obj);
    }

    /**
     * Returns {@code true} if this list contains no elements.
     *
     * @return {@code true} if this list contains no elements
     */ 
    public boolean isEmpty() {
        return this.elems.isEmpty();
    }

    /**
     * Returns an iterator over the elements in this list in proper sequence.
     *
     * @return an iterator over the elements in this list in proper sequence
     */
    public Iterator<E> iterator() {
        return this.elems.iterator();
    }

    /**
     * Removes the element at the specified position in this list.
     *
     * @param index the index of the element to be removed
     * @return the list after removal of the element
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public ImList<E> remove(int index) {
        ImList<E> newList = new ImList<E>(this.elems);
        if (index >= 0 && index < this.size()) {
            newList.elems.remove(index);
        }
        return newList;
    }

    /**
     * Replaces the element at the specified position in this list with
     * the specified element.
     *
     * @param index index of the element to replace
     * @param elem element to be stored at the specified position
     * @return the list after replacement of the element
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public ImList<E> set(int index, E elem) {
        ImList<E> newList = new ImList<E>(this.elems, x -> {
            this.f.map(a -> a.apply(x));
            String hold = "Setting: " + index + " to " + elem.toString();
            x.accept(hold);
            return hold;
        });
        if (index >= 0 && index < this.size()) {
            newList.elems.set(index, elem);
        }
        //System.out.println("Setting: " + index + " to " + elem.toString());
        return newList;
    }

    /**
     * Returns the number of elements in this list.
     *
     * @return the number of elements in this list
     */
    public int size() {
        return this.elems.size();
    }

    /**
     * Sorts this list according to the order induced by the specified
     * {@link Comparator}.  The sort is <i>stable</i>: this method must not
     * reorder equal elements.
     *
     * <p>All elements in this list must be <i>mutually comparable</i> using the
     * specified comparator (that is, {@code c.compare(e1, e2)} must not throw
     * a {@code ClassCastException} for any elements {@code e1} and {@code e2}
     * in the list).
     *
     * <p>If the specified comparator is {@code null} then all elements in this
     * list must implement the {@link Comparable} interface and the elements'
     * {@linkplain Comparable natural ordering} should be used.
     *
     * @param cmp the {@code Comparator} used to compare list elements.
     *          A {@code null} value indicates that the elements'
     *          {@linkplain Comparable natural ordering} should be used
     * @return the sorted list
     * @throws ClassCastException if the list contains elements that are not
     *         <i>mutually comparable</i> using the specified comparator
     * @throws UnsupportedOperationException if the list's list-iterator does
     *         not support the {@code set} operation
     * @throws IllegalArgumentException
     *         (<a href="Collection.html#optional-restrictions">optional</a>)
     *         if the comparator is found to violate the {@link Comparator}
     *         contract
     */
    public ImList<E> sort(Comparator<? super E> cmp) {
        ImList<E> newList = new ImList<E>(this.elems);
        newList.elems.sort(cmp);
        return newList;
    }

    /**
     * Returns a sequential {@code Stream} with this immutable list as its source.
     *
     * @return a sequential {@code Stream} over the elements in this immutable list
     * @since 1.8
     */
    public Stream<E> stream() {
        return this.elems.stream();
    }

    /**
     * Returns a string representation of this list.  The string
     * representation consists of a list of elements in the order they are
     * returned by its iterator, enclosed in square brackets ({@code "[]"}).  
     * Adjacent elements are separated by the characters {@code ", "} (comma and space).
     * Elements are converted to strings as by {@link String#valueOf(Object)}.
     *
     * @return a string representation of this list
     */
    @Override
    public String toString() {
        return "ImList";
    }
}
`

**Comment by LimZiXiong** [comment]
```
import java.util.List;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Iterator;
import java.util.stream.Stream;

/**
 * An immutable implementation of the {@code ArrayList} using an 
 * immutable delegation design pattern.
 *
 * @author  cs2030
 * @param <E> the type of elements in this list
 */
public class ImList<E> implements Iterable<E> {
    private final ArrayList<E> elems;
    private final Optional<Function<Consumer<String>, String>> f;
    /**
     * Constructs an empty list.
     */
    public ImList() {
        this.elems = new ArrayList<E>();
        this.f = Optional.empty();
    }

    /**
     * Constructs a list containing the elements of the specified list of
     * type {@code List}, in the order they are returned by the latter's
     * iterator.
     *
     * @param list the list whose elements are to be placed into this list
     * @throws NullPointerException if the specified list is null
     */    
    public ImList(List<? extends E> list) {
        this.elems = new ArrayList<E>(list);
        this.f = Optional.empty();
    }

    public ImList(List<? extends E> list, Function<Consumer<String>, String> f) {
        this.elems = new ArrayList<E>(list);
        this.f = Optional.of(f);
    }

    /**
     * Appends the specified element to the end of this list.
     *
     * @param elem element to be appended to this list
     * @return the list with the element added
     */
    public ImList<E> add(E elem) {
        ImList<E> newList = new ImList<E>(this.elems, x -> {
            this.f.map(a -> a.apply(x));
            String hold2 = "Adding: " + elem.toString();
            x.accept(hold2);
            return hold2;
        });
        newList.elems.add(elem);
        return newList;
    }

    /**
     * Appends all of the elements in the specified immutable list to
     * the end of this list, in the order that they are returned by the
     * specified list's Iterator.  
     *
     * @param list list containing elements to be added to this list
     * @return the list with the all elements of the specified list appended
     * @throws NullPointerException if the specified collection is null
     */
    public ImList<E> addAll(ImList<? extends E> list) {
        return this.addAll(list.elems);
    }

    /**
     * Appends all of the elements in the specified (@code List) list to
     * the end of this list, in the order that they are returned by the
     * specified list's Iterator.  
     *
     * @param list list containing elements to be added to this list
     * @return the list with the all elements of the specified list appended
     * @throws NullPointerException if the specified collection is null
     */
    public ImList<E> addAll(List<? extends E> list) {
        ImList<E> newList = new ImList<E>(this.elems);
        newList.elems.addAll(list);
        return newList;
    }

    /**
     * Compares the specified object with this immutable list for equality.
     * Returns {@code true} if and only if the specified object is also an
     * immutable list having the same size, and all corresponding pairs of
     * elements in the two lists are <i>equal</i>.  (Two elements {@code e1}
     * and {@code e2} are <i>equal</i> if {@code Objects.equals(e1, e2)}.)
     * In other words, two immutable lists are defined to be
     * equal if they contain the same elements in the same order.  
     *
     * @param obj the object to be compared for equality with this list
     * @return {@code true} if the specified object is equal to this list
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        } else if (obj instanceof ImList<?> otherList) {
            return this.elems.equals(otherList.elems);
        } else {
            return false;
        }
    }

    /**
     * Returns the element at the specified position in this list.
     *
     * @param  index index of the element to return
     * @return the element at the specified position in this list
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public E get(int index) {
        Consumer<String> ff = x -> System.out.println(x);
        f.orElseThrow().apply(ff);
        return this.elems.get(index);
    }

    /**
     * Returns the hash code value for this list.
     *
     * @return the hash code value for this list
     */
    @Override
    public int hashCode() {
        return this.elems.hashCode();
    }

    /**
     * Returns the index of the first occurrence of the specified element
     * in this list, or -1 if this list does not contain the element.
     * More formally, returns the lowest index {@code i} such that
     * {@code Objects.equals(obj, get(i))},
     * or -1 if there is no such index.
     *
     * @param obj element to search for
     * @return the index of the first occurrence of the specified element in
     *         this list, or -1 if this list does not contain the element
     */
    public int indexOf(Object obj) {
        return this.elems.indexOf(obj);
    }

    /**
     * Returns {@code true} if this list contains no elements.
     *
     * @return {@code true} if this list contains no elements
     */ 
    public boolean isEmpty() {
        return this.elems.isEmpty();
    }

    /**
     * Returns an iterator over the elements in this list in proper sequence.
     *
     * @return an iterator over the elements in this list in proper sequence
     */
    public Iterator<E> iterator() {
        return this.elems.iterator();
    }

    /**
     * Removes the element at the specified position in this list.
     *
     * @param index the index of the element to be removed
     * @return the list after removal of the element
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public ImList<E> remove(int index) {
        ImList<E> newList = new ImList<E>(this.elems);
        if (index >= 0 && index < this.size()) {
            newList.elems.remove(index);
        }
        return newList;
    }

    /**
     * Replaces the element at the specified position in this list with
     * the specified element.
     *
     * @param index index of the element to replace
     * @param elem element to be stored at the specified position
     * @return the list after replacement of the element
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public ImList<E> set(int index, E elem) {
        ImList<E> newList = new ImList<E>(this.elems, x -> {
            this.f.map(a -> a.apply(x));
            String hold = "Setting: " + index + " to " + elem.toString();
            x.accept(hold);
            return hold;
        });
        if (index >= 0 && index < this.size()) {
            newList.elems.set(index, elem);
        }
        //System.out.println("Setting: " + index + " to " + elem.toString());
        return newList;
    }

    /**
     * Returns the number of elements in this list.
     *
     * @return the number of elements in this list
     */
    public int size() {
        return this.elems.size();
    }

    /**
     * Sorts this list according to the order induced by the specified
     * {@link Comparator}.  The sort is <i>stable</i>: this method must not
     * reorder equal elements.
     *
     * <p>All elements in this list must be <i>mutually comparable</i> using the
     * specified comparator (that is, {@code c.compare(e1, e2)} must not throw
     * a {@code ClassCastException} for any elements {@code e1} and {@code e2}
     * in the list).
     *
     * <p>If the specified comparator is {@code null} then all elements in this
     * list must implement the {@link Comparable} interface and the elements'
     * {@linkplain Comparable natural ordering} should be used.
     *
     * @param cmp the {@code Comparator} used to compare list elements.
     *          A {@code null} value indicates that the elements'
     *          {@linkplain Comparable natural ordering} should be used
     * @return the sorted list
     * @throws ClassCastException if the list contains elements that are not
     *         <i>mutually comparable</i> using the specified comparator
     * @throws UnsupportedOperationException if the list's list-iterator does
     *         not support the {@code set} operation
     * @throws IllegalArgumentException
     *         (<a href="Collection.html#optional-restrictions">optional</a>)
     *         if the comparator is found to violate the {@link Comparator}
     *         contract
     */
    public ImList<E> sort(Comparator<? super E> cmp) {
        ImList<E> newList = new ImList<E>(this.elems);
        newList.elems.sort(cmp);
        return newList;
    }

    /**
     * Returns a sequential {@code Stream} with this immutable list as its source.
     *
     * @return a sequential {@code Stream} over the elements in this immutable list
     * @since 1.8
     */
    public Stream<E> stream() {
        return this.elems.stream();
    }

    /**
     * Returns a string representation of this list.  The string
     * representation consists of a list of elements in the order they are
     * returned by its iterator, enclosed in square brackets ({@code "[]"}).  
     * Adjacent elements are separated by the characters {@code ", "} (comma and space).
     * Elements are converted to strings as by {@link String#valueOf(Object)}.
     *
     * @return a string representation of this list
     */
    @Override
    public String toString() {
        return "ImList";
    }
}
```

**Comment by LimZiXiong** [comment]
```
import java.util.List;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Iterator;
import java.util.stream.Stream;

/**
 * An immutable implementation of the {@code ArrayList} using an 
 * immutable delegation design pattern.
 *
 * @author  cs2030
 * @param <E> the type of elements in this list
 */
public class ImList<E> implements Iterable<E> {
    private final ArrayList<E> elems;
    private final Optional<Function<Consumer<String>, String>> f;
    /**
     * Constructs an empty list.
     */
    public ImList() {
        this.elems = new ArrayList<E>();
        this.f = Optional.empty();
    }

    /**
     * Constructs a list containing the elements of the specified list of
     * type {@code List}, in the order they are returned by the latter's
     * iterator.
     *
     * @param list the list whose elements are to be placed into this list
     * @throws NullPointerException if the specified list is null
     */    
    public ImList(List<? extends E> list) {
        this.elems = new ArrayList<E>(list);
        this.f = Optional.empty();
    }

    public ImList(List<? extends E> list, Function<Consumer<String>, String> f) {
        this.elems = new ArrayList<E>(list);
        this.f = Optional.of(f);
    }

    /**
     * Appends the specified element to the end of this list.
     *
     * @param elem element to be appended to this list
     * @return the list with the element added
     */
    public ImList<E> add(E elem) {
        ImList<E> newList = new ImList<E>(this.elems, x -> {
            String hold2 = "Adding: " + elem.toString();
            x.accept(hold2);
            this.f.map(a -> a.apply(x));
            return hold2;
        });
        newList.elems.add(elem);
        return newList;
    }

    /**
     * Appends all of the elements in the specified immutable list to
     * the end of this list, in the order that they are returned by the
     * specified list's Iterator.  
     *
     * @param list list containing elements to be added to this list
     * @return the list with the all elements of the specified list appended
     * @throws NullPointerException if the specified collection is null
     */
    public ImList<E> addAll(ImList<? extends E> list) {
        return this.addAll(list.elems);
    }

    /**
     * Appends all of the elements in the specified (@code List) list to
     * the end of this list, in the order that they are returned by the
     * specified list's Iterator.  
     *
     * @param list list containing elements to be added to this list
     * @return the list with the all elements of the specified list appended
     * @throws NullPointerException if the specified collection is null
     */
    public ImList<E> addAll(List<? extends E> list) {
        ImList<E> newList = new ImList<E>(this.elems);
        newList.elems.addAll(list);
        return newList;
    }

    /**
     * Compares the specified object with this immutable list for equality.
     * Returns {@code true} if and only if the specified object is also an
     * immutable list having the same size, and all corresponding pairs of
     * elements in the two lists are <i>equal</i>.  (Two elements {@code e1}
     * and {@code e2} are <i>equal</i> if {@code Objects.equals(e1, e2)}.)
     * In other words, two immutable lists are defined to be
     * equal if they contain the same elements in the same order.  
     *
     * @param obj the object to be compared for equality with this list
     * @return {@code true} if the specified object is equal to this list
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        } else if (obj instanceof ImList<?> otherList) {
            return this.elems.equals(otherList.elems);
        } else {
            return false;
        }
    }

    /**
     * Returns the element at the specified position in this list.
     *
     * @param  index index of the element to return
     * @return the element at the specified position in this list
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public E get(int index) {
        Consumer<String> ff = x -> System.out.println(x);
        f.orElseThrow().apply(ff);
        return this.elems.get(index);
    }

    /**
     * Returns the hash code value for this list.
     *
     * @return the hash code value for this list
     */
    @Override
    public int hashCode() {
        return this.elems.hashCode();
    }

    /**
     * Returns the index of the first occurrence of the specified element
     * in this list, or -1 if this list does not contain the element.
     * More formally, returns the lowest index {@code i} such that
     * {@code Objects.equals(obj, get(i))},
     * or -1 if there is no such index.
     *
     * @param obj element to search for
     * @return the index of the first occurrence of the specified element in
     *         this list, or -1 if this list does not contain the element
     */
    public int indexOf(Object obj) {
        return this.elems.indexOf(obj);
    }

    /**
     * Returns {@code true} if this list contains no elements.
     *
     * @return {@code true} if this list contains no elements
     */ 
    public boolean isEmpty() {
        return this.elems.isEmpty();
    }

    /**
     * Returns an iterator over the elements in this list in proper sequence.
     *
     * @return an iterator over the elements in this list in proper sequence
     */
    public Iterator<E> iterator() {
        return this.elems.iterator();
    }

    /**
     * Removes the element at the specified position in this list.
     *
     * @param index the index of the element to be removed
     * @return the list after removal of the element
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public ImList<E> remove(int index) {
        ImList<E> newList = new ImList<E>(this.elems);
        if (index >= 0 && index < this.size()) {
            newList.elems.remove(index);
        }
        return newList;
    }

    /**
     * Replaces the element at the specified position in this list with
     * the specified element.
     *
     * @param index index of the element to replace
     * @param elem element to be stored at the specified position
     * @return the list after replacement of the element
     * @throws IndexOutOfBoundsException {@inheritDoc}
     */
    public ImList<E> set(int index, E elem) {
        ImList<E> newList = new ImList<E>(this.elems, x -> {
            
            String hold = "Setting: " + index + " to " + elem.toString();
            x.accept(hold);
            this.f.map(a -> a.apply(x));
            return hold;
        });
        if (index >= 0 && index < this.size()) {
            newList.elems.set(index, elem);
        }
        //System.out.println("Setting: " + index + " to " + elem.toString());
        return newList;
    }

    /**
     * Returns the number of elements in this list.
     *
     * @return the number of elements in this list
     */
    public int size() {
        return this.elems.size();
    }

    /**
     * Sorts this list according to the order induced by the specified
     * {@link Comparator}.  The sort is <i>stable</i>: this method must not
     * reorder equal elements.
     *
     * <p>All elements in this list must be <i>mutually comparable</i> using the
     * specified comparator (that is, {@code c.compare(e1, e2)} must not throw
     * a {@code ClassCastException} for any elements {@code e1} and {@code e2}
     * in the list).
     *
     * <p>If the specified comparator is {@code null} then all elements in this
     * list must implement the {@link Comparable} interface and the elements'
     * {@linkplain Comparable natural ordering} should be used.
     *
     * @param cmp the {@code Comparator} used to compare list elements.
     *          A {@code null} value indicates that the elements'
     *          {@linkplain Comparable natural ordering} should be used
     * @return the sorted list
     * @throws ClassCastException if the list contains elements that are not
     *         <i>mutually comparable</i> using the specified comparator
     * @throws UnsupportedOperationException if the list's list-iterator does
     *         not support the {@code set} operation
     * @throws IllegalArgumentException
     *         (<a href="Collection.html#optional-restrictions">optional</a>)
     *         if the comparator is found to violate the {@link Comparator}
     *         contract
     */
    public ImList<E> sort(Comparator<? super E> cmp) {
        ImList<E> newList = new ImList<E>(this.elems);
        newList.elems.sort(cmp);
        return newList;
    }

    /**
     * Returns a sequential {@code Stream} with this immutable list as its source.
     *
     * @return a sequential {@code Stream} over the elements in this immutable list
     * @since 1.8
     */
    public Stream<E> stream() {
        return this.elems.stream();
    }

    /**
     * Returns a string representation of this list.  The string
     * representation consists of a list of elements in the order they are
     * returned by its iterator, enclosed in square brackets ({@code "[]"}).  
     * Adjacent elements are separated by the characters {@code ", "} (comma and space).
     * Elements are converted to strings as by {@link String#valueOf(Object)}.
     *
     * @return a string representation of this list
     */
    @Override
    public String toString() {
        return "ImList";
    }
}
```

**Comment by xiang-qiuyu** [comment]
1 import java.util.List;
  2 import java.util.ArrayList;
  3 import java.util.function.Supplier;
  4
  5 class ImList<T> {
  6
  7     private final Supplier<List<T>> list;
  8
  9     ImList() {
 10         this.list = () -> new ArrayList<T>();
 11     }
 12
 13     private ImList(Supplier<List<T>> list) {
 14         this.list = list;
 15     }
 16
 17     ImList<T> add(T t) {
 18         return new ImList<T>(() -> {
 19             System.out.println("Adding: " + t);
 20             List<T> newList = new ArrayList<T>(this.list.get());
 21             newList.add(t);
 22             return newList;
 23         });
 24     }
 25
 26     ImList<T> set(int index, T t) {
 27         return new ImList<T>(() -> {
 28             System.out.println("Setting: " + index + ", " + t);
 29             List<T> newList = new ArrayList<T>(this.list.get());
 30             newList.set(index, t);
 31             return newList;
 32         });
 33     }
 34
 35     T get(int index) {
 36         return this.list.get().get(index);
 37     }
 38
 39     public String toString() {
 40         return "ImList";
 41     }
 42 }

Instead of having a List<T> as an attribute, I had a Supplier<List<T>>. Not sure if it's correct but it works for the test cases below.

**Comment by w1nsl** [comment]
thank you!

**Comment by lifrocszh** [comment]
I implemented it using runnables:  



import java.util.List;
import java.util.ArrayList;


class ImList<T> {
    private final ArrayList<T> list;
    private final ArrayList<Runnable> runnables;
    
    ImList() {
        this.list = new ArrayList<T>();
        this.runnables = new ArrayList<Runnable>();
    }
    
    private ImList(ArrayList<T> list, ArrayList<Runnable> runnables) {
        this.list = list;
        this.runnables = runnables;
    }
    
    ImList<T> add(T t) {
        runnables.add(() -> {
            System.out.println("Adding: " + t);
            list.add(t);
        });
        return new ImList<>(list, runnables);
    }
    
    ImList<T> set(int index, T t) {
        runnables.add(() -> {
            System.out.println("Setting: " + index + ", " + t);
            list.set(index, t);
        });
        return new ImList<>(list, runnables);
    }
    
    T get(int index) {
        for (Runnable runnable: runnables) {
            runnable.run();
        }
        return list.get(index);
    }
    
    @Override
    public String toString() {
        return "ImList";
    }
}
