### ISSUE TITLE
vim stuff

### ISSUE THREAD

**Issue by oneday578** [nus-cs2030/2324-s2#783]
- :! after pressing esc it'll show you the vim screen (the one with the $ idk what it's called) so that you can look at errors/warnings and stuff then clicking enter will take you back to your cursor in the code. So you don't need to like navigate back to where you were editing etc.

- pressing v will get you visual mode to copy and paste large chunks of texts

- o will give you a new line in insert mode

- right click to paste

- double click [ ] to go to the start and end of the code

- for easy compiling can just write a jsh file with /open name.java in order, then open jsh file in jshell

**Comment by CSnoobCS** [comment]
thanks for the insights but i dont think we can use vim in finals though.

**Comment by lohkeyyy** [comment]
yea not gna use vim ever aft pa2... just use VSCODE for future work or projects

**Comment by quadryan** [comment]
Perhaps this could be shared with CS2030 students next sem onwards :)

**Comment by oneday578** [comment]
Awww man, thanks for letting me know, i didn't realise this is the last time we're using vim.
