### ISSUE TITLE
Project Test Case 9_9

### ISSUE THREAD

**Issue by branbranyu** [nus-cs2030/2324-s2#785]
<img width="1211" alt="Screenshot 2024-04-28 at 1 17 42 AM" src="https://github.com/nus-cs2030/2324-s2/assets/164456159/f0bbcd60-d89e-4617-a904-3f5ebc803d78">
 
Can anyone help me please :(

**Comment by quadryan** [comment]
Hey there, it might have something to do with your wait event (if you implemented such that customer always waits at first self check). Did you loop thru list of avail servers? and if yes, did you transfer over the wrong index/ID (maybe of the first SC) to the serve event?

**Comment by branbranyu** [comment]
Hey, yeap you're right sia, I called the toString(), let me try to fix it! Thank you!

**Comment by Timmyneedsbzahelp** [comment]
I think you are not passing in the right SCC server! from the correct timings it seems that the right server is being served just that the string u are printing is wrong :(( The other issue is probably just your arrival even not managing when the server should wait properly, might want to double check if you are looping through the SCCs even if there are no human servers (in the case of test case 9)! All the best!

**Comment by branbranyu** [comment]
Ohh that makes sense thank you!
