### ISSUE TITLE
Project Testcase 9_12

### ISSUE THREAD

**Issue by EhYongE** [nus-cs2030/2324-s2#793]
# Summary
Anyone could help me on how to solve this?

## Description 
I thought maybe there's some error with Event Comparator, but I'm not so sure about it.

My thought was that my current implementation executes in such order of : 

(Queue 994) -> (Queue 995) 
Once Queue.nextEvent() (i.e. Serve) is executed, the event queue goes as : 
(Queue 995) -> (Serve 994) 
while it's supposed to be :
(Serve 994) -> (Queue 995)

But I've been playing around with the Event Comparator, but I am not seeing any special changes in the output. 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://github.com/nus-cs2030/2324-s2/assets/88820796/32867d6b-1041-4244-8606-d87d5ecd123b)

This is my eventcomparator: 
![image](https://github.com/nus-cs2030/2324-s2/assets/88820796/84edc775-4269-4e32-9f37-0ff2e9fdcba6)

**Comment by ZHD1987E** [comment]
Honestly speaking, the customer's arrival number matters more.

**Comment by EhYongE** [comment]
> Honestly speaking, the customer's arrival number matters more.
> 
> By using a String-based comparison, this can cause problems to arise thanks to the lexicographical ordering, which might not be what you want.

I am assuming what you mean by customer's arrival number = customerID, 

Apparently my aa.compare(bb) compares their ID, I have fixed my comparator to make more sense, but still causing the same error

**Comment by ZHD1987E** [comment]
You should NOT consider event length at all!

**Comment by W-WJ-Ryan** [comment]
> > Honestly speaking, the customer's arrival number matters more.
> > By using a String-based comparison, this can cause problems to arise thanks to the lexicographical ordering, which might not be what you want.
> 
> I am assuming what you mean by customer's arrival number = customerID,
> 
> Apparently my aa.compare(bb) compares their ID, I have fixed my comparator to make more sense, but still causing the same error
> 
> My comparison order is :
> 
> 1. arrival time
> 2. customer number
> 3. event length (serves/done b4 queue/wait)

hi bro, i think your first 2 should suffice already as there shouldnt be an instance where there are 2 events with the same customer since each customer is supposed to have only 1 event at any one time in the pq anyway

**Comment by EhYongE** [comment]
> > > Honestly speaking, the customer's arrival number matters more.
> > > By using a String-based comparison, this can cause problems to arise thanks to the lexicographical ordering, which might not be what you want.
> > 
> > 
> > I am assuming what you mean by customer's arrival number = customerID,
> > Apparently my aa.compare(bb) compares their ID, I have fixed my comparator to make more sense, but still causing the same error
> > My comparison order is :
> > 
> > 1. arrival time
> > 2. customer number
> > 3. event length (serves/done b4 queue/wait)
> 
> hi bro, i think your first 2 should suffice already as there shouldnt be an instance where there are 2 events with the same customer since each customer is supposed to have only 1 event at any one time in the pq anyway

Yep I'm not using string comparison at all anymore. Still having the same issue tho

**Comment by LimJiaWeng** [comment]
Comparing the event time followed by customer number should be sufficient because if 2 events have the same time, then the customer who arrived first should have their event occur first (eg. 4 done before 5 is served)
