### ISSUE TITLE
REMINDER: PA2 AND PROJECT IS DUE TODAY!!!

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#794]
Did you submit PA2? Did you submit the Project? Did you submit Exercise 6?

# NO?

**THEN DO IT NOW!!!**

![RightNowGIF](https://github.com/nus-cs2030/2324-s2/assets/140680858/ffe9394d-352c-4ccd-8a96-f332a19437d4)

**Comment by ZHD1987E** [comment]
# Also as a reminder...

It is good to try out some past papers but take breaks and don't overdo it.

**Comment by hansneddyanto** [comment]
Thank you for the reminders! :D

**Comment by jaydenntann77** [comment]
Thank you for the timely reminder!

**Comment by JosiahPraeman** [comment]
thanks for the reminders haodong

**Comment by CSnoobCS** [comment]
you're so upz!

**Comment by tyy28** [comment]
Thank you for the reminder!

**Comment by wxlee1807** [comment]
thanks for the reminder!

**Comment by ZHD1987E** [comment]
It's over.
