### ISSUE TITLE
restriction for finals

### ISSUE THREAD

**Issue by jianhaosoh** [nus-cs2030/2324-s2#798]
Will there by any restrictions for finals just like PE? Eg. cannot use Optional's get() etc or in general we can just assume everything can be used?

**Comment by ezclap02** [comment]
i think it will be specified in the question if any methods are banned

**Comment by W-WJ-Ryan** [comment]
> i think it will be specified in the question if any methods are banned

yep, i think what she said was correct but based on pyps you can probably expect the standard stuff like null values, Optional getters, and adherence to OOP principles etc

**Comment by JosiahPraeman** [comment]
> > i think it will be specified in the question if any methods are banned
> 
> yep, i think what she said was correct but based on pyps you can probably expect the standard stuff like null values, Optional getters, and adherence to OOP principles etc

agree on this the question should specify but i think prof chia expects us to stick with the proper coding principles.

**Comment by isabellatjx** [comment]
i think in each question they will tell you what methods to not use

**Comment by wxlee1807** [comment]
yup i think they will js specify it in the preamble or question!
