### ISSUE TITLE
unable to install msys for windows

### ISSUE THREAD

**Issue by garethdcruz** [nus-cs2030/2324-s2#8]
# Summary
Hi I keep getting the same given error message when attempting to download msys(step 3 in setting up Unix for windows). I have used the troubleshooting methods mentioned in the previous threads but they havent worked for me. Any help would be much appreciated!

![Command Prompt 16_1_2024 12_41_16 am](https://github.com/nus-cs2030/2324-s2/assets/137087296/99383f43-1ded-4a90-908d-5484d88dbe5a)

**Comment by ZHD1987E** [comment]
Try this command instead:

`scoop install main/msys`

**Comment by hwkchia** [comment]
That's interesting... I wonder why we need to specify the `main` bucket.  Please let me know if this works?  If it does, we will then update the wiki.

**Comment by ZHD1987E** [comment]
Hello.

I tried it, it works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by garethdcruz** [comment]
> Try this command instead:
> 
> `scoop install main/msys`
This command worked perfectly. Thanks!
