### ISSUE TITLE
PYP 23/24 Sem 1 Q9

### ISSUE THREAD

**Issue by timothyngcy** [nus-cs2030/2324-s2#802]
Hi all! 

I was looking at the PYP video and for the `thenApply(Task task)` method, is there a reason why this return is valid?

`return UOpOrCF.applyB....` should return a CompletableFuture<Integer> but the return type of `thenApply(Task task)` is `Task`. Is there something that I'm missing?

<img width="976" alt="Screenshot 2024-04-29 at 1 31 21 AM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/049f70ca-ab93-4002-b124-95e4cde5d3c0">

Thanks in advance!

**Comment by samuelneo** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/24467645/f2551e25-737c-4b92-89c3-4be1475ffaff)
prof edited it in the last minute of the video
