### ISSUE TITLE
Avoiding Cyclic Dependency

### ISSUE THREAD

**Issue by Partillay** [nus-cs2030/2324-s2#803]
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/c3fdfcee-4d19-4af4-a034-3c659b4f19cc)
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/352199f7-c7b8-41af-8ae2-9547c7539a7c)

This question was from AY2110, I want to ask, to what extent are classes identified to be cyclic dependent on one another? If the toggle() method under RedLight returns a GreenLight object, are they dependent already? If so, does anyone know how to implement a proper design to prevent such dependency?

**Comment by W-WJ-Ryan** [comment]
No, i don't believe what you mentioned is considered cyclic dependency. I would say cyclic dependency occurs when two or more classes depend on each other directly or indirectly during their instantiation or construction. This means that Class A depends on Class B, and Class B depends on Class A, forming a loop of dependencies.

**Comment by Partillay** [comment]
> No, i don't believe what you mentioned is considered cyclic dependency. I would say cyclic dependency occurs when two or more classes depend on each other directly or indirectly during their instantiation or construction. This means that Class A depends on Class B, and Class B depends on Class A, forming a loop of dependencies.

Hmm, but based on 2(a), if toggle() returns RedLight and GreenLight for GreenLight and RedLight respectively, the question will think that there is cyclic dependency, unless my speculation is wrong.

**Comment by W-WJ-Ryan** [comment]
> > No, i don't believe what you mentioned is considered cyclic dependency. I would say cyclic dependency occurs when two or more classes depend on each other directly or indirectly during their instantiation or construction. This means that Class A depends on Class B, and Class B depends on Class A, forming a loop of dependencies.
> 
> Hmm, but based on 2(a), if toggle() returns RedLight and GreenLight for GreenLight and RedLight respectively, the question will think that there is cyclic dependency, unless my speculation is wrong.

Hmmmmm, wait why tho. Because redlight or green light does not depend on each other to instantiate tho. Rather, it is just the state in which the method references but returns a new light based on the ifelse logic. I.e. one does not have to exist before the other can be instantiated. In my understanding that doesn't violate cyclic dependency

**Comment by xiang-qiuyu** [comment]
> > > No, i don't believe what you mentioned is considered cyclic dependency. I would say cyclic dependency occurs when two or more classes depend on each other directly or indirectly during their instantiation or construction. This means that Class A depends on Class B, and Class B depends on Class A, forming a loop of dependencies.
> > 
> > 
> > Hmm, but based on 2(a), if toggle() returns RedLight and GreenLight for GreenLight and RedLight respectively, the question will think that there is cyclic dependency, unless my speculation is wrong.
> 
> Hmmmmm, wait why tho. Because redlight or green light does not depend on each other to instantiate tho. Rather, it is just the state in which the method references but returns a new light based on the ifelse logic. I.e. one does not have to exist before the other can be instantiated. In my understanding that doesn't violate cyclic dependency

this is chatgpt's take which aligns with ryan's understanding:

In the scenario you've described, where the toggle() method of one class returns an instance of another class and vice versa, there is no cyclic dependency.

Cyclic dependency occurs when two or more classes depend on each other directly or indirectly during their instantiation or construction. This means that Class A depends on Class B, and Class B depends on Class A, forming a loop of dependencies.

In the case of the toggle() method returning instances of RedLight and GreenLight, there's no cyclic dependency because:

The classes RedLight and GreenLight can be instantiated independently of each other.
The toggle() method simply returns a new instance based on the current state, without directly depending on the class definitions during construction.
There's no loop of dependencies during instantiation or construction, as each class can exist and function independently.

but it's weird that the question specified "unlike in qn 2a, there should be no cyclic dependencies among classes" since ifl most people would have already implemented the return new GreenLight() return new RedLight() way which according to chatgpt and ryan, does not result in cyclic dependency.

**Comment by xiang-qiuyu** [comment]
tbh i have no idea how to do (c) and (d) with the restrictions implemened by the question, would greatly appreciate if anyone knows how to solve them!

**Comment by LimZiXiong** [comment]
> tbh i have no idea how to do (c) and (d) with the restrictions implemened by the question, would greatly appreciate if anyone knows how to solve them!

for qn c what I did is to create a new amberLight class. I dont think it's cyclic though honestly not sure but amber will return red so the sequence will become red -> green -> amber -> red.

For qn2d i believe the question didn't stop you from creating new classes so what I did is to create newAmber1 newAmber2 newRed and newGreen class. 2 amber class is needed because the amber from red will return green while the amber from green will return red. dk if this approach is acceptable but it's the only way i could think of

**Comment by Partillay** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/df983c55-6569-4f77-a390-ad1dcc9ea6d5)
![image](https://github.com/nus-cs2030/2324-s2/assets/157334305/6351bfd3-b16c-4ad4-b4d4-1293a0d443ce)
Hi everyone, I looked at forum of previous semester (my short memory brain forgot which sem's forum was it from) and they mentioned the usage of anonymous inner classes (TrafficLight and all ColoredLight classes are abstract  here so i guess this is the implementation that the question wanted. By the way, personally, i find the placing of semicolons in the last few lines confusing lolz I might needa work on that.

**Comment by Partillay** [comment]
> ![image](https://private-user-images.githubusercontent.com/157334305/326856191-df983c55-6569-4f77-a390-ad1dcc9ea6d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODk0MDEsIm5iZiI6MTcxNDQ4OTEwMSwicGF0aCI6Ii8xNTczMzQzMDUvMzI2ODU2MTkxLWRmOTgzYzU1LTY1NjktNGY3Ny1hMzkwLWFkMWRjYzllYTZkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNDU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmExMmJmMDZlZTg1ZjIyN2NhODYwOWU5YTJiMGNjMTM1MjU5ZGIzMmFiZThjYzhhZTRhYTIyMjFkZGYwYjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2KijJ05y7C5Q0eplvA_sskOqX2t9b_4Q3NXN5WZ9Mq4) ![image](https://private-user-images.githubusercontent.com/157334305/326854873-6351bfd3-b16c-4ad4-b4d4-1293a0d443ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODk0MDEsIm5iZiI6MTcxNDQ4OTEwMSwicGF0aCI6Ii8xNTczMzQzMDUvMzI2ODU0ODczLTYzNTFiZmQzLWIxNmMtNGFkNC1iNGQ0LTEyOTNhMGQ0NDNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNDU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzk1MTBhYjQ2MDE5ZGY3NDg0MjU3MmUwZjgyNDc0NGZlNTUzMDk0ZTk0Yzk0MjAwODQxNjdhNWQzYTYyYzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tQk4Ay2qsPgB01uL-EE7KOT2g_x0nffREQKwsuY37Ng) Hi everyone, I looked at the forum of one of the previous semesters (my short memory brain forgot which sem's forum was it from) and they mentioned the usage of anonymous inner classes (TrafficLight and all ColoredLight classes are abstract here) so i guess this is the implementation that the question wanted. By the way, personally, i find the placing of semicolons in the last few lines confusing lolz I might needa work on that.

I think this is also why for 2(d) the classes need not be modified at all

**Comment by xiang-qiuyu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/157334305/326856191-df983c55-6569-4f77-a390-ad1dcc9ea6d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODk0MDEsIm5iZiI6MTcxNDQ4OTEwMSwicGF0aCI6Ii8xNTczMzQzMDUvMzI2ODU2MTkxLWRmOTgzYzU1LTY1NjktNGY3Ny1hMzkwLWFkMWRjYzllYTZkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNDU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmExMmJmMDZlZTg1ZjIyN2NhODYwOWU5YTJiMGNjMTM1MjU5ZGIzMmFiZThjYzhhZTRhYTIyMjFkZGYwYjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2KijJ05y7C5Q0eplvA_sskOqX2t9b_4Q3NXN5WZ9Mq4) ![image](https://private-user-images.githubusercontent.com/157334305/326854873-6351bfd3-b16c-4ad4-b4d4-1293a0d443ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODk0MDEsIm5iZiI6MTcxNDQ4OTEwMSwicGF0aCI6Ii8xNTczMzQzMDUvMzI2ODU0ODczLTYzNTFiZmQzLWIxNmMtNGFkNC1iNGQ0LTEyOTNhMGQ0NDNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNDU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzk1MTBhYjQ2MDE5ZGY3NDg0MjU3MmUwZjgyNDc0NGZlNTUzMDk0ZTk0Yzk0MjAwODQxNjdhNWQzYTYyYzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tQk4Ay2qsPgB01uL-EE7KOT2g_x0nffREQKwsuY37Ng) Hi everyone, I looked at the forum of one of the previous semesters (my short memory brain forgot which sem's forum was it from) and they mentioned the usage of anonymous inner classes (TrafficLight and all ColoredLight classes are abstract here) so i guess this is the implementation that the question wanted. By the way, personally, i find the placing of semicolons in the last few lines confusing lolz I might needa work on that.
> 
> I think this is also why for 2(d) the classes need not be modified at all

i see! thank you so much for the update
