### ISSUE TITLE
Error in execution of sample code

### ISSUE THREAD

**Issue by Andrew22Teoh** [nus-cs2030/2324-s2#81]
# Summary

Within the Lab 2 information provided, there is some code to demonstrate how a comparator can be used to sort a list. The first line shows how to create an ImList<Integer> under the List<Integer> interface, which is as follows:
`jshell> List<Integer> list = new ImList<Integer>(List.of(1, 2, 3))`

`list ==> [1, 2, 3]`

However, when I try to run this same line on my msys.bat, I get an error for incompatible types, saying that ImList<Integer> cannot be converted to List<Integer>. (See first screenshot)

Some other parts of the demonstration code also presents a problem, even when I substitute `ImList` with `ArrayList` as a placeholder. When I try running `jshell> PQ<Integer> pq = new PQ<Integer>(new IntComp())`, I get a "cannot find symbol" error, despite being in the directory with PQ.java and having the PQ class show up in `/list`. (See second screenshot)

I'm not sure if this is intended or an oversight of something on my part. Any help would be appreciated!

## Screenshots
![image](https://github.com/nus-cs2030/2324-s2/assets/122327616/2c4bb8df-9474-480c-85be-e4f69819eee4)
![image](https://github.com/nus-cs2030/2324-s2/assets/122327616/77b337fb-3d73-4302-96ea-fdac386e999a)

**Comment by AustinKong** [comment]
Correct me if I'm wrong. But in the documentation for ImList, it shows that ImList only implements the Iterable interface, and not the List interface itself. So, I don't think its possible to create an ImList under the List interface like you have shown.

Screenshot from the documentation for reference:

![image](https://github.com/nus-cs2030/2324-s2/assets/69255175/404a801f-6b0d-4d69-888e-d6f3b7463d98)

**Comment by Andrew22Teoh** [comment]
Thank you for the reply @AustinKong! That makes sense to me, I suppose it must have been a mistake on the part of the sample code provided in Lab 2. 

Can I check if you encounter any issues when trying to create an instance of PQ with the code shown in the Lab 2 instructions? I'm unsure if it's a problem with my machine or setup or if it's another mistake in the Lab 2 instructions.

**Comment by ZHD1987E** [comment]
Yes, I encountered it.

I think that means having to load ALL dependencies, because I think JShell may refuse to load classes if there are any errors, and will spit out an error.

You can try creating a `Main.java` for that to get that around.
