### ISSUE TITLE
mapToObj and map

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#810]
Hi! May I know in the case of generic streams, can mapToObj and map be used interchangeably when we want to convert each element in the stream to another type?

**Comment by W-WJ-Ryan** [comment]
I would say I think so? But it might be safer to use mapToObj when you want to switch types cause essentially what it does is you return a Stream<Obj>, which is very sure that you will not cause a compile error when you map it over.

**Comment by ucantseemexr** [comment]
There is no mapToObj in generic stream since you can just use map to convert the type T to any Type R

**Comment by naomiiiwu** [comment]
tks guys
