### ISSUE TITLE
Are there any solutions for 2324 S1 paper?

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#811]
Are there any solutions for 2324 S1 paper?

**Comment by LimZiXiong** [comment]
check panopto prof did a walkthrough for the paper

**Comment by BZAStudent** [comment]
> check panopto prof did a walkthrough for the paper

wasn't that for 2223 paper?

**Comment by BZAStudent** [comment]
> check panopto prof did a walkthrough for the paper
ok thanks. I missed it
