### ISSUE TITLE
How does stream::reduce with 3 arguments work?

### ISSUE THREAD

**Issue by lifrocszh** [nus-cs2030/2324-s2#812]
the one that takes in identity, accumulator and combiner as arguments

**Comment by W-WJ-Ryan** [comment]
![screenshot-1714467773032](https://github.com/nus-cs2030/2324-s2/assets/157394238/51a19024-f904-44e6-b023-d8384663101c)
![image](https://github.com/nus-cs2030/2324-s2/assets/157394238/e18f5b87-6847-4ed3-8597-91f5b0dd0ff9)

I think the best way to think about this is that upon insertion of the parallel(), the pipeline is segmented into a few portions. Then, the accumulator is performed on the individual segments, before the combiner performs the specified operation combining the result again. It is best to keep in mind that even when performing this, the operations must be associative. We do not know how parallel() treats the pipeline and segments it, so as long as the operation as a whole (accumulator and combiner) is not associative, we will have a chance of obtaining indeterministic results. E.g. (1*2 + 3*4 != 1 + 2*3 + 4). Hence, even if the 2 individual operations are associative, the combined operation need not be
