### ISSUE TITLE
Pastpaper AY22/23 question 4: Optional

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#818]
<img width="1035" alt="Screenshot 2024-04-30 at 11 07 35 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/0ca3d634-5ff6-4caa-aad5-d6457eb85f5c">
Hi anyone knows how this code manages to handle the case where list only contains one element? If theres only one element, how will the map function work? (you basically remove the only element from the list and map? how is that possible? )
Also, Optional.empty().map(whatever) will still return an empty optional right?

**Comment by aloy99** [comment]
We can look at the reduce implementation with identity and BiFunction to see what happens:

![image](https://github.com/nus-cs2030/2324-s2/assets/6649195/5ac068fd-cf43-4393-b623-75ed123ef237)

The function iterates over the elements in `this`, but if there are no elements it simply returns the identity it was initially passed.

In the implementation of reduce that accepts a Function, the call to this other reduce method is made with the first element as the identity. So it returns an Optional that wraps the first (and only) element.

**Comment by naomiiiwu** [comment]
tks I got it!!
