### ISSUE TITLE
AY23/24 Sem 1 Q8

### ISSUE THREAD

**Issue by sje5398p** [nus-cs2030/2324-s2#819]
<img width="823" alt="Screenshot 2024-05-01 at 7 22 30 AM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/7522ecde-3a54-4d52-9219-657676fc46de">

I'm a bit confused as to why it is not necessary to use .get() for the `apply` methods, as I had thought that since a and b are optional, mapping them would also return an optional?

**Comment by starryfieldz** [comment]
orElseThrow() will return what is wrapped inside the optional, and it throws an error if it is empty

**Comment by W-WJ-Ryan** [comment]
I would recommend double checking the API when you face doubts like this. Methods like ```orElse(), orElseGet(), orElseThrow()``` all have a return type of ```<T>``` , hence when you use them, they will unwrap the optional and return the value inside.
