### ISSUE TITLE
Compilation error : actual and formal argument lists differ in length

### ISSUE THREAD

**Issue by HoSCD** [nus-cs2030/2324-s2#82]
# Summary
Hello! While trying to compile LeaveEvent for lab 2 I got this error and I'm unsure of what it means. LeaveEvent inherits from my Abstract Class Event that has the properties customer and time.

## Screenshots
<img width="525" alt="Picture1" src="https://github.com/nus-cs2030/2324-s2/assets/158131860/f1734286-9ac8-4996-a347-04866ed2a44f">

**Comment by Andrew22Teoh** [comment]
Hi, this error just means that you have passed the wrong number of inputs to your constructor argument! You may notice the lines that say 
`required: Customer, double`
`found: Customer`

This means that you are only initialising with a Customer, and omitting the double that is required by your constructor method! Try looking at the constructor definition and your constructor call to ensure that you are passing the correct number and types of input arguments. Hope this helps! :)

**Comment by HoSCD** [comment]
Thanks for the explanation!
