### ISSUE TITLE
Import statements in finals

### ISSUE THREAD

**Issue by sendhelpps** [nus-cs2030/2324-s2#820]
hi just checking do we need to write import statements in our answers for the final?

**Comment by LeeJiaWei23** [comment]
I don't think so. Just the answer is fine.

**Comment by naomiiiwu** [comment]
hi I think we need to if we need to write out the whole class but if its a single method/code snippets theres no need

**Comment by noerrormessage** [comment]
Yea, same. I think you just need to write the answer!

**Comment by ucantseemexr** [comment]
I dont think we need to write the import statement since we are not required to compile

**Comment by CSnoobCS** [comment]
Based on past year walk through videos, we dont need to import.
