### ISSUE TITLE
[AY23/24 S1 Final] Difference between List.of and new ArrayList()

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#822]
Hi, in that paper, I saw this question. It said List is part of `ImmutableCollections`, which I never knew before doing the paper. May I ask why `List<Integer> list = List.of(1, 2, 3)` is different from `List<Integer> list = new ArrayList<>()`, where we can add new elements by `list.add(1)` later?
![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/f7dccde1-b9f0-462c-a9c5-c5a82156b8ed)

**Comment by RaysonTay** [comment]
Hii! The difference between `List.of()` and `new ArrayList<>()` lies in their mutability. `List.of(1, 2, 3)` returns an immutable list, which means that its contents cannot be modified after creation. This is why calling `list.add(1)` on a list created with `List.of()` will result in an `UnsupportedOperationException`. In contrast, a list created with `new ArrayList<>()` is mutable, allowing elements to be added, removed, or changed after its creation, making it suitable for dynamic data manipulation. Hopefully this answers your question!!

**Comment by minhkiwi14** [comment]
> Hii! The difference between `List.of()` and `new ArrayList<>()` lies in their mutability. `List.of(1, 2, 3)` returns an immutable list, which means that its contents cannot be modified after creation. This is why calling `list.add(1)` on a list created with `List.of()` will result in an `UnsupportedOperationException`. In contrast, a list created with `new ArrayList<>()` is mutable, allowing elements to be added, removed, or changed after its creation, making it suitable for dynamic data manipulation. Hopefully this answers your question!!

But may I know why `List.of` is immutable why `new ArrayList<>()` is not? For instance, we can create a new `ImList` via `new ImList<>()` but that `ImList` is immutable (as everyone here knows).

**Comment by noerrormessage** [comment]
Hi! I am abit confused about your question. Are you asking why new ArrayList<>() is not immutable? If that's your question, ArrayList and ImList are different things! ArrayList is a resizable array where you can change variables, add or remove etc. https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html
ImList on the other hand, is what we were using for most of our projects here. The ImList aka Immutable List takes reference from the ArrayList, but it has the immutable component. Hence, everytime we want to make edits to an ImList, we cant directly edit it, but we need to create a new ImList with the changes. Do let me know if i interpreted your question correctly and if I answered it :)

**Comment by LimZiXiong** [comment]
> > Hii! The difference between `List.of()` and `new ArrayList<>()` lies in their mutability. `List.of(1, 2, 3)` returns an immutable list, which means that its contents cannot be modified after creation. This is why calling `list.add(1)` on a list created with `List.of()` will result in an `UnsupportedOperationException`. In contrast, a list created with `new ArrayList<>()` is mutable, allowing elements to be added, removed, or changed after its creation, making it suitable for dynamic data manipulation. Hopefully this answers your question!!
> 
> But may I know why `List.of` is immutable why `new ArrayList<>()` is not? For instance, we can create a new `ImList` via `new ImList<>()` but that `ImList` is immutable (as everyone here knows).

ArrayList is build to be mutable. Writing new ImList<>() vs new ArrayList<>() has nothing to do with immutability. List.of is immutable because java made it this way

**Comment by minhkiwi14** [comment]
> > > Hii! The difference between `List.of()` and `new ArrayList<>()` lies in their mutability. `List.of(1, 2, 3)` returns an immutable list, which means that its contents cannot be modified after creation. This is why calling `list.add(1)` on a list created with `List.of()` will result in an `UnsupportedOperationException`. In contrast, a list created with `new ArrayList<>()` is mutable, allowing elements to be added, removed, or changed after its creation, making it suitable for dynamic data manipulation. Hopefully this answers your question!!
> > 
> > 
> > But may I know why `List.of` is immutable why `new ArrayList<>()` is not? For instance, we can create a new `ImList` via `new ImList<>()` but that `ImList` is immutable (as everyone here knows).
> 
> ArrayList is build to be mutable. Writing new ImList<>() vs new ArrayList<>() has nothing to do with immutability. List.of is immutable because java made it this way

Oh so it is the matter of conventions right?

**Comment by LimZiXiong** [comment]
> > > > Hii! The difference between `List.of()` and `new ArrayList<>()` lies in their mutability. `List.of(1, 2, 3)` returns an immutable list, which means that its contents cannot be modified after creation. This is why calling `list.add(1)` on a list created with `List.of()` will result in an `UnsupportedOperationException`. In contrast, a list created with `new ArrayList<>()` is mutable, allowing elements to be added, removed, or changed after its creation, making it suitable for dynamic data manipulation. Hopefully this answers your question!!
> > > 
> > > 
> > > But may I know why `List.of` is immutable why `new ArrayList<>()` is not? For instance, we can create a new `ImList` via `new ImList<>()` but that `ImList` is immutable (as everyone here knows).
> > 
> > 
> > ArrayList is build to be mutable. Writing new ImList<>() vs new ArrayList<>() has nothing to do with immutability. List.of is immutable because java made it this way
> 
> Oh so it is the matter of conventions right?

If you use List.of(...) it will return a List that cannot be modified. If you use ArrayList then it's mutable. ImList is somewhat in between you can add stuff inside it or remove stuff but to save the changes, you need to assign the variable to the new list

**Comment by minhkiwi14** [comment]
Thanks guys, I understood!
