### ISSUE TITLE
[AY23/24 S1 Final] About binding in generic methods

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#828]
In question 8, the answer given in the video was in the image below. Why do we only have to bind `<C>`, but not A and B (i.e. why don't we do something like `<A,B,C> C apply A(...) { }`)?
![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/62dd3225-8752-4523-a0a1-53cd0b75619a)

**Comment by iceflakes12** [comment]
A and B already defined in the class, so dont have to redefine it for the method. Also B is not relevant here.

**Comment by minhkiwi14** [comment]
> A and B already defined in the class, so dont have to redefine it for the method. Also B is not relevant here.

So that means generic types defined in the class's name need not to be declared again right?

**Comment by iceflakes12** [comment]
> > A and B already defined in the class, so dont have to redefine it for the method. Also B is not relevant here.
> 
> So that means generic types defined in the class's name need not to be declared again right?

ye correct

**Comment by lifrocszh** [comment]
yes, so before you define classes or methods u can to define generics, at the top of IfElse it goes:
```class IfElse<T,R> {...}```
here T and R is defined, so in a method it does not have to be redefined, however if you want to introduce new generics, you have to define them at the begining on each method

**Comment by minhkiwi14** [comment]
Thank you for all your responses.
