### ISSUE TITLE
[AY23/24 S1 Final] Not sure if my issorted is correct

### ISSUE THREAD

**Issue by minhkiwi14** [nus-cs2030/2324-s2#830]
```
<T extends Comparable<T>> boolean issorted(Stream<T> stream) {
   return stream.filter(x -> !x.equals(stream.toList().get((stream.toList().size() - 1))) // filter the last element out of the stream
       .map(x -> new Pair<T,T>(x, stream.toList().get(stream.toList().indexOf(x)+1))) // to pair two consecutive elements
       .map(x -> x.first().compareTo(x.second()) <= 0)
       .allMatch(x -> x == true);
}

```
I know that this method is quite weird, but I am not sure if it would be accepted...

**Comment by sc2603** [comment]
Complexity and Error-Prone: The logic tries to pair each element with its successor by indexing into a list. This is inherently complex and prone to errors, especially around the handling of the last element and the general overhead of managing indices.

**Comment by arqhll** [comment]
hi! i am not too sure but i think there might be a chance it wont be accepted. The method repeatedly converts the stream to a list (stream.toList()) multiple times. In Java, streams are not reusable; once a terminal operation is executed (like toList()), the stream is considered consumed and cannot be used again. hence reusing the stream multiple times in the same expression will throw an IllegalStateException because the stream has already been operated upon or closed.

**Comment by minhkiwi14** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/39adb8ba-5062-4d75-84b5-b2f3421f617d)


I tried to throw the code to jshell and there are too many errors here. Can anyone explain each one for me please?

**Comment by jaydenntann77** [comment]
These are some explanations to your errors:

Error 1: boolean cannot be dereferenced
The expression inside `filter `or `allMatch `returns a boolean primitive, and you cannot call methods on primitives like you can on objects.

Error 2: variable x is already defined
You're trying to redefine the variable x within the same lambda expression scope. In lambda expressions, each parameter name must be unique within its scope.

Error 3: incompatible types: `java.util.stream.Stream<T>` cannot be converted to boolean
You're trying to use a Stream<T> as a `boolean`. This likely occurs in a context where a boolean expression is expected, such as within a `filter `or `allMatch`.

**Comment by minhkiwi14** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/142191494/e36e5dd9-e28d-48e0-968a-9c48e9552d2d)

Actually my code did not compile due to some typos with brackets. But it gives exactly an IllegalStateException that you mentioned. Thanks!

> hi! i am not too sure but i think there might be a chance it wont be accepted. The method repeatedly converts the stream to a list (stream.toList()) multiple times. In Java, streams are not reusable; once a terminal operation is executed (like toList()), the stream is considered consumed and cannot be used again. hence reusing the stream multiple times in the same expression will throw an IllegalStateException because the stream has already been operated upon or closed.

**Comment by ZHD1987E** [comment]
finals is over you can close this issue
