### ISSUE TITLE
 thenCompose vs. thenCombine

### ISSUE THREAD

**Issue by luudgia** [nus-cs2030/2324-s2#834]
what's the difference between them / when should 1 be used over the other?

**Comment by jennipho** [comment]
i think thenCompose you can remember it as a flatMap and thenCombine is used when two separate results of CF (both this and the other CF that is taken in) are combined to work in a bifunction to give you a result

**Comment by Partillay** [comment]
they are analogous to flatMap and reduce

**Comment by ZHD1987E** [comment]
finals is over you can close this issue
