### ISSUE TITLE
Lecture 02 Q1

### ISSUE THREAD

**Issue by AvaZard** [nus-cs2030/2324-s2#84]
Q1: Do we need to establish an interface for every direct dependency from client to implementer?

I don't think it is necessary to establish an interface for every direct dependency from client to implementer. Since some methods are strictly specific to certain implementer classes, it may be unnecessary to establish an interface for every single method. However, in the case where there are likely to be multiple implementations of a particular functionality, the contract functionality of an interface is especially useful in ensuring consistencies through the establishment of a has-a relationship as well as in making sure that the various client classes do not break by replacing the single direct dependency with having both client and implementer depend on the interface instead (by 'programming to the interface').

**Comment by ZHD1987E** [comment]
I agree: it really is a lifesaver when programming things for my lab, by making sure my events have a common interface, it allows my Simulator to just execute it, it does not know what kind of event it is unless it's told in some way.

By the way, I will not post my code here, so no cheating people!!!

**Comment by hwkchia** [comment]
Included in Lecture02
