### ISSUE TITLE
Lab 2: How to implement Leaves

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#86]
# Summary

I have managed to get most of my code working except the Leaves function that keeps repeatedly printing out.

## Description:

How should I modify my code to stop the leaves function from printing immediately after a customer is done

## Code Snippets

class Simulator {

    private final int numOfServers;
    private final ImList<Double> arrivalTimes;
    private final ImList<Double> serviceTimes;

    public Simulator(int numOfServers, ImList<Double> arrivalTimes, ImList<Double> serviceTimes) {
        this.numOfServers = numOfServers;
        this.arrivalTimes = arrivalTimes;
        this.serviceTimes = serviceTimes;
    }

    public String simulate() {
        ImList<Server> serverList = new ImList<>();
        int customersServed = 0;
        int customersLeft = 0;
        String output = "";
        PQ<Event> pq = new PQ<Event>(new EventComparator());

        for (int i = 0; i < numOfServers; i++) {
            serverList = serverList.add(new Server(0.000));
        }

        for (int i = 1; i <= arrivalTimes.size(); i++) {
            pq = pq.add(new Arrives(arrivalTimes.get(i - 1), "Arrives", i));
        }

        while (!pq.isEmpty()) {
            Pair<Event, PQ<Event>> pair = pq.poll();
            pq = pair.second();
            String arrives = "Arrives";

            if (Event.eventComparer(arrives, pair.first())) {
                for (int i = 1; i <= arrivalTimes.size(); i++) {
                    Customer customer = new Customer(arrivalTimes.get(i - 1), 
                        serviceTimes.get(i - 1));
        
                    boolean served = false;
                    
                    for (int j = 1; j <= numOfServers; j++) {
                        if (Server.isServerAvailable(i - 1, j - 1, arrivalTimes, serverList)) {
                            serverList = serverList.set(j - 1, 
                                new Server(customer.customerDuration()));
                            pq = pq.add(new Serve(arrivalTimes.get(i - 1),"Serve", i, j));
                            pq = pq.add(new Done(customer.customerDuration(), "Done", i, j));
                            customersServed++;
                            served = true;
                            break;
                        }
                    }

                    if (!served) {
                        pq = pq.add(new Leave(arrivalTimes.get(i - 1), "Leaves", i));
                        customersLeft++;
                    }
                }
            }

            output = output + pair.first().toString();
        }

        return output  + "[" + customersServed + " " + customersLeft + "]";
    }
}

    

## Screenshots
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/1471f455-8b9d-47fe-8a9b-c05b6436ce71)
Screenshots (if any)

**Comment by ZHD1987E** [comment]
Or if still not really sure, your IDE (Visual Studio Code/IDEA) would have features to allow debugging to step and trace.

Used that a lot in CS2040, helps a lot.

Yes, at the end of the day Vim is a text editor, and you'll have to work with Vim most of the time, but if your IDE has an advanced debugger, go use it.

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/e4ca49ce-c0d4-4f6e-9c9f-91c7717ab755)

Here's an example of debugging on Visual Studio Code. You can set breakpoints, step through the program, or view variables.

**Comment by zuoshihua** [comment]
Forgive me for being blunt, but your code is quite convoluted. You're trying to handle customers, servers and events all at the same time.

Here's my suggestion:

- Keep your two loops for the customers and servers. They should add events into the priority queue as and when they happen
- After the two loops are done, your priority queue should be filled with events. Retrieve the events from the priority queue. If your event comparator logic is correct, the priority queue will be able to retrieve them on the correct order.
