### ISSUE TITLE
Exercise 3 loaderId

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#90]
Hello. 

For exercise 3 level 3, we are expected to create a new service base on expired service (if there are expired services). However, there is no getter method to get LoaderId. 

Am I allowed to create additional help methods? 

If no, then can I get the LoaderId?

**Comment by wkleow123** [comment]
i feel that getting loaderId in this context is fine because it does make sense for a service to know the Id of the loader carrying out the service

**Comment by ZHD1987E** [comment]
Then it’s fine, up to you :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
