### ISSUE TITLE
Unable to use "protected" modifier in Self prac exercise 2

### ISSUE THREAD

**Issue by andrelau123** [nus-cs2030/2324-s2#92]
I am unable to use the protected modifier as code crunch requires me to use "private final".
<img width="1091" alt="Screenshot 2024-02-09 at 1 10 03 AM" src="https://github.com/nus-cs2030/2324-s2/assets/81068338/cb0f1681-9eea-4471-89a0-9d1bcf0c2d97">

**Comment by LimZiXiong** [comment]
Need to change all class attributes to private final protected is not allowed as classes that should not be using that attribute can still access it if it's protected

**Comment by Bryng23** [comment]
You can check the lecture 3 slides, prof went through an example using the protected modifier while keeping the class attributes private final
