### ISSUE TITLE
Unable to calculate volume of sphere without violating checkstyle

### ISSUE THREAD

**Issue by mChewWW** [nus-cs2030/2324-s2#93]
Part of exercise 02 requires you to create a method to calculate the volume of a sphere in the sphere class, which requires the formula (4.0/3) * Math.PI * radius * radius * radius. Having the numbers 4.0 and 3 in my code however is considered as a magic number and hence doesn't pass checkstyle. Is there a workaround for this?

**Comment by Bryng23** [comment]
you can define the 4.0/3.0 as a variable first. eg.

class Sphere {
    private static final double formulaNumber = 4.0 / 3.0;
   ....
}

**Comment by wkleow123** [comment]
the best way to deal with any magic number would be to write them out as private static final variables of the class since this will be more favourable in the spirit of OOP and will make it easier for you to edit the code if necessary in future as well
