### ISSUE TITLE
Lecture 2 Q4

### ISSUE THREAD

**Issue by jpowcm** [nus-cs2030/2324-s2#94]
# Question Description

Q4: Note the use of compareTo in the compare method of the LexiComp class. By referring to the String class in the Java API, what can you find out about the compareTo method?

## Your contribution:

The compareTo method in the String class compares two strings lexicographically (in alphabetical/dictionary order). There is also a compareToIgnoreCase method, which compares two strings lexicographically, ignoring case differences.

**Comment by hwkchia** [comment]
Included in lecture 2 notes.
