### ISSUE TITLE
Issues with PQ.java

### ISSUE THREAD

**Issue by jwoongg** [nus-cs2030/2324-s2#95]
Hi guys, anyone experiencing this issue of being unable to instantiate an object of the PQ class when you load it onto jshell?

jshell> PQ<Integer> pq = new PQ<Integer>(new IntComp());
|  Error:
|  cannot find symbol
|    symbol:   class PQ
|  PQ<Integer> pq = new PQ<Integer>(new IntComp());
|  ^^
|  Error:
|  cannot find symbol
|    symbol:   class PQ
|  PQ<Integer> pq = new PQ<Integer>(new IntComp());

**Comment by lequinus** [comment]
Hi, when instantiating an object of the PQ class, you'll need to specify the type of the PQ like so PQ<Integer>.  Example from Lab 2 on codecrunch: 
jshell> PQ<Integer> pq = new PQ<Integer>(new IntComp())

**Comment by BZAStudent** [comment]
Hi. In order to use PQ, make sure u open Pair as well as PQ is dependent on Pair for its method(s).

**Comment by hwkchia** [comment]
Issue expired.
