### ISSUE TITLE
Time Limit exceeded

### ISSUE THREAD

**Issue by tzs69** [nus-cs2030/2324-s2#98]
# Summary

I keep on getting "Time Limit Exceeded" when I submit my code to codecrunch.

## Description:

After some testing, I have found out that the cause of this problem might be due to the way I check for server availability in my Arrive class.

I use a method next() which takes in an ImList<Server> as its argument and runs it through a loop to check if any of the servers can serve the specific customer of my Arrive event class. If the customer can be served by the server, I update the server list with a new server which reflects the next available service timing after serving said customer, and create a new Serve event which is then added into my PQ in my simulate(). If after running through the loop and no available servers to serve the customer, a new Leave event is created and added into PQ.

Is it wrong to pass an ImList to my next() method to check for server availability for each Arrive event? Is there a better way to do it?

## Screenshots

![Screenshot 2024-02-13 132917](https://github.com/nus-cs2030/2324-s2/assets/156649283/c921d2ef-2674-4e3c-b697-5ed73dc45cbf)

**Comment by walkaround54** [comment]
I don't think it's necessarily wrong to pass the ImList of servers in to the Arrive event, as I managed to make my code work with that implementation. However, I'm more confused with regards to why you make your customer a parent class. Based on this, I assume your Arrive and other events are child classes of Customer. 

I get that they may have overlapping attributes i.e time arrived, customer index etc but you could consider the alternative of having the events take in Customers as input when initialising (if you are not already dong that).

**Comment by tzs69** [comment]
@walkaround54 My customer class is not a parent class it is just one of the attributes of my Event superclass, the other attribute being the time of the event. My Arrive event extends Event.

![Screenshot 2024-02-13 143255](https://github.com/nus-cs2030/2324-s2/assets/156649283/c9ae4457-ae5f-4753-8660-a1c79636c79a)

**Comment by wkleow123** [comment]
maybe theres some part of your code logic that causes your PQ to never empty out and results in some infinite loop? just a thought

**Comment by LimZiXiong** [comment]
In your simulator method did you update the list of server there? If not after 1 event chain your serverlist won't be up to date anymore
