### ISSUE TITLE
Self prac 3 exercise - use of restricted API detected

### ISSUE THREAD

**Issue by ethanmanzz** [nus-cs2030/2324-s2#99]
Hi guys,

Does anyone know the problem for this? It seems I have used restricted API in the java.utils.objects. However, I do not think I used API so I am quite confused. It also does not tell me specifically which API I cannot use. Is it a method I used? For ImList, I used add, indexOf, remove, get methods and I used the hasNext and next method for iterator. Pls help !! Thankss
<img width="471" alt="Screenshot 2024-02-13 at 4 03 11 PM" src="https://github.com/nus-cs2030/2324-s2/assets/159884036/a711c575-50ae-45b4-a86b-d2baca079e08">

**Comment by samuelneo** [comment]
if the iterator you're referring to is `java.util.Iterator`, it's banned. basically any data structures that aren't those provided (i.e. `ImList`, `PQ`, `Pair`) are banned

**Comment by ethanmanzz** [comment]
@samuelneo oh, I thought can use because it was taught in lecture, so I thought can use it since we also used Comparator in our lab 2.

**Comment by chinwn** [comment]
Java iterators use imperative code with side-effects. The  programming exercises in CS2030 currently emphasizes on functional (FP) approach to coding with immutable data structures/objects. Hence, the restriction..

**Comment by hwkchia** [comment]
I've regraded your submission.  It's due to non-static constants.  You should declare them as `static`.

**Comment by ethanmanzz** [comment]
@hwkchia alright, it works now, thank you for the clarification!
